# -*- coding: utf-8 -*-
"""tutorial-spatial-panels-cigarette-demand.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HCZJog7F9_9v7O57rk6TilyNvq1IBhKU

# Spatial panel data: Cigar demand application
"""

* Clean environment
clear all
macro drop _all
set more off
version 12

* Install packages: SPMAT, XSMLE, SPWMATRIX
*net install st0292, from (http://www.stata-journal.com/software/sj13-2)
*net install xsmle, from (http://fmwww.bc.edu/RePEc/bocode/x)
*net install spwmatrix, from (http://fmwww.bc.edu/RePEc/bocode/s)

"""## Import W matrix and data"""

* Generate row-standardized W matrix from .dta file as spwmatrix (required for the xsmle package)
use "https://github.com/quarcs-lab/data-open/raw/master/cigar/Wct_bin.dta", replace
spmat dta Wst m1-m46, norm(row) replace

* Panel data set up
use "https://github.com/quarcs-lab/data-open/raw/master/cigar/baltagi_cigar.dta", clear
sort year state
xtset state year
xtsum

"""## Non-spatial panel

### Pooled OLS
"""

reg logc logp logy
estimate store pool

"""### Region FE"""

xtreg logc logp logy, fe
estimate store rfe

"""### Time FE"""

reg logc logp logy i.year
estimate store tfe

"""### Two-way FE"""

xtreg logc logp logy i.year, fe
estimate store rtfe

"""### Comparison"""

estimates table pool rfe tfe rtfe, b(%7.2f) star(0.1 0.05 0.01) stf(%9.0f)

"""## Spatial panel

### SDM with two-way FE
"""

xsmle logc logp logy, fe type(both) wmat(Wst) mod(sdm) effects nsim(999) nolog
estimate store sdm1

"""### Lee and Yu correction"""

xsmle logc logp logy, fe type(both) leeyu wmat(Wst) mod(sdm) effects nsim(999) nolog
estimate store sdm2

"""### Comparison"""

estimates table sdm1 sdm2, b(%7.3f) star(0.1 0.05 0.01) stf(%9.0f)

"""### Wald tests"""

quietly xsmle logc logp logy, fe type(both) leeyu wmat(Wst) mod(sdm) effects nsim(999) nolog

* Wald test: Reduce to SAR? (NO if p < 0.05)
test ([Wx]logp = 0) ([Wx]logy = 0)

* Wald test: Reduce to SLX? (NO if p < 0.05)
test ([Spatial]rho = 0)

* Wald test: Reduce to SEM? (NO if p < 0.05)
testnl ([Wx]logp = -[Spatial]rho*[Main]logp) ([Wx]logy = -[Spatial]rho*[Main]logy)

"""## Dynamic spatial panel

### Non-dynamic
"""

xsmle logc logp logy,fe type(both) wmat(Wst) mod(sdm) effects nsim(999) nolog
*estimate store sdm0
eststo SDM0

"""### Dynamic: tau*y_it-1"""

xsmle logc logp logy, dlag(1) fe type(both) wmat(Wst) type(ind) mod(sdm) effects nsim(999) nolog
*estimate store dsdm1
eststo dySDM1

"""### Dynamic: psi*W*y_it-1"""

xsmle logc logp logy, dlag(2) fe type(both) wmat(Wst) type(ind) mod(sdm) effects nsim(999) nolog
*estimate store dsdm2
eststo dySDM2

"""### Dynamic: tau*y_it-1 + psi*W*y_it-1"""

xsmle logc logp logy, dlag(3) fe type(both) wmat(Wst) type(ind) mod(sdm) effects nsim(999) nolog
*estimate store dsdm3
eststo dySDM3

"""### Comparison"""

*estimates table sdm0 dsdm1 dsdm2 dsdm3, b(%7.2f) star(0.1 0.05 0.01)

"""HTML version of the table"""

esttab SDM0 dySDM1 dySDM2 dySDM3,  mtitle("SDM" "dySDM1" "dySDM2" "dySDM3")

# Commented out IPython magic to ensure Python compatibility.
# %html
esttab SDM0 dySDM1 dySDM2 dySDM3,  mtitle("SDM" "dySDM1" "dySDM2" "dySDM3") html

