// app.js — wires the DOM controls in index.html to dgp/lasso/charts.
// Generated by /project:write-app for content/post/python_mgwrfer/.
// Pedagogical mapping: LASSO penalty ⇄ within-transformation strength;
// "rigorous" tag ⇄ within-transform; "cv" tag ⇄ pooled (no within).

(function () {
  "use strict";

  // ---- Tab switching ---------------------------------------------------------
  function activateTab(paneId) {
    document.querySelectorAll(".tab-strip button").forEach(btn => {
      const isActive = btn.dataset.pane === paneId;
      btn.classList.toggle("active", isActive);
      btn.setAttribute("aria-selected", isActive ? "true" : "false");
    });
    document.querySelectorAll(".tab-pane").forEach(pane => {
      pane.classList.toggle("active", pane.id === paneId);
    });
    window.scrollTo({ top: 0, behavior: "smooth" });
  }
  document.querySelectorAll(".tab-strip button").forEach(btn => {
    btn.addEventListener("click", () => activateTab(btn.dataset.pane));
  });
  document.querySelectorAll(".cta-card").forEach(card => {
    card.addEventListener("click", () => activateTab(card.dataset.goto));
  });

  // ---- TAB 1: L1 vs L2 animation (as MGWFER vs PMGWR stand-in) ----------------
  CHARTS.l1_vs_l2_animation(document.getElementById("intro-anim"));

  // ---- TAB 2: Confounder Lab --------------------------------------------------
  const lab = {
    n: 200, p: 40, signal: 0.6, lambdaIdx: 40, seed: 1,
    path: null,
    chart: CHARTS.coefficient_path(document.getElementById("lab-path")),
  };

  function lab_refit() {
    const sim = DGP.simulate_lasso({ n: lab.n, p: lab.p, signal: lab.signal, seed: lab.seed });
    lab.sim = sim;
    lab.path = LASSO.lasso_path(sim.X, sim.y, sim.n, sim.p, { nLam: 80, maxIter: 60, tol: 1e-5 });
    lab_render();
  }

  function lab_render() {
    if (!lab.path) return;
    const K = lab.path.lambdas.length;
    const k = Math.max(0, Math.min(K - 1, lab.lambdaIdx));
    const lambda = lab.path.lambdas[k];
    const beta = lab.path.betas[k];
    lab.chart.update(lab.path, lambda);

    document.getElementById("lab-l-val").textContent = lambda.toExponential(2);
    let nz = 0;
    for (let j = 0; j < beta.length; j++) if (Math.abs(beta[j]) > 1e-9) nz++;
    document.getElementById("lab-stat-nz").textContent = nz;
    document.getElementById("lab-stat-p").textContent = lab.p;
    document.getElementById("lab-stat-alpha-l").textContent = beta[0].toFixed(3);

    // Post-OLS on selected support (treatment column 0 always included).
    const support = [];
    for (let j = 0; j < beta.length; j++) if (Math.abs(beta[j]) > 1e-9) support.push(j);
    if (!support.includes(0)) support.unshift(0);
    const n = lab.sim.n, p = lab.sim.p;
    const d = new Float64Array(n);
    for (let i = 0; i < n; i++) d[i] = lab.sim.X[i * p + 0];
    const rest = support.filter(j => j !== 0);
    const Xs = LASSO.subset_columns(lab.sim.X, n, p, rest);
    const ols = LASSO.ols_with_treatment(d, Xs, lab.sim.y, n, rest.length);
    document.getElementById("lab-stat-alpha-o").textContent = ols ? ols.alpha_hat.toFixed(3) : "—";
  }

  function debounce(fn, ms) {
    let h = null;
    return function () { clearTimeout(h); h = setTimeout(fn, ms); };
  }

  const onParamChange = debounce(lab_refit, 80);
  document.getElementById("lab-n").addEventListener("input", e => {
    lab.n = +e.target.value;
    document.getElementById("lab-n-val").textContent = lab.n;
    onParamChange();
  });
  document.getElementById("lab-p").addEventListener("input", e => {
    lab.p = +e.target.value;
    document.getElementById("lab-p-val").textContent = lab.p;
    onParamChange();
  });
  document.getElementById("lab-s").addEventListener("input", e => {
    lab.signal = +e.target.value;
    document.getElementById("lab-s-val").textContent = lab.signal.toFixed(2);
    onParamChange();
  });
  document.getElementById("lab-l").addEventListener("input", e => {
    lab.lambdaIdx = +e.target.value;
    lab_render();
  });
  document.getElementById("lab-reseed").addEventListener("click", () => {
    lab.seed = Math.floor(Math.random() * 1e9) + 1;
    lab_refit();
  });
  document.getElementById("lab-reset").addEventListener("click", () => {
    lab.n = 200; lab.p = 40; lab.signal = 0.6; lab.lambdaIdx = 40; lab.seed = 1;
    document.getElementById("lab-n").value = lab.n;
    document.getElementById("lab-p").value = lab.p;
    document.getElementById("lab-s").value = lab.signal;
    document.getElementById("lab-l").value = lab.lambdaIdx;
    document.getElementById("lab-n-val").textContent = lab.n;
    document.getElementById("lab-p-val").textContent = lab.p;
    document.getElementById("lab-s-val").textContent = lab.signal.toFixed(2);
    lab_refit();
  });

  lab_refit();

  // ---- TAB 3: Within vs Pooled simulator --------------------------------------
  const sh = {
    n: 200, p: 40, signal: 0.5, asymmetry: 0.80, seed: 7,
    cmp: CHARTS.alpha_compare(document.getElementById("sh-compare")),
    hist: CHARTS.alpha_histograms(document.getElementById("sh-hist")),
  };

  function sh_refit() {
    const sim = DGP.simulate_dl({
      n: sh.n, p: sh.p, signal: sh.signal,
      asymmetry: sh.asymmetry, seed: sh.seed,
    });
    sh.sim = sim;
    // "rigorous" -> our within / FE branding; "cv" -> our pooled branding.
    const rig = LASSO.double_lasso(sim.X, sim.d, sim.y, sim.n, sim.p, "rigorous");
    const cvr = LASSO.double_lasso(sim.X, sim.d, sim.y, sim.n, sim.p, "cv",
                                   { nLam: 50, seed: sh.seed });
    sh.rig = rig; sh.cv = cvr;
    sh_render();
  }

  function fmt(x) { return (x === null || Number.isNaN(x)) ? "—" : x.toFixed(3); }
  function fmt4(x) { return (x === null || Number.isNaN(x)) ? "—" : x.toFixed(4); }

  function sh_render() {
    const r = sh.rig, c = sh.cv;
    document.getElementById("sh-rig-alpha").textContent = fmt(r.alpha_hat);
    document.getElementById("sh-rig-se").textContent    = fmt4(r.se_alpha);
    document.getElementById("sh-rig-iy").textContent    = r.n_Iy;
    document.getElementById("sh-rig-id").textContent    = r.n_Id;
    document.getElementById("sh-rig-un").textContent    = r.n_union;
    document.getElementById("sh-rig-lam").textContent   =
      `${r.lambda_y.toExponential(2)}, ${r.lambda_d.toExponential(2)}`;

    document.getElementById("sh-cv-alpha").textContent = fmt(c.alpha_hat);
    document.getElementById("sh-cv-se").textContent    = fmt4(c.se_alpha);
    document.getElementById("sh-cv-iy").textContent    = c.n_Iy;
    document.getElementById("sh-cv-id").textContent    = c.n_Id;
    document.getElementById("sh-cv-un").textContent    = c.n_union;
    document.getElementById("sh-cv-lam").textContent   =
      `${c.lambda_y.toExponential(2)}, ${c.lambda_d.toExponential(2)}`;

    sh.cmp.update({
      rigorous: r.alpha_hat,
      cv: c.alpha_hat,
      alpha_true: sh.sim.alpha_true,
    });
  }

  const onShParamChange = debounce(sh_refit, 120);
  document.getElementById("sh-n").addEventListener("input", e => {
    sh.n = +e.target.value;
    document.getElementById("sh-n-val").textContent = sh.n;
    onShParamChange();
  });
  document.getElementById("sh-p").addEventListener("input", e => {
    sh.p = +e.target.value;
    document.getElementById("sh-p-val").textContent = sh.p;
    onShParamChange();
  });
  document.getElementById("sh-s").addEventListener("input", e => {
    sh.signal = +e.target.value;
    document.getElementById("sh-s-val").textContent = sh.signal.toFixed(2);
    onShParamChange();
  });
  document.getElementById("sh-a").addEventListener("input", e => {
    sh.asymmetry = +e.target.value;
    document.getElementById("sh-a-val").textContent = sh.asymmetry.toFixed(2);
    onShParamChange();
  });

  document.getElementById("sh-run").addEventListener("click", function () {
    const btn = this;
    btn.disabled = true;
    const progBar = document.querySelector("#sh-progress > div");
    const progLabel = document.getElementById("sh-progress-label");
    const histEl = document.getElementById("sh-hist");
    const histStats = document.getElementById("sh-hist-stats");

    const N_SIMS = 100;
    const alphas_rig = [];
    const alphas_cv = [];

    let i = 0;
    function step() {
      const batch = 2;
      const end = Math.min(N_SIMS, i + batch);
      for (; i < end; i++) {
        const sim = DGP.simulate_dl({
          n: sh.n, p: sh.p, signal: sh.signal,
          asymmetry: sh.asymmetry, seed: sh.seed + i + 1,
        });
        const r = LASSO.double_lasso(sim.X, sim.d, sim.y, sim.n, sim.p, "rigorous");
        const c = LASSO.double_lasso(sim.X, sim.d, sim.y, sim.n, sim.p, "cv",
                                     { nLam: 40, seed: sh.seed + i + 1 });
        if (Number.isFinite(r.alpha_hat)) alphas_rig.push(r.alpha_hat);
        if (Number.isFinite(c.alpha_hat)) alphas_cv.push(c.alpha_hat);
      }
      const pct = (i / N_SIMS) * 100;
      progBar.style.width = pct + "%";
      progLabel.textContent = `simulation ${i} / ${N_SIMS}`;
      if (i < N_SIMS) {
        setTimeout(step, 0);
      } else {
        progLabel.textContent = `done (${N_SIMS} simulations)`;
        histEl.style.display = "block";
        histStats.style.display = "grid";
        sh.hist.update({
          alphas_rig, alphas_cv,
          alpha_true: sh.sim.alpha_true,
        });
        const meanRig = d3.mean(alphas_rig);
        const meanCV  = d3.mean(alphas_cv);
        const sdRig   = d3.deviation(alphas_rig);
        const sdCV    = d3.deviation(alphas_cv);
        document.getElementById("sh-cv-mean").textContent = (meanCV ?? 0).toFixed(3);
        document.getElementById("sh-cv-sd").textContent   = (sdCV  ?? 0).toFixed(3);
        document.getElementById("sh-rig-mean").textContent = (meanRig ?? 0).toFixed(3);
        document.getElementById("sh-rig-sd").textContent   = (sdRig  ?? 0).toFixed(3);
        btn.disabled = false;
      }
    }
    step();
  });

  sh_refit();

  // ---- TAB 4: Recovery forest from real CSV-derived data ----------------------
  const fp = {
    chart: CHARTS.forest_plot(document.getElementById("fp-chart")),
    bars: CHARTS.selection_bars(document.getElementById("fp-bars")),
    data: null,
  };

  function fp_refresh() {
    if (!fp.data) return;
    const outcomes = Array.from(document.querySelectorAll("#fp-outcomes input:checked")).map(el => el.value);
    const methods  = Array.from(document.querySelectorAll("#fp-methods input:checked")).map(el => el.value);
    fp.chart.update(fp.data.estimates, methods, outcomes);
    fp.bars.update(fp.data.selection, outcomes);
  }

  document.querySelectorAll("#fp-outcomes input, #fp-methods input").forEach(el => {
    el.addEventListener("change", fp_refresh);
  });

  fetch("data/results.json").then(r => r.json()).then(data => {
    fp.data = data;
    fp_refresh();
  }).catch(err => {
    document.getElementById("fp-chart").innerHTML =
      `<div style="padding:20px;color:#d97757;">Failed to load results.json: ${err}</div>`;
  });

  // ---- Global error handler ---------------------------------------------------
  window.addEventListener("error", function (e) {
    console.error("[write-app] uncaught error:", e.error);
  });
})();
