<!DOCTYPE html>
<html lang="en"><head>
<script src="slides_files/libs/clipboard/clipboard.min.js"></script>
<script src="slides_files/libs/quarto-html/tabby.min.js"></script>
<script src="slides_files/libs/quarto-html/popper.min.js"></script>
<script src="slides_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="slides_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="slides_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="slides_files/libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="dcterms.date" content="2026-06-11">
  <title>Taming Model Uncertainty in the EKC</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/theme/quarto-530021870a52ee60b3f5e86ec9e6fece.css">
  <link href="slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Taming Model Uncertainty in the EKC</h1>
  <p class="subtitle">BMA and Double-Selection LASSO with panel data, graded against a known answer key</p>
  <div class="title-result-strip">
    <div class="kr"><span class="kr-num">−7.139</span><span class="kr-cap">BMA recovers GDP coefficient · true −7.100</span></div>
    <div class="kr"><span class="kr-num">6 / 8</span><span class="kr-cap">true predictors flagged · zero false positives</span></div>
    <div class="kr"><span class="kr-num">2–3×</span><span class="kr-cap">bias when fixed effects are dropped</span></div>
  </div>
  <p class="author"><a href="https://carlos-mendez.org">Carlos Mendez</a></p>
  <p class="institute">Nagoya University (GSID)</p>
  <p class="date">June 11, 2026</p>
</section>
<section>
<section id="the-tension" class="title-slide slide level1 divider center" data-background-color="#d97757">
<h1>The Tension</h1>
<p><span class="act">Act I</span></p>
</section>
<section id="with-12-candidate-controls-there-are-4096-ways-to-test-the-ekc-which-one-do-you-trust" class="slide level2 center">
<h2>With 12 candidate controls, there are 4,096 ways to test the EKC — which one do you trust?</h2>
<p>Does pollution fall as countries get rich? Testing the <strong>inverted-N</strong> Environmental Kuznets Curve needs a cubic in GDP — and a choice of controls.</p>
<div class="fragment">
<p>With 12 candidates, <span class="math inline">\(2^{12} = 4{,}096\)</span> regressions are possible. <em>Picking one is a hidden assumption.</em></p>
<aside class="notes">
<p>This is the model-uncertainty problem. The EKC is the substantive object — log CO2 per capita as a cubic function of log GDP, producing the inverted-N shape (fall, rise, fall). But beyond GDP, many controls might matter. Choosing a single specification is an unstated, consequential assumption. Two principled fixes: Bayesian model averaging and post-double-selection LASSO.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="the-gdp-coefficient-moves-with-the-controls-you-choose" class="slide level2 center">
<h2>The GDP coefficient moves with the controls you choose</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Coefficient</th>
<th style="text-align: right;">Sparse FE</th>
<th style="text-align: right;">Kitchen-sink FE</th>
<th style="text-align: right;">True DGP</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\beta_1\)</span> (GDP)</td>
<td style="text-align: right;"><span class="key">−7.498</span></td>
<td style="text-align: right;">−7.131</td>
<td style="text-align: right;">−7.100</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\beta_2\)</span> (GDP<span class="math inline">\(^2\)</span>)</td>
<td style="text-align: right;">0.849</td>
<td style="text-align: right;">0.806</td>
<td style="text-align: right;">0.810</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\beta_3\)</span> (GDP<span class="math inline">\(^3\)</span>)</td>
<td style="text-align: right;">−0.031</td>
<td style="text-align: right;">−0.030</td>
<td style="text-align: right;">−0.030</td>
</tr>
</tbody>
</table>
<p><span class="comment">Same data, same fixed effects — the linear term swings from −7.498 to −7.131 just by adding controls.</span></p>
<aside class="notes">
<p>Both standard specifications get the inverted-N sign pattern right (β1&lt;0, β2&gt;0, β3&lt;0), but the magnitudes shift. Kitchen-sink is closer to the truth because the sparse model omits true controls and that biases it. But which of the 12 actually belong? Standard FE can’t tell you — it just hands you whichever model you chose.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-synthetic-panel-with-an-answer-key-lets-us-grade-every-method" class="slide level2 center">
<h2>A synthetic panel with an answer key lets us grade every method</h2>

<img data-src="../stata_bma_dsl_fig1_scatter.png" class="r-stretch quarto-figure-center"><p class="caption">Synthetic CO2 vs income: 80 countries, 1995–2014, N = 1,600. The cloud bends — the inverted-N shape the methods must recover.</p><aside class="notes">
<p>The trick that makes this tutorial work: synthetic data with a known data-generating process. We designed it so that 5 controls truly affect CO2 and 7 are pure noise, with the true coefficients written down in advance. That turns “did the method work?” from a guess into an exam we can grade. Inspired by Gravina and Lanzafame (2025) but fully synthetic.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="where-were-going" class="slide level2 center">
<h2>Where we’re going</h2>
<ul>
<li class="fragment">The lab: an 80-country, 20-year panel with a 5-true / 7-noise answer key</li>
<li class="fragment">Standard FE exposes the model-uncertainty problem</li>
<li class="fragment">BMA — average over 4,096 models, score each variable with a PIP</li>
<li class="fragment">Double-Selection LASSO — select controls twice, then run OLS</li>
<li class="fragment">The verdict: both work, but only with fixed effects in place</li>
</ul>
</section></section>
<section>
<section id="the-investigation" class="title-slide slide level1 divider center" data-background-color="#6a9bcc">
<h1>The Investigation</h1>
<p><span class="act">Act II</span></p>
</section>
<section id="the-lab-80-countries-20-years-5-true-controls-hidden-among-7-decoys" class="slide level2 center">
<h2>The lab: 80 countries × 20 years, 5 true controls hidden among 7 decoys</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="true-predictors-5">True predictors (5)</h3>
<ul>
<li><code>fossil_fuel</code> (+0.015)</li>
<li><code>renewable</code> (−0.010)</li>
<li><code>urban</code> (+0.007)</li>
<li><code>democracy</code> (−0.005)</li>
<li><code>industry</code> (+0.010)</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="noise-7-decoys">Noise (7 decoys)</h3>
<ul>
<li><code>globalization</code>, <code>services</code>, <code>trade</code>, <code>credit</code> — <em>correlated with GDP</em></li>
<li><code>pop_density</code>, <code>corruption</code>, <code>fdi</code></li>
</ul>
</div></div>
<p><span class="comment">Four decoys are deliberately correlated with GDP — they will look “significant” by piggybacking on GDP’s real effect.</span></p>
<aside class="notes">
<p>N = 1,600 (80 countries, 20 years). The outcome is generated from a cubic EKC with country and year fixed effects plus the 5 true controls. The hard part: four noise variables are correlated with GDP, so a naive regression flags them as significant. The job of BMA and DSL is to see through that correlation and keep only the 5 true controls.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-model-uncertainty-we-are-fighting-written-as-one-equation" class="slide level2 center">
<h2>The model uncertainty we are fighting, written as one equation</h2>
<p><span class="math display">\[\ln(\text{CO2})_{it} = \beta_1 \ln G_{it} + \beta_2 (\ln G_{it})^2 + \beta_3 (\ln G_{it})^3 + \mathbf{X}_{it}^{\text{true}}\boldsymbol{\gamma} + \alpha_i + \delta_t + \varepsilon_{it}\]</span></p>
<p><span class="comment">A cubic in log GDP <span class="math inline">\(G\)</span> gives the inverted-N; <span class="math inline">\(\alpha_i\)</span> and <span class="math inline">\(\delta_t\)</span> absorb country and year heterogeneity; <span class="math inline">\(\mathbf{X}^{\text{true}}\)</span> is the 5 controls we must rediscover.</span></p>
<aside class="notes">
<p>This is the true DGP. The inverted-N needs β1&lt;0, β2&gt;0, β3&lt;0, and we built it with exactly that pattern (−7.1, 0.81, −0.03). Country fixed effects α_i and year effects δ_t soak up unobserved heterogeneity — keep this in mind, because dropping them later breaks everything. The exam: can BMA and DSL recover both the cubic shape and the 5 true controls?</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="throw-in-all-12-controls-and-the-answer-barely-moves-so-which-controls-belong" class="slide level2 center">
<h2>Throw in all 12 controls and the answer barely moves — so which controls belong?</h2>

<img data-src="../stata_bma_dsl_fig2_instability.png" class="r-stretch quarto-figure-center"><p class="caption">GDP polynomial coefficients shift between the sparse and kitchen-sink fixed effects specifications — the visible signature of model uncertainty.</p><aside class="notes">
<p>The kitchen-sink regression (all 12 controls) gets the three strong predictors right — fossil fuel, industry, urban are significant — and most noise variables are insignificant. But democracy’s estimate (−0.0003, p=0.97) is nowhere near its true −0.005: weak signals are hard even with the correct model. The coefficients shift enough to move the turning points by ~$2,000. Standard FE leaves us guessing.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="bma-averages-over-all-4096-models-and-weights-each-by-how-well-it-fits" class="slide level2 center">
<h2>BMA averages over all 4,096 models and weights each by how well it fits</h2>
<p><span class="math display">\[P(M_k \mid \text{data}) = \frac{P(\text{data} \mid M_k)\, P(M_k)}{\sum_{l} P(\text{data} \mid M_l)\, P(M_l)}\]</span></p>
<p>Each model’s weight is its fit (marginal likelihood) times its prior. Better-fitting, <strong>parsimonious</strong> models earn more weight — BMA’s built-in Occam’s razor.</p>
<p><span class="comment">Instead of betting on one horse, BMA spreads bets across the whole field.</span></p>
<aside class="notes">
<p>The marginal likelihood integrates over all coefficient values, so a model with many parameters spreads its prior thin and only recovers that probability if the data strongly support the extra dimensions. That is why BMA automatically penalizes complexity. With these weights in hand we can do two things: average coefficients, and score each variable.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-pip-is-a-democratic-vote-what-share-of-good-models-keep-a-variable" class="slide level2 center">
<h2>The PIP is a democratic vote: what share of good models keep a variable?</h2>
<p><span class="math display">\[\text{PIP}_j = \sum_{k:\, x_j \in M_k} P(M_k \mid \text{data})\]</span></p>
<p><span class="comment">A variable in every high-probability model has <span class="math inline">\(\text{PIP} \to 1\)</span>; one only in long-shot models stays near 0. We treat <span class="math inline">\(\text{PIP} \geq 0.80\)</span> as “robust.”</span></p>
<aside class="notes">
<p>PIP sums the posterior weight of every model that contains the variable — Raftery’s thresholds: ≥0.99 decisive, 0.95–0.99 very strong, 0.80–0.95 strong/robust, below 0.50 weak. 0.80 is the standard applied cutoff. The BMA posterior mean shrinks each coefficient toward zero in proportion to the evidence against inclusion, so a PIP of 0.5 roughly halves the conditional estimate. PIP is the signature output we grade against the answer key.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="six-lines-of-stata-run-bma-with-fixed-effects-always-in-the-model" class="slide level2 center">
<h2>Six lines of Stata run BMA with fixed effects always in the model</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-code-line-numbers="1|2|3|4"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb1-1"><a href=""></a>bmaregress <span class="ot">$outcome</span> <span class="ot">$gdp_vars</span> <span class="ot">$controls</span> <span class="co">///</span></span>
<span id="cb1-2"><a href=""></a>    (<span class="ot">$fe</span>, always), <span class="co">///</span></span>
<span id="cb1-3"><a href=""></a>    mprior(uniform) groupfv gprior(uip) <span class="co">///</span></span>
<span id="cb1-4"><a href=""></a>    mcmcsize(50000) rseed(9988) inputorder pipcutoff(0.8)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><span class="comment"><code>($fe, always)</code> forces country and year FE into every model; <code>groupfv</code> moves the 80 country dummies as one package, not 80 independent choices.</span></p>
<aside class="notes">
<p>Uniform model prior = every model equally likely a priori; UIP = unit-information g-prior, relatively uninformative. mcmcsize draws 50,000 models via MC³; rseed fixes reproducibility. Without groupfv, i.country_id would be 80 separate selection choices — a 2^80 model space, meaningless. With it, the dummies enter or leave as a roster. pipcutoff(0.8) is a display threshold only.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="bma-recovers-the-gdp-coefficient-almost-exactly-7.139-vs-true-7.100" class="slide level2 center" data-background-color="#141413">
<h2>BMA recovers the GDP coefficient almost exactly — −7.139 vs true −7.100</h2>
<p><span class="bignum">−7.139</span></p>
<p><span class="bignum-label">BMA posterior mean on <span class="math inline">\(\beta_1\)</span> · true DGP value −7.100; cubic term −0.030 matches the truth exactly</span></p>
<aside class="notes">
<p>The three GDP terms come back at −7.139, 0.808, −0.030 against the truth −7.100, 0.810, −0.030 — within about 1% each, and the cubic term is exact to three decimals. This is meaningfully closer than the sparse FE (−7.498). BMA averaged over 163 sampled models (of 4,096) with sampling correlation 0.9997, concentrating on the high-probability region rather than visiting every model.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="bma-flags-6-of-8-true-predictors-and-zero-noise-the-answer-key-confirmed" class="slide level2 center">
<h2>BMA flags 6 of 8 true predictors and zero noise — the answer key confirmed</h2>

<img data-src="../stata_bma_dsl_fig3_pip.png" class="r-stretch quarto-figure-center"><p class="caption">PIPs for all 15 variables: true predictors (steel blue) clear the 0.80 line; all 7 noise variables (gray) sit near zero.</p><aside class="notes">
<p>Top of the chart, near PIP 1.0: the three GDP terms, fossil fuel (1.000), industry (0.999), renewable (0.959) — six of the eight true predictors flagged robust. Bottom, near zero: all seven noise variables, correctly rejected. Zero false positives. The only misses are urban (PIP ≈ 0.27) and democracy (≈ 0.02), whose true coefficients (+0.007, −0.005) are simply too small to detect at this sample size — an honest limitation, not a failure.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-posterior-densities-sit-far-from-zero-strong-evidence-for-all-six-robust-variables" class="slide level2 center">
<h2>The posterior densities sit far from zero — strong evidence for all six robust variables</h2>

<img data-src="../stata_bma_dsl_fig4_coefdensity.png" class="r-stretch quarto-figure-center"><p class="caption">Posterior coefficient densities for the six PIP &gt; 0.80 variables. Top row: GDP linear, squared, cubic. Bottom: fossil fuel, renewable, industry. All concentrated away from zero.</p><aside class="notes">
<p>Each blue curve is the density conditional on inclusion; the flat red line is the probability of non-inclusion (1 − PIP). Near-zero red line plus a blue curve far from zero = strong evidence. The GDP terms center on −7.1, +0.81, −0.030 (the truth); the controls on +0.014, −0.007, +0.009. Renewable’s −0.007 is slightly attenuated from its true −0.010 — BMA shrinkage, because its PIP is below 1.0.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="dsl-takes-a-different-road-select-controls-twice-then-run-a-clean-ols" class="slide level2 center">
<h2>DSL takes a different road: select controls twice, then run a clean OLS</h2>
<p><span class="math display">\[\hat{S} = \hat{S}_Y \cup \hat{S}_{D_1} \cup \hat{S}_{D_2} \cup \hat{S}_{D_3}, \qquad \hat{\boldsymbol{\beta}}^{\text{LASSO}} = \arg\min_{\boldsymbol{\beta}}\ \tfrac{1}{2N}\textstyle\sum_i (y_i - \mathbf{x}_i'\boldsymbol{\beta})^2 + \lambda\sum_j |\beta_j|\]</span></p>
<p>LASSO on the outcome (<span class="math inline">\(\hat S_Y\)</span>) <strong>and</strong> on each GDP term (<span class="math inline">\(\hat S_{D_k}\)</span>); the <strong>union</strong> is the safety net; then OLS on that union.</p>
<p><span class="comment">The second selection catches a confounder the outcome-LASSO would miss — that is the “double.”</span></p>
<aside class="notes">
<p>Belloni, Chernozhukov &amp; Hansen (2014). The L1 penalty’s sharp corner at zero forces weak coefficients to exactly zero — that is what makes LASSO a selector, unlike Ridge. The union is the key insight: a control that predicts the treatment but only weakly predicts the outcome could be dropped by a single outcome-LASSO and bias the GDP coefficient. The d-LASSO catches it. dsregress chooses λ by a plugin formula, no cross-validation.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="with-fixed-effects-dsl-gives-fast-valid-estimates-7.433-in-seconds" class="slide level2 center">
<h2>With fixed effects, DSL gives fast, valid estimates — −7.433 in seconds</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Coefficient</th>
<th style="text-align: right;">DSL (FE)</th>
<th style="text-align: right;">True DGP</th>
<th style="text-align: center;">Significant?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\beta_1\)</span> (GDP)</td>
<td style="text-align: right;"><span class="key">−7.433</span></td>
<td style="text-align: right;">−7.100</td>
<td style="text-align: center;">yes</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\beta_2\)</span> (GDP<span class="math inline">\(^2\)</span>)</td>
<td style="text-align: right;">0.840</td>
<td style="text-align: right;">0.810</td>
<td style="text-align: center;">yes</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\beta_3\)</span> (GDP<span class="math inline">\(^3\)</span>)</td>
<td style="text-align: right;">−0.031</td>
<td style="text-align: right;">−0.030</td>
<td style="text-align: center;">yes</td>
</tr>
</tbody>
</table>
<p><span class="comment">Cluster-robust SEs, four internal LASSOs, union, then OLS — all in seconds. Wald <span class="math inline">\(\chi^2 = 53.15\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>.</span></p>
<aside class="notes">
<p>DSL lands between the sparse and kitchen-sink FE, close to BMA. Why not closer to the truth? In this panel, 99 of 112 candidates are FE dummies; LASSO retains nearly all of them (102 of 112) and has little room to discriminate among the 12 controls of interest. So the final OLS sits near the kitchen-sink. To see LASSO’s selection power unleashed, you have to remove the FE — which we do next, with a warning.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="strip-the-fixed-effects-and-the-gdp-coefficient-explodes-to-21.26" class="slide level2 center" data-background-color="#141413">
<h2>Strip the fixed effects and the GDP coefficient explodes to −21.26</h2>
<p><span class="bignum">−21.26</span></p>
<p><span class="bignum-label">Pooled BMA <span class="math inline">\(\beta_1\)</span> (no FE) · 3× the true −7.100; pooled DSL agrees at −22.03</span></p>
<aside class="notes">
<p>Treat the panel as a pooled cross-section — no country or year effects — and both methods inflate the GDP coefficient 2–3x. Pooled BMA gives −21.26, pooled DSL −22.03. The fact that a Bayesian and a frequentist method agree so closely on the WRONG answer is the tell: the bias is not about variable selection, it is the omitted fixed effects. The GDP terms absorb persistent cross-country differences in emissions levels.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="worse-pooled-bma-hands-robust-status-to-5-noise-variables" class="slide level2 center">
<h2>Worse, pooled BMA hands robust status to 5 noise variables</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="with-fixed-effects">With fixed effects</h3>
<ul>
<li>6 variables clear PIP <span class="math inline">\(\geq 0.80\)</span></li>
<li>all 7 noise → PIP <span class="math inline">\(\approx 0\)</span></li>
<li><strong>zero</strong> false positives</li>
<li>intervals cover the truth</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="pooled-no-fe">Pooled (no FE)</h3>
<ul>
<li>12 of 15 clear PIP <span class="math inline">\(\geq 0.80\)</span></li>
<li>services, credit, pop. density → PIP = 1.000</li>
<li><strong>5</strong> false positives</li>
<li>intervals miss the truth, all 3 terms</li>
</ul>
</div></div>
<aside class="notes">
<p>This is the sharpest lesson in the deck. Without FE, the noise variables are correlated with the omitted country effects, and BMA reads those spurious correlations as genuine predictive power. PIP thresholds are only meaningful when the model set is correctly specified. The pooled credible intervals are actually narrower than the FE ones — false precision from a misspecified model, the worst case.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="both-curves-trace-the-same-inverted-n-bma-and-dsl-agree-on-the-shape" class="slide level2 center">
<h2>Both curves trace the same inverted-N — BMA and DSL agree on the shape</h2>

<img data-src="../stata_bma_dsl_fig5_ekc_curves.png" class="r-stretch quarto-figure-center"><p class="caption">Predicted EKC curves (normalized at mean GDP): BMA (solid blue) and DSL (dashed orange) are nearly indistinguishable, with closely aligned turning points.</p><aside class="notes">
<p>Normalizing both curves to zero at the sample-mean GDP makes the shape pop. CO2 falls at very low income, rises through industrialization, falls again at high income — the inverted-N. The two methods, built on entirely different logic (Bayesian averaging vs frequentist selection), land on essentially the same curve. When a Bayesian and a frequentist method agree on the correctly specified model, the finding is robust.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="does-machine-selection-make-this-causal-no-it-disciplines-it-does-not-identify" class="slide level2 center">
<h2>Does machine selection make this causal? No — it disciplines, it does not identify</h2>
<p><span class="objection">Objection.</span> “BMA and LASSO pick controls automatically — surely that delivers the causal effect of income on emissions.”</p>
<div class="fragment">
<p><span class="rebuttal">Response.</span> No.&nbsp;These are <strong>model-uncertainty</strong> tools, not identification tools. They tame which controls enter and report honest robustness (PIPs, valid SEs). Identifying a causal EKC still needs the usual assumptions — and the synthetic answer key grades <em>recovery of a known DGP</em>, not a real-world causal claim.</p>
<aside class="notes">
<p>Steelman, don’t strawman. BMA and DSL solve “which of these candidate controls belong?” and “how robust is each?” They do not manufacture identification — endogeneity (e.g.&nbsp;via 2SLS-BMA in Gravina &amp; Lanzafame), reverse causality, and omitted confounders outside the candidate set remain the analyst’s job. This deck demonstrates accurate variable selection against ground truth, framed as model averaging and robustness, not a causal estimand.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section></section>
<section>
<section id="the-resolution" class="title-slide slide level1 divider center" data-background-color="#00d4c8">
<h1>The Resolution</h1>
<p><span class="act">Act III</span></p>
</section>
<section id="the-verdict-6-of-8-true-predictors-recovered-zero-false-positives-with-fixed-effects" class="slide level2 center">
<h2>The verdict: 6 of 8 true predictors recovered, zero false positives — with fixed effects</h2>

<img data-src="../stata_bma_dsl_fig6_answer_key.png" class="r-stretch quarto-figure-center"><p class="caption">Answer key: BMA PIPs by ground truth. True predictors (blue circles) cluster above 0.80; noise variables (gray diamonds) cluster below.</p><aside class="notes">
<p>BMA’s report card: of 8 true predictors (3 GDP terms + 5 controls), it flags 6 at PIP &gt; 0.80 with zero false positives — only the two weak-signal misses (urban, democracy). DSL gives fast, valid cluster-robust estimates in seconds. Both recover the inverted-N. The synthetic answer key confirms both are doing their job, with the expected limitation that weak signals are genuinely hard to detect.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="choose-the-tool-by-the-question-averaging-vs-fast-valid-inference" class="slide level2 center">
<h2>Choose the tool by the question — averaging vs fast valid inference</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="use-bma-when">Use BMA when…</h3>
<ul>
<li>the question is <em>which variables robustly predict?</em></li>
<li>you want PIPs + coefficient densities</li>
<li>most accurate here: −7.139 vs −7.100</li>
<li>cost: MCMC takes minutes</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="use-dsl-when">Use DSL when…</h3>
<ul>
<li>you have a clear variable of interest + many controls</li>
<li>you want fast, valid frequentist inference</li>
<li>runs in seconds, cluster-robust SEs</li>
<li>limited by FE-heavy candidate sets</li>
</ul>
</div></div>
<aside class="notes">
<p>Different questions, not better/worse. BMA’s wider credible intervals honestly account for model uncertainty by averaging across thousands of models; frequentist methods condition on one model and understate it. Best of all: run both. If a Bayesian and a frequentist method agree on sign, magnitude, and significance, the finding is unlikely to be an artifact of any single modeling choice — and disagreements flag where evidence is assumption-sensitive.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section id="tame-model-uncertainty-with-bma-or-dsl-but-absorb-the-fixed-effects-first." class="title-slide slide level1 divider center" data-background-color="#141413">
<h1>Tame model uncertainty with BMA or DSL — but absorb the fixed effects first.</h1>
<aside class="notes">
<p>The single takeaway. Both methods recover the inverted-N EKC and the true predictors — BMA’s −7.139 is the closest of all to the truth’s −7.100, with zero false positives. But strip the fixed effects and both inflate the GDP coefficient 2–3x and invent five robust noise variables. Method agreement is no substitute for correct specification: in panel data, absorb the unobserved heterogeneity before you average or select.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="slides_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="slides_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="slides_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="slides_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="slides_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="slides_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="slides_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>