* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- pension_raw.dta ----
use "pension_raw.dta", clear
label data "1991 SIPP 401(k) cross-section: net wealth + eligibility + covariates"
note _dta: Real 1991 SIPP 401(k) sample loaded via DoubleML's fetch_401K (Chernozhukov et al. 2018; Poterba, Venti & Wise 1995). 9,915 households, 14 variables, single cross-section. e401 = eligibility (treatment / instrument), p401 = participation (endogenous treatment), net_tfa = outcome.
note nifa: Net financial assets held outside 401(k) accounts.. Construction: From the SIPP wealth module (financial assets excluding 401(k) balances).. Units: US$. Source: 1991 SIPP / fetch_401K
note net_tfa: Household net total financial assets; the outcome variable in the tutorial.. Construction: Total financial assets net of liabilities, from the SIPP wealth module.. Units: US$. Source: 1991 SIPP / fetch_401K
note tw: Household total wealth (broader than net_tfa).. Construction: Total net worth from the SIPP wealth module; not used in the post's models.. Units: US$. Source: 1991 SIPP / fetch_401K
note age: Age of the reference person of the household.. Construction: SIPP demographic record; sample restricted to working ages (25-64).. Units: years. Source: 1991 SIPP / fetch_401K
note inc: Annual household income - the dominant confounder.. Construction: SIPP income record; covariate X in all models.. Units: US$. Source: 1991 SIPP / fetch_401K
note fsize: Number of household members.. Construction: SIPP household roster; covariate X.. Units: persons. Source: 1991 SIPP / fetch_401K
note educ: Years of schooling of the household head.. Construction: SIPP education record; covariate X.. Units: years. Source: 1991 SIPP / fetch_401K
note db: 1 if the household head has a defined-benefit pension, else 0.. Construction: SIPP pension record; covariate X.. Units: 0/1. Source: 1991 SIPP / fetch_401K
note marr: Marital status of the household head.. Construction: SIPP demographic record; covariate X.. Units: 0/1. Source: 1991 SIPP / fetch_401K
note twoearn: 1 if the household has two earners, else 0.. Construction: SIPP income record; covariate X.. Units: 0/1. Source: 1991 SIPP / fetch_401K
note e401: 1 if the household is eligible for a 401(k) plan, else 0. Plausibly exogenous after conditioning on X; the treatment in PLR/IRM and the instrument in IIVM.. Construction: SIPP-derived eligibility flag (employer offers a 401(k)). Eligible: 3,682 / 9,915 (37.1%).. Units: 0/1. Source: 1991 SIPP / fetch_401K
note p401: 1 if the household participates in a 401(k) plan, else 0. The endogenous treatment in IIVM (instrumented by e401).. Construction: SIPP-derived participation flag (household enrolled). Participating: 2,594 / 9,915 (26.2%).. Units: 0/1. Source: 1991 SIPP / fetch_401K
note pira: 1 if the household participates in an IRA, else 0.. Construction: SIPP pension/saving record; covariate X.. Units: 0/1. Source: 1991 SIPP / fetch_401K
note hown: 1 if the household owns its home, else 0.. Construction: SIPP housing record; covariate X.. Units: 0/1. Source: 1991 SIPP / fetch_401K
save "pension_raw.dta", replace
