* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- source_data.dta ----
use "source_data.dta", clear
label data "Raw balanced Barro convergence panel (country x period)"
note _dta: Synthetic balanced panel; 150 countries x 8 periods = 1,200 obs. Carries the dependent variable (growth), log initial income, the raw investment/population/human-capital inputs, and the three log regressors. This is the file feols() is estimated on.
note id: Sequential country index (the entity dimension of the panel; treated as a factor for the fixed effects).. Construction: 1..150, one per synthetic country.. Units: integer code. Source: Simulation
note time: Sequential time-period index (the time dimension of the panel; treated as a factor for the fixed effects).. Construction: 1..8, one per period.. Units: integer code. Source: Simulation
note growth: Annualized GDP-per-capita growth rate - the outcome regressed in the TWFE model.. Construction: Simulated outcome of the Barro convergence data-generating process.. Units: rate (per year). Source: Simulation
note ln_y_initial: Natural log of initial GDP per capita - the beta-convergence regressor (a negative slope means poorer countries grow faster).. Construction: Simulated log initial income.. Units: log US$. Source: Simulation
note s_k: Physical-capital investment share of GDP (Solow-style accumulation rate).. Construction: Simulated; log_s_k = log(s_k).. Units: 0-1 (share). Source: Simulation
note n_pop: Population growth rate (the n in the Solow n + g + d term).. Construction: Simulated; log_n_gd = log(n_pop + 0.05).. Units: rate (per year). Source: Simulation
note hcap: Human-capital stock proxy (e.g., schooling-based index).. Construction: Simulated; log_hcap = log(hcap).. Units: index. Source: Simulation
note gov_cons: Government consumption as a share of GDP - a control regressor.. Construction: Simulated.. Units: 0-1 (share). Source: Simulation
note log_s_k: Natural log of the investment share of GDP (Solow capital-accumulation regressor).. Construction: log(s_k).. Units: log share. Source: Derived
note log_n_gd: Natural log of population growth plus the standard 0.05 for growth and depreciation - the Solow n + g + d regressor.. Construction: log(n_pop + 0.05).. Units: log rate. Source: Derived
note log_hcap: Natural log of the human-capital index.. Construction: log(hcap).. Units: log index. Source: Derived
save "source_data.dta", replace

* ---- data_demeaned.dta ----
use "data_demeaned.dta", clear
label data "Within-transformed (two-way demeaned) analysis data"
note _dta: The within-transformed version of source_data: the same 1,200 rows with each of the six model variables in both raw form and two-way demeaned form (suffix _dm). The _dm column = value - country mean - time mean + grand mean.
note id: Sequential country index (the entity dimension of the panel; treated as a factor for the fixed effects).. Construction: 1..150, one per synthetic country.. Units: integer code. Source: Simulation
note time: Sequential time-period index (the time dimension of the panel; treated as a factor for the fixed effects).. Construction: 1..8, one per period.. Units: integer code. Source: Simulation
note growth: Annualized GDP-per-capita growth rate - the outcome regressed in the TWFE model.. Construction: Simulated outcome of the Barro convergence data-generating process.. Units: rate (per year). Source: Simulation
note ln_y_initial: Natural log of initial GDP per capita - the beta-convergence regressor (a negative slope means poorer countries grow faster).. Construction: Simulated log initial income.. Units: log US$. Source: Simulation
note log_s_k: Natural log of the investment share of GDP (Solow capital-accumulation regressor).. Construction: log(s_k).. Units: log share. Source: Derived
note log_n_gd: Natural log of population growth plus the standard 0.05 for growth and depreciation - the Solow n + g + d regressor.. Construction: log(n_pop + 0.05).. Units: log rate. Source: Derived
note log_hcap: Natural log of the human-capital index.. Construction: log(hcap).. Units: log index. Source: Derived
note gov_cons: Government consumption as a share of GDP - a control regressor.. Construction: Simulated.. Units: 0-1 (share). Source: Simulation
note growth_dm: Two-way demeaned growth: deviation of growth from its country mean and time mean (grand mean added back). The within-variation that identifies the TWFE coefficient.. Construction: growth - country_mean(growth) - time_mean(growth) + grand_mean(growth); mean ? 0.. Units: rate (deviation). Source: Derived (within transform)
note ln_y_initial_dm: Two-way demeaned log initial income (deviation from country + time means, grand mean restored).. Construction: ln_y_initial - country mean - time mean + grand mean; mean ? 0.. Units: log US$ (deviation). Source: Derived (within transform)
note log_s_k_dm: Two-way demeaned log investment share (deviation from country + time means, grand mean restored).. Construction: log_s_k - country mean - time mean + grand mean; mean ? 0.. Units: log share (deviation). Source: Derived (within transform)
note log_n_gd_dm: Two-way demeaned log of population growth plus g + d (deviation from country + time means, grand mean restored).. Construction: log_n_gd - country mean - time mean + grand mean; mean ? 0.. Units: log rate (deviation). Source: Derived (within transform)
note log_hcap_dm: Two-way demeaned log human capital (deviation from country + time means, grand mean restored).. Construction: log_hcap - country mean - time mean + grand mean; mean ? 0.. Units: log index (deviation). Source: Derived (within transform)
note gov_cons_dm: Two-way demeaned government consumption share (deviation from country + time means, grand mean restored).. Construction: gov_cons - country mean - time mean + grand mean; mean ? 0.. Units: share (deviation). Source: Derived (within transform)
save "data_demeaned.dta", replace
