* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- sim_resource_curse.dta ----
use "sim_resource_curse.dta", clear
label data "District-year panel: outcomes, treatment, moderators, controls"
note _dta: Balanced district-year panel; 300 synthetic districts over 2003-2012 across 8 fictional countries (3,000 rows). Outcomes ntl_log and conflict; a 4-level mining/price treatment; institutional moderators (exec_constraints, quality_of_govt) plus economic and geographic covariates. Treatment is highly imbalanced (~85% control). Known ground-truth effects allow direct validation.
note district_id: District identifier; the panel unit.. Construction: Sequential integer 1..300 in the simulation.. Units: integer. Source: Simulation
note country_id: Country identifier; districts are nested within 8 fictional countries.. Construction: Integer 1..8 assigned in the simulation; used as i.country_id control.. Units: integer. Source: Simulation
note year: Annual time index; the panel time dimension.. Construction: 2003..2012 for every district (balanced); used as i.year control.. Units: year. Source: Simulation
note treatment: Four-level mining/mineral-price treatment: 0 no mining, 1/2/3 mining at low/medium/high price.. Construction: Assigned in the DGP; ~85% level 0 and ~5% each of 1,2,3. Split into binary pairwise contrasts for cate.. Units: 0-3. Source: Simulation
note mining: 1 if the district-year has active mining (treatment > 0), else 0.. Construction: Indicator derived from treatment (1 for levels 1-3, 0 for level 0).. Units: 0/1. Source: Simulation
note price_index: Global mineral-price index applied to the district-year.. Construction: Set by the treatment price level in the DGP (0 for non-mining).. Units: index. Source: Simulation
note exec_constraints: Institutional-quality moderator: strength of constraints on executive power.. Construction: Drawn per district in the DGP; rounded to exec_con (1-6) in Stata for GATE grouping.. Units: 1-6 scale. Source: Simulation
note quality_of_govt: Alternative institutional-quality moderator: overall quality of government.. Construction: Drawn per district in the DGP; quartile-binned (qog_cat) for GATEs in the post.. Units: 0-1 index. Source: Simulation
note gdp_pc: District GDP per capita (economic control).. Construction: Simulated district economic level (range ~500-5,000).. Units: US$. Source: Simulation
note elevation: Mean district elevation (geographic control / heterogeneity covariate).. Construction: Drawn per district in the DGP.. Units: meters. Source: Simulation
note temperature: Mean district temperature (geographic control).. Construction: Drawn per district in the DGP.. Units: degrees C. Source: Simulation
note ruggedness: Terrain ruggedness index (geographic control).. Construction: Drawn per district in the DGP.. Units: index. Source: Simulation
note distance_capital: Distance from the district to the national capital (geographic control).. Construction: Drawn per district in the DGP.. Units: meters. Source: Simulation
note agri_suitability: Suitability of district land for agriculture (economic/geographic control).. Construction: Drawn per district in the DGP, scaled to [0,1].. Units: 0-1. Source: Simulation
note population: District population (economic control).. Construction: Drawn per district in the DGP.. Units: persons. Source: Simulation
note ethnic_frac: Degree of ethnic heterogeneity in the district (control).. Construction: Drawn per district in the DGP, scaled to [0,1].. Units: 0-1. Source: Simulation
note ntl_log: Log of nighttime-light intensity; the development-proxy outcome.. Construction: Simulated outcome driven by treatment, moderators, controls, and DGP ground-truth effects.. Units: log intensity. Source: Simulation
note conflict: 1 if a conflict event occurred in the district-year, else 0; the secondary outcome.. Construction: Simulated binary outcome; baseline ~10.7% for non-mining, raised by mining in the DGP.. Units: 0/1. Source: Simulation
save "sim_resource_curse.dta", replace
