# -*- coding: utf-8 -*-
"""STATA_columbus-20231124 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P8apVk4SwJdlVMAoKXu9H8PLsukA2QI2

# Spatial cross-section models in Stata: An application to crime data

> Mendez C. (2021). Spatial econometrics for cross-sectional data in Stata: An application to crime. DOI: [10.5281/zenodo.5151076](https://doi.org/10.5281/zenodo.5151076). Notebook available at https://colab.research.google.com/drive/1P8apVk4SwJdlVMAoKXu9H8PLsukA2QI2?usp=sharing and [![DOI](https://zenodo.org/badge/387109687.svg)](https://zenodo.org/badge/latestdoi/387109687)

## Roadmap

![](https://github.com/quarcs-lab/data-open/raw/master/Columbus/columbus/SpatialEcometricsRoad.jpg)
"""

* Clean your environment
clear all
macro drop _all
set more off
*cls
*version 17

* Install packages: esttab, estadd, eststo, estout, estpost (http://repec.sowi.unibe.ch/stata/estout/index.html)
* net install st0085_2, from(http://www.stata-journal.com/software/sj14-2)
* ssc install estout, replace

"""## Import W and data"""

* Import .dta weights matrix with spmatrix (official function from Stata15)
use "https://github.com/quarcs-lab/data-open/raw/master/Columbus/columbus/Wqueen_fromStata_spmat.dta", clear
gen id = _n
order id, first
spset id
spmatrix fromdata WqueenS_fromStata15 = v*, normalize(row) replace
spmatrix summarize WqueenS_fromStata15

* Import the dataset and set up the spatial id: https://geodacenter.github.io/data-and-lab/columbus/
use "https://github.com/quarcs-lab/data-open/raw/master/Columbus/columbus/columbusDbase.dta", clear
spset id

label var CRIME "Crime"
label var INC   "Income"
label var HOVAL "House value"

"""## OLS"""

regress CRIME INC HOVAL
eststo OLS

estat ic
mat s=r(S)
quietly estadd scalar AIC = s[1,5]

"""### Moran's I test"""

regress CRIME INC HOVAL
estat moran, errorlag(WqueenS_fromStata15)

"""### LM tests"""

spatwmat using "https://github.com/quarcs-lab/data-open/raw/master/Columbus/columbus/Wqueen_fromStata_spmat.dta", name(WqueenS_fromStata_spatwmat) eigenval(eWqueenS_fromStata_spatwmat) standardize

quietly reg CRIME INC HOVAL
spatdiag, weights(WqueenS_fromStata_spatwmat)

"""## SAR"""

spregress CRIME INC HOVAL, ml dvarlag(WqueenS_fromStata15)
eststo SAR

estat ic
mat s=r(S)
quietly estadd scalar AIC = s[1,5]

estat impact

"""## SEM"""

spregress CRIME INC HOVAL, ml errorlag(WqueenS_fromStata15)
eststo SEM

estat ic
mat s=r(S)
quietly estadd scalar AIC = s[1,5]

estat impact

"""## SLX"""

spregress CRIME INC HOVAL, ml ivarlag(WqueenS_fromStata15: INC HOVAL)
eststo SLX

estat ic
mat s=r(S)
quietly estadd scalar AIC = s[1,5]

estat impact

"""## SDM"""

spregress CRIME INC HOVAL, ml dvarlag(WqueenS_fromStata15) ivarlag(WqueenS_fromStata15: INC HOVAL)
eststo SDM

estat ic
mat s=r(S)
quietly estadd scalar AIC = s[1,5]

estat impact

"""### Wald tests

### Reduce to OLS?
"""

* Wald test: Reduce to OLS? (NO if p < 0.05 of the spatial terms)
spregress CRIME INC HOVAL, ml dvarlag(WqueenS_fromStata15) ivarlag(WqueenS_fromStata15: INC HOVAL)

"""### Reduce to SLX?"""

* Wald test: Reduce to SLX? (NO if p < 0.05)
test ([WqueenS_fromStata15]CRIME = 0)

"""### Reduce to SAR?"""

* Wald test: Reduce to SAR? (NO if p < 0.05)
test ([WqueenS_fromStata15]INC = 0) ([WqueenS_fromStata15]HOVAL = 0)

"""### Reduce to SEM?"""

* Wald test: Reduce to SEM? (NO if p < 0.05)
testnl ([WqueenS_fromStata15]INC = -[WqueenS_fromStata15]CRIME*[CRIME]INC) ([WqueenS_fromStata15]HOVAL = -[WqueenS_fromStata15]CRIME*[CRIME]HOVAL)

"""## SDEM"""

spregress CRIME INC HOVAL, ml ivarlag(WqueenS_fromStata15: INC HOVAL) errorlag(WqueenS_fromStata15)
eststo SDEM

estat ic
mat s=r(S)
quietly estadd scalar AIC = s[1,5]

estat impact

"""## SAC"""

spregress CRIME INC HOVAL, ml dvarlag(WqueenS_fromStata15) errorlag(WqueenS_fromStata15)
eststo SAC

estat ic
mat s=r(S)
quietly estadd scalar AIC = s[1,5]

estat impact

"""## GNS"""

spregress CRIME INC HOVAL, ml dvarlag(WqueenS_fromStata15) ivarlag(WqueenS_fromStata15: INC HOVAL) errorlag(WqueenS_fromStata15)
eststo GNS

estat ic
mat s=r(S)
quietly estadd scalar AIC = s[1,5]

estat impact

"""## Comparison"""

# Commented out IPython magic to ensure Python compatibility.
# %html
esttab OLS SAR SEM SLX SDM SDEM SAC GNS, label stats(AIC) mtitle("OLS" "SAR" "SEM" "SLX" "SDM" "SDEM" "SAC" "GNS") html

eststo clear

"""The following comparison requires Stata 17.  Caution is needed as the p-values are not shown"""

collect clear

quietly spregress CRIME INC HOVAL, ml dvarlag(WqueenS_fromStata15)
collect: quietly estat impact

quietly spregress CRIME INC HOVAL, ml ivarlag(WqueenS_fromStata15: INC HOVAL)
collect: quietly estat impact

quietly spregress CRIME INC HOVAL, ml dvarlag(WqueenS_fromStata15) ivarlag(WqueenS_fromStata15: INC HOVAL)
collect: quietly estat impact

quietly spregress CRIME INC HOVAL, ml ivarlag(WqueenS_fromStata15: INC HOVAL) errorlag(WqueenS_fromStata15)
collect: quietly estat impact

quietly spregress CRIME INC HOVAL, ml dvarlag(WqueenS_fromStata15) errorlag(WqueenS_fromStata15)
collect: quietly estat impact

quietly spregress CRIME INC HOVAL, ml dvarlag(WqueenS_fromStata15) ivarlag(WqueenS_fromStata15: INC HOVAL) errorlag(WqueenS_fromStata15)
collect: quietly estat impact


collect label list cmdset, all
collect style autolevels result b_direct b_indirect
collect label levels cmdset 1 "SAR" 2 "SLX" 3 "SDM" 4 "SDEM" 5 "SAC" 6 "GNS"
collect style cell, nformat(%7.2f)
collect layout (colname#result) (cmdset)