<!DOCTYPE html>
<html lang="en"><head>
<script src="slides_files/libs/clipboard/clipboard.min.js"></script>
<script src="slides_files/libs/quarto-html/tabby.min.js"></script>
<script src="slides_files/libs/quarto-html/popper.min.js"></script>
<script src="slides_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="slides_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="slides_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="slides_files/libs/quarto-html/quarto-syntax-highlighting-dark-f1aadacce99040138bbb613f9330654f.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="dcterms.date" content="2026-08-02">
  <title>The Ladder and the Defaults</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #e1e4e8; background-color: #24292e; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #e1e4e8; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #f97583; } /* Attribute */
    code span.bn { color: #79b8ff; } /* BaseN */
    code span.bu { color: #f97583; } /* BuiltIn */
    code span.cf { color: #f97583; } /* ControlFlow */
    code span.ch { color: #9ecbff; } /* Char */
    code span.cn { color: #79b8ff; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #f97583; } /* DataType */
    code span.dv { color: #79b8ff; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #f97583; font-weight: bold; } /* Extension */
    code span.fl { color: #79b8ff; } /* Float */
    code span.fu { color: #b392f0; } /* Function */
    code span.im { color: #9ecbff; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #f97583; } /* Keyword */
    code span.op { color: #e1e4e8; } /* Operator */
    code span.ot { color: #b392f0; } /* Other */
    code span.pp { color: #f97583; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #79b8ff; } /* SpecialChar */
    code span.ss { color: #9ecbff; } /* SpecialString */
    code span.st { color: #9ecbff; } /* String */
    code span.va { color: #ffab70; } /* Variable */
    code span.vs { color: #9ecbff; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/theme/quarto-9b58ec14c6e77dd4bed0a59f9cec700e.css">
  <link href="slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-dark">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">The Ladder and the Defaults</h1>
  <p class="subtitle">Climbing six synthetic control estimators in mlsynth — and finding the settings matter more</p>
  <div class="title-result-strip">
    <div class="kr"><span class="kr-num">1.76 pp</span><span class="kr-cap">one default’s covariate spread</span></div>
    <div class="kr"><span class="kr-num">0.31 pp</span><span class="kr-cap">the whole ladder’s spread</span></div>
    <div class="kr"><span class="kr-num">92</span><span class="kr-cap">estimators behind one config dict</span></div>
  </div>
  <p class="author"><a href="https://carlos-mendez.org">Carlos Mendez</a></p>
  <p class="institute">Nagoya University (GSID)</p>
  <p class="date">August 2, 2026</p>
</section>
<section>
<section id="one-treated-unit" class="title-slide slide level1 divider center" data-background-color="#d97757">
<h1>One Treated Unit</h1>
<p><span class="act">Act I</span></p>
</section>
<section id="there-is-only-one-united-kingdom-and-it-voted-to-leave" class="slide level2 center">
<h2>There is only one United Kingdom, and it voted to leave</h2>
<p>On 23 June 2016, 51.9% voted to leave the European Union.</p>
<div class="fragment">
<p>To say what that decision cost, you need the United Kingdom that stayed.</p>
</div>
<div class="fragment">
<p><em>There is no such country. Every estimator in this deck is a different way of building one.</em></p>
<aside class="notes">
<p>This is the fundamental problem of causal inference, stated as concretely as it ever gets. We observe one potential outcome — the UK that left. The other one, the UK that stayed, was never realised and never will be. Everything that follows is a machine for manufacturing that missing series out of countries we do observe. The interesting question is not whether such a machine exists. Six of them do. The question is how much the answer depends on which machine you pick, and — this is where the deck is going — on which knobs you leave alone.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="one-line-in-a-crowd" class="slide level2 center">
<h2>One line in a crowd</h2>

<img data-src="../python_sc_dsc_sdid_01_gdp_paths.png" class="r-stretch quarto-figure-center"><p class="caption">Log real GDP for 24 OECD economies, 1995-2020. The United Kingdom in orange; the dashed line marks the 2016 referendum.</p><p><span class="takeaway fragment">24 countries · 23 donors · 86 pre-treatment quarters · treatment dated 2016Q3.</span></p>
<aside class="notes">
<p>No single donor tracks the UK, which is why we blend rather than pick. Two things to notice. First, the series are strongly trending and highly correlated — close to a set of random walks with drift. That will matter enormously when we get to the time weights. Second, look at 2008-09: every line collapses together. That synchronised movement is a common factor, and it is what the demeaned and time-weighted stages are built to exploit.</p>
<p>The panel is quarterly log real GDP assembled by Born, Müller, Schularick and Sedláček, redistributed in the replication package of de Brabander, Juodis and Miyazato Szini. No missing values.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ninety-two-estimators-one-configuration-dictionary" class="slide level2 center">
<h2>Ninety-two estimators, one configuration dictionary</h2>
<p>One interface for the whole single-treated-unit literature: build a config, call <code>.fit()</code>, read a standardized result.</p>
<div class="fragment">
<p><strong>Six stages in this deck. Eighty-six more estimators behind the same door.</strong></p>
</div>
<div class="fragment">
<p><span class="takeaway fragment">Pin the commit, not the release — <code>__version__</code> says <code>1.0.0</code> either way.</span></p>
<aside class="notes">
<p>This is the pitch, and it is the reason a package-level reading is worth doing at all. Normally climbing this ladder means learning Synth, then synthdid, then masc, then augsynth — four packages, four interfaces, four result formats, four sets of conventions about signs. Here it is one config dict and one result object throughout.</p>
<p>The version warning is not pedantry. The release numbered 1.0.0 on PyPI is missing a config field this deck uses, and the version string does not distinguish it from git main. Pin the commit.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="where-were-going" class="slide level2 center">
<h2>Where we’re going</h2>
<ul>
<li class="fragment"><strong>Read</strong> one config dict and one result object — the entire API surface.</li>
<li class="fragment"><strong>Map</strong> each stage of the ladder onto a specific <code>mlsynth</code> class.</li>
<li class="fragment"><strong>Identify</strong> the three defaults that change the answer materially.</li>
<li class="fragment"><strong>Compare</strong> the stages on a placebo tournament, and read the ranking sceptically.</li>
<li class="fragment"><strong>Report</strong> a cloud of estimates rather than a point.</li>
</ul>
<aside class="notes">
<p>Four acts. Act I is the problem. Act II climbs the ladder — this is the longest stretch and the most code. Act III is where the deck earns its title: the defaults. Act IV asks which stage to choose and how confident we are allowed to be about the answer.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="one-config-six-stages" class="title-slide slide level1 divider center" data-background-color="#6a9bcc">
<h1>One Config, Six Stages</h1>
<p><span class="act">Act II</span></p>
</section>
<section id="every-stage-is-the-same-regression-weighted-differently" class="slide level2 center">
<h2>Every stage is the same regression, weighted differently</h2>
<p><span class="math display">\[(\hat\tau, \hat\mu, \hat\alpha, \hat\beta) = \arg\min \sum_{i,t} \omega_i \lambda_t \left( Y_{it} - \mu - \alpha_i - \beta_t - \tau D_{it} \right)^2\]</span></p>
<p><span class="comment">A two-way fixed-effects regression — but some countries and some quarters count more.</span></p>
<div class="fragment">
<p><span class="takeaway fragment">The stages differ only in how <span class="math inline">\(\omega\)</span> and <span class="math inline">\(\lambda\)</span> are chosen.</span></p>
<aside class="notes">
<p>This is the unifying idea, and it is worth pausing on because it makes the whole ladder legible. Difference-in-differences, synthetic control, demeaned SC and SDID are not four different models. They are one model with four different weighting schemes. MASC and ASCM break the pattern slightly — they change what weights are allowed at all rather than which weights get chosen — which is why the ladder branches at the top rather than continuing straight up.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="the-ladder-is-two-dials-who-counts-and-when" class="slide level2 smaller center">
<h2>The ladder is two dials: who counts, and when</h2>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Stage</th>
<th><span class="math inline">\(\omega\)</span> (who counts)</th>
<th><span class="math inline">\(\lambda\)</span> (when)</th>
<th>mlsynth call</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DiD</td>
<td>uniform</td>
<td>uniform</td>
<td><code>FDID(cfg).fit().did</code></td>
</tr>
<tr class="even">
<td>SC</td>
<td>fitted, simplex</td>
<td>uniform</td>
<td><code>VanillaSC(cfg)</code></td>
</tr>
<tr class="odd">
<td>DSC</td>
<td>fitted, simplex + intercept</td>
<td>uniform</td>
<td><code>TSSC(cfg, method="MSCa")</code></td>
</tr>
<tr class="even">
<td>SDID</td>
<td>fitted, simplex + intercept</td>
<td><span class="key">fitted, simplex</span></td>
<td><code>SDID(cfg, zeta=0.0)</code></td>
</tr>
<tr class="odd">
<td>MASC</td>
<td>convex blend of matching and SC</td>
<td>uniform</td>
<td><code>MASC(cfg, set_f=...)</code></td>
</tr>
<tr class="even">
<td>ASCM</td>
<td>SC weights plus a ridge correction</td>
<td>uniform</td>
<td><code>VanillaSC(cfg, augment="ridge")</code></td>
</tr>
</tbody>
</table>
<p><span class="takeaway fragment">One dial for who counts, one for when. Only SDID turns both.</span></p>
<aside class="notes">
<p>This is the table to bookmark. Everything in the next fifteen slides is an expansion of one of these six rows. Note that DSC and SDID share a unit-weight scheme and differ only in the time weights — that is the cleanest controlled comparison on the ladder, and section 11 of the post uses it.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="five-fields-one-long-panel-and-one-config-dict" class="slide level2 center">
<h2>Five fields, one long panel — and one config dict</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-code-line-numbers="1-3|5"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href=""></a><span class="kw">def</span> cfg(post, pre<span class="op">=</span>T0, <span class="op">**</span>extra):</span>
<span id="cb1-2"><a href=""></a>    <span class="cf">return</span> <span class="bu">dict</span>(df<span class="op">=</span>window(post, pre), outcome<span class="op">=</span><span class="st">"log_rgdp"</span>, treat<span class="op">=</span><span class="st">"treat"</span>,</span>
<span id="cb1-3"><a href=""></a>                unitid<span class="op">=</span><span class="st">"country"</span>, time<span class="op">=</span><span class="st">"tt"</span>, display_graphs<span class="op">=</span><span class="va">False</span>, <span class="op">**</span>extra)</span>
<span id="cb1-4"><a href=""></a></span>
<span id="cb1-5"><a href=""></a>res <span class="op">=</span> VanillaSC(cfg(<span class="dv">96</span>, inference<span class="op">=</span><span class="va">False</span>)).fit()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><span class="comment"><code>treat</code> means <em>under treatment right now</em>, not <em>ever treated</em>.</span></p>
<p><span class="takeaway fragment">Every later code block is one line, because <code>cfg</code> already did the work.</span></p>
<aside class="notes">
<p>The <code>treat</code> convention is where most first attempts go wrong. It is not a unit-level “ever treated” flag; it is a unit-period indicator that is zero for the treated unit before treatment. mlsynth infers both the donor pool and the treatment date from it, so getting it wrong does not raise — it silently answers a different question.</p>
<p>The <code>window</code> helper does one more trick worth knowing: it keeps the 86 pre-treatment quarters plus a single quarter of interest and renumbers time, so “the ATT averaged over all post periods” becomes exactly the shortfall at that quarter. No post-estimation arithmetic anywhere in the deck.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="one-result-object-seven-accessors-that-work-everywhere" class="slide level2 smaller center">
<h2>One result object, seven accessors that work everywhere</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Flat accessor</th>
<th>Resolves to</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>.att</code></td>
<td><code>effects.att</code></td>
</tr>
<tr class="even">
<td><code>.att_ci</code></td>
<td><code>(inference.ci_lower, inference.ci_upper)</code></td>
</tr>
<tr class="odd">
<td><code>.counterfactual</code></td>
<td><code>time_series.counterfactual_outcome</code></td>
</tr>
<tr class="even">
<td><code>.gap</code></td>
<td><code>time_series.estimated_gap</code></td>
</tr>
<tr class="odd">
<td><code>.donor_weights</code></td>
<td><code>weights.donor_weights</code></td>
</tr>
<tr class="even">
<td><code>.weight_vector</code></td>
<td>dense array over the donor pool</td>
</tr>
<tr class="odd">
<td><code>.pre_rmse</code></td>
<td><code>fit_diagnostics.rmse_pre</code></td>
</tr>
</tbody>
</table>
<p><span class="takeaway fragment">Learn these seven and you can read the output of any effect estimator in the library without opening its documentation.</span></p>
<aside class="notes">
<p>Two traps behind the convenience. <code>len(result.donor_weights)</code> is 9 here, not 23 — mlsynth returns only the non-zero weights, so do not treat that dictionary as a dense vector. And <code>method_details.method_name</code> reports which backend the “auto” setting actually resolved to, which is precisely the information you need when comparing against another implementation. Come back to that on the solver slide.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="stage-0-did-weights-every-country-and-every-quarter-the-same" class="slide level2 center">
<h2>Stage 0 — DiD weights every country and every quarter the same</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href=""></a>did <span class="op">=</span> FDID(cfg(<span class="dv">96</span>)).fit().did      <span class="co"># no standalone DiD class; it rides inside FDID</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>4.98%</strong> at end-2018 — nearly double every other stage.</p>
<div class="fragment">
<p>23 donors, each weighted exactly <span class="math inline">\(1/23 = 0.0435\)</span>. Nothing was fitted.</p>
<p><span class="takeaway fragment">Pre-treatment RMSE 0.0217 — four times SC’s 0.0056. That gap is why the ladder exists.</span></p>
<aside class="notes">
<p>mlsynth has no standalone DiD class and this trips people up. The textbook two-way estimator comes free inside FDID — Forward DiD, Li 2024 — which fits its own estimator and the plain benchmark side by side and exposes them as <code>.fdid</code> and <code>.did</code>.</p>
<p>A free seventh stage, if you want it: Forward DiD itself selects four donors greedily — Norway, Hungary, Austria, the United States — cuts the pre-treatment RMSE from 0.0217 to 0.0088, and lands at 2.42%, remarkably close to the published 2.4%. Three of its four donors are also among synthetic control’s five largest weights.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="stage-1-synthetic-control-fits-who-counts" class="slide level2 center">
<h2>Stage 1 — Synthetic control fits who counts</h2>
<p><span class="math display">\[\hat\omega = \arg\min_{\omega \in \mathbb{W}} \sum_{t=1}^{T_0} \Big( Y_{\text{UK},t} - \sum_j \omega_j Y_{j,t} \Big)^2, \qquad \mathbb{W} = \Big\{ \omega : \omega_j \ge 0, \ \sum_j \omega_j = 1 \Big\}\]</span></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href=""></a>sc <span class="op">=</span> VanillaSC(cfg(<span class="dv">96</span>, inference<span class="op">=</span><span class="va">False</span>)).fit()      <span class="co"># 3.04%</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><span class="takeaway fragment">Nine of 23 donors get non-zero weight; the simplex zeroes the rest. Pre-treatment <span class="math inline">\(R^2 = 0.998\)</span>.</span></p>
<aside class="notes">
<p>In words: pick the non-negative weights summing to one that make the blend track the UK as closely as possible over the 86 pre-treatment quarters. The sparsity is a feature of the simplex, not an accident, and it is why synthetic control estimates are usually easy to describe in a sentence.</p>
<p>Note that the United States carries about a fifth of the counterfactual. We come back to that in the robustness checks — dropping it moves the SC estimate only from 3.04 to 3.06.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="indistinguishable-until-2016-then-persistently-below" class="slide level2 center">
<h2>Indistinguishable until 2016, then persistently below</h2>

<img data-src="../python_sc_dsc_sdid_04_sc_fit_gap.png" class="r-stretch quarto-figure-center"><p class="caption">UK log real GDP against its synthetic control (top) and the gap between them (bottom), shaded orange after the referendum.</p><p><span class="takeaway fragment">The synthetic UK is roughly a fifth Hungary, a fifth the United States, a fifth Japan, a sixth Canada and an eighth Norway.</span></p>
<aside class="notes">
<p>The top panel is the fit; the bottom panel is the estimate. For two decades the gap hovers around zero — that is the credibility of the design, visible rather than assumed. Then it turns persistently negative from 2016 and keeps widening. The shortfall at the end of 2018 is 3.04%; a year later it is 4.17%.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="stage-2-demeaned-sc-allows-a-level-gap" class="slide level2 center">
<h2>Stage 2 — Demeaned SC allows a level gap</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href=""></a>dsc <span class="op">=</span> TSSC(cfg(<span class="dv">96</span>, method<span class="op">=</span><span class="st">"MSCa"</span>, inference<span class="op">=</span><span class="va">False</span>)).fit()   <span class="co"># 2.99%</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>One extra free parameter — a constant offset. Match the UK’s <strong>shape</strong>, not its <strong>level</strong>.</p>
<p><span class="takeaway fragment">The offset is <span class="math inline">\(+0.0024\)</span> log points. Its smallness is the finding: SC was already level-balanced.</span></p>
<aside class="notes">
<p>Why an offset helps: plain SC will reject a well-shaped blend sitting slightly too high in favour of a worse-shaped blend at the right level. Demeaned SC removes that constraint. Here the offset comes out at a quarter of one per cent of GDP, which is why DSC’s 2.99% sits so close to SC’s 3.04%.</p>
<p>In mlsynth this is the MSCa variant of the Li and Shankar two-step estimator, reached through the TSSC class. Left to itself TSSC fits all four variants — SC, MSCa, MSCb, MSCc — and runs a subsampling procedure to choose one; here it recommends plain SC, because the Step-1 test does not reject the restriction.</p>
<p>The cost of that convenience is real: four variants with 500 subsampling draws takes about 17 seconds, forcing one variant with inference off takes 0.01 seconds. A factor of roughly 1,700, which is exactly why the placebo tournament in Act IV sets <code>method=</code> and <code>inference=False</code>.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="stage-3-sdid-also-fits-which-quarters-count" class="slide level2 center">
<h2>Stage 3 — SDID also fits which quarters count</h2>
<p><span class="math display">\[\hat\tau_t = \Big( Y_{\text{UK},t} - \sum_j \hat\omega_j Y_{j,t} \Big) - \sum_{s \le T_0} \hat\lambda_s \Big( Y_{\text{UK},s} - \sum_j \hat\omega_j Y_{j,s} \Big)\]</span></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href=""></a>sdid <span class="op">=</span> SDID(cfg(<span class="dv">96</span>, zeta<span class="op">=</span><span class="fl">0.0</span>, vce<span class="op">=</span><span class="st">"placebo"</span>, B<span class="op">=</span><span class="dv">500</span>)).fit()   <span class="co"># 2.80%</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><span class="comment">The gap at the evaluation quarter, minus the <span class="math inline">\(\lambda\)</span>-weighted average gap before it.</span></p>
<aside class="notes">
<p>SDID solves the transposed version of the same problem: which blend of quarters, judged across all donors, best predicts the treatment quarter. DSC still treats all 86 pre-treatment quarters as equally informative; SDID does not.</p>
<p>Note the standard error already: 0.0264 against a point estimate of 0.0280, which gives a confidence interval that comfortably contains zero and a placebo p-value of 0.20. Hold that thought until the objection slide.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="and-the-time-weights-collapse-onto-one-quarter" class="slide level2 center">
<h2>And the time weights collapse onto one quarter</h2>

<img data-src="../python_sc_dsc_sdid_06_sdid_time_weights.png" class="r-stretch quarto-figure-center"><p class="caption">Stem plot of SDID’s 86 time weights. Almost all the mass sits on 2016Q2; the dashed line is the uniform weight DiD would use.</p><p><span class="takeaway fragment"><strong>0.958</strong> on 2016Q2 against DiD’s uniform <span class="math inline">\(1/86 \approx 0.012\)</span>.</span></p>
<aside class="notes">
<p>95.85% of the mass on the last pre-treatment quarter, 3.9% on 2008Q4, 0.3% on 2014Q3, and essentially nothing on the other 83.</p>
<p>Do not read this as a bug. Read it as SDID correctly discovering that most of the pre-treatment history is not informative about the level at the treatment date. The source paper reports the same collapse and attributes it to the same cause. It is also a warning: if your outcome is a near-random walk, SDID’s “time weights” are close to a one-period comparison, whatever the method’s name suggests.</p>
<p>Practical note: the time weights live on the cohort object, not on <code>weights</code>. <code>list(result.cohorts.values())[0].time_weights</code>.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="flat-before-negative-after" class="slide level2 center">
<h2>Flat before, negative after</h2>

<img data-src="../python_sc_dsc_sdid_07_sdid_event_study.png" class="r-stretch quarto-figure-center"><p class="caption">SDID event study by quarters since the referendum, with a 95% placebo confidence band.</p><p><span class="takeaway fragment">Pre-treatment effects average <span class="math inline">\(+0.0021\)</span>, post-treatment <span class="math inline">\(-0.0281\)</span> — a falsification test the single ATT number cannot give you, for the cost of one extra line.</span></p>
<aside class="notes">
<p><code>result.event_study</code> is aggregated alongside the headline ATT, which the R packages on this ladder do not do. The flat pre-treatment path is the part that matters: it is evidence about the design rather than about the effect, and it is the kind of thing a reader will ask for.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="stages-4-and-5-buy-the-trade-off-or-drop-the-constraint" class="slide level2 smaller center">
<h2>Stages 4 and 5 — buy the trade-off, or drop the constraint</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="masc-blend-with-matching">MASC — blend with matching</h3>
<p><span class="math display">\[\hat{Y}^{\text{MASC}} = \phi\,\hat{Y}^{\text{match}}_m + (1-\phi)\,\hat{Y}^{\text{SC}}\]</span></p>
<p><code>MASC(cfg, m_grid=..., set_f=...)</code></p>
<p>CV picks <span class="math inline">\(m = 10\)</span>, <span class="math inline">\(\phi = 0.158\)</span>.</p>
<p><strong>2.73%</strong> — the lowest stage.</p>
</div><div class="column" style="width:50%;">
<h3 id="ascm-relax-the-simplex">ASCM — relax the simplex</h3>
<p>Ridge-correct what the simplex cannot close. Negative weights allowed.</p>
<p><code>VanillaSC(cfg, augment="ridge")</code></p>
<p>Eight negative weights, largest <span class="math inline">\(-0.009\)</span>.</p>
<p><strong>3.04%</strong> — same as plain SC.</p>
</div></div>
<p><span class="takeaway fragment">The UK sits comfortably inside the hull, so there is almost nothing to correct.</span></p>
<aside class="notes">
<p>The motivation for MASC is the bias decomposition: synthetic control attacks extrapolation bias, matching attacks interpolation bias, and the cross-validation buys whichever trade-off the data prefer.</p>
<p>Two mlsynth gotchas here. MASC’s tuned dials live in <code>weights.summary_stats</code>, not in <code>method_details.parameters_used</code>, which is None for this estimator. And ASCM’s <code>residualize=True</code> — the paper’s “ASCM res.” column — returns identical numbers with no covariates supplied, which is correct behaviour rather than a silent failure.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="five-estimators-essentially-the-same-five-countries" class="slide level2 center">
<h2>Five estimators, essentially the same five countries</h2>

<img data-src="../python_sc_dsc_sdid_09_donor_weights.png" class="r-stretch quarto-figure-center"><p class="caption">Donor weights under SC, DSC, SDID, MASC and augmented SC across the donor pool; the shaded region marks negative weights.</p><p><span class="takeaway fragment">Hungary, the United States, Japan, Canada and Norway carry 87-91% of the counterfactual under every method. Only ASCM ever goes negative.</span></p>
<aside class="notes">
<p>Five estimators built on quite different principles are picking essentially the same five countries. That is reassuring in a way the point estimates alone are not: the disagreement between stages is not a disagreement about which countries resemble the UK.</p>
<p>MASC spreads a small uniform-looking 0.0158 across seven otherwise-zero donors — that is the matching component showing through.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-paths-agree-until-the-referendum-then-fan-apart" class="slide level2 center">
<h2>The paths agree until the referendum, then fan apart</h2>

<img data-src="../python_sc_dsc_sdid_10_all_counterfactuals.png" class="r-stretch quarto-figure-center"><p class="caption">Six counterfactual paths for the United Kingdom alongside the observed series, 2014-2020.</p><p><span class="takeaway fragment">Difference-in-differences is the clear outlier. The other five are hard to tell apart by eye — which is the point.</span></p>
<aside class="notes">
<p>This is one call: fit each stage on the untruncated panel and overlay the counterfactuals. Before 2016 they are all on top of each other and on top of the data. After 2016 they fan, and the fan is the specification uncertainty made visible.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-whole-ladder-side-by-side" class="slide level2 smaller center">
<h2>The whole ladder, side by side</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Stage</th>
<th>mlsynth call</th>
<th style="text-align: right;">end-2018</th>
<th style="text-align: right;">end-2019</th>
<th style="text-align: right;">published</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DiD</td>
<td><code>FDID(...).fit().did</code></td>
<td style="text-align: right;">4.98</td>
<td style="text-align: right;">6.18</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td>SC</td>
<td><code>VanillaSC(...)</code></td>
<td style="text-align: right;">3.04</td>
<td style="text-align: right;">4.17</td>
<td style="text-align: right;">3.06</td>
</tr>
<tr class="odd">
<td>DSC</td>
<td><code>TSSC(..., method="MSCa")</code></td>
<td style="text-align: right;">2.99</td>
<td style="text-align: right;">4.12</td>
<td style="text-align: right;">2.98</td>
</tr>
<tr class="even">
<td>SDID</td>
<td><code>SDID(..., zeta=0.0)</code></td>
<td style="text-align: right;"><span class="key">2.80</span></td>
<td style="text-align: right;">3.94</td>
<td style="text-align: right;">2.79</td>
</tr>
<tr class="odd">
<td>MASC</td>
<td><code>MASC(..., set_f=range(6, 87))</code></td>
<td style="text-align: right;">2.73</td>
<td style="text-align: right;">3.83</td>
<td style="text-align: right;">2.73</td>
</tr>
<tr class="even">
<td>ASCM</td>
<td><code>VanillaSC(..., augment="ridge")</code></td>
<td style="text-align: right;">3.04</td>
<td style="text-align: right;">4.19</td>
<td style="text-align: right;">3.04</td>
</tr>
</tbody>
</table>
<p><span class="takeaway fragment">The width of the cluster — 2.73-3.04% — not any point inside it, is the honest answer.</span></p>
<aside class="notes">
<p>The published column is the R edition of this post, using synthdid, Synth, masc and augsynth. Three of the six stages — DiD, MASC and ASCM — agree to two decimals. DSC lands a hundredth above only because 2.9887 sits on a rounding boundary.</p>
<p>The two real disagreements are SC (3.04 against 3.06) and SDID (2.80 against 2.79), and both differ in the same direction and for the same reason. That reason is the last slide of the next act.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="every-stage-exceeds-the-published-2.4" class="slide level2 center">
<h2>Every stage exceeds the published 2.4%</h2>

<img data-src="../python_sc_dsc_sdid_11_att_dotplot.png" class="r-stretch quarto-figure-center"><p class="caption">Every stage’s estimated UK GDP shortfall at 2018Q4 and 2019Q4, with the three SDID flavours shown separately; the dashed line is the published 2.4%.</p><p><span class="takeaway fragment"><strong>2.73-3.04%</strong> at end-2018 and <strong>3.83-4.19%</strong> a year later — every stage above the 2.4% previously published for this same dataset.</span></p>
<aside class="notes">
<p>The earlier 2.4% came from a specification that matched on covariates. The covariate slides in the next act show why that matters here: on this panel, covariates make the counterfactual worse rather than better.</p>
<p>Also visible: the three SDID flavours sit almost on top of each other, within 0.03 percentage points. The choice among SDID variants is not where the uncertainty lives — which is worth remembering when we reach the published placebo ranking.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="the-defaults" class="title-slide slide level1 divider center" data-background-color="#141413">
<h1>The Defaults</h1>
<p><span class="act">Act III</span></p>
</section>
<section id="three-defaults-each-move-the-answer-more-than-the-ladder-does" class="slide level2 smaller center">
<h2>Three defaults each move the answer more than the ladder does</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Setting</th>
<th style="text-align: right;">At its default</th>
<th style="text-align: right;">Set deliberately</th>
<th style="text-align: right;">Moves the estimate by</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>zeta</code> — SDID’s unit-weight penalty</td>
<td style="text-align: right;">2.67</td>
<td style="text-align: right;">2.80</td>
<td style="text-align: right;">0.13 pp</td>
</tr>
<tr class="even">
<td><code>set_f</code> — MASC’s cross-validation folds</td>
<td style="text-align: right;">3.19</td>
<td style="text-align: right;">2.73</td>
<td style="text-align: right;">0.47 pp</td>
</tr>
<tr class="odd">
<td>the covariate method</td>
<td style="text-align: right;">3.61</td>
<td style="text-align: right;">1.85</td>
<td style="text-align: right;"><span class="key">1.76 pp</span></td>
</tr>
<tr class="even">
<td><em>the whole ladder, DiD excluded</em></td>
<td style="text-align: right;"><em>2.73</em></td>
<td style="text-align: right;"><em>3.04</em></td>
<td style="text-align: right;"><em>0.31 pp</em></td>
</tr>
</tbody>
</table>
<p><span class="takeaway fragment">You can pick the wrong default and land further from the truth than if you had picked the wrong estimator.</span></p>
<aside class="notes">
<p>This is the thesis of the deck, and it is not an econometric finding — it is a software finding. None of these three defaults is wrong. Each is a defensible choice that happens not to be the one your reference used. The covariate spread alone is nearly six times the entire spread across the ladder.</p>
<p>The practical implication is on the takeaways slide: when you report a synthetic control estimate, say which defaults you set. On this dataset that sentence carries more information than the name of the estimator.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="zeta-penalises-the-unit-weights-unless-you-pass-a-literal-zero" class="slide level2 center">
<h2><code>zeta</code> penalises the unit weights unless you pass a literal zero</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6" data-code-line-numbers="1|2"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href=""></a>SDID(cfg(<span class="dv">96</span>)).fit()                   <span class="co"># zeta at its default  -&gt;  2.67%</span></span>
<span id="cb6-2"><a href=""></a>SDID(cfg(<span class="dv">96</span>, zeta<span class="op">=</span><span class="fl">0.0</span>)).fit()         <span class="co"># what the paper solves -&gt;  2.80%</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Every language penalises by default: R needs <code>zeta.omega = 0</code>, Stata needs <code>zeta_omega(0)</code>.</p>
<p><span class="takeaway fragment">0.13 pp — larger than the whole spread between SC, DSC and ASCM.</span></p>
<aside class="notes">
<p>Stata’s version is the nastiest of the three. Its documented default is <code>zeta_omega(1e-6)</code>, which looks like a value but is a magic sentinel: sdid.ado reads <code>if (EOmega==1e-6) EtaOmega = (yNtr*yTpost)^(1/4)</code>, so passing the documented default explicitly still requests the full penalty. Only a literal zero switches it off.</p>
<p>The lesson survives translation. If you are replicating a published synthetic-DiD number, find out what the authors did with the penalty before concluding anything about the data.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="set_f-decides-which-folds-masc-learns-from" class="slide level2 center">
<h2><code>set_f</code> decides which folds MASC learns from</h2>

<img data-src="../python_sc_dsc_sdid_08_masc_cv.png" class="r-stretch quarto-figure-center"><p class="caption">The 2018Q4 estimate for each forced neighbour count from 1 to 10, each bar labelled with its phi; the dashed line marks the freely cross-validated 2.73%.</p><p><span class="takeaway fragment"><code>set_f=range(6, 87)</code> gives <strong>2.73%</strong>; the default <code>min_preperiods</code> resolves to 43 and gives <strong>3.19%</strong>. One argument, 0.47 pp.</span></p>
<aside class="notes">
<p>Two patterns in the bars. First, phi rises with m — the more neighbours you average over, the more weight the cross-validation is willing to give matching, because averaging reduces the variance that makes matching unattractive. Second, the estimate is not monotone in m: it wanders between 2.73% and 3.23% with no obvious structure.</p>
<p>That non-monotonicity is worth remembering when someone reports a single MASC number without saying what grid produced it.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="control-for-a-covariate-means-three-different-things" class="slide level2 smaller center">
<h2>“Control for a covariate” means three different things</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Key</th>
<th>Method</th>
<th>What it does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>"adjust"</code></td>
<td>Kranz (2022)</td>
<td>residualise the <em>outcome</em>, then run SDID</td>
</tr>
<tr class="even">
<td><code>"match"</code></td>
<td>de Brabander et al.</td>
<td>covariates <em>inside</em> the unit-weight problem</td>
</tr>
<tr class="odd">
<td><code>"optimized"</code></td>
<td>Arkhangelsky et al.</td>
<td>weights and coefficients <em>jointly</em></td>
</tr>
</tbody>
</table>
<p><code>covariates</code> is a dict keyed by method. Pass a bare list and it raises.</p>
<p><span class="takeaway fragment">Three defensible readings in the literature — so three different estimators.</span></p>
<aside class="notes">
<p>The API design here is the honest one: rather than pick a house convention and hide it, mlsynth forces you to name which of the three you mean. The companion setting <code>match_pre_periods</code> takes “all”, “half”, “last” or an integer, and mlsynth’s own benchmarks report that agreement with R’s Synth degrades from a weight correlation of 0.998 under “last” to 0.636 under “all”.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="and-they-disagree-by-1.76-percentage-points" class="slide level2 center">
<h2>And they disagree by 1.76 percentage points</h2>

<img data-src="../python_sc_dsc_sdid_13_covariate_methods.png" class="r-stretch quarto-figure-center"><p class="caption">SDID with no covariates and under the adjust, match and optimized methods, plus VanillaSC’s bilevel route; the dashed line is the published 2.4%.</p><p><span class="takeaway fragment">3.61 / 1.85 / 3.11 against 2.80 with no covariates at all.</span></p>
<aside class="notes">
<p>The cleanest demonstration is in VanillaSC. Fit the identical bilevel model twice with the same seed and the same data, changing only how long the differential-evolution search runs. If the predictor weights V were well identified, the budget would not matter. It does: the estimate moves from 1.32% to 1.11%, and the predictor weights move from a corner solution putting everything on the import share to a spread across labour productivity, employment and the consumption and investment shares. Those are different economic stories about what makes a country comparable to the UK.</p>
<p>Three diagnostics agree: the pre-treatment fit gets worse, <code>v_agreement</code> sits at 0.055 to 0.083 rather than near zero, and the answer moves with the optimiser budget — which is the definition of a non-identified problem. With 86 quarters of the outcome itself already in the matching set, six covariate means are not adding information.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="one-estimator-silently-rounds-the-number-you-are-most-likely-to-quote" class="slide level2 center">
<h2>One estimator silently rounds the number you are most likely to quote</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7" data-code-line-numbers="1|2"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href=""></a>d18.att                    <span class="co"># -0.03                -&gt;  3.0000%</span></span>
<span id="cb7-2"><a href=""></a>np.asarray(d18.gap)[<span class="op">-</span><span class="dv">1</span>]    <span class="co"># -0.0298873295228968  -&gt;  2.9887%</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>TSSC</code> rounds every scalar. The series stay full precision.</p>
<p><span class="takeaway fragment">When the scalar and the series disagree — trust the series.</span></p>
<aside class="notes">
<p><code>rmse_pre</code> is rounded too — it comes back as 0.006. All four TSSC variants report <code>.att</code> as exactly minus 0.03, while their gap series carry 3.039, 2.989, 3.041 and 3.021. A hundredth of a percentage point will not change anyone’s policy view, but it will make you think you have failed to replicate a table when you have not.</p>
<p>The fix is three lines: read the last element of the unrounded gap series instead of the scalar.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-name-is-a-mnemonic-not-a-definition" class="slide level2 smaller center">
<h2>A name is a mnemonic, not a definition</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Class</th>
<th>Is actually</th>
<th>Not to be confused with</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>DSC</code></td>
<td><strong>D</strong>istributional SC (Gunsilius)</td>
<td>demeaned SC = <code>TSSC(method="MSCa")</code></td>
</tr>
<tr class="even">
<td><code>DSCAR</code></td>
<td><strong>D</strong>ynamic SC for <strong>A</strong>uto-<strong>R</strong>egressive processes</td>
<td>either of the above</td>
</tr>
<tr class="odd">
<td><code>SCD</code></td>
<td>SC with <strong>D</strong>ifferencing</td>
<td><code>DSC</code></td>
</tr>
<tr class="even">
<td><code>DRSC</code></td>
<td><strong>D</strong>istribution-<strong>R</strong>egression SC</td>
<td><code>DSC</code></td>
</tr>
<tr class="odd">
<td><code>MEDSC</code></td>
<td><strong>Med</strong>iation SC</td>
<td>demeaned SC</td>
</tr>
</tbody>
</table>
<p><span class="takeaway fragment"><code>mlsynth.DSC</code> is not this deck’s DSC — and importing it raises no error.</span></p>
<aside class="notes">
<p>This is the failure mode a package with 92 estimators cannot fully design away, and it is the one worth flagging to students. Every one of these classes is correct and documented. The hazard is entirely in the reader’s head — you go looking for demeaned synthetic control, you find a class called DSC, and it fits without complaint.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-synthetic-control-estimate-carries-its-solvers-fingerprint" class="slide level2 center">
<h2>A synthetic control estimate carries its solver’s fingerprint</h2>

<img data-src="../python_sc_dsc_sdid_03_solver_comparison.png" class="r-stretch quarto-figure-center"><p class="caption">Four mlsynth solver routes, all at 3.039%, against R’s Frank-Wolfe implementation at 3.060%.</p><p><span class="takeaway fragment">Three languages, two camps — split by optimiser, not by author. Replicate a published number and land 0.02 away? Suspect the optimiser before the data.</span></p>
<aside class="notes">
<p>The synthetic-control objective on this panel has a condition number of roughly 7.5 times ten to the fifth: a long, narrow, nearly flat valley of near-optimal weight vectors. Any optimiser has to decide when to stop walking down it.</p>
<p>R’s synthdid walks it with Frank-Wolfe on a capped iteration budget and stops at 3.06%. mlsynth hands the identical problem to a convex solver which runs it to optimality and returns 3.039%. Stata’s sdid inherits synthdid’s Frank-Wolfe and stops in the same place — tighten its convergence and its SDID estimate drifts from 2.79% to 2.80%, which is where mlsynth already is.</p>
<p>Four independent code paths inside mlsynth — two backends, an explicit constraint family, and a completely different estimator class — agree to three decimals. This is not a bug in either library. It is the normal state of affairs, and the post ships all three cheat sheets so you can run the comparison yourself.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="which-stage" class="title-slide slide level1 divider center" data-background-color="#00d4c8">
<h1>Which Stage?</h1>
<p><span class="act">Act IV</span></p>
</section>
<section id="score-the-stages-on-a-task-whose-true-answer-is-zero" class="slide level2 center">
<h2>Score the stages on a task whose true answer is zero</h2>
<p>Move the treatment date to a quarter when nothing happened.</p>
<div class="fragment">
<p>The true effect is zero, so every estimate is pure error.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href=""></a><span class="kw">def</span> placebo_one(k, h):</span>
<span id="cb8-2"><a href=""></a>    <span class="co">"""Fit every stage on 1..k, predict k + h. Truth is zero."""</span></span>
<span id="cb8-3"><a href=""></a>    ...</span>
<span id="cb8-4"><a href=""></a></span>
<span id="cb8-5"><a href=""></a>errors <span class="op">=</span> [placebo_one(k, h) <span class="cf">for</span> k <span class="kw">in</span> FAKE_DATES <span class="cf">for</span> h <span class="kw">in</span> (<span class="dv">1</span>, <span class="dv">4</span>)]   <span class="co"># 20 dates</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><span class="takeaway fragment"><code>inference=False</code> and an explicit <code>m_grid</code> are what keep this to <strong>13 seconds</strong>.</span></p>
<aside class="notes">
<p>Everything the earlier acts taught about defaults now pays off in wall-clock time. Twenty dates times seven estimators, refit from scratch each pass, is 140 fits. The four settings that make it tractable are <code>vce="noinference"</code> on SDID, <code>method="MSCa"</code> and <code>inference=False</code> on TSSC, and an explicit <code>m_grid</code> on MASC. With TSSC left to select its own variant, that step alone would be around forty minutes.</p>
<p>This is the source paper’s answer to “which stage”, and it is a good one — but read the next slide before accepting the ranking it produces.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="the-time-weights-earn-their-keep" class="slide level2 center">
<h2>The time weights earn their keep</h2>

<img data-src="../python_sc_dsc_sdid_12_placebo_tournament.png" class="r-stretch quarto-figure-center"><p class="caption">Twenty placebo errors for each of the seven estimators, graded one quarter ahead and four quarters ahead; the orange diamond marks the RMSE.</p><p><span class="takeaway fragment">At <span class="math inline">\(h = 1\)</span>: SDID <strong>0.0066</strong> against <strong>0.0086</strong> for SC, DSC and ASCM — a 23% cut.</span></p>
<aside class="notes">
<p>This is the paper’s central theoretical claim surviving an empirical test. The time weights are not decoration; on this panel they buy a genuine improvement in out-of-sample prediction, and the ordering below SDID is stable — MASC, then SC, ASCM and DSC, and those last three are indistinguishable.</p>
<p>MASC at 0.0080 sits between them, which is roughly what you would expect from an estimator that is five-sixths synthetic control.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="but-the-published-ranking-was-graded-on-a-different-exam" class="slide level2 smaller center">
<h2>But the published ranking was graded on a different exam</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Method</th>
<th style="text-align: right;">RMSE, <span class="math inline">\(h = 1\)</span></th>
<th style="text-align: right;">RMSE, <span class="math inline">\(h = 4\)</span></th>
<th style="text-align: right;">Published</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SC</td>
<td style="text-align: right;">0.0086</td>
<td style="text-align: right;">0.0145</td>
<td style="text-align: right;">0.0089</td>
</tr>
<tr class="even">
<td>DSC</td>
<td style="text-align: right;">0.0086</td>
<td style="text-align: right;">0.0146</td>
<td style="text-align: right;">0.0087</td>
</tr>
<tr class="odd">
<td>SDID (i)</td>
<td style="text-align: right;">0.0066</td>
<td style="text-align: right;">0.0132</td>
<td style="text-align: right;">0.0067</td>
</tr>
<tr class="even">
<td>SDID (ii)</td>
<td style="text-align: right;">0.0066</td>
<td style="text-align: right;">0.0133</td>
<td style="text-align: right;"><span class="key">0.0134</span></td>
</tr>
<tr class="odd">
<td>SDID (iii)</td>
<td style="text-align: right;">0.0066</td>
<td style="text-align: right;">0.0133</td>
<td style="text-align: right;"><span class="key">0.0134</span></td>
</tr>
<tr class="even">
<td>MASC</td>
<td style="text-align: right;">0.0080</td>
<td style="text-align: right;">0.0140</td>
<td style="text-align: right;">0.0080</td>
</tr>
<tr class="odd">
<td>ASCM</td>
<td style="text-align: right;">0.0086</td>
<td style="text-align: right;">0.0146</td>
<td style="text-align: right;">0.0086</td>
</tr>
</tbody>
</table>
<p><span class="takeaway fragment">Two rows were graded four quarters ahead. Matched, the three SDID flavours are indistinguishable.</span></p>
<aside class="notes">
<p>Every cell reproduces the published value to within 0.0003 except the two that were graded on a different task. Forecasting a year out is strictly harder, so part of the reported gap is the horizon.</p>
<p>The published conclusion that variants (ii) and (iii) “perform the worst” is an artefact. What survives is the finding that matters more: at either horizon the whole SDID family beats every other stage. The R edition of this post reaches the same conclusion with a different library, which is about as much corroboration as a result of this kind can get.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-uks-gap-is-deeper-than-any-placebos" class="slide level2 center">
<h2>The UK’s gap is deeper than any placebo’s</h2>

<img data-src="../python_sc_dsc_sdid_14_placebo_in_space.png" class="r-stretch quarto-figure-center"><p class="caption">Twenty-three grey placebo gap paths, one per donor given the treatment in turn, with the United Kingdom in orange.</p><p><span class="takeaway fragment">RMSPE ratio <strong>5.85</strong>, rank <strong>1 of 24</strong>, giving a permutation p-value of <span class="math inline">\(1/24 = 0.042\)</span>.</span></p>
<aside class="notes">
<p>The statistic is the ratio of post-treatment to pre-treatment root mean squared prediction error. Dividing by the pre-treatment fit is what stops a badly fitted donor from looking treated — Finland’s raw post-treatment error is larger than the UK’s, but its pre-treatment fit is four times worse.</p>
<p>The UK is first, Belgium second at 3.52, Finland third at 3.29. First of 24 is the best rank available.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-strongest-objection-and-the-answer" class="slide level2 center">
<h2>The strongest objection — and the answer</h2>
<p><span class="objection">Objection.</span> <span class="math inline">\(p = 0.042\)</span> is the <em>smallest attainable</em> with 24 units — the test is at its floor. And SDID’s own interval contains zero.</p>
<div class="fragment">
<p><span class="rebuttal">Response.</span> Five inference routes span <span class="math inline">\(p = 0.006\)</span> to <span class="math inline">\(0.042\)</span> and all reject at 5%. But the floor is real, and no estimator changes it.</p>
</div>
<div class="fragment">
<p><span class="takeaway fragment">Which is why the deliverable is the cluster, not the point.</span></p>
<aside class="notes">
<p>Steelman this properly. The five inference methods are not five independent tests — they share a point estimate and a donor pool and differ only in how they build a reference distribution from 23 donors. Read them as orders of magnitude, not as digits.</p>
<p>Three further caveats belong with the number. It is a net gap between the UK and a blend of OECD economies, so anything else distinctive that happened to the UK after mid-2016 is inside it. The no-interference assumption is strong over four years when the United States carries a fifth of the weight. And <code>jackknife_plus</code> raises MlsynthEstimationError on this configuration and is excluded — reported rather than quietly dropped.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="what-the-referendum-cost" class="slide level2 center" data-background-color="#1a3a8a">
<h2>What the referendum cost</h2>
<p><span class="bignum">2.7 – 3.0%</span></p>
<p><span class="bignum-label">UK GDP shortfall at end-2018, at every stage of the ladder · 3.8 – 4.2% a year later · against 2.4% previously published</span></p>
<aside class="notes">
<p>That is the answer, and the range is the answer — not a rounding of some sharper number we could have reported instead. Every stage of the ladder puts the cost above the previously published 2.4%, and the reason is not exotic: the earlier figure came from a specification that matched on covariates, and on this panel covariates make the counterfactual worse.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-to-take-away" class="slide level2 center">
<h2>What to take away</h2>
<ol type="1">
<li><strong>Fit the ladder, not a stage.</strong> Publish the cloud — six estimators, one config, thirteen seconds.</li>
<li><strong>Say which defaults you set.</strong> Here that matters more than the estimator’s name.</li>
<li><strong>Pin the commit, not the release.</strong> A version number is not a version.</li>
<li><strong>A second-decimal disagreement is the optimiser</strong>, not the data.</li>
</ol>
<aside class="notes">
<p>If the audience remembers one thing, make it the second point. The econometrics on this ladder is settled and well documented. What is not documented anywhere except in source code is which knob your reference turned, and that turns out to matter more.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="materials" class="slide level2 smaller center">
<h2>Materials</h2>
<ul>
<li><strong>Post, notebook, Colab</strong> — <a href="./post/python_sc_dsc_sdid/">carlos-mendez.org/post/python_sc_dsc_sdid</a></li>
<li><strong>Three cheat sheets</strong> — Python, R and Stata; each hard-codes the others’ column.</li>
<li><strong>R edition</strong> — <a href="./post/r_sc_dsc_sdid/">r_sc_dsc_sdid</a> hand-codes every estimator; go there for the derivations.</li>
<li><strong>Data</strong> — Born, Müller, Schularick and Sedláček (2019), via de Brabander et al.</li>
<li><strong>Library</strong> — <code>mlsynth</code> by Jared Greathouse, pinned at <code>15f168b</code>.</li>
</ul>
<aside class="notes">
<p>On the cheat sheets: same data, same treatment date, same two evaluation quarters, same comparative table at the end. Each file hard-codes the other languages’ column, so a disagreement shows up the moment you run any one of them. Python takes about half a minute, Stata twenty seconds with standard errors off, R thirty seconds with SE set to FALSE.</p>
<p>Next steps from here, all taking the config you already wrote: CLUSTERSC or PDA if you have many more donors than periods; SequentialSDID if adoption is staggered; SPOTSYNTH if you suspect spillovers onto the donor pool.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section id="fit-the-ladder-not-a-stage-and-publish-the-cloud-not-the-point." class="title-slide slide level1 divider center" data-background-color="#1a3a8a">
<h1>Fit the ladder, not a stage — and publish the cloud, not the point.</h1>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="slides_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="slides_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="slides_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="slides_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="slides_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="slides_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="slides_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>