* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- fwl_store_data.dta ----
use "fwl_store_data.dta", clear
label data "Simulated retail stores: sales, coupons, income, day of week"
note _dta: Simulated by script.py with numpy default_rng(42) (PCG64): income ~ N(50, 10); dayofweek uniform on 1-7; coupons = 60 - 0.5 x income + N(0, 5); sales = 10 + 0.2 x coupons + 0.3 x income + 0.5 x dayofweek + N(0, 3). True coupon effect +0.2. sales, coupons and income rounded to 2 decimals.
note sales: Daily sales of the store - the outcome variable. One unit is 1,000 US dollars. Construction: sales = 10 + 0.2 x coupons + 0.3 x income + 0.5 x dayofweek + e, e ~ N(0, 3); computed from the unrounded draws, then rounded to 2 decimals. Units: thousands of US dollars. Source: Simulation (script.py, seed 42)
note coupons: Coupon usage at the store, in percent - the treatment (regressor of interest). Its true effect on sales is +0.2 per percentage point. Construction: coupons = 60 - 0.5 x income + u, u ~ N(0, 5); rounded to 2 decimals. Wealthier neighborhoods use fewer coupons. Units: percent. Source: Simulation (script.py, seed 42)
note income: Income of the store's neighborhood - the confounder: it lowers coupon usage (-0.5 per unit) and raises sales (+0.3 per unit). Construction: income ~ N(50, 10); rounded to 2 decimals. Units: thousands of US dollars. Source: Simulation (script.py, seed 42)
note dayofweek: Day-of-week index, an integer from 1 to 7. It shifts sales (+0.5 per step) but is unrelated to coupons by construction; the post adds it as a second control. No weekday names are attached to the codes. Construction: rng.integers(1, 8): uniform on the integers 1 to 7 (the upper bound 8 is exclusive). Units: index 1-7. Source: Simulation (script.py, seed 42)
save "fwl_store_data.dta", replace
