* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- synthetic_ekc_panel.dta ----
use "synthetic_ekc_panel.dta", clear
label data "Synthetic country-year EKC panel: CO2, GDP cubic + 12 controls"
note _dta: Balanced annual panel of 80 synthetic countries, 1995-2014 (1,600 obs). Outcome is log CO2 per capita generated from a cubic GDP polynomial + 5 true controls + country/year fixed effects + noise; 7 further controls are pure noise (true coefficient 0). Set as a panel with xtset country_id year, yearly. Inspired by Gravina & Lanzafame (2025) but fully synthetic.
note country_id: Synthetic country identifier (1-80); no real-country mapping.. Construction: Sequential 1..80 assigned at panel creation (gen country_id = _n).. Units: integer (1-80). Source: Simulation
note year: Annual time index, 1995-2014.. Construction: 1995 + sequence within country (20 years per country, balanced).. Units: year. Source: Simulation
note ln_co2: Outcome variable: natural log of CO2 emissions per capita.. Construction: Generated from the DGP: b1*ln_gdp + b2*ln_gdp_sq + b3*ln_gdp_cb + 5 true controls + country FE + year FE + N(0,0.15) noise.. Units: log. Source: Simulation (DGP outcome)
note ln_gdp: Log GDP per capita; the income axis of the EKC.. Construction: Country baseline (uniform 7.0-11.5) + annual growth*(year-1995) + N(0,0.05) noise.. Units: log international $. Source: Simulation
note ln_gdp_sq: Quadratic GDP term for the EKC polynomial.. Construction: ln_gdp^2.. Units: log^2. Source: Derived
note ln_gdp_cb: Cubic GDP term (inverted-N) for the EKC polynomial.. Construction: ln_gdp^3.. Units: log^3. Source: Derived
note fossil_fuel: TRUE predictor (coef +0.015): fossil-fuel share of energy; more fossil fuels -> more CO2.. Construction: Country base (correlated with GDP) + N(0,3) noise - 0.3*(year-1995), bounded to [5,95].. Units: % (5-95). Source: Simulation (true predictor)
note renewable: TRUE predictor (coef -0.010): renewable share of energy; more renewables -> less CO2.. Construction: Country base (negatively correlated with GDP) + N(0,2) + 0.4*(year-1995), bounded to [1,80].. Units: % (1-80). Source: Simulation (true predictor)
note urban: TRUE predictor (coef +0.007, weak): urbanization rate; more urban -> more CO2.. Construction: Country base (correlated with GDP) + N(0,1.5) + 0.3*(year-1995), bounded to [10,95].. Units: % (10-95). Source: Simulation (true predictor)
note globalization: NOISE control (true coef 0): tricky decoy, strongly correlated with GDP.. Construction: Country base (strong GDP corr) + N(0,3) + 0.2*(year-1995), bounded to [20,95].. Units: index (20-95). Source: Simulation (noise)
note pop_density: NOISE control (true coef 0): population density; no GDP correlation.. Construction: Log-normal base exp(N(4,1.2)) * (1+0.01*(year-1995)) + N(0,5), floored at 1.. Units: persons per km^2. Source: Simulation (noise)
note democracy: TRUE predictor (coef -0.005, weak): democracy index (-10 to 10); more democracy -> less CO2.. Construction: Country base (uniform -5..10) + N(0,0.5), bounded to [-10,10].. Units: index (-10 to 10). Source: Simulation (true predictor)
note corruption: NOISE control (true coef 0): corruption score; no GDP correlation.. Construction: Country base (uniform 0-100) + N(0,5), bounded to [0,100].. Units: index (0-100). Source: Simulation (noise)
note industry: TRUE predictor (coef +0.010): industry value added share; more industry -> more CO2.. Construction: Country base (correlated with GDP) + N(0,2) - 0.1*(year-1995), bounded to [5,60].. Units: % of GDP (5-60). Source: Simulation (true predictor)
note services: NOISE control (true coef 0): tricky decoy, strongly correlated with GDP.. Construction: Country base (strong GDP corr) + N(0,2) + 0.2*(year-1995), bounded to [10,80].. Units: % of GDP (10-80). Source: Simulation (noise)
note trade: NOISE control (true coef 0): trade openness; moderately correlated with GDP.. Construction: Country base (moderate GDP corr) + N(0,5), bounded to [10,200].. Units: % of GDP (10-200). Source: Simulation (noise)
note fdi: NOISE control (true coef 0): foreign direct investment inflows; no GDP correlation.. Construction: Country base N(3,4) + N(0,2).. Units: % of GDP. Source: Simulation (noise)
note credit: NOISE control (true coef 0): domestic credit; moderately correlated with GDP.. Construction: Country base (moderate GDP corr) + N(0,5) + 0.3*(year-1995), floored at 5.. Units: % of GDP. Source: Simulation (noise)
save "synthetic_ekc_panel.dta", replace
