#!/usr/bin/env python3
"""Regenerate references/tutorial.qmd and notebook.ipynb from index.md.

Usage:
    `python3 regen_companions.py`            writes both companions
    `python3 regen_companions.py --check`    exits with status 1 when either is stale

The post index.md is the single source of truth for the text and the code. This
script parses its body into Markdown, code fences, learning cards, figures, and
the sc-lab shortcode, and it renders two companions from that parse.

* references/tutorial.qmd is the Quarto notebook of the downloadable bundle.
  Learning cards become Quarto callouts, and every figure is regenerated by its
  plotting chunk. A verification chunk checks the environment of setup_env.py.
* notebook.ipynb is the Google Colab notebook. Learning cards become plain
  Markdown, and the Mermaid diagram becomes a numbered list. Its first cells
  install mlsynth 1.0.0 and check the installation.

The script needs only the Python standard library, and it never edits index.md.
After a change to index.md, run it again, and then run build_bundle.sh.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

SLUG = "python_sc101"
POST = Path(__file__).resolve().parent
SITE = "https://carlos-mendez.org"
POST_URL = f"{SITE}/post/{SLUG}/"
REPO_URL = "https://github.com/cmg777/starter-academic-v501"
RAW = f"https://raw.githubusercontent.com/cmg777/starter-academic-v501/master/content/tutorials/{SLUG}/"
COLAB_URL = ("https://colab.research.google.com/github/cmg777/starter-academic-v501/"
             f"blob/master/content/tutorials/{SLUG}/notebook.ipynb")
BADGE_URL = "https://colab.research.google.com/assets/colab-badge.svg"
DATA_URL = "https://github.com/quarcs-lab/data-open/raw/master/isds/smoking_sc.dta"
KERNEL = f"{SLUG}-tutorial"
QMD_PATH = POST / "references" / "tutorial.qmd"
IPYNB_PATH = POST / "notebook.ipynb"

# Headline packages that the verification chunk of the qmd checks. They must
# agree with the PINNED dictionary of references/setup_env.py (checked below).
HEADLINE = {
    "mlsynth": "1.0.0",
    "numpy": "2.3.5",
    "pandas": "3.0.1",
    "scipy": "1.17.1",
    "matplotlib": "3.10.8",
    "cvxpy": "1.8.1",
    "scs": "3.2.8",
    "statsmodels": "0.14.6",
}

# --------------------------------------------------------------------------
# Text that only the companions contain (the writing rules of the post apply)
# --------------------------------------------------------------------------
SUBTITLE = "The Proposition 99 tobacco case, from synthetic California to placebo tests"

RENDER_BLOCKS = [
    "**Easiest (one click).** Extract the bundle ZIP, and double-click `render.command` on "
    "macOS or `render.bat` on Windows. The wrapper first runs `setup_env.py`, which builds a "
    "local Python environment, and then calls `quarto render`. When the render finishes, the "
    "wrapper opens `tutorial.html` in the default browser.",
    "**Manual.** A terminal offers the same two steps. Open it in the bundle folder, and run "
    "the two commands below. The first command builds the environment, and the second "
    "renders the tutorial.",
    "```bash\n"
    "python3 setup_env.py            # one-time setup: builds .venv/ and registers the kernel\n"
    'quarto render tutorial.qmd      # or click "Render" in Positron\n'
    "```",
    "The setup script is idempotent, so a second run finishes within seconds. Every render "
    "still runs all the computations of the tutorial, which takes a few minutes. The "
    "placebo and robustness checks of Sections 8 to 12 account for most of that time.",
    "**Prerequisites.** The bundle needs Python 3.11, 3.12, or 3.13 and a working Quarto "
    "installation. When the default `python3` is outside that range, `setup_env.py` "
    "searches the machine for a supported version. On Windows, the command is "
    "`python setup_env.py` when `python3` is not on the PATH.",
]

QMD_SOLUTION_LEAD = (
    "The code below solves the exercise with the objects of the walkthrough. Its output "
    "lists the numbers that the exercise asks for. The text after the output interprets them."
)

NB_SOLUTION_LEAD = (
    "**Solution.** Attempt the exercise first, and run the next cell only afterward. The "
    "cell solves it with the objects of the walkthrough, and its output lists the numbers "
    "to report. The text after the output interprets them."
)

LAB_NOTE = (
    "The interactive lab runs only on the published post, because it needs the JavaScript "
    "of the website. This version of the tutorial therefore omits the lab but keeps the "
    "guided experiments below. Open the lab in [Section 13 of the published post]({url}), "
    "and follow the experiments there."
)

NB_INTRO = (
    "This notebook is the executable companion of the post [{title}]({url}). It contains the "
    "text and the code of the post, and it reproduces every result, from the data checks to "
    "the exercises. Only the interactive lab of Section 13 is missing, because it runs on "
    "the published post alone."
)

NB_RUNTIME = (
    "**Expected runtime.** A full run takes about three minutes on a recent laptop, and most "
    "of that time goes to the placebo and robustness refits of Sections 8 to 12. On Google "
    "Colab, the installation adds about one minute, and slower hardware can stretch the run "
    "to about ten minutes. Another software stack can also move a few placebo numbers in "
    "the third decimal, as Section 2 explains."
)

NB_INSTALL = (
    "The next cell installs mlsynth 1.0.0, the release that produced every number of the "
    "post, together with its dependencies. Google Colab already provides numpy, pandas, "
    "scipy, and matplotlib, so the installation adds only the missing packages. If Colab "
    "asks to restart the session afterward, restart it, and then run the notebook again "
    "from the version check below."
)

NB_PIP = "%pip install -q mlsynth==1.0.0"

NB_VERSION_CHECK = '''\
# Check the installation: the versions and the build should match Section 2
from importlib import metadata

from mlsynth.utils.vanillasc_helpers.config import VanillaSCConfig

for package in ["mlsynth", "numpy", "pandas", "scipy", "cvxpy", "statsmodels"]:
    print(f"{package:<12} {metadata.version(package)}")
build = "pypi" if "fit_window" not in VanillaSCConfig.model_fields else "git"
print(f"mlsynth build: {build}")'''

# The notebook replaces the Mermaid diagram, which Colab cannot draw, with this
# list. Every fact in it must still appear in the diagram (see STUDY_DESIGN_FACTS).
STUDY_DESIGN = """\
1. **Case study.** The data cover 39 US states from 1970 to 2000, a panel of 1,209 rows. California adopted Proposition 99 in 1989, and the 38 other states, which had no large tobacco program, form the donor pool.
2. **Synthetic control in mlsynth.** Seven predictors enter the fit: four covariates averaged over 1980–1988 and sales in 1975, 1980, and 1988. `VanillaSC` runs a nested search over the predictor weights V and the donor weights W, and five donors receive weight. The gap between California and its synthetic control gives an ATT of −18.98 packs.
3. **Can we break it?** The in-space placebo ranks California first among 39 states (p = 0.026). The in-time placebo moves the start to 1985, and five leave-one-out refits each drop one donor.
4. **Extension.** An estimator tour applies outcome-only synthetic control, SDID, and PCR to the same data."""

STUDY_DESIGN_FACTS = [
    "39 US states", "1970–2000, 1,209 rows", "Proposition 99 from 1989", "38 donor states",
    "no large tobacco program", "Seven predictors", "4 covariates, 1980–1988",
    "sales in 1975, 1980, 1988", "predictor weights V", "donor weights W",
    "5 donors with weight", "ATT = −18.98 packs", "rank 1 of 39, p = 0.026",
    "fake start in 1985", "5 refits", "outcome-only, SDID, PCR",
]

# The paragraph after the diagram describes its colors, so the notebook drops it.
COLORS_PARAGRAPH = "The colors of the diagram encode the role of each box."

# Phrases that describe the web page (one click, collapsed blocks, cards) and the
# wording that fits the companion instead. Each phrase must occur in index.md.
COMMON_WORDING = [
    ("The lab below runs on", "The lab runs on"),
]
NOTEBOOK_WORDING = [
    ("The definition is always visible, while the example and the analogy open with a click.",
     "The definition comes first, and the example and the analogy follow it."),
    ("The collapsed block below sets the colors", "The next code cell sets the colors"),
    ("proof card below", "optional proof below"),
    ("this card shows", "this proof shows"),
    ("proof card of Section", "proof of Section"),
    ("Each card below states", "Each entry below states"),
    ("each solution card holds", "each solution holds"),
    ("before you open its solution", "before you run its solution"),
    ("The diagram summarizes the study design in three blocks.",
     "The list below summarizes the study design in three blocks and one extension."),
]


# --------------------------------------------------------------------------
# Parsing index.md
# --------------------------------------------------------------------------
class Node:
    """One element of the post body: Markdown text, a fence, a card, an image, and so on."""

    def __init__(self, kind: str, **attrs):
        self.kind = kind
        self.children: list[Node] = []
        self.__dict__.update(attrs)


FENCE_OPEN = re.compile(r"^```(\w+)\s*$")
DETAILS_OPEN = re.compile(r'^<details(?: class="([^"]+)")?>$')
SUMMARY = re.compile(r'^<summary>(?:<span class="learn-card-kicker">([^<]+)</span>\s*)?(.+?)</summary>$')
DIV_OPEN = re.compile(r'^<div class="([^"]+)">$')
KICKER = re.compile(r'^<p class="learn-card-kicker">([^<]+)</p>$')
IMAGE = re.compile(r"^!\[([^\]]*)\]\(([\w.-]+\.png)\)$")
CAPTION = re.compile(r"^\*(Figure (\d+)\. .+)\*$")
SHORTCODE = re.compile(r"^\{\{<\s*([\w-]+)\s*>\}\}$")
BADGE = re.compile(r'^<a href="https://colab\.research\.google\.com/[^"]+"[^>]*><img [^>]+></a>$')


def split_front_matter(md: str) -> tuple[str, str, int]:
    """Return the front matter, the body, and the number of lines before the body."""
    if not md.startswith("---\n"):
        raise SystemExit("index.md must start with YAML front matter")
    end = md.index("\n---\n", 4)
    return md[4:end], md[end + 5:], md[:end + 5].count("\n")


def front_scalar(front: str, key: str) -> str:
    m = re.search(rf'^{key}:\s*"?(.*?)"?\s*$', front, re.M)
    if not m:
        raise SystemExit(f"index.md has no {key} in its front matter")
    return m.group(1)


def front_links(front: str) -> list[dict[str, str]]:
    """Parse the links list of the front matter (icon, icon_pack, name, url)."""
    m = re.search(r"(?ms)^links:\n(.*?)(?=^[^\s-]|\Z)", front + "\n")  # items may start at column 0
    items: list[dict[str, str]] = []
    for line in (m.group(1).splitlines() if m else []):
        km = re.match(r"^(-\s+|\s+)(\w+):\s*(.*)$", line)
        if not km:
            continue
        if km.group(1).startswith("-"):
            items.append({})
        if items:
            items[-1][km.group(2)] = km.group(3).strip().strip('"')
    return items


def parse_body(body: str, offset: int) -> Node:
    """Parse the body of the post into a tree of nodes."""
    root = Node("root")
    stack = [root]
    lines = body.split("\n")

    def where(i: int) -> str:
        return f"index.md, line {i + offset + 1}"

    def add(node: Node) -> Node:
        stack[-1].children.append(node)
        return node

    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("```"):
            m = FENCE_OPEN.match(line)
            if not m:
                raise SystemExit(f"{where(i)}: a code fence needs a language: {line!r}")
            end = lines.index("```", i + 1)
            add(Node("fence", lang=m.group(1), code="\n".join(lines[i + 1:end]) + "\n"))
            i = end + 1
            continue
        m = DETAILS_OPEN.match(line)
        if m:
            sm = SUMMARY.match(lines[i + 1])
            if not sm:
                raise SystemExit(f"{where(i + 1)}: a <details> block needs a one-line <summary>")
            node = add(Node("details", cls=m.group(1) or "", kicker=sm.group(1), summary=sm.group(2)))
            stack.append(node)
            i += 2
            continue
        if line == "</details>":
            if stack[-1].kind != "details":
                raise SystemExit(f"{where(i)}: </details> without an open <details>")
            stack.pop()
            i += 1
            continue
        m = DIV_OPEN.match(line)
        if m:
            stack.append(add(Node("div", cls=m.group(1))))
            i += 1
            continue
        if line == "</div>":
            if stack[-1].kind != "div":
                raise SystemExit(f"{where(i)}: </div> without an open <div>")
            stack.pop()
            i += 1
            continue
        m = KICKER.match(line)
        if m:
            add(Node("kicker", text=m.group(1)))
            i += 1
            continue
        m = IMAGE.match(line)
        if m:
            cm = CAPTION.match(lines[i + 1]) if i + 1 < len(lines) else None
            if not cm:
                raise SystemExit(f"{where(i)}: a figure needs an italic caption on the next line")
            add(Node("image", alt=m.group(1), src=m.group(2), caption=cm.group(1)))
            i += 2
            continue
        m = SHORTCODE.match(line)
        if m:
            add(Node("shortcode", name=m.group(1)))
            i += 1
            continue
        if BADGE.match(line):
            add(Node("badge"))
            i += 1
            continue
        if line.startswith("<") and not line.startswith("<http"):
            raise SystemExit(f"{where(i)}: unexpected HTML line: {line[:70]!r}")
        kids = stack[-1].children
        if kids and kids[-1].kind == "md":
            kids[-1].text += "\n" + line
        else:
            add(Node("md", text=line))
        i += 1
    if len(stack) != 1:
        raise SystemExit("index.md has an unclosed <details> or <div> block")
    return root


def walk(node: Node):
    """Yield every descendant of a node in document order."""
    for child in node.children:
        yield child
        yield from walk(child)


def hugo_anchor(heading: str) -> str:
    """Return the anchor that Goldmark (GitHub style) gives a heading on the site."""
    text = re.sub(r"[^\w\- ]", "", heading.strip().lower())
    return text.replace(" ", "-")


STOP_WORDS = {"a", "an", "and", "by", "for", "in", "it", "of", "on", "the", "to", "versus",
              "with"}


def heading_label(heading: str) -> str:
    """Turn a numbered heading into a chunk label, for example s3-1-load-data."""
    m = re.match(r"^(\d+(?:\.\d+)*)\.?\s+(.*)$", heading)
    number, title = (m.group(1), m.group(2)) if m else ("0", heading)
    words = [w for w in re.findall(r"[a-z0-9]+", title.lower()) if w not in STOP_WORDS][:4]
    return "-".join(["s" + number.replace(".", "-"), *words])


def annotate(root: Node) -> dict:
    """Attach headings, figures, exercise numbers, and chunk labels to the nodes."""
    order = list(walk(root))
    heading, exercise = "", None
    fences: list[Node] = []
    stats = {"python": 0, "figures": 0, "cards": {}, "lab_anchor": None}
    for k, node in enumerate(order):
        if node.kind == "md":
            for line in node.text.split("\n"):
                hm = re.match(r"^#{2,6}\s+(.*)$", line)
                if hm:
                    heading = hm.group(1).strip()
                em = re.match(r"^\*\*Exercise (\d+):", line)
                if em:
                    exercise = int(em.group(1))
        elif node.kind == "fence" and node.lang == "python":
            node.heading, node.fig, node.exercise = heading, None, None
            fences.append(node)
        elif node.kind == "image":
            j = k - 1
            while order[j].kind == "md" and not order[j].text.strip():
                j -= 1
            prev = order[j]
            if not (prev.kind == "fence" and prev.lang == "python"):
                raise SystemExit(f"the figure {node.src} does not follow its plotting code")
            prev.fig = node
        elif node.kind == "details":
            node.exercise = exercise
            key = node.cls or "plain"
            stats["cards"][key] = stats["cards"].get(key, 0) + 1
            if node.cls == "learn-card solution-card":
                if exercise is None:
                    raise SystemExit("a solution card precedes every exercise statement")
                for sub in walk(node):
                    if sub.kind == "fence" and sub.lang == "python":
                        sub.solution = exercise
        elif node.kind == "div":
            key = node.cls
            stats["cards"][key] = stats["cards"].get(key, 0) + 1
        elif node.kind == "shortcode":
            if node.name != "sc-lab":
                raise SystemExit(f"no conversion rule for the shortcode {node.name}")
            node.anchor = hugo_anchor(heading)
            stats["lab_anchor"] = node.anchor
    labels = {"setup-packages"}
    counts: dict[str, int] = {}
    for f in fences:
        if f.fig is not None:
            stem = re.sub(r"^sc101_", "", f.fig.src[:-4])
            label = "fig-" + stem.replace("_", "-")
            stats["figures"] += 1
        elif getattr(f, "solution", None):
            label = f"exercise-{f.solution}-solution"
        else:
            base = heading_label(f.heading)
            counts[base] = counts.get(base, 0) + 1
            label = base if counts[base] == 1 else f"{base}-{counts[base]}"
        if label in labels:
            raise SystemExit(f"duplicate chunk label {label}")
        labels.add(label)
        f.label = label
        stats["python"] += 1
    return stats


# --------------------------------------------------------------------------
# Shared text helpers
# --------------------------------------------------------------------------
def md_blocks(text: str) -> list[str]:
    """Split Markdown into blocks at blank lines, without empty blocks."""
    return [b.strip("\n") for b in re.split(r"\n[ \t]*\n", text) if b.strip()]


def undo_escapes(text: str, currency: str) -> str:
    """Undo the Goldmark escapes of the post, which MathJax on the site needs."""
    text = text.replace("\\\\$", currency)             # currency, written \\$ in the post
    text = re.sub(r"\\\\([,;!{}%])", r"\\\1", text)     # \\, becomes the LaTeX space \,
    text = text.replace("\\\\_", "_").replace("\\_", "_")
    if "\\\\" in text:
        raise SystemExit("index.md contains a Goldmark escape that this script does not handle")
    return text


def apply_wording(text: str, pairs: list[tuple[str, str]], used: dict[str, int]) -> str:
    for old, new in pairs:
        used[old] = used.get(old, 0) + text.count(old)
        text = text.replace(old, new)
    return text


def check_wording(pairs: list[tuple[str, str]], used: dict[str, int]) -> None:
    missing = [old for old, _ in pairs if not used.get(old)]
    if missing:
        raise SystemExit("index.md no longer contains these phrases; update the wording "
                         "lists of regen_companions.py: " + "; ".join(missing))


def common_text(text: str, used: dict[str, int]) -> str:
    text = text.replace("](/post/", f"]({SITE}/post/")
    return apply_wording(text, COMMON_WORDING, used)


def yaml_str(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


# --------------------------------------------------------------------------
# Quarto notebook
# --------------------------------------------------------------------------
def is_paragraph(block: str) -> bool:
    return not re.match(r"^(```|#|\||[-*+] |\d+\. |\$\$|<|:::|>)", block)


def callout(cls: str, title: str, inner: list[str], *, collapse: bool = False,
            simple: bool = False) -> list[str]:
    """Wrap blocks in a Quarto callout whose fences touch the first and the last paragraph."""
    if not inner or not is_paragraph(inner[0]):
        raise SystemExit(f"the callout {title!r} must open with a paragraph")
    last_line = inner[-1].split("\n")[-1]
    if not (is_paragraph(last_line) or last_line == ":::"):
        raise SystemExit(f"the callout {title!r} must close after a paragraph")
    if '"' in title:
        if "'" in title:
            raise SystemExit(f"the callout title {title!r} mixes both kinds of quotes")
        quoted = f"'{title}'"
    else:
        quoted = f'"{title}"'
    attrs = f".{cls}" + (' collapse="true"' if collapse else "") + \
        (' appearance="simple"' if simple else "") + f" title={quoted}"
    inner = list(inner)
    inner[0] = "::: {" + attrs + "}\n" + inner[0]
    inner[-1] = inner[-1] + "\n:::"
    return inner


def qmd_fence(node: Node) -> list[str]:
    if node.lang == "text":
        return []                      # the render prints fresh output
    if node.lang == "mermaid":
        return ["```{mermaid}\n" + node.code + "```"]
    if node.lang != "python":
        return [f"```{node.lang}\n{node.code}```"]
    opts = [f"#| label: {node.label}"]
    if node.fig is not None:
        caption = re.sub(r"^Figure \d+\.\s+", "", node.fig.caption)
        opts += [f"#| fig-cap: {yaml_str(caption)}", f"#| fig-alt: {yaml_str(node.fig.alt)}"]
    if getattr(node, "solution", None):
        opts.append("#| code-fold: false")
    return ["```{python}\n" + "\n".join(opts) + "\n\n" + node.code + "```"]


def qmd_nodes(nodes: list[Node], used: dict[str, int]) -> list[str]:
    out: list[str] = []
    for node in nodes:
        if node.kind == "md":
            out += md_blocks(undo_escapes(common_text(node.text, used), currency="$"))
        elif node.kind == "fence":
            out += qmd_fence(node)
        elif node.kind in ("image", "badge"):
            continue                   # the plotting chunk carries the caption; no badge
        elif node.kind == "shortcode":
            note = LAB_NOTE.format(url=f"{POST_URL}#{node.anchor}")
            out += callout("callout-note", "Web version only", [note])
        elif node.kind == "div":
            out += qmd_div(node, used)
        elif node.kind == "details":
            out += qmd_details(node, used)
        else:
            raise SystemExit(f"no Quarto rule for a {node.kind} node")
    return out


def qmd_div(node: Node, used: dict[str, int]) -> list[str]:
    if node.cls == "concept-pair":
        return qmd_nodes(node.children, used)
    if node.cls == "learn-card predict-card":
        kicker, *rest = node.children
        if kicker.kind != "kicker":
            raise SystemExit("a predict card must start with its kicker")
        return callout("callout-tip", kicker.text, qmd_nodes(rest, used))
    raise SystemExit(f"no Quarto rule for <div class={node.cls!r}>")


def qmd_details(node: Node, used: dict[str, int]) -> list[str]:
    blocks = qmd_nodes(node.children, used)
    cls = node.cls
    if cls == "":
        return blocks                  # plotting code: code-fold already hides it
    if cls in ("concept-card concept-example", "concept-card concept-analogy"):
        return callout("callout-note", node.summary, blocks, collapse=True, simple=True)
    if cls == "learn-card-reveal":
        return callout("callout-note", node.summary, blocks, collapse=True)
    if cls == "learn-card misconception-card":
        return callout("callout-warning", f"{node.kicker}: {node.summary}", blocks, collapse=True)
    if cls == "learn-card proof-card":
        return callout("callout-note", f"{node.kicker}: {node.summary}", blocks, collapse=True)
    if cls == "learn-card solution-card":
        return callout("callout-note", f"Solution to Exercise {node.exercise}",
                       [QMD_SOLUTION_LEAD, *blocks], collapse=True)
    raise SystemExit(f"no Quarto rule for <details class={cls!r}>")


def qmd_header(title: str, date: str) -> str:
    return "\n".join([
        "---",
        f"title: {yaml_str(title)}",
        f"subtitle: {yaml_str(SUBTITLE)}",
        'author: "Carlos Mendez"',
        f'date: "{date}"',
        f"jupyter: {KERNEL}",
        "format:",
        "  html:",
        "    theme: cosmo",
        "    embed-resources: true",
        "    toc: true",
        "    toc-depth: 3",
        "    code-fold: true",
        '    code-summary: "Show code"',
        "    fig-width: 9",
        "    fig-height: 5.5",
        "    fig-dpi: 150",
        "    include-in-header:",
        "      text: |",
        "        <style>",
        "          img, .cell-output-display img { max-width: 100%; height: auto; }",
        "          main a { overflow-wrap: anywhere; }",
        "          @media (max-width: 767px) {",
        "            main table { display: block; max-width: 100%; overflow-x: auto; }",
        "          }",
        "        </style>",
        "execute:",
        "  warning: false",
        "  message: false",
        "---",
    ])


def setup_packages_chunk() -> str:
    width = max(len(p) for p in HEADLINE) + 3
    pins = "\n".join(f'    {yaml_str(p) + ":":<{width}} "{v}",' for p, v in HEADLINE.items())
    return f'''```{{python}}
#| label: setup-packages

import sys
from importlib import metadata
from pathlib import Path

from mlsynth.utils.vanillasc_helpers.config import VanillaSCConfig

# setup_env.py installs these versions in .venv/ before Quarto runs, so this
# chunk only verifies the environment that produced the numbers of the post
PINNED = {{
{pins}
}}

py = Path(sys.executable).resolve()
assert ".venv" in py.parts, (
    f"The kernel runs outside the tutorial .venv (sys.executable={{py}}). "
    "Run setup_env.py, and then render the tutorial again."
)
print(f"Python: {{py}}")
for package, want in PINNED.items():
    have = metadata.version(package)
    status = "OK" if have == want else f"MISMATCH (want {{want}})"
    print(f"  {{package:<12}} {{have:<8}} [{{status}}]")

# The PyPI build of mlsynth 1.0.0 has no fit_window field, unlike the GitHub build
build = "pypi" if "fit_window" not in VanillaSCConfig.model_fields else "git"
assert metadata.version("mlsynth") == "1.0.0" and build == "pypi", \\
    "the tutorial needs mlsynth 1.0.0 from PyPI"
print(f"mlsynth build: {{build}}")
```'''


def source_files(links: list[dict[str, str]]) -> str:
    aha = next((item["url"] for item in links
                if "ahaslides" in (item.get("name", "") + item.get("url", "")).lower()), None)
    slides = f"[HTML]({POST_URL}slides/index.html) and " + (
        f"[interactive slides (AhaSlides)]({aha})" if aha
        else f"interactive slides (AhaSlides), linked from the [published post]({POST_URL})")
    return "\n".join([
        "## Source files",
        "",
        f"- Companion script: [`script.py`]({RAW}script.py), also in this bundle",
        f"- Cheat sheets, also in this bundle: [`cheatsheet_python.py`]({RAW}cheatsheet_python.py), "
        f"[`cheatsheet_R.R`]({RAW}cheatsheet_R.R), and [`cheatsheet_stata.do`]({RAW}cheatsheet_stata.do)",
        f"- Data in this bundle: `smoking_sc.csv`, with the same values as the "
        f"[Stata file]({DATA_URL}) that the post loads",
        f"- Data dictionary: <{POST_URL}data/index.html>",
        f"- Slides: {slides}",
        f"- Interactive web app: <{POST_URL}web_app/index.html>",
        f"- Google Colab notebook: <{COLAB_URL}>",
        f"- Stata edition of this post: <{SITE}/post/stata_sc/>",
        f"- Published post: <{POST_URL}>",
        f"- GitHub repository: <{REPO_URL}>",
    ])


def build_qmd(front: str, root: Node) -> str:
    used: dict[str, int] = {}
    title = front_scalar(front, "title")
    date = front_scalar(front, "date")[:10]
    parts = [qmd_header(title, date),
             *callout("callout-important", "How to render this tutorial", RENDER_BLOCKS),
             setup_packages_chunk(),
             *qmd_nodes(root.children, used),
             source_files(front_links(front))]
    check_wording(COMMON_WORDING, used)
    return "\n\n".join(parts) + "\n"


# --------------------------------------------------------------------------
# Colab notebook
# --------------------------------------------------------------------------
class NotebookCells:
    """Collect Markdown blocks into cells, with a new cell at every heading."""

    def __init__(self):
        self.cells: list[tuple[str, str]] = []
        self.buf: list[str] = []

    def md(self, block: str) -> None:
        if block.startswith("#") and self.buf:
            self.flush()
        self.buf.append(block)

    def flush(self) -> None:
        if self.buf:
            self.cells.append(("markdown", "\n\n".join(self.buf)))
            self.buf = []

    def code(self, source: str) -> None:
        self.flush()
        self.cells.append(("code", source.rstrip("\n")))


class NotebookBuilder:
    def __init__(self):
        self.nb = NotebookCells()
        self.used: dict[str, int] = {}
        self.drop_colors = False

    def text(self, raw: str) -> list[str]:
        t = common_text(raw, self.used)
        t = apply_wording(t, NOTEBOOK_WORDING, self.used)
        return md_blocks(undo_escapes(t, currency="\\$"))

    def card_blocks(self, node: Node) -> list[str]:
        if any(c.kind != "md" for c in node.children):
            raise SystemExit(f"the card {node.summary!r} may contain only text in the notebook")
        return [b for c in node.children for b in self.text(c.text)]

    def nodes(self, nodes: list[Node]) -> None:
        nb = self.nb
        for node in nodes:
            if node.kind == "md":
                for block in self.text(node.text):
                    if self.drop_colors:
                        if not block.startswith(COLORS_PARAGRAPH):
                            raise SystemExit("the paragraph after the diagram changed; "
                                             "update COLORS_PARAGRAPH")
                        self.drop_colors = False
                        continue
                    nb.md(block)
            elif node.kind == "fence":
                if node.lang == "python":
                    nb.code(node.code)
                elif node.lang == "mermaid":
                    missing = [f for f in STUDY_DESIGN_FACTS if f not in node.code]
                    if missing:
                        raise SystemExit("the Mermaid diagram of index.md changed; update "
                                         "STUDY_DESIGN in regen_companions.py: " + "; ".join(missing))
                    nb.md(STUDY_DESIGN)
                    self.drop_colors = True
                elif node.lang != "text":
                    nb.md(f"```{node.lang}\n{node.code}```")
            elif node.kind == "image":
                if re.search(r"[*_`\[]", node.caption):
                    raise SystemExit(f"the caption of {node.src} needs a Markdown-safe rewrite")
                nb.md(f"<em>{node.caption}</em>")
            elif node.kind == "badge":
                continue                   # the badge sits in the first cell
            elif node.kind == "shortcode":
                note = LAB_NOTE.format(url=f"{POST_URL}#{node.anchor}")
                nb.md(f"> **Web version only.** {note}")
            elif node.kind == "div":
                self.div(node)
            elif node.kind == "details":
                self.details(node)
            else:
                raise SystemExit(f"no notebook rule for a {node.kind} node")

    def div(self, node: Node) -> None:
        if node.cls == "concept-pair":
            self.nodes(node.children)
            return
        if node.cls != "learn-card predict-card":
            raise SystemExit(f"no notebook rule for <div class={node.cls!r}>")
        kicker, *rest = node.children
        reveal = [c for c in rest if c.kind == "details"]
        if kicker.kind != "kicker" or len(reveal) != 1 or rest[-1] is not reveal[0]:
            raise SystemExit("a predict card needs a kicker, text, and one reveal at the end")
        blocks = [b for c in rest[:-1] for b in self.text(c.text)]
        blocks[0] = f"**{kicker.text}.** " + blocks[0]
        quote = "\n>\n".join("\n".join("> " + line for line in b.split("\n")) for b in blocks)
        self.nb.md(quote)
        answer = "\n\n".join(self.card_blocks(reveal[0]))
        self.nb.md(f"<details>\n<summary>{reveal[0].summary}</summary>\n\n{answer}\n\n</details>")

    def details(self, node: Node) -> None:
        cls = node.cls
        if cls == "":
            self.nodes(node.children)      # plotting code becomes an ordinary code cell
            return
        if cls == "learn-card solution-card":
            self.nb.md(NB_SOLUTION_LEAD)
            self.nodes(node.children)
            return
        blocks = self.card_blocks(node)
        if cls in ("concept-card concept-example", "concept-card concept-analogy"):
            blocks[0] = f"**{node.summary}.** " + blocks[0]
        elif cls == "learn-card misconception-card":
            blocks[0] = f"**{node.kicker}:** {node.summary}<br>\n" + blocks[0]
        elif cls == "learn-card proof-card":
            blocks[0] = f"**{node.kicker} (optional).** *{node.summary}.*<br>\n" + blocks[0]
        else:
            raise SystemExit(f"no notebook rule for <details class={cls!r}>")
        for block in blocks:
            self.nb.md(block)


def build_ipynb(front: str, root: Node) -> str:
    title = front_scalar(front, "title")
    builder = NotebookBuilder()
    nb = builder.nb
    badge = (f'<a href="{COLAB_URL}" target="_blank" rel="noopener">'
             f'<img src="{BADGE_URL}" alt="Open In Colab"></a>')
    nb.md(f"# {title}")
    nb.md(NB_INTRO.format(title=title, url=POST_URL))
    nb.md(badge)
    nb.md(NB_RUNTIME)
    nb.md("## Install the packages")
    nb.md(NB_INSTALL)
    nb.code(NB_PIP)
    nb.code(NB_VERSION_CHECK)
    builder.nodes(root.children)
    footer = source_files(front_links(front))
    # The notebook travels without the bundle, so the footer drops the bundle wording.
    footer = (footer.replace(", also in this bundle", "")
              .replace("Cheat sheets, also in this bundle:", "Cheat sheets:")
              .replace("- Data in this bundle: `smoking_sc.csv`",
                       f"- Data: [`smoking_sc.csv`]({RAW}data/smoking_sc.csv)"))
    nb.md(footer)
    nb.flush()
    check_wording(NOTEBOOK_WORDING, builder.used)
    cells = []
    for k, (kind, source) in enumerate(nb.cells):
        lines = source.split("\n")
        cell = {"cell_type": kind, "id": f"cell-{k:03d}", "metadata": {},
                "source": [line + "\n" for line in lines[:-1]] + [lines[-1]]}
        if kind == "code":
            cell.update(execution_count=None, outputs=[])
        cells.append(cell)
    notebook = {
        "cells": cells,
        "metadata": {
            "colab": {"provenance": [], "toc_visible": True},
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    return json.dumps(notebook, indent=1, ensure_ascii=False, sort_keys=True) + "\n"


# --------------------------------------------------------------------------
# Driver
# --------------------------------------------------------------------------
def check_pins() -> None:
    """Make the verification chunk agree with the pins of setup_env.py."""
    env = POST / "references" / "setup_env.py"
    if not env.exists():
        return
    pins = dict(re.findall(r'^\s+"([\w-]+)":\s+"([^"]+)",', env.read_text(encoding="utf-8"), re.M))
    for package, version in HEADLINE.items():
        if pins.get(package) != version:
            raise SystemExit(f"setup_env.py pins {package} {pins.get(package)}, "
                             f"but HEADLINE expects {version}")


def main(argv: list[str]) -> int:
    if any(a != "--check" for a in argv):
        print(__doc__)
        return 2
    check = "--check" in argv
    check_pins()
    front, body, offset = split_front_matter((POST / "index.md").read_text(encoding="utf-8"))
    root = parse_body(body, offset)
    stats = annotate(root)
    outputs = {QMD_PATH: build_qmd(front, root), IPYNB_PATH: build_ipynb(front, root)}
    if check:
        stale = [p for p, text in outputs.items()
                 if not p.exists() or p.read_text(encoding="utf-8") != text]
        for p in stale:
            print(f"stale: {p.relative_to(POST)} (run python3 regen_companions.py)")
        if not stale:
            print("tutorial.qmd and notebook.ipynb match index.md")
        return 1 if stale else 0
    for path, text in outputs.items():
        path.parent.mkdir(exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
    cards = ", ".join(f"{v} {k}" for k, v in sorted(stats["cards"].items()))
    print(f"wrote references/tutorial.qmd and notebook.ipynb: {stats['python']} python chunks, "
          f"{stats['figures']} figures, lab anchor #{stats['lab_anchor']}")
    print(f"cards: {cards}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
