* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- data.dta ----
use "data.dta", clear
label data "Annual country panel: GDP per capita + OECD covariates"
note _dta: Annual country panel for 17 countries, 1960-2003 (748 rows). The SCPI tutorial uses only country, year, and gdp; the remaining columns are the original Abadie (2021) predictor covariates, carried verbatim and used in the covariate-adjustment exercise.
note index: Numeric identifier for the country (from the source Abadie dataset; not sequential).. Construction: Carried from the source dataset; constant within a country across years.. Units: integer code. Source: Abadie (2021)
note country: Country identifier - the treated unit (West Germany) plus 16 OECD donor countries.. Construction: Carried from the source dataset.. Units: string. Source: Abadie (2021)
note year: Annual time index, 1960-2003.. Construction: Carried from the source dataset.. Units: year. Source: Abadie (2021)
note gdp: Real GDP per capita in thousands of US dollars - the outcome variable for the synthetic control.. Construction: Carried from the source dataset; the only outcome used in estimation (outcome_var='gdp').. Units: thousand US$. Source: Abadie (2021)
note infrate: Annual inflation rate (consumer prices), a predictor covariate in the original Abadie analysis.. Construction: Carried from the source dataset; not used by this tutorial's headline estimation.. Units: % per year. Source: Abadie (2021)
note trade: Trade (exports + imports) as a share of GDP, a predictor covariate.. Construction: Carried from the source dataset; available for the covariate-adjustment exercise.. Units: % of GDP. Source: Abadie (2021)
note schooling: Share of the population with secondary schooling, a human-capital predictor covariate.. Construction: Carried from the source dataset; reported only for selected years (sparse).. Units: % of population. Source: Abadie (2021)
note invest60: Average investment-to-output ratio over the 1960s (time-invariant per country).. Construction: Carried from the source dataset; one value per country (period average).. Units: ratio. Source: Abadie (2021)
note invest70: Average investment-to-output ratio over the 1970s (time-invariant per country).. Construction: Carried from the source dataset; one value per country (period average).. Units: ratio. Source: Abadie (2021)
note invest80: Average investment-to-output ratio over the 1980s (time-invariant per country).. Construction: Carried from the source dataset; one value per country (period average).. Units: % / ratio. Source: Abadie (2021)
note industry: Industry value added as a share of GDP, a structural predictor covariate.. Construction: Carried from the source dataset; available for the covariate-adjustment exercise.. Units: % of GDP. Source: Abadie (2021)
save "data.dta", replace
