* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- maketable1.dta ----
use "maketable1.dta", clear
label data "AJR Table 1 data: full archive, summary statistics"
note _dta: Full AJR archive used for descriptive statistics; carries the income, institutions, settler, historical-institution, and mortality variables plus the baseco flag.
note shortnam: Three-letter country identifier; the row key in every dataset.. Construction: AJR country abbreviation (e.g. AUS, USA, NGA); used for scatter point labels (mlabel).. Units: string. Source: AJR (2001)
note euro1900: Share of the population that was of European descent in 1900 (also used as an alternative instrument).. Construction: Percent European in 1900, AJR.. Units: % (0-100). Source: AJR (2001)
note avexpr: Average index of protection against expropriation of private investment, ~1985-95 (the endogenous regressor X - 'modern institutions').. Construction: Mean over available years of the Political Risk Services expropriation-risk index, scaled 0 (worst) to 10 (best).. Units: 0-10 scale. Source: AJR (2001), from Political Risk Services
note logpgp95: Natural log of 1995 PPP GDP per capita (the outcome Y).. Construction: log of World Bank PPP GDP per capita, 1995.. Units: log US$ (PPP). Source: AJR (2001), from World Bank
note cons1: Polity constraint-on-the-executive score in the country's first year of independence.. Construction: Polity index, 1 (low) to 7 (high) constraint.. Units: 1-7 scale. Source: Polity via AJR
note democ00a: Polity democracy score in 1900 (a historical-institution / alternative-instrument variable).. Construction: Polity democracy index, 0 (low) to 10 (high).. Units: 0-10 scale. Source: Polity via AJR
note cons00a: Polity constraint-on-the-executive score in 1900 (historical-institution / alternative instrument).. Construction: Polity index, 1 (low) to 7 (high) constraint.. Units: 1-7 scale. Source: Polity via AJR
note extmort4: Annualized European settler/soldier mortality during colonization (raw level behind logem4).. Construction: Deaths per 1,000 mean strength, corrected/standardized by AJR (?2.55 to 2,940).. Units: deaths per 1,000. Source: AJR (2001)
note logem4: Natural log of European settler/soldier mortality during early colonization (the instrument Z).. Construction: log of corrected annualized deaths per 1,000 (extmort4).. Units: log deaths per 1,000. Source: AJR (2001), from Curtin and related sources
note loghjypl: Natural log of GDP per worker from Hall & Jones (1999); an alternative income measure.. Construction: log of Hall-Jones output per worker.. Units: log US$. Source: Hall & Jones (1999) via AJR
note baseco: Indicator for the 64-country base sample of ex-colonies with valid settler-mortality data.. Construction: 1 for base-sample countries; MISSING (not 0) otherwise. Restrict with keep if baseco==1.. Units: 1/missing. Source: AJR (2001)
save "maketable1.dta", replace

* ---- maketable2.dta ----
use "maketable2.dta", clear
label data "AJR Table 2 data: OLS benchmark (income, institutions, controls)"
note _dta: Holds the continent dummies (africa, asia, other) and latitude used as OLS controls in AJR Table 2.
note shortnam: Three-letter country identifier; the row key in every dataset.. Construction: AJR country abbreviation (e.g. AUS, USA, NGA); used for scatter point labels (mlabel).. Units: string. Source: AJR (2001)
note africa: 1 if the country is in Africa (continent control).. Construction: Binary continent indicator.. Units: 0/1. Source: AJR (2001)
note lat_abst: Absolute latitude of the capital, divided by 90 (a geography control).. Construction: abs(latitude of capital) / 90.. Units: 0-1. Source: AJR (2001)
note avexpr: Average index of protection against expropriation of private investment, ~1985-95 (the endogenous regressor X - 'modern institutions').. Construction: Mean over available years of the Political Risk Services expropriation-risk index, scaled 0 (worst) to 10 (best).. Units: 0-10 scale. Source: AJR (2001), from Political Risk Services
note logpgp95: Natural log of 1995 PPP GDP per capita (the outcome Y).. Construction: log of World Bank PPP GDP per capita, 1995.. Units: log US$ (PPP). Source: AJR (2001), from World Bank
note other: 1 if the country is not in Asia, Africa, or the Americas (continent control).. Construction: Binary continent indicator.. Units: 0/1. Source: AJR (2001)
note asia: 1 if the country is in Asia (continent control).. Construction: Binary continent indicator.. Units: 0/1. Source: AJR (2001)
note loghjypl: Natural log of GDP per worker from Hall & Jones (1999); an alternative income measure.. Construction: log of Hall-Jones output per worker.. Units: log US$. Source: Hall & Jones (1999) via AJR
note baseco: Indicator for the 64-country base sample of ex-colonies with valid settler-mortality data.. Construction: 1 for base-sample countries; MISSING (not 0) otherwise. Restrict with keep if baseco==1.. Units: 1/missing. Source: AJR (2001)
save "maketable2.dta", replace

* ---- maketable3.dta ----
use "maketable3.dta", clear
label data "AJR Table 3 data: first stage + determinants of institutions"
note _dta: Carries the historical-institution variables (cons00a, democ00a, cons1, indtime, euro1900) and raw/log mortality (extmort4, logem4) for the determinants-of-institutions table.
note lat_abst: Absolute latitude of the capital, divided by 90 (a geography control).. Construction: abs(latitude of capital) / 90.. Units: 0-1. Source: AJR (2001)
note euro1900: Share of the population that was of European descent in 1900 (also used as an alternative instrument).. Construction: Percent European in 1900, AJR.. Units: % (0-100). Source: AJR (2001)
note excolony: 1 if the country was ever a European colony (FLOPS definition).. Construction: Binary indicator from AJR/FLOPS coding.. Units: 0/1. Source: AJR (2001)
note avexpr: Average index of protection against expropriation of private investment, ~1985-95 (the endogenous regressor X - 'modern institutions').. Construction: Mean over available years of the Political Risk Services expropriation-risk index, scaled 0 (worst) to 10 (best).. Units: 0-10 scale. Source: AJR (2001), from Political Risk Services
note logpgp95: Natural log of 1995 PPP GDP per capita (the outcome Y).. Construction: log of World Bank PPP GDP per capita, 1995.. Units: log US$ (PPP). Source: AJR (2001), from World Bank
note cons1: Polity constraint-on-the-executive score in the country's first year of independence.. Construction: Polity index, 1 (low) to 7 (high) constraint.. Units: 1-7 scale. Source: Polity via AJR
note indtime: Number of years a country had been independent by 1995.. Construction: 1995 minus the first year of independence.. Units: years. Source: AJR (2001)
note democ00a: Polity democracy score in 1900 (a historical-institution / alternative-instrument variable).. Construction: Polity democracy index, 0 (low) to 10 (high).. Units: 0-10 scale. Source: Polity via AJR
note cons00a: Polity constraint-on-the-executive score in 1900 (historical-institution / alternative instrument).. Construction: Polity index, 1 (low) to 7 (high) constraint.. Units: 1-7 scale. Source: Polity via AJR
note extmort4: Annualized European settler/soldier mortality during colonization (raw level behind logem4).. Construction: Deaths per 1,000 mean strength, corrected/standardized by AJR (?2.55 to 2,940).. Units: deaths per 1,000. Source: AJR (2001)
note logem4: Natural log of European settler/soldier mortality during early colonization (the instrument Z).. Construction: log of corrected annualized deaths per 1,000 (extmort4).. Units: log deaths per 1,000. Source: AJR (2001), from Curtin and related sources
save "maketable3.dta", replace

* ---- maketable4.dta ----
use "maketable4.dta", clear
label data "AJR Table 4 data: main 2SLS estimate"
note _dta: The core IV dataset; adds the rich4 (neo-Europe) dummy used in robustness columns of AJR Table 4.
note shortnam: Three-letter country identifier; the row key in every dataset.. Construction: AJR country abbreviation (e.g. AUS, USA, NGA); used for scatter point labels (mlabel).. Units: string. Source: AJR (2001)
note africa: 1 if the country is in Africa (continent control).. Construction: Binary continent indicator.. Units: 0/1. Source: AJR (2001)
note lat_abst: Absolute latitude of the capital, divided by 90 (a geography control).. Construction: abs(latitude of capital) / 90.. Units: 0-1. Source: AJR (2001)
note rich4: 1 for the 'neo-Europes' (e.g. Australia, Canada, New Zealand, USA); dropped in some robustness columns.. Construction: Binary indicator from AJR.. Units: 0/1. Source: AJR (2001)
note avexpr: Average index of protection against expropriation of private investment, ~1985-95 (the endogenous regressor X - 'modern institutions').. Construction: Mean over available years of the Political Risk Services expropriation-risk index, scaled 0 (worst) to 10 (best).. Units: 0-10 scale. Source: AJR (2001), from Political Risk Services
note logpgp95: Natural log of 1995 PPP GDP per capita (the outcome Y).. Construction: log of World Bank PPP GDP per capita, 1995.. Units: log US$ (PPP). Source: AJR (2001), from World Bank
note logem4: Natural log of European settler/soldier mortality during early colonization (the instrument Z).. Construction: log of corrected annualized deaths per 1,000 (extmort4).. Units: log deaths per 1,000. Source: AJR (2001), from Curtin and related sources
note asia: 1 if the country is in Asia (continent control).. Construction: Binary continent indicator.. Units: 0/1. Source: AJR (2001)
note loghjypl: Natural log of GDP per worker from Hall & Jones (1999); an alternative income measure.. Construction: log of Hall-Jones output per worker.. Units: log US$. Source: Hall & Jones (1999) via AJR
note baseco: Indicator for the 64-country base sample of ex-colonies with valid settler-mortality data.. Construction: 1 for base-sample countries; MISSING (not 0) otherwise. Restrict with keep if baseco==1.. Units: 1/missing. Source: AJR (2001)
save "maketable4.dta", replace

* ---- maketable5.dta ----
use "maketable5.dta", clear
label data "AJR Table 5 data: colonial, legal & religion controls"
note _dta: Adds colonizer-identity dummies (f_brit, f_french), French legal origin (sjlofr), and 1980 religion-composition shares (catho80, muslim80, no_cpm80).
note shortnam: Three-letter country identifier; the row key in every dataset.. Construction: AJR country abbreviation (e.g. AUS, USA, NGA); used for scatter point labels (mlabel).. Units: string. Source: AJR (2001)
note catho80: Percent of population Catholic in 1980 (religion-composition control).. Construction: Percent Catholic, World Christian Encyclopedia 1995.. Units: % (0-100). Source: WCE via AJR
note muslim80: Percent of population Muslim in 1980 (religion-composition control).. Construction: Percent Muslim, World Christian Encyclopedia 1995.. Units: % (0-100). Source: WCE via AJR
note lat_abst: Absolute latitude of the capital, divided by 90 (a geography control).. Construction: abs(latitude of capital) / 90.. Units: 0-1. Source: AJR (2001)
note no_cpm80: 100 minus Catholic, Protestant, and Muslim shares in 1980 (residual religion-composition control).. Construction: 100 - (Catholic + Protestant + Muslim) percent, 1980.. Units: % (0-100). Source: WCE via AJR
note f_brit: 1 if the country was a British colony (colonizer-identity control).. Construction: Binary indicator (FLOPS expansion).. Units: 0/1. Source: AJR (2001)
note f_french: 1 if the country was a French colony (colonizer-identity control).. Construction: Binary indicator (FLOPS expansion).. Units: 0/1. Source: AJR (2001)
note avexpr: Average index of protection against expropriation of private investment, ~1985-95 (the endogenous regressor X - 'modern institutions').. Construction: Mean over available years of the Political Risk Services expropriation-risk index, scaled 0 (worst) to 10 (best).. Units: 0-10 scale. Source: AJR (2001), from Political Risk Services
note sjlofr: 1 if the country has French legal origin (legal-tradition control).. Construction: Recoded French-legal-origin indicator.. Units: 0/1. Source: AJR (2001), legal-origins literature
note logpgp95: Natural log of 1995 PPP GDP per capita (the outcome Y).. Construction: log of World Bank PPP GDP per capita, 1995.. Units: log US$ (PPP). Source: AJR (2001), from World Bank
note logem4: Natural log of European settler/soldier mortality during early colonization (the instrument Z).. Construction: log of corrected annualized deaths per 1,000 (extmort4).. Units: log deaths per 1,000. Source: AJR (2001), from Curtin and related sources
note baseco: Indicator for the 64-country base sample of ex-colonies with valid settler-mortality data.. Construction: 1 for base-sample countries; MISSING (not 0) otherwise. Restrict with keep if baseco==1.. Units: 1/missing. Source: AJR (2001)
save "maketable5.dta", replace

* ---- maketable6.dta ----
use "maketable6.dta", clear
label data "AJR Table 6 data: geography, climate & resources"
note _dta: The widest file (29 vars): five temperature and four humidity indices, six soil/climate dummies, five mineral-resource measures, landlock, ethnolinguistic fractionalization (avelf), and European-descent share (edes1975).
note shortnam: Three-letter country identifier; the row key in every dataset.. Construction: AJR country abbreviation (e.g. AUS, USA, NGA); used for scatter point labels (mlabel).. Units: string. Source: AJR (2001)
note avelf: Average ethnolinguistic fractionalization index (probability two random people differ).. Construction: Average of 5 fractionalization indicators (East-Levine).. Units: 0-1. Source: AJR (2001)
note lat_abst: Absolute latitude of the capital, divided by 90 (a geography control).. Construction: abs(latitude of capital) / 90.. Units: 0-1. Source: AJR (2001)
note temp1: First of five temperature indices used as climate controls.. Construction: AJR temperature indicator (degrees C scale).. Units: index (deg C). Source: AJR (2001)
note temp2: Second of five temperature indices (climate control).. Construction: AJR temperature indicator.. Units: index (deg C). Source: AJR (2001)
note temp3: Third of five temperature indices (climate control).. Construction: AJR temperature indicator.. Units: index (deg C). Source: AJR (2001)
note temp4: Fourth of five temperature indices (climate control).. Construction: AJR temperature indicator.. Units: index (deg C). Source: AJR (2001)
note temp5: Fifth of five temperature indices (climate control).. Construction: AJR temperature indicator.. Units: index (deg C). Source: AJR (2001)
note humid1: First of four humidity indices used as climate controls.. Construction: AJR humidity indicator.. Units: index. Source: AJR (2001)
note humid2: Second of four humidity indices (climate control).. Construction: AJR humidity indicator.. Units: index. Source: AJR (2001)
note humid3: Third of four humidity indices (climate control).. Construction: AJR humidity indicator.. Units: index. Source: AJR (2001)
note humid4: Fourth of four humidity indices (climate control).. Construction: AJR humidity indicator.. Units: index. Source: AJR (2001)
note steplow: First of six soil/climate-zone indicators (1 if low-latitude steppe).. Construction: Binary soil/climate-zone indicator.. Units: 0/1. Source: AJR (2001)
note deslow: Soil/climate-zone indicator (1 if low-latitude desert).. Construction: Binary soil/climate-zone indicator.. Units: 0/1. Source: AJR (2001)
note stepmid: Soil/climate-zone indicator (1 if mid-latitude steppe).. Construction: Binary soil/climate-zone indicator.. Units: 0/1. Source: AJR (2001)
note desmid: Soil/climate-zone indicator (1 if mid-latitude desert).. Construction: Binary soil/climate-zone indicator.. Units: 0/1. Source: AJR (2001)
note drystep: Soil/climate-zone indicator (1 if dry steppe).. Construction: Binary soil/climate-zone indicator.. Units: 0/1. Source: AJR (2001)
note drywint: Soil/climate-zone indicator (1 if dry-winter climate).. Construction: Binary soil/climate-zone indicator.. Units: 0/1. Source: AJR (2001)
note edes1975: Percent of the population of European descent in 1975.. Construction: Percent European descent, 1975.. Units: % (0-100). Source: AJR (2001)
note avexpr: Average index of protection against expropriation of private investment, ~1985-95 (the endogenous regressor X - 'modern institutions').. Construction: Mean over available years of the Political Risk Services expropriation-risk index, scaled 0 (worst) to 10 (best).. Units: 0-10 scale. Source: AJR (2001), from Political Risk Services
note logpgp95: Natural log of 1995 PPP GDP per capita (the outcome Y).. Construction: log of World Bank PPP GDP per capita, 1995.. Units: log US$ (PPP). Source: AJR (2001), from World Bank
note landlock: 1 if the country is landlocked (geography control).. Construction: Binary indicator.. Units: 0/1. Source: AJR (2001)
note goldm: First of five mineral-resource measures (gold).. Construction: Resource-quantity measure, AJR (not a 0/1 dummy).. Units: resource units. Source: AJR (2001)
note iron: Iron mineral-resource measure (geology control).. Construction: Resource-quantity measure, AJR.. Units: resource units. Source: AJR (2001)
note silv: Silver mineral-resource measure (geology control).. Construction: Resource-quantity measure, AJR.. Units: resource units. Source: AJR (2001)
note zinc: Zinc mineral-resource measure (geology control).. Construction: Resource-quantity measure, AJR.. Units: resource units. Source: AJR (2001)
note oilres: Oil-reserves measure (resource control).. Construction: Resource-quantity measure, AJR.. Units: resource units. Source: AJR (2001)
note logem4: Natural log of European settler/soldier mortality during early colonization (the instrument Z).. Construction: log of corrected annualized deaths per 1,000 (extmort4).. Units: log deaths per 1,000. Source: AJR (2001), from Curtin and related sources
note baseco: Indicator for the 64-country base sample of ex-colonies with valid settler-mortality data.. Construction: 1 for base-sample countries; MISSING (not 0) otherwise. Restrict with keep if baseco==1.. Units: 1/missing. Source: AJR (2001)
save "maketable6.dta", replace

* ---- maketable7.dta ----
use "maketable7.dta", clear
label data "AJR Table 7 data: modern health channels"
note _dta: The trickiest robustness file: modern health controls (malfal94, leb95, imr95, yellow) plus McArthur-Sachs geography instruments (meantemp, lt100km, latabs) used in the overidentified Hansen-J columns.
note shortnam: Three-letter country identifier; the row key in every dataset.. Construction: AJR country abbreviation (e.g. AUS, USA, NGA); used for scatter point labels (mlabel).. Units: string. Source: AJR (2001)
note africa: 1 if the country is in Africa (continent control).. Construction: Binary continent indicator.. Units: 0/1. Source: AJR (2001)
note lat_abst: Absolute latitude of the capital, divided by 90 (a geography control).. Construction: abs(latitude of capital) / 90.. Units: 0-1. Source: AJR (2001)
note malfal94: Index of falciparum-malaria prevalence in 1994 (modern health channel).. Construction: Share of population at risk of falciparum malaria, 1994 (0-1).. Units: 0-1. Source: AJR (2001), from Gallup-Sachs
note avexpr: Average index of protection against expropriation of private investment, ~1985-95 (the endogenous regressor X - 'modern institutions').. Construction: Mean over available years of the Political Risk Services expropriation-risk index, scaled 0 (worst) to 10 (best).. Units: 0-10 scale. Source: AJR (2001), from Political Risk Services
note logpgp95: Natural log of 1995 PPP GDP per capita (the outcome Y).. Construction: log of World Bank PPP GDP per capita, 1995.. Units: log US$ (PPP). Source: AJR (2001), from World Bank
note logem4: Natural log of European settler/soldier mortality during early colonization (the instrument Z).. Construction: log of corrected annualized deaths per 1,000 (extmort4).. Units: log deaths per 1,000. Source: AJR (2001), from Curtin and related sources
note asia: 1 if the country is in Asia (continent control).. Construction: Binary continent indicator.. Units: 0/1. Source: AJR (2001)
note yellow: 1 if the yellow-fever vector is present today (disease-environment control).. Construction: Binary indicator.. Units: 0/1. Source: AJR (2001)
note baseco: Indicator for the 64-country base sample of ex-colonies with valid settler-mortality data.. Construction: 1 for base-sample countries; MISSING (not 0) otherwise. Restrict with keep if baseco==1.. Units: 1/missing. Source: AJR (2001)
note leb95: Life expectancy at birth in 1995 (modern health channel).. Construction: Years; World Bank / WHO.. Units: years. Source: AJR (2001)
note imr95: Infant mortality rate in 1995, deaths per 1,000 live births (modern health channel).. Construction: Deaths per 1,000 live births; World Bank.. Units: per 1,000 births. Source: AJR (2001)
note meantemp: Mean annual temperature, used as a geography instrument in overidentified specs.. Construction: Degrees Celsius; McArthur & Sachs.. Units: deg C. Source: McArthur & Sachs via AJR
note lt100km: Fraction of territory within 100 km of the coast (geography instrument).. Construction: Share 0-1; McArthur & Sachs.. Units: 0-1. Source: McArthur & Sachs via AJR
note latabs: Absolute latitude (0-1 scaled), McArthur-Sachs version, used as a geography instrument.. Construction: abs(latitude) / 90, McArthur & Sachs.. Units: 0-1. Source: McArthur & Sachs via AJR
save "maketable7.dta", replace

* ---- maketable8.dta ----
use "maketable8.dta", clear
label data "AJR Table 8 data: alternative instruments & overidentification"
note _dta: Holds the alternative instruments (euro1900, cons00a, democ00a, cons1, democ1, indtime) tested against logem4 for joint exogeneity.
note shortnam: Three-letter country identifier; the row key in every dataset.. Construction: AJR country abbreviation (e.g. AUS, USA, NGA); used for scatter point labels (mlabel).. Units: string. Source: AJR (2001)
note lat_abst: Absolute latitude of the capital, divided by 90 (a geography control).. Construction: abs(latitude of capital) / 90.. Units: 0-1. Source: AJR (2001)
note euro1900: Share of the population that was of European descent in 1900 (also used as an alternative instrument).. Construction: Percent European in 1900, AJR.. Units: % (0-100). Source: AJR (2001)
note avexpr: Average index of protection against expropriation of private investment, ~1985-95 (the endogenous regressor X - 'modern institutions').. Construction: Mean over available years of the Political Risk Services expropriation-risk index, scaled 0 (worst) to 10 (best).. Units: 0-10 scale. Source: AJR (2001), from Political Risk Services
note logpgp95: Natural log of 1995 PPP GDP per capita (the outcome Y).. Construction: log of World Bank PPP GDP per capita, 1995.. Units: log US$ (PPP). Source: AJR (2001), from World Bank
note democ1: Polity democracy score in the country's first year of independence (alternative instrument).. Construction: Polity democracy index, 0 (low) to 10 (high).. Units: 0-10 scale. Source: Polity via AJR
note cons1: Polity constraint-on-the-executive score in the country's first year of independence.. Construction: Polity index, 1 (low) to 7 (high) constraint.. Units: 1-7 scale. Source: Polity via AJR
note indtime: Number of years a country had been independent by 1995.. Construction: 1995 minus the first year of independence.. Units: years. Source: AJR (2001)
note democ00a: Polity democracy score in 1900 (a historical-institution / alternative-instrument variable).. Construction: Polity democracy index, 0 (low) to 10 (high).. Units: 0-10 scale. Source: Polity via AJR
note cons00a: Polity constraint-on-the-executive score in 1900 (historical-institution / alternative instrument).. Construction: Polity index, 1 (low) to 7 (high) constraint.. Units: 1-7 scale. Source: Polity via AJR
note logem4: Natural log of European settler/soldier mortality during early colonization (the instrument Z).. Construction: log of corrected annualized deaths per 1,000 (extmort4).. Units: log deaths per 1,000. Source: AJR (2001), from Curtin and related sources
note baseco: Indicator for the 64-country base sample of ex-colonies with valid settler-mortality data.. Construction: 1 for base-sample countries; MISSING (not 0) otherwise. Restrict with keep if baseco==1.. Units: 1/missing. Source: AJR (2001)
save "maketable8.dta", replace
