* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- tutoring_did.dta ----
use "tutoring_did.dta", clear
label data "Tutoring and GPA, 2x2 DiD panel: 35 schools x 2 periods"
note _dta: Simulated teaching data (Corral and Yang 2024), from quarcs-lab/data-open isds/tutoring_did.dta. Treated schools are id 26-35. time 1 = before, 2 = after the program; post = time == 2; txp = treated x post.
note id: High-school identifier, 1 to 35. Schools 26-35 adopt the tutoring program. Construction: As provided in the original .dta files. Units: id. Source: Corral and Yang (2024), via quarcs-lab/data-open
note time: Time period. In the 2x2 file, 1 = before and 2 = after the program; in the event-study file, periods 1-8 with adoption at the start of period 5. Construction: As provided in the original .dta files. Units: period. Source: Corral and Yang (2024), via quarcs-lab/data-open
note treated: 1 for the 10 schools that adopt the after-school tutoring program, 0 for the 25 comparison schools. Constant within school. Construction: 1 if id is 26-35. Units: 0/1. Source: Corral and Yang (2024), via quarcs-lab/data-open
note post: 1 in periods after the program starts: time = 2 in the 2x2 file, time >= 5 in the event-study file. Construction: post = (time == 2) in the 2x2 file; post = (time >= 5) in the event-study file. Units: 0/1. Source: Corral and Yang (2024), via quarcs-lab/data-open
note txp: The DiD treatment indicator: 1 for a treated school in a post-adoption period. Its coefficient in the regressions is the DiD estimate. Construction: txp = treated x post. Units: 0/1. Source: Corral and Yang (2024), via quarcs-lab/data-open
note gpa: The outcome: the school's average GPA of low-income students, described as a 0-100 score (simulated values reach 107.68 in the event-study file). Construction: Simulated by Corral and Yang (2024); stored as single-precision float in the original .dta, written at full precision in the CSV. Units: GPA points. Source: Corral and Yang (2024), via quarcs-lab/data-open
note female_share: Share of female students in the school, between 0 and 1. Varies within schools over time; used as a robustness covariate. Construction: Simulated by Corral and Yang (2024); single-precision float in the original .dta. Units: share (0-1). Source: Corral and Yang (2024), via quarcs-lab/data-open
save "tutoring_did.dta", replace

* ---- tutoring_didevent.dta ----
use "tutoring_didevent.dta", clear
label data "Tutoring and GPA, event-study panel: 35 schools x 8 periods"
note _dta: Simulated teaching data (Corral and Yang 2024), from quarcs-lab/data-open isds/tutoring_didevent.dta. A separate simulation from the 2x2 file. post = time >= 5; timeToTreat = time - 5 for treated schools and missing for comparison schools.
note id: High-school identifier, 1 to 35. Schools 26-35 adopt the tutoring program. Construction: As provided in the original .dta files. Units: id. Source: Corral and Yang (2024), via quarcs-lab/data-open
note time: Time period. In the 2x2 file, 1 = before and 2 = after the program; in the event-study file, periods 1-8 with adoption at the start of period 5. Construction: As provided in the original .dta files. Units: period. Source: Corral and Yang (2024), via quarcs-lab/data-open
note treated: 1 for the 10 schools that adopt the after-school tutoring program, 0 for the 25 comparison schools. Constant within school. Construction: 1 if id is 26-35. Units: 0/1. Source: Corral and Yang (2024), via quarcs-lab/data-open
note gpa: The outcome: the school's average GPA of low-income students, described as a 0-100 score (simulated values reach 107.68 in the event-study file). Construction: Simulated by Corral and Yang (2024); stored as single-precision float in the original .dta, written at full precision in the CSV. Units: GPA points. Source: Corral and Yang (2024), via quarcs-lab/data-open
note female_share: Share of female students in the school, between 0 and 1. Varies within schools over time; used as a robustness covariate. Construction: Simulated by Corral and Yang (2024); single-precision float in the original .dta. Units: share (0-1). Source: Corral and Yang (2024), via quarcs-lab/data-open
note post: 1 in periods after the program starts: time = 2 in the 2x2 file, time >= 5 in the event-study file. Construction: post = (time == 2) in the 2x2 file; post = (time >= 5) in the event-study file. Units: 0/1. Source: Corral and Yang (2024), via quarcs-lab/data-open
note txp: The DiD treatment indicator: 1 for a treated school in a post-adoption period. Its coefficient in the regressions is the DiD estimate. Construction: txp = treated x post. Units: 0/1. Source: Corral and Yang (2024), via quarcs-lab/data-open
note timeToTreat: Event time for treated schools: time - 5, from -4 to 3 (0 = first treated period, -1 = the reference period in the post). Missing for comparison schools, which are never treated. Construction: timeToTreat = time - 5 if treated == 1; missing otherwise. Units: periods. Source: Corral and Yang (2024), via quarcs-lab/data-open
save "tutoring_didevent.dta", replace
