# -*- coding: utf-8 -*-
"""Basic_synthetic_control

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11LC9x24l4nczS_zR81SJ2LgCkpVALk1E

# Basic synthetic control

![](https://raw.githubusercontent.com/slides777/images/main/covers/synthBasque.png)

This note is based on the article "Synth: An R Package for Synthetic Control Methods in Comparative Case Studies" by Alberto Abadie, Alexis Diamond, and Jens Hainmueller, which introduces the Synth package in R. This package implements synthetic control methods used in comparative case studies. These methods construct a synthetic control unit as weighted average of available control units that best approximate the relevant characteristics of the treated unit prior to the treatment. The Synth package includes functions such as `synth()`, which constructs the synthetic control unit, and `dataprep()`, which organizes the data. Other functions like `synth.tables()`, `path.plot()`, and `gaps.plot()` help in summarizing and illustrating the results. The authors demonstrate the use of these functions with an example from a study on the economic effects of conflict in the Basque Country using other Spanish regions as potential control units. They conclude by discussing future extensions to the Synth package

# Setup
"""

install.packages("Synth")
install.packages("skimr")

library(Synth)
#library(SCtools)
library(tidyverse)
library(skimr)

"""# Import data"""

data("basque")

glimpse(basque)

#skim(basque) %>% as.tibble()

"""In Abadie and Gardeazabal (2003), there are 16 control regions and the 13 predictor variables:

-   1964-1969 averages for gross total investment/GDP (invest).

-   1964-1969 averages for the share of education:

    -   1964-1969 averages for the share of the working-age population that was illiterate (school.illit)
    -   1964-1969 averages for the share of the working-age population with up to primary school education (school.prim)
    -   1964-1969 averages for the share of the working-age population with some high school (school.med)
    -   1964-1969 averages for the share of the working-age population wit high school (school.high)

-   1961-1969 averages for six industrial-sector shares as a percentage of total production (these variables are named with a sec. prefix). These variables are available on a biennial basis $(1961,1963, \ldots, 1969)$

-   1960-1969 averages for real GDP per-capita (gdpcap) measured in thousands of 1986 USD.

-   1969 population density measured in persons per square kilometer (popdens).

# Prepare data

At a minimum, `synth()` requires as inputs the four data matrices: $X_{1}, X_{0}, Z_{1}$, and $Z_{0}$. In our example, these four data matrices are:

-   $X_{1}$ is the $(13 \times 1)$ vector of Basque region predictors
-   $X_{0}$ is the $(13 \times 16)$ matrix of values of the same variables for the 16 control regions. Note that all but one of these predictors is an average value over some range of the pre-treatment period, and the precise date-range varies across predictor variables.
-   $Z_{1}$ is a $(10 \times 1)$ vector which contain the values for the outcome variable for the Basque country
-   $Z_{0}$ is a $(10 \times 16)$ matrix which contain the values for the outcome variable for the control units for the 10 pre-intervention periods over which we want to minimize the MSPE.

It is strongly recommended to use `dataprep()` to extract and package the inputs for `synth()` in a single list object. This list object is also used by other functions such as `synth.tables()`, `path.plot()`, and `gaps.plot()` to produce tables and figures that illustrate the results

-   To obtain $X_{1}$ and $X_{0}$ the user must define the predictor variables, the operator (e.g., mean), and time-period (e.g., 1964:1969) applied to these variables.
-   The user must specify the dependent variable (e.g., gdpcap), the variable(s) identifying unit names (e.g., regionname) and/or numbers (e.g., regionno), the variable identifying time-periods (e.g., year), the treated unit (e.g., region number 17 which is the Basque country), the control units (e.g., regions number $c(2: 16,18))$, the time-period over which to optimize (e.g., the pre-treatment period 1960:1969). This refers to $Z_{1}$ and $Z_{0}$ accordingly.
-   The user should also specify time-period over which outcome data should be plotted (usually before and after treatment, e.g., $1955:1997$ )

How to use the function `dataprep()`

-   Some of the predictor information is given by the arguments `predictors`, `predictors.op`, and `time.predictors.prior`.\
-   The rest of the information for the other predictors is specified in the `special.predictors list`.

This separation allow for easy handling of several predictors with the same operator over the same pre-treatment period (in this case, the school and investment variables) as well as additional custom (or "special") predictors with heterogeneous operators and time-periods. For example, the variables for the sector production shares (with the sec prefix) are only available on a biennial basis $(1961,1963, \ldots, 1969)$ extracted via seq $(1961,1969,2)$. Averaging over the available years is easily accommodated using the `special.predictors list`. For more details and examples check the help file of `dataprep().`
"""

# Prepare the data for analysis
dataprep.out <- dataprep(
  foo = basque,  # the dataset to be prepared

  # the predictor variables to be used in the model
  predictors = c("school.illit", "school.prim", "school.med",
                 "school.high", "school.post.high", "invest"),

  predictors.op = "mean",  # operation to be applied on the predictors

  time.predictors.prior = 1964:1969,  # time period for the predictors

  # special predictors with their respective time periods and operations
  special.predictors = list(
    list("gdpcap", 1960:1969, "mean"),
    list("sec.agriculture", seq(1961,1969,2), "mean"),
    list("sec.energy", seq(1961,1969,2), "mean"),
    list("sec.industry", seq(1961,1969,2), "mean"),
    list("sec.construction", seq(1961,1969,2), "mean"),
    list("sec.services.venta", seq(1961,1969,2), "mean"),
    list("sec.services.nonventa", seq(1961,1969,2), "mean"),
    list("popdens", 1969, "mean")
  ),

  dependent = "gdpcap",  # the dependent variable

  unit.variable = "regionno",  # the variable representing the unit of observation

  unit.names.variable = "regionname",  # the variable representing the names of the units

  time.variable = "year",  # the variable representing the time period

  treatment.identifier = 17,  # the identifier for the treatment group

  controls.identifier = c(2:16,18),  # the identifiers for the control groups

  time.optimize.ssr = 1960:1969,  # the time period over which the sum of squared residuals (SSR) is minimized to estimate the weights

  time.plot = 1955:1997  # the time period for the plot
)

"""We can confirm the contents of the four data matrices:

-   $X_1$ contains the predictors of the treatment unit (region 17).
-   Education-related predictors are averaged over the 1964-1969 period.
-   GPDpc averaged over the 1960-1969 period is also included as a predictor.
-   Sector-related predictors are averaged over the 1961-1969 period (on a biannual basis).
-   Population density is only available for the year 1969.
"""

dataprep.out$X1

"""Notice that `dataprep.out` appends the associated date-range only to the names of the `special.predictors`.

In the matrix $X_0$:
- Region 1 is not included because it is national value
- Region 17 is not included because it is the treatment unit.
"""

dataprep.out$X0

"""-   $Z_1$ contains the outcome values of the treatment unit BEFORE treatment (that is 1960-1969)."""

dataprep.out$Z1

"""-   $Z_0$ contains the outcome values of the control units BEFORE treatment (that is 1960-1969)."""

dataprep.out$Z0

"""There may be instances where it's beneficial to adjust and alter $X_{0}$ and $X_{1}$ directly, without referring back to the original dataset. For instance, consider the five distinct education variables (school.illit, school.prim, school.med, school.high, school.post.high), which denote the count of individuals with different education levels, in thousands. In their 2003 study, Abadie and Gardeazabal combined the two highest categories (school.high and school.post.high) to represent all individuals with education beyond high school. They also used the percentage share for each predictor instead of the total count of individuals. The subsequent code demonstrates how to merge these variables in both $X_{0}$ and $X_{1}$, and how to convert the relevant values into percentage distributions:"""

# Combine 'school.high' and 'school.post.high' in X1 and X0 matrices
dataprep.out$X1["school.high",] <- dataprep.out$X1["school.high",] + dataprep.out$X1["school.post.high",]
dataprep.out$X0["school.high",] <- dataprep.out$X0["school.high",] + dataprep.out$X0["school.post.high",]

# Remove 'school.post.high' from X1 and X0 matrices
post_high_row <- which(rownames(dataprep.out$X1)=="school.post.high")
dataprep.out$X1 <- as.matrix(dataprep.out$X1[-post_high_row,])
dataprep.out$X0 <- as.matrix(dataprep.out$X0[-post_high_row,])

# Find the indices of 'school.illit' and 'school.high' in X0 matrix
illit_row_index <- which(rownames(dataprep.out$X0)=="school.illit")
high_row_index  <- which(rownames(dataprep.out$X0)=="school.high")

# Scale the values in the rows between 'school.illit' and 'school.high' in X1 and X0 matrices to percentages
dataprep.out$X1[illit_row_index:high_row_index,] <- (100*dataprep.out$X1[illit_row_index:high_row_index,]) / sum(dataprep.out$X1[illit_row_index:high_row_index,])
dataprep.out$X0[illit_row_index:high_row_index,] <- 100*scale(dataprep.out$X0[illit_row_index:high_row_index,], center=FALSE, scale=colSums(dataprep.out$X0[illit_row_index:high_row_index,]))

"""# Run the algorithm

The function `synth()` identifies the synthetic control for the Basque region by determining the weight vector $W^{*}$, which is achieved by solving the nested optimization problem outlined in equations (1) and (2).

$$
\left\|X_{1}-X_{0} W\right\|_{V}=\sqrt{\left(X_{1}-X_{0} W\right)^{\prime} V\left(X_{1}-X_{0} W\right)}  \hspace{1cm} (1)
$$

$$
\arg \min _{V \in V}\left(Z_{1}-Z_{0} W^{*}(V)\right)^{\prime}\left(Z_{1}-Z_{0} W^{*}(V)\right) \hspace{1cm} (2)
$$

For any given $V$, the function `synth()` locates a $W^{*}(V)$ by minimizing equation (1). This minimization is achieved using a constrained quadratic optimization function from the `kernlab` package in R. The function `synth()` then determines the diagonal matrix $V^{*}$ that minimizes equation (2), thereby minimizing the Mean Squared Prediction Error (MSPE) for the pre-intervention period. To solve the optimization problem presented in equation (2), the authors utilize the general-purpose optimization function `optim()` in R.
"""

synth.out <- synth(data.prep.obj = dataprep.out,
                    method = "BFGS" #   set optim() to use the BFGS quasi-Newton algorithm.
                    )

"""# Obtaining results

The annual discrepancies in the GPD trend between the Basque region and its synthetic control
"""

gaps <- dataprep.out$Y1plot - (dataprep.out$Y0plot %*% synth.out$solution.w)
 gaps[1:3, 1]

gaps

"""Tables are produced by using the `synth.tab()` function:"""

synth.tables <- synth.tab(dataprep.res = dataprep.out,
                           synth.res    = synth.out
                           )

"""This function produces four different types of tables"""

names(synth.tables)

"""-   tab.pred compares pre-treatment predictor values for the treated unit, the synthetic control unit, and all the units in the sample."""

synth.tables$tab.pred

"""The synthetic Basque country is fairly similar to the real Basque country. The sample means of the predictor variables over the 16 control regions are provided as a comparison.

-   tab.v shows the weight corresponding to each predictor
"""

synth.tables$tab.v

"""
-   tab.v shows the weight corresponding to each potential control unit"""

synth.tables$tab.w

"""We see that Cataluna contributes 85 percent and Madrid contributes 15 percent to the synthetic Basque country; a zero weight is assigned to all the other control regions."""

path.plot(synth.res = synth.out,
           dataprep.res = dataprep.out,
           Ylab = "Real GDPpc",
           Xlab = "year",
           Ylim = c(0,12),
           Legend = c("Basque country","synthetic Basque country"),
           Legend.position = "bottomright"
           )

"""We know that for the Basque country, terrorism claimed its first victim in 1968, but large scale terrorist activity only began in the mid-70s.

-   The gaps.plot() function shows how the difference between treated and synthetic control outcomes change over time.

"""

gaps.plot(synth.res = synth.out,
           dataprep.res = dataprep.out,
           Ylab = "Gap in real GDPpc",
           Xlab = "year",
           Ylim = c(-1.5,1.5),
           Main = NA
           )

"""# Placebo tests"""

dataprep.out <-
              dataprep(foo = basque,
                       predictors = c("school.illit" , "school.prim" , "school.med" ,
                                      "school.high" , "school.post.high" , "invest") ,
                       predictors.op = "mean" ,
                       time.predictors.prior = 1964:1969 ,
                       special.predictors = list(
                         list("gdpcap" , 1960:1969 , "mean"),
                         list("sec.agriculture" ,      seq(1961,1969,2), "mean"),
                         list("sec.energy" ,           seq(1961,1969,2), "mean"),
                         list("sec.industry" ,         seq(1961,1969,2), "mean"),
                         list("sec.construction" ,     seq(1961,1969,2), "mean"),
                         list("sec.services.venta" ,   seq(1961,1969,2), "mean"),
                         list("sec.services.nonventa" ,seq(1961,1969,2), "mean"),
                         list("popdens", 1969, "mean")
                                                ),
                       dependent = "gdpcap",
                       unit.variable = "regionno",
                       unit.names.variable = "regionname",
                       time.variable = "year",
                       treatment.identifier = 10, # Change the ID to other unit that did NOT receive the treatment
                       controls.identifier = c(2:9,11:16,18),
                       time.optimize.ssr = 1960:1969,
                       time.plot = 1955:1997
                       )

# Combine 'school.high' and 'school.post.high' in X1
dataprep.out$X1["school.high",] <- dataprep.out$X1["school.high",] + dataprep.out$X1["school.post.high",]

# Remove 'school.post.high' from X1
dataprep.out$X1 <- as.matrix(dataprep.out$X1[-which(rownames(dataprep.out$X1)=="school.post.high"),])

# Combine 'school.high' and 'school.post.high' in X0
dataprep.out$X0["school.high",] <- dataprep.out$X0["school.high",] + dataprep.out$X0["school.post.high",]

# Remove 'school.post.high' from X0
dataprep.out$X0 <- dataprep.out$X0[-which(rownames(dataprep.out$X0)=="school.post.high"),]

# Find the row indices for 'school.illit' and 'school.high'
lowest  <- which(rownames(dataprep.out$X0)=="school.illit")
highest <- which(rownames(dataprep.out$X0)=="school.high")

# Convert the values in X1 from 'school.illit' to 'school.high' into percentage shares
dataprep.out$X1[lowest:highest,] <- (100*dataprep.out$X1[lowest:highest,]) / sum(dataprep.out$X1[lowest:highest,])

# Scale the values in X0 from 'school.illit' to 'school.high' and convert into percentages
dataprep.out$X0[lowest:highest,] <- 100*scale(dataprep.out$X0[lowest:highest,], center=FALSE, scale=colSums(dataprep.out$X0[lowest:highest,]))

synth.out <- synth(data.prep.obj = dataprep.out,
                   method = "BFGS"
                   )

path.plot(synth.res = synth.out,
          dataprep.res = dataprep.out,
          tr.intake = NA,
          Ylab = "Real GDPpc",
          Xlab = "year",
          Ylim = c(0,12),
          Legend = c("Catalonia country","synthetic Catalonia"),
          Legend.position = "bottomright",
          )

gaps.plot(synth.res = synth.out,
           dataprep.res = dataprep.out,
           Ylab = "Gap in real GDPpc",
           Xlab = "year",
           Ylim = c(-1.5,1.5),
           Main = NA
           )

"""-   Synthetic control methods are beneficial because they allow for placebo tests. These tests reassign the intervention to units and periods where it didn't occur to test the method's effectiveness.
-   Abadie and Gardeazabal (2003) demonstrated the placebo test for the synthetic control method using Catalonia as an example. They showed that there was no identifiable treatment effect when the synthetic control method was applied to Catalonia.
-   There are several types of placebo tests that can be run with this package, such as placebos-in-time and placebos with outcome variables that should be unaffected by the treatment.
-   Users can perform exact inferential techniques similar to permutation tests by applying the synthetic control method to every control unit in the sample and collecting information on the gaps.
-   The user can plot these gaps to visually determine whether the line associated with the true synthetic control unit conspicuously differentiates itself from the rest.
-   The approach is implemented by running a for loop to implement placebo tests across all control units in the sample and collecting information on the gaps.
-   The results of this inferential technique can be seen in the figure below, where regions with a poor fit for the pre-treatment period are excluded.
-   The figure demonstrates that when exposure to terrorism is reassigned to other regions, there is a very low probability of obtaining a gap as large as the one obtained for the Basque region.
-   Poor-fitting regions are usually those that are very unusual in their pre-treatment characteristics, so no combination of other regions in the sample can reproduce the pre-treatment trends for these regions.
-   An alternative to excluding regions based on MPSE is to compute the distribution of the ratio of post- to pre-treatment MPSE.
"""

store <- matrix(NA,length(1955:1997),17)
colnames(store) <- unique(basque$regionname)[-1]

# run placebo test
for(iter in 2:18)
 {
 dataprep.out <-
              dataprep(foo = basque,
                       predictors = c("school.illit" , "school.prim" , "school.med" ,
                                      "school.high" , "school.post.high" , "invest") ,
                       predictors.op = "mean" ,
                       time.predictors.prior = 1964:1969 ,
                       special.predictors = list(
                         list("gdpcap" , 1960:1969 , "mean"),
                         list("sec.agriculture" ,      seq(1961,1969,2), "mean"),
                         list("sec.energy" ,           seq(1961,1969,2), "mean"),
                         list("sec.industry" ,         seq(1961,1969,2), "mean"),
                         list("sec.construction" ,     seq(1961,1969,2), "mean"),
                         list("sec.services.venta" ,   seq(1961,1969,2), "mean"),
                         list("sec.services.nonventa" ,seq(1961,1969,2), "mean"),
                         list("popdens", 1969, "mean")
                                                ),
                       dependent = "gdpcap",
                       unit.variable = "regionno",
                       unit.names.variable = "regionname",
                       time.variable = "year",
                       treatment.identifier = iter,
                       controls.identifier = c(2:18)[-iter+1],
                       time.optimize.ssr = 1960:1969,
                       time.plot = 1955:1997
                       )




 dataprep.out$X1["school.high",] <-
   dataprep.out$X1["school.high",] + dataprep.out$X1["school.post.high",]
 dataprep.out$X1 <-
   as.matrix(dataprep.out$X1[-which(rownames(dataprep.out$X1)=="school.post.high"),])
 dataprep.out$X0["school.high",] <-
   dataprep.out$X0["school.high",] + dataprep.out$X0["school.post.high",]
 dataprep.out$X0 <-
   dataprep.out$X0[-which(rownames(dataprep.out$X0)=="school.post.high"),]

 lowest  <- which(rownames(dataprep.out$X0)=="school.illit")
 highest <- which(rownames(dataprep.out$X0)=="school.high")

 dataprep.out$X1[lowest:highest,] <-
  (100*dataprep.out$X1[lowest:highest,]) /
   sum(dataprep.out$X1[lowest:highest,])
 dataprep.out$X0[lowest:highest,] <-
   100*scale(dataprep.out$X0[lowest:highest,],
             center=FALSE,
             scale=colSums(dataprep.out$X0[lowest:highest,])
  )

# run synth
synth.out <- synth(
                   data.prep.obj = dataprep.out,
                   method = "BFGS"
                   )

# store gaps
store[,iter-1] <- dataprep.out$Y1plot - (dataprep.out$Y0plot %*% synth.out$solution.w)
}

# now do figure
data <- store
rownames(data) <- 1955:1997

# Set bounds in gaps data
gap.start     <- 1
gap.end       <- nrow(data)
years         <- 1955:1997
gap.end.pre  <- which(rownames(data)=="1969")

#  MSPE Pre-Treatment
mse        <-             apply(data[ gap.start:gap.end.pre,]^2,2,mean)
basque.mse <- as.numeric(mse[16])
# Exclude states with 5 times higher MSPE than basque
data <- data[,mse<5*basque.mse]
Cex.set <- .75

# Plot
plot(years,data[gap.start:gap.end,which(colnames(data)=="Basque Country (Pais Vasco)")],
     ylim=c(-2,2),xlab="year",
     xlim=c(1955,1997),ylab="Gap in real GDPpc",
     type="l",lwd=2,col="black",
     xaxs="i",yaxs="i")

# Add lines for control states
for (i in 1:ncol(data)) { lines(years,data[gap.start:gap.end,i],col="gray") }

## Add Basque Line
lines(years,data[gap.start:gap.end,which(colnames(data)=="Basque Country (Pais Vasco)")],lwd=2,col="black")

# Add grid
abline(v=1970,lty="dotted",lwd=2)
abline(h=0,lty="dashed",lwd=2)
legend("bottomright",legend=c("Basque country","control regions"),
lty=c(1,1),col=c("black","gray"),lwd=c(2,1),cex=.8)
arrows(1967,-1.5,1968.5,-1.5,col="black",length=.1)
text(1961.5,-1.5,"Terrorism Onset",cex=Cex.set)
abline(v=1955)
abline(v=1997)
abline(h=-2)
abline(h=2)

"""# Concluding remarks

-   Synthetic control methods can be used to estimate causal effects.
-   These methods also enable precise inferential techniques when used with the Synth package in R.
-   Several enhancements to Synth are currently under development.
-   A regression-based method is being tested to populate the entire $V$ matrix, not just its diagonal.
-   A version of Synth is being refined to select the $W$ weights that best fit multiple outcome variables at the same time.
-   Work is in progress on a version of Synth that can handle multiple treatments introduced over a period of time.

# References

1. Abadie, A., Diamond, A., & Hainmueller, J. (2011). "Synth: An R Package for Synthetic Control Methods in Comparative Case Studies." *Journal of Statistical Software, 42*(13), 1--17. [DOI](https://doi.org/10.18637/jss.v042.i13)

2. Abadie, A., Diamond, A., & Hainmueller, J. (2010). "Synthetic Control Methods for Comparative Case Studies: Estimating the Effect of California's Tobacco Control Program." *Journal of the American Statistical Association, 105*(490), 493-505.

3. Abadie, A., & Gardeazabal, J. (2003). "The Economic Costs of Conflict: A Case Study of the Basque Country." *American Economic Review, 93*(1), 112-132.

4. Bertrand, M., Duflo, E., & Mullainathan, S. (2004). "How Much Should We Trust Differences-in-Differences Estimates?" *Quarterly Journal of Economics, 119*(1), 249-275.

5. Karatzoglou, A., Smola, A., Hornik, K., & Zeileis, A. (2004). "kernlab - An S4 Package for Kernel Methods in R." *Journal of Statistical Software, 11*(9), 1-20. [URL](http://www.jstatsoft.org/v11/i09/)

6. Lehmann, E. L. (1997). *Testing Statistical Hypotheses. 2nd edition.* University of California Press, Berkeley.

7. Mebane Jr, W. R., & Sekhon, J. S. (2011). "Genetic Optimization Using Derivatives: The rgenoud Package for R." *Journal of Statistical Software, 42*(11), 1-26. [URL](http://www.jstatsoft.org/v42/i11/)

# Videos

1. [Synthetic Control Method - MENAS workshop](https://www.youtube.com/watch?v=OyMB_D7RAtA)

2. [Overview and recent developments by Carl Bonander](https://www.youtube.com/watch?v=e5hmK5GzCHc)

3. [Synthetic Control I by Ben Elsner](https://www.youtube.com/watch?v=vmx3R8emVjQ)

4. [Synthetic Control II by Ben Elsner](https://www.youtube.com/watch?v=RwbFdga1V4Q)


5. [Methods NBER Lecture "Synthetic Controls: Methods and Practice" by Alberto Abadie](https://www.youtube.com/watch?v=oDNaOpNK6G4)

6. [Introduction to synthetic controls by Alberto Abadie](https://www.youtube.com/watch?v=nKzNp-qpE-I)

7. [El Control Sintético (In Spanish)](https://www.youtube.com/watch?v=uT6Gtzg1dyw)
"""

