<!DOCTYPE html>
<html lang="en"><head>
<script src="slides_files/libs/clipboard/clipboard.min.js"></script>
<script src="slides_files/libs/quarto-html/tabby.min.js"></script>
<script src="slides_files/libs/quarto-html/popper.min.js"></script>
<script src="slides_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="slides_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="slides_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="slides_files/libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="dcterms.date" content="2026-06-11">
  <title>Difference-in-Differences in Python</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/theme/quarto-530021870a52ee60b3f5e86ec9e6fece.css">
  <link href="slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Difference-in-Differences in Python</h1>
  <p class="subtitle">From the classic 2×2 design to staggered adoption and honest sensitivity</p>
  <div class="title-result-strip">
    <div class="kr"><span class="kr-num">5.12</span><span class="kr-cap">classic 2×2 ATT · true effect 5.0</span></div>
    <div class="kr"><span class="kr-num">2.41</span><span class="kr-cap">Callaway–Sant’Anna · TWFE biased to 2.18</span></div>
    <div class="kr"><span class="kr-num">M = 15</span><span class="kr-cap">HonestDiD breakdown</span></div>
  </div>
  <p class="author"><a href="https://carlos-mendez.org">Carlos Mendez</a></p>
  <p class="institute">Nagoya University (GSID)</p>
  <p class="date">June 11, 2026</p>
</section>
<section>
<section id="the-tension" class="title-slide slide level1 divider center" data-background-color="#d97757">
<h1>The Tension</h1>
<p><span class="act">Act I</span></p>
</section>
<section id="an-education-ministry-rolls-out-ai-tutors-in-some-cities-did-it-work-or-were-they-already-rising" class="slide level2 center">
<h2>An education ministry rolls out AI tutors in some cities — did it work, or were they already rising?</h2>
<p>Some cities adopt AI tutoring bots; others do not. Scores climb in the treated cities.</p>
<div class="fragment">
<p>But maybe those cities were <em>already</em> on the way up. <em>How do you separate the policy from the trend it rode in on?</em></p>
<aside class="notes">
<p>This is the core challenge of policy evaluation: separating the genuine effect of an intervention from pre-existing trends and selection differences between treated and untreated groups. Card and Krueger (1994) pioneered the answer with New Jersey vs Pennsylvania fast-food employment after a minimum-wage rise.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="did-uses-the-control-group-as-a-mirror-for-the-treated-groups-missing-counterfactual" class="slide level2 center">
<h2>DiD uses the control group as a mirror for the treated group’s missing counterfactual</h2>

<img data-src="../did_parallel_trends.png" class="r-stretch quarto-figure-center"><p class="caption">Both groups track in lockstep for periods 0–4, then the treated group jumps at treatment onset. The gap after period 5 is the effect.</p><aside class="notes">
<p>Spoiler-style framing figure. Don’t dwell on the numbers yet — just plant the idea: if the two groups moved in parallel before treatment, the control group’s post-treatment path is what the treated group would have done absent the policy. The gap is the causal effect.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="where-were-going" class="slide level2 center">
<h2>Where we’re going</h2>
<ul>
<li class="fragment">The logic: why differencing twice identifies the ATT under parallel trends</li>
<li class="fragment">The classic 2×2 estimator and a formal pre-trends test</li>
<li class="fragment">Event studies: the effect period by period</li>
<li class="fragment">Why naive TWFE breaks under staggered timing — and how Callaway–Sant’Anna fixes it</li>
<li class="fragment">HonestDiD: how wrong can parallel trends be before the answer flips?</li>
</ul>
</section></section>
<section>
<section id="the-investigation" class="title-slide slide level1 divider center" data-background-color="#6a9bcc">
<h1>The Investigation</h1>
<p><span class="act">Act II</span></p>
</section>
<section id="did-estimates-the-att-the-effect-on-the-units-that-actually-got-treated" class="slide level2 center">
<h2>DiD estimates the ATT — the effect on the units that actually got treated</h2>
<p><span class="math display">\[\text{ATT} = E[Y^1_k - Y^0_k \mid \text{Post}]\]</span></p>
<p>The average gap between what treated units experienced and what they <em>would have</em> experienced without the policy.</p>
<p><span class="comment"><span class="math inline">\(E[Y^0_k\mid\text{Post}]\)</span> — the treated group’s untreated outcome — is a counterfactual we never observe. DiD reconstructs it from the control group.</span></p>
<aside class="notes">
<p>The fundamental problem of causal inference: for any one unit we see only one potential outcome. We give up on individual effects and target the average over the treated subpopulation. ATT, not ATE — this is the policy-relevant quantity: did it help the people it was aimed at?</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="difference-twice-kill-the-level-gap-then-kill-the-common-trend" class="slide level2 center">
<h2>Difference twice: kill the level gap, then kill the common trend</h2>
<p><span class="math display">\[\hat{\delta}^{2 \times 2}_{kU} = \big( \bar{Y}_k^{Post} - \bar{Y}_k^{Pre} \big) - \big( \bar{Y}_U^{Post} - \bar{Y}_U^{Pre} \big)\]</span></p>
<p>The first difference removes time-invariant differences between groups; the second removes the trend common to both.</p>
<p><span class="comment">Algebra splits this into <span class="math inline">\(\underbrace{\text{ATT}}\)</span> plus a <span class="math inline">\(\underbrace{\text{non-parallel-trends bias}}\)</span>. The bias vanishes exactly when parallel trends holds.</span></p>
<aside class="notes">
<p>The Cunningham (2021) decomposition: the 2×2 estimator equals the ATT plus a bias term comparing the untreated trajectories of the two groups. If their untreated outcomes would have moved in parallel, the bias is zero and DiD cleanly identifies the ATT.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="parallel-trends-is-about-slopes-not-levels-and-it-is-fundamentally-untestable" class="slide level2 center">
<h2>Parallel trends is about slopes, not levels — and it is fundamentally untestable</h2>
<p><span class="math display">\[E[Y^0_k|\text{Post}] - E[Y^0_k|\text{Pre}] = E[Y^0_U|\text{Post}] - E[Y^0_U|\text{Pre}]\]</span></p>
<p>Two cities can sit at different score <em>levels</em>; DiD only needs them to have been <em>rising at the same speed</em> absent treatment.</p>
<p><span class="comment">We can check pre-treatment trends, but never the post-treatment counterfactual — which is why Act III brings sensitivity analysis.</span></p>
<aside class="notes">
<p>This is the load-bearing assumption. It does not require equal levels — only equal trends. And the post-treatment half is untestable because the treated group’s untreated outcome is never observed. Roth (2022) also warns that conditioning on passing a pre-test distorts later inference.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-lab-a-100-unit-10-period-panel-built-with-a-known-true-effect-of-5.0" class="slide level2 center">
<h2>The lab: a 100-unit, 10-period panel built with a known true effect of 5.0</h2>
<ul>
<li class="fragment"><strong>1,000 observations</strong> — 100 units × 10 periods (0–9)</li>
<li class="fragment"><strong>50 treated, 50 control</strong>; treatment switches on at period 5</li>
<li class="fragment"><strong>True effect = 5.0</strong> baked in, so every estimate has a ground truth to hit</li>
</ul>
<p><span class="comment">A built-in <code>true_effect</code> column gives every estimate a known target to hit.</span></p>
<aside class="notes">
<p>Using simulated data with a known effect is the pedagogical move: we can verify the estimator recovers the truth before trusting it on real data where the truth is unknown. The 2×2 crosstab is perfectly balanced — 250 observations in each of the four cells.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="before-treatment-the-two-groups-overlap-after-the-treated-box-jumps-far-higher" class="slide level2 center">
<h2>Before treatment the two groups overlap; after, the treated box jumps far higher</h2>

<img data-src="../did_outcome_distribution.png" class="r-stretch quarto-figure-center"><p class="caption">Outcome distributions by group × period. Control (steel) and treated (orange) overlap pre-treatment near 10.6–11.1; the treated box jumps to ~18.9 post-treatment.</p><aside class="notes">
<p>The raw means already tell the story: pre-treatment the control mean is 10.61 and treated 11.11 — a negligible 0.50 gap. Post-treatment the control rises to 13.09 (+2.47) but the treated jumps to 18.71 (+7.59). The extra gain, 7.59 − 2.47 = 5.12, is the DiD estimate before we run any regression.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-shaded-gap-is-the-causal-effect-treated-outcomes-minus-their-projected-counterfactual" class="slide level2 center">
<h2>The shaded gap <em>is</em> the causal effect: treated outcomes minus their projected counterfactual</h2>

<img data-src="../did_treatment_effect.png" class="r-stretch quarto-figure-center"><p class="caption">The teal dashed line is the control group’s path shifted to the treated group’s pre-level — the no-treatment counterfactual. The shaded gap is the ~5.1 ATT.</p><aside class="notes">
<p>This makes the DiD logic tangible. We build the counterfactual by shifting the control group’s post-treatment trajectory up by the pre-treatment level gap between the groups. The shaded area between the actual treated outcomes and that counterfactual is the estimated causal effect — about 5.1 per period. The control group is the mirror.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="six-lines-fit-the-classic-22-estimator-with-the-diff-diff-package" class="slide level2 center">
<h2>Six lines fit the classic 2×2 estimator with the diff-diff package</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-code-line-numbers="1-2|4-5|6"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href=""></a><span class="im">from</span> diff_diff <span class="im">import</span> DifferenceInDifferences, generate_did_data</span>
<span id="cb1-2"><a href=""></a>data <span class="op">=</span> generate_did_data(n_units<span class="op">=</span><span class="dv">100</span>, n_periods<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb1-3"><a href=""></a>                         treatment_effect<span class="op">=</span><span class="fl">5.0</span>, treatment_period<span class="op">=</span><span class="dv">5</span>, seed<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb1-4"><a href=""></a>did <span class="op">=</span> DifferenceInDifferences()</span>
<span id="cb1-5"><a href=""></a>res <span class="op">=</span> did.fit(data, outcome<span class="op">=</span><span class="st">"outcome"</span>, treatment<span class="op">=</span><span class="st">"treated"</span>, time<span class="op">=</span><span class="st">"post"</span>)</span>
<span id="cb1-6"><a href=""></a>res.print_summary()   <span class="co"># ATT = 5.1216, 95% CI [4.6399, 5.6034]</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>A scikit-learn-style API: build the estimator, call .fit() with the column names for outcome, treatment, and the pre/post time indicator. The diff-diff package validates 13+ DiD estimators against their R counterparts. Full script is in the post.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-classic-estimator-recovers-5.12-within-2.4-of-the-true-5.0" class="slide level2 center" data-background-color="#141413">
<h2>The classic estimator recovers 5.12 — within 2.4% of the true 5.0</h2>
<p><span class="bignum">5.12</span></p>
<p><span class="bignum-label">Classic 2×2 <span class="math inline">\(\widehat{\text{ATT}}\)</span> (SE 0.25, <span class="math inline">\(t = 20.9\)</span>) · 95% CI [4.64, 5.60] covers the true 5.0</span></p>
<aside class="notes">
<p>The 95% confidence interval [4.64, 5.60] comfortably contains the true value of 5.0. The 0.12 overshoot is sampling variability, not bias. With one treatment time and two groups, the classic estimator is exactly right for the job.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-formal-pre-trends-test-fails-to-reject-parallel-trends-slope-gap-0.12-p-0.29" class="slide level2 center">
<h2>A formal pre-trends test fails to reject parallel trends: slope gap 0.12, p = 0.29</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Group</th>
<th style="text-align: right;">Pre-trend slope</th>
<th style="text-align: right;">SE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Treated</td>
<td style="text-align: right;">0.5262</td>
<td style="text-align: right;">0.0839</td>
</tr>
<tr class="even">
<td>Control</td>
<td style="text-align: right;">0.4047</td>
<td style="text-align: right;">0.0798</td>
</tr>
<tr class="odd">
<td>Difference</td>
<td style="text-align: right;"><span class="key">0.1216</span></td>
<td style="text-align: right;">0.1158</td>
</tr>
</tbody>
</table>
<p><span class="comment"><span class="math inline">\(t = 1.05\)</span>, <span class="math inline">\(p = 0.29\)</span> — fail to reject equal slopes. But <em>failing to reject is not confirming</em>: the test has low power with only 5 pre-periods.</span></p>
<aside class="notes">
<p>The treated and control slopes differ by just 0.12, far from significant. This removes the most obvious objection to parallel trends but cannot prove it. With only 5 pre-treatment periods the test has limited power, and Roth (2022) shows pre-testing can distort later inference. That is precisely why HonestDiD enters in Act III.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-event-study-splits-the-single-att-into-one-effect-per-period-relative-to-treatment" class="slide level2 center">
<h2>The event study splits the single ATT into one effect per period relative to treatment</h2>
<p><span class="math display">\[Y_{it} = \gamma_i + \lambda_t + \sum_{k=-K+1}^{-2}\beta_k^{lead}D_{it}^k + \sum_{k=0}^{L}\beta_k^{lag}D_{it}^k + \varepsilon_{it}\]</span></p>
<p>The <strong>leads</strong> <span class="math inline">\(\beta_k^{lead}\)</span> are placebo tests (should be ~0); the <strong>lags</strong> <span class="math inline">\(\beta_k^{lag}\)</span> trace how the effect evolves. The period before treatment is the omitted reference.</p>
<aside class="notes">
<p>This one equation does two jobs at once: the leads test parallel trends period by period, and the lags reveal whether the effect appears instantly, builds up, or fades. Unit and time fixed effects implement the “two-way” structure. Period k = −1 is normalized to zero as the baseline.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="leads-sit-on-zero-lags-snap-to-5.0-the-visual-signature-of-a-clean-did" class="slide level2 center">
<h2>Leads sit on zero, lags snap to ~5.0 — the visual signature of a clean DiD</h2>

<img data-src="../did_event_study.png" class="r-stretch quarto-figure-center"><p class="caption">Pre-treatment coefficients (steel) hover at zero with CIs crossing it; post-treatment coefficients (orange) jump to ~5.0, matching the teal true-effect line.</p><aside class="notes">
<p>Pre-treatment leads range from −0.52 to −0.28, all insignificant (p &gt; 0.3) — the placebo test passes. Post-treatment lags run 4.65 to 5.02, all with t &gt; 9. The effect is stable: no build-up, no fade-out. The teal dotted line at 5.0 shows every post estimate landing on the truth.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="real-policies-roll-out-city-by-city-and-that-staggered-timing-breaks-naive-twfe" class="slide level2 center">
<h2>Real policies roll out city by city — and that staggered timing breaks naive TWFE</h2>
<ul>
<li class="fragment"><strong>3,000 observations</strong> — 300 units × 10 periods</li>
<li class="fragment"><strong>Three cohorts</strong> adopt at periods 3, 5, 7 (60, 75, 75 units)</li>
<li class="fragment"><strong>90 never-treated</strong> units — a clean control group</li>
<li class="fragment">Effects <strong>grow over time</strong> by construction (2.0 → 3.2 for the earliest cohort)</li>
</ul>
<p><span class="comment">TWFE fits one pooled <span class="math inline">\(\delta\)</span> — a weighted average of many 2×2 comparisons, some of them poisoned.</span></p>
<aside class="notes">
<p>The TWFE specification is Y_it = γ_i + λ_t + δ·D_it + ε_it. With a single treatment time, δ is correct. With staggered timing it becomes a weighted average of all pairwise 2×2 comparisons — and some of those use already-treated units as controls. When effects grow over time, that drags the estimate down.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="cohorts-move-in-parallel-then-jump-at-their-own-onset-twfe-then-mis-uses-early-adopters-as-controls" class="slide level2 center">
<h2>Cohorts move in parallel, then jump at <em>their own</em> onset — TWFE then mis-uses early adopters as controls</h2>

<img data-src="../did_staggered_trends.png" class="r-stretch quarto-figure-center"><p class="caption">Four cohorts track together pre-treatment, then cohort 3 (orange), 5 (teal), 7 (near black) each jump at its onset; never-treated (steel) drifts gently up.</p><aside class="notes">
<p>Between periods 3 and 7, TWFE uses cohort 3 — already treated and elevated — as a comparison for the not-yet-treated cohort 7. Cohort 3’s outcomes already carry a treatment effect of ~2.8, so the comparison understates cohort 7’s true effect. This is the forbidden comparison made visible.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-goodmanbacon-decomposition-shows-28.3-of-twfes-weight-is-on-forbidden-comparisons" class="slide level2 center">
<h2>The Goodman–Bacon decomposition shows 28.3% of TWFE’s weight is on forbidden comparisons</h2>

<img data-src="../did_bacon_decomposition.png" class="r-stretch quarto-figure-center"><p class="caption">Left: each 2×2 comparison as a point, forbidden ones (dark orange) cluster low. Right: weight by type — nearly a third on forbidden comparisons.</p><table class="caption-top">
<thead>
<tr class="header">
<th>Comparison type</th>
<th style="text-align: right;">Weight</th>
<th style="text-align: right;">Avg effect</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Treated vs never-treated (clean)</td>
<td style="text-align: right;">0.433</td>
<td style="text-align: right;">2.37</td>
</tr>
<tr class="even">
<td>Earlier vs later treated</td>
<td style="text-align: right;">0.284</td>
<td style="text-align: right;">2.20</td>
</tr>
<tr class="odd">
<td>Later vs earlier (forbidden)</td>
<td style="text-align: right;"><span class="key">0.283</span></td>
<td style="text-align: right;">1.60</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>The decomposition writes TWFE as a weighted average of every 2×2. The forbidden comparisons — already-treated units as controls — carry 28.3% of the weight and an average of only 1.60, well below the 2.37 from clean comparisons. That downward pull is what biases TWFE.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="forbidden-comparisons-drag-twfe-down-to-a-biased-2.18" class="slide level2 center" data-background-color="#141413">
<h2>Forbidden comparisons drag TWFE down to a biased 2.18</h2>
<p><span class="bignum">2.18</span></p>
<p><span class="bignum-label">Naive TWFE <span class="math inline">\(\hat{\delta}\)</span> · downward-biased by 28.3% weight on forbidden comparisons (avg effect 1.60)</span></p>
<aside class="notes">
<p>For a policymaker reading the TWFE number, 2.18 understates the true impact. The contamination is not a rounding error — it is a structural feature of pooling heterogeneous, dynamically-growing effects with already-treated controls.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="callawaysantanna-rebuilds-the-estimate-from-clean-group-time-atts-only" class="slide level2 center">
<h2>Callaway–Sant’Anna rebuilds the estimate from clean group-time ATTs only</h2>
<p><span class="math display">\[\text{ATT}(g,t) = E[Y_t - Y_{g-1}\mid G=g] - E[Y_t - Y_{g-1}\mid G=\infty]\]</span></p>
<p>Each building block is a 2×2 that compares cohort <span class="math inline">\(g\)</span> against the <strong>never-treated</strong> group only — every forbidden comparison eliminated by construction.</p>
<p><span class="comment">A <em>doubly robust</em> version reweights controls (propensity) <strong>and</strong> models their outcome change (regression): valid if <em>either</em> is right.</span></p>
<aside class="notes">
<p>CS computes a separate ATT for each cohort g and calendar period t, using only never-treated controls, then aggregates with valid weights. The doubly robust estimator is belt-and-suspenders: inverse-probability weighting plus outcome regression, consistent if either model is correctly specified.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="theory-vs-naive-same-data-but-cs-uses-only-valid-comparisons" class="slide level2 center">
<h2>Theory vs naive: same data, but CS uses only valid comparisons</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="naive-twfe">Naive TWFE</h3>
<ul>
<li>one pooled coefficient</li>
<li>28.3% weight on forbidden comparisons</li>
<li><span class="math inline">\(\hat{\delta} = 2.18\)</span> (biased low)</li>
<li>hides the dynamics</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="callawaysantanna">Callaway–Sant’Anna</h3>
<ul>
<li>clean group-time ATTs</li>
<li>never-treated controls only</li>
<li>overall <span class="math inline">\(\widehat{\text{ATT}} = 2.41\)</span></li>
<li>recovers the growth path</li>
</ul>
</div></div>
<aside class="notes">
<p>Same staggered data, two estimators. CS’s 2.41 is a 10% upward correction over TWFE’s 2.18 — precisely the bias the Bacon decomposition predicted. And CS does something TWFE cannot: it preserves the period-by-period dynamics instead of collapsing them into one number.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="cs-recovers-a-clean-2.41-and-the-effect-grows-from-1.97-to-3.27-over-six-periods" class="slide level2 center">
<h2>CS recovers a clean 2.41, and the effect <em>grows</em> from 1.97 to 3.27 over six periods</h2>

<img data-src="../did_staggered_att.png" class="r-stretch quarto-figure-center"><p class="caption">CS event study: pre-treatment effects pinned near zero (period −1 = 0 by construction); post-treatment effects rise steadily from ~2.0 to ~3.3.</p><aside class="notes">
<p>Overall CS ATT = 2.41 (SE 0.06, p &lt; 0.001), CI [2.31, 2.52] — above TWFE’s 2.18, confirming the downward bias. The seven pre-treatment coefficients all hover near zero (none individually significant), and the lags climb from 1.97 immediately post-treatment to 3.27 by six periods out. The growing path is exactly the case where TWFE fails worst.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="does-machine-selecting-comparisons-make-this-causal-no-parallel-trends-still-carries-the-weight" class="slide level2 center">
<h2>Does machine-selecting comparisons make this causal? No — parallel trends still carries the weight</h2>
<p><span class="objection">Objection.</span> Switching from TWFE to Callaway–Sant’Anna can’t manufacture identification.</p>
<div class="fragment">
<p><span class="rebuttal">Response.</span> Correct. CS only removes <em>contaminated</em> comparisons; the ATT is still identified <strong>only under parallel trends and no anticipation</strong>. It buys credibility on the timing problem, not on the untestable counterfactual — so we stress-test that next.</p>
<aside class="notes">
<p>Steelman, don’t strawman. CS fixes the aggregation problem (forbidden comparisons), not the identifying assumption. Parallel trends in the post-treatment period remains untestable. That honest gap is what HonestDiD is built to quantify.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section></section>
<section>
<section id="the-resolution" class="title-slide slide level1 divider center" data-background-color="#00d4c8">
<h1>The Resolution</h1>
<p><span class="act">Act III</span></p>
</section>
<section id="honestdid-asks-how-big-a-parallel-trends-violation-before-the-answer-flips" class="slide level2 center">
<h2>HonestDiD asks: how big a parallel-trends violation before the answer flips?</h2>
<p><span class="math display">\[|\delta_t| \leq M \cdot \max_{t' &lt; g}|\delta_{t'}|, \quad \text{for all } t \geq g\]</span></p>
<p><span class="math inline">\(M\)</span> is a stress dial: <span class="math inline">\(M=0\)</span> assumes perfect parallel trends; <span class="math inline">\(M=5\)</span> allows post-treatment violations five times the worst pre-treatment one. The <strong>breakdown value</strong> is where the CI first touches zero.</p>
<aside class="notes">
<p>Rambachan &amp; Roth (2023) replace the all-or-nothing parallel-trends assumption with a bounded one. As M rises, the robust CI widens. The breakdown value of M — where significance is lost — is the single most informative robustness number you can report.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-ci-stays-above-zero-even-when-violations-are-15-the-worst-pre-trend" class="slide level2 center">
<h2>The CI stays above zero even when violations are 15× the worst pre-trend</h2>

<img data-src="../did_honest_sensitivity.png" class="r-stretch quarto-figure-center"><p class="caption">Robust 95% CI (steel band) widening with M; ATT (teal) flat at 2.41; the lower bound is still positive (0.38) at the M = 15 grid edge (orange line).</p><p><span class="comment">At <span class="math inline">\(M=0\)</span>: CI [2.53, 2.66]. At <span class="math inline">\(M=15\)</span>: CI [0.38, 4.81] — still excludes zero.</span></p>
<aside class="notes">
<p>The band expands symmetrically as M grows. At M = 10 the lower bound is still 1.10; at M = 15 it is 0.38 — the grid edge, with the true breakdown lying even further out. In applied work a breakdown above M = 3 is considered strong. This result clears that bar five times over.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-conclusion-survives-violations-15-worse-than-anything-seen-pre-treatment" class="slide level2 center" data-background-color="#141413">
<h2>The conclusion survives violations 15× worse than anything seen pre-treatment</h2>
<p><span class="bignum">M = 15</span></p>
<p><span class="bignum-label">HonestDiD breakdown value · CI excludes zero even at 15× the largest pre-treatment deviation</span></p>
<aside class="notes">
<p>To overturn the effect, post-treatment parallel-trend violations would have to exceed 15 times the worst pre-treatment departure — an extreme structural break coinciding exactly with treatment timing. Even a determined skeptic would struggle to argue the treatment did nothing.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="three-estimators-one-honest-verdict-the-effect-is-real-growing-and-robust" class="slide level2 center">
<h2>Three estimators, one honest verdict: the effect is real, growing, and robust</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Setting</th>
<th>Estimator</th>
<th style="text-align: right;"><span class="math inline">\(\widehat{\text{ATT}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Single timing</td>
<td>Classic 2×2</td>
<td style="text-align: right;"><span class="key">5.12</span></td>
</tr>
<tr class="even">
<td>Staggered (naive)</td>
<td>TWFE</td>
<td style="text-align: right;">2.18</td>
</tr>
<tr class="odd">
<td>Staggered (clean)</td>
<td>Callaway–Sant’Anna</td>
<td style="text-align: right;"><span class="key">2.41</span></td>
</tr>
</tbody>
</table>
<p><span class="comment">Always report the breakdown value alongside the estimate — here <span class="math inline">\(M = 15\)</span>, exceptionally robust.</span></p>
<aside class="notes">
<p>The classic estimator nails 5.0 when timing is uniform. Under staggered timing, naive TWFE is biased to 2.18; CS corrects it to 2.41 and reveals the growth dynamics; HonestDiD certifies robustness at M = 15. Caveats: synthetic data, linearly-growing effects, no spillovers — real applications need covariates and additional robustness checks.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section id="let-the-design-not-the-default-regression-choose-your-comparisons." class="title-slide slide level1 divider center" data-background-color="#141413">
<h1>Let the design — not the default regression — choose your comparisons.</h1>
<aside class="notes">
<p>The single takeaway. Under staggered timing, the default TWFE coefficient silently mixes forbidden comparisons; a modern estimator that uses only clean comparisons, paired with an honest sensitivity bound, is the difference between a biased 2.18 and a credible, robust 2.41.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="slides_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="slides_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="slides_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="slides_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="slides_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="slides_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="slides_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>