* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- quota_example.dta ----
use "quota_example.dta", clear
label data "Balanced country panel: women in parliament + gender quotas, 1990-2015"
note _dta: Balanced annual panel from the sdid package (Bhalotra, Clarke, Gomes & Venkataramani 2023): 119 countries x 26 years = 3,094 obs. Outcome womparl, absorbing treatment quota, covariate lngdp; quotaYear gives each adopting country's cohort (2000-2013), missing for the 110 never-treated.
note womparl: Percentage of seats held by women in the national (lower) parliament - the outcome.. Construction: Distributed with the quota_example dataset; observed annually per country.. Units: % of seats. Source: quota_example (Bhalotra et al. 2023)
note lnmmrt: Natural log of the maternal mortality ratio (ships with the dataset; not used in the post's quota analysis).. Construction: Distributed with the quota_example dataset.. Units: log ratio. Source: quota_example (Bhalotra et al. 2023)
note country: Country name - the panel unit (i).. Construction: 119 countries; 9 ever adopt a quota, 110 never treated (the donor pool).. Units: string. Source: quota_example (Bhalotra et al. 2023)
note year: Calendar year - the panel time index (t).. Construction: Annual, 1990-2015 (26 years), balanced across all countries.. Units: year. Source: quota_example (Bhalotra et al. 2023)
note quota: Treatment indicator: 1 once a country has a reserved-seat gender quota, 0 before / never.. Construction: Absorbing - switches to 1 in the adoption year and stays on; 1 for ~3% of country-years.. Units: 0/1. Source: quota_example (Bhalotra et al. 2023)
note lngdp: Natural log of GDP per capita - the covariate (X).. Construction: Distributed with the quota_example dataset; used in the optimized/projected covariate specifications.. Units: log GDP. Source: quota_example (Bhalotra et al. 2023)
note quotaYear: First year a country is treated - its adoption cohort; missing for the 110 never-treated countries.. Construction: Cohorts: 2000, 2002, 2003, 2005, 2010, 2012, 2013 (two countries each in 2002 and 2003, one in the rest).. Units: year. Source: quota_example (Bhalotra et al. 2023)
save "quota_example.dta", replace
