* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- abdata.dta ----
use "abdata.dta", clear
label data "Arellano-Bond UK firm panel: employment, wages, capital (levels + logs)"
note _dta: The classic Arellano & Bond (1991) UK manufacturing employment panel, distributed with pydynpd. Columns n/w/k/ys are the natural logs of emp/wage/cap/indoutpt; estimation uses the logged variables.
note id: Sequential firm (panel unit) identifier; 140 UK manufacturing firms.. Construction: From the Arellano-Bond panel; the panel id passed to estimators as [id, year].. Units: integer. Source: Arellano & Bond (1991)
note year: Annual time index of the observation.. Construction: From the Arellano-Bond panel; range 1976-1984.. Units: year. Source: Arellano & Bond (1991)
note emp: Firm employment in thousands (the level behind log employment n).. Construction: Raw level; n = log(emp).. Units: thousands of employees. Source: Arellano & Bond (1991)
note wage: Firm real product wage (the level behind log wage w).. Construction: Raw level; w = log(wage).. Units: index/level. Source: Arellano & Bond (1991)
note cap: Firm gross capital stock (the level behind log capital k).. Construction: Raw level; k = log(cap).. Units: index/level. Source: Arellano & Bond (1991)
note indoutpt: Industry-level output for the firm's sector (the level behind log industry output ys).. Construction: Raw level; ys = log(indoutpt).. Units: index/level. Source: Arellano & Bond (1991)
note n: Natural log of firm employment; the dependent variable of the dynamic model.. Construction: log(emp).. Units: log thousands. Source: Arellano & Bond (1991)
note w: Natural log of the firm real wage; a current control.. Construction: log(wage).. Units: log level. Source: Arellano & Bond (1991)
note k: Natural log of the firm gross capital stock; a current control.. Construction: log(cap).. Units: log level. Source: Arellano & Bond (1991)
note ys: Natural log of industry output for the firm's sector (auxiliary variable).. Construction: log(indoutpt).. Units: log level. Source: Arellano & Bond (1991)
save "abdata.dta", replace

* ---- data_prepared.dta ----
use "data_prepared.dta", clear
label data "Analysis sample: abdata plus firm-wise lags and first differences"
note _dta: abdata.csv with one-period lags (n_lag1, w_lag1, k_lag1), the two-period employment lag (n_lag2), and firm-wise first differences (d_n, d_w, d_k, d_n_lag1, d_w_lag1, d_k_lag1). All transforms computed within firm id; the lagged/differenced columns are blank for the observations that lack a prior year.
note id: Sequential firm (panel unit) identifier; 140 UK manufacturing firms.. Construction: From the Arellano-Bond panel; the panel id passed to estimators as [id, year].. Units: integer. Source: Arellano & Bond (1991)
note year: Annual time index of the observation.. Construction: From the Arellano-Bond panel; range 1976-1984.. Units: year. Source: Arellano & Bond (1991)
note emp: Firm employment in thousands (the level behind log employment n).. Construction: Raw level; n = log(emp).. Units: thousands of employees. Source: Arellano & Bond (1991)
note wage: Firm real product wage (the level behind log wage w).. Construction: Raw level; w = log(wage).. Units: index/level. Source: Arellano & Bond (1991)
note cap: Firm gross capital stock (the level behind log capital k).. Construction: Raw level; k = log(cap).. Units: index/level. Source: Arellano & Bond (1991)
note indoutpt: Industry-level output for the firm's sector (the level behind log industry output ys).. Construction: Raw level; ys = log(indoutpt).. Units: index/level. Source: Arellano & Bond (1991)
note n: Natural log of firm employment; the dependent variable of the dynamic model.. Construction: log(emp).. Units: log thousands. Source: Arellano & Bond (1991)
note w: Natural log of the firm real wage; a current control.. Construction: log(wage).. Units: log level. Source: Arellano & Bond (1991)
note k: Natural log of the firm gross capital stock; a current control.. Construction: log(cap).. Units: log level. Source: Arellano & Bond (1991)
note ys: Natural log of industry output for the firm's sector (auxiliary variable).. Construction: log(indoutpt).. Units: log level. Source: Arellano & Bond (1991)
note n_lag1: Last year's log employment; the lagged dependent variable carrying persistence rho (labeled L1.n in GMM output).. Construction: Within firm id: n_i,t-1 = groupby('id')['n'].shift(1).. Units: log thousands. Source: Derived (this study)
note w_lag1: Last year's log real wage; a lagged control in the levels equation.. Construction: Within firm id: w_i,t-1 = groupby('id')['w'].shift(1).. Units: log level. Source: Derived (this study)
note k_lag1: Last year's log capital stock; a lagged control in the levels equation.. Construction: Within firm id: k_i,t-1 = groupby('id')['k'].shift(1).. Units: log level. Source: Derived (this study)
note n_lag2: Log employment two years ago; the Anderson-Hsiao instrument for the differenced lag.. Construction: Within firm id: n_i,t-2 = groupby('id')['n'].shift(2).. Units: log thousands. Source: Derived (this study)
note d_n: Year-on-year change in log employment; the dependent variable of the differenced equation.. Construction: Within firm id: n_it - n_i,t-1 = groupby('id')['n'].diff().. Units: log change. Source: Derived (this study)
note d_w: Year-on-year change in the log real wage.. Construction: Within firm id: w_it - w_i,t-1 = groupby('id')['w'].diff().. Units: log change. Source: Derived (this study)
note d_k: Year-on-year change in the log capital stock.. Construction: Within firm id: k_it - k_i,t-1 = groupby('id')['k'].diff().. Units: log change. Source: Derived (this study)
note d_n_lag1: Last year's change in log employment; the endogenous regressor in the Anderson-Hsiao 2SLS.. Construction: Within firm id: d_n_i,t-1 = groupby('id')['d_n'].shift(1).. Units: log change. Source: Derived (this study)
note d_w_lag1: Last year's change in the log real wage; a control in the differenced equation.. Construction: Within firm id: d_w_i,t-1 = groupby('id')['d_w'].shift(1).. Units: log change. Source: Derived (this study)
note d_k_lag1: Last year's change in the log capital stock; a control in the differenced equation.. Construction: Within firm id: d_k_i,t-1 = groupby('id')['d_k'].shift(1).. Units: log change. Source: Derived (this study)
save "data_prepared.dta", replace
