<!DOCTYPE html>
<html lang="en"><head>
<script src="slides_files/libs/clipboard/clipboard.min.js"></script>
<script src="slides_files/libs/quarto-html/tabby.min.js"></script>
<script src="slides_files/libs/quarto-html/popper.min.js"></script>
<script src="slides_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="slides_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="slides_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="slides_files/libs/quarto-html/quarto-syntax-highlighting-dark-f1aadacce99040138bbb613f9330654f.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="dcterms.date" content="2026-07-08">
  <title>Evaluating a Cash Transfer RCT with Panel Data</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #e1e4e8; background-color: #24292e; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #e1e4e8; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #f97583; } /* Attribute */
    code span.bn { color: #79b8ff; } /* BaseN */
    code span.bu { color: #f97583; } /* BuiltIn */
    code span.cf { color: #f97583; } /* ControlFlow */
    code span.ch { color: #9ecbff; } /* Char */
    code span.cn { color: #79b8ff; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #f97583; } /* DataType */
    code span.dv { color: #79b8ff; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #f97583; font-weight: bold; } /* Extension */
    code span.fl { color: #79b8ff; } /* Float */
    code span.fu { color: #b392f0; } /* Function */
    code span.im { color: #9ecbff; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #f97583; } /* Keyword */
    code span.op { color: #e1e4e8; } /* Operator */
    code span.ot { color: #b392f0; } /* Other */
    code span.pp { color: #f97583; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #79b8ff; } /* SpecialChar */
    code span.ss { color: #9ecbff; } /* SpecialString */
    code span.st { color: #9ecbff; } /* String */
    code span.va { color: #ffab70; } /* Variable */
    code span.vs { color: #9ecbff; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/theme/quarto-30e199f8599492bc715969fb4e1d58d2.css">
  <link href="slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-dark">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Evaluating a Cash Transfer RCT with Panel Data</h1>
  <p class="subtitle">When randomization is clean, every estimator should land on the truth — and here it does</p>
  <div class="title-result-strip">
    <div class="kr"><span class="kr-num">0.113</span><span class="kr-cap">RA · IPW · DR all converge</span></div>
    <div class="kr"><span class="kr-num">0.137</span><span class="kr-cap">doubly-robust DiD (ATT)</span></div>
    <div class="kr"><span class="kr-num">0.12</span><span class="kr-cap">true effect · every CI covers it</span></div>
  </div>
  <p class="author"><a href="https://carlos-mendez.org">Carlos Mendez</a></p>
  <p class="institute">Nagoya University (GSID)</p>
  <p class="date">July 8, 2026</p>
</section>
<section>
<section id="the-tension" class="title-slide slide level1 divider center" data-background-color="#d97757">
<h1>The Tension</h1>
<p><span class="act">Act I</span></p>
</section>
<section id="governments-spend-billions-on-cash-transfers-but-does-the-money-actually-raise-welfare" class="slide level2 center">
<h2>Governments spend billions on cash transfers — but does the money actually raise welfare?</h2>
<p>The hard part isn’t sending the money — it is <em>proving</em> it worked.</p>
<div class="fragment">
<p>So we simulate a known truth: the program raises consumption by <strong>12%</strong> (<span class="math inline">\(0.12\)</span> log points). <em>Can the estimators recover it?</em></p>
<aside class="notes">
<p>Cash transfers are among the most common development interventions worldwide. Open with the policy stakes, then reveal the pedagogical trick: simulated data with a known true effect of 0.12 log points. The whole talk is a controlled experiment on the estimators themselves — we judge each method by how close it lands to a ground truth we planted.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="one-dataset-twelve-estimates-and-the-spread-already-tells-a-story" class="slide level2 center">
<h2>One dataset, twelve estimates — and the spread already tells a story</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Estimator family</th>
<th style="text-align: center;">Estimand</th>
<th style="text-align: center;">Estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cross-sectional (RA / IPW / DR)</td>
<td style="text-align: center;">ATE (offer)</td>
<td style="text-align: center;"><span class="key">0.113</span></td>
</tr>
<tr class="even">
<td>Difference-in-differences</td>
<td style="text-align: center;">ATT (offer)</td>
<td style="text-align: center;">0.135–0.137</td>
</tr>
<tr class="odd">
<td>Endogenous treatment (IV)</td>
<td style="text-align: center;">ATE (receipt)</td>
<td style="text-align: center;">0.147</td>
</tr>
<tr class="even">
<td><strong>True effect</strong></td>
<td style="text-align: center;">—</td>
<td style="text-align: center;"><strong>0.12</strong></td>
</tr>
</tbody>
</table>
<p><span class="takeaway fragment">Twelve specifications, three estimands, one truth at <span class="math inline">\(0.12\)</span> — and <em>every</em> 95% CI covers it.</span></p>
<aside class="notes">
<p>This is the spoiler table. Don’t defend each row yet — just plant that the methods cluster tightly and the true value sits inside every interval. We earn each estimator in Act II and return to this picture at the close.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="where-were-going" class="slide level2 center">
<h2>Where we’re going</h2>
<ul>
<li class="fragment">Did randomization actually balance the groups?</li>
<li class="fragment">Three cross-sectional strategies — model the outcome, the treatment, or both</li>
<li class="fragment">Panel power: difference-in-differences and its doubly-robust cousin</li>
<li class="fragment">Offer vs.&nbsp;receipt — what imperfect compliance changes</li>
</ul>
<aside class="notes">
<p>The roadmap mirrors the post’s learning objectives. Each stage adds robustness: balance → cross-section → panel → compliance. Keep it to four beats so the audience can hold the whole arc.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="the-investigation" class="title-slide slide level1 divider center" data-background-color="#6a9bcc">
<h1>The Investigation</h1>
<p><span class="act">Act II</span></p>
</section>
<section id="the-lab-2000-households-two-waves-one-known-answer" class="slide level2 center">
<h2>The lab: 2,000 households, two waves, one known answer</h2>
<ul>
<li class="fragment"><strong>Outcome</strong> — log monthly consumption (<span class="math inline">\(y\)</span>); true effect <span class="math inline">\(= 0.12\)</span></li>
<li class="fragment"><strong>Design</strong> — balanced panel, baseline 2021 + endline 2024, 4,000 rows</li>
<li class="fragment"><strong>Assignment</strong> — <code>treat</code> randomized within poverty strata (intent-to-treat)</li>
<li class="fragment"><strong>Receipt</strong> — <code>D</code>, endogenous: only 85% of offered households took up</li>
</ul>
<p><span class="takeaway fragment">State the wedge early: random <code>treat</code> is exogenous; actual <code>D</code> is a choice. Most of the deck estimates the <em>offer</em> effect; Act III’s coda returns to <em>receipt</em>.</span></p>
<aside class="notes">
<p>The simulated panel is strongly balanced — every household appears in both waves, no attrition. Distinguish offer (treat, exogenous by randomization) from receipt (D, endogenous by self-selection). 51.8% were offered; 46.15% received. That 5.65pp gap is the compliance problem we postpone to Act III.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="randomization-worked-every-covariate-sits-under-the-10-balance-threshold" class="slide level2 center">
<h2>Randomization worked: every covariate sits under the 10% balance threshold</h2>

<img data-src="../stata_rct_balance_plot.png" class="r-stretch quarto-figure-center"><p class="caption">Standardized mean differences for all baseline covariates. Dashed lines mark the <span class="math inline">\(\pm 10\%\)</span> rule of thumb; <code>female</code> is the only borderline case at <span class="math inline">\(\approx 9.3\%\)</span>.</p><aside class="notes">
<p>The first thing to verify in any RCT. SMD is the scale-free imbalance measure: mean gap over pooled SD. Everything clears 10%; female is the lone borderline at 9.3% — a chance imbalance, not a design flaw. We will control for it, not to remove bias, but to recover the precision randomization left on the table.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-only-chance-imbalance-is-female-headship-and-it-is-borderline-not-broken" class="slide level2 center">
<h2>The only chance imbalance is female-headship — and it is borderline, not broken</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Covariate</th>
<th style="text-align: right;">Control</th>
<th style="text-align: right;">Treatment</th>
<th style="text-align: right;">SMD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Consumption <span class="math inline">\(y\)</span></td>
<td style="text-align: right;">10.025</td>
<td style="text-align: right;">10.006</td>
<td style="text-align: right;">&lt;0.05</td>
</tr>
<tr class="even">
<td>Age</td>
<td style="text-align: right;">35.34</td>
<td style="text-align: right;">34.93</td>
<td style="text-align: right;">&lt;0.05</td>
</tr>
<tr class="odd">
<td>Education</td>
<td style="text-align: right;">11.97</td>
<td style="text-align: right;">12.08</td>
<td style="text-align: right;">0.052</td>
</tr>
<tr class="even">
<td>Female-headed</td>
<td style="text-align: right;">0.484</td>
<td style="text-align: right;">0.531</td>
<td style="text-align: right;"><span class="key">0.093</span></td>
</tr>
<tr class="odd">
<td>Poverty</td>
<td style="text-align: right;">0.307</td>
<td style="text-align: right;">0.318</td>
<td style="text-align: right;">&lt;0.05</td>
</tr>
</tbody>
</table>
<p><span class="takeaway fragment"><span class="math inline">\(p = 0.038\)</span> flags <code>female</code>, but the SMD of <span class="math inline">\(9.3\%\)</span> is the right lens — large <span class="math inline">\(n\)</span> makes tiny gaps “significant.”</span></p>
<aside class="notes">
<p>P-values mislead at large n — they flag a 4.6pp gender gap as “significant” while the SMD says it is small and below threshold. The lesson: judge balance with standardized differences, not p-values. We carry female (and the others) into estimation as precision controls.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-formal-balance-check-aipw-on-baseline-data-should-and-does-find-nothing" class="slide level2 center">
<h2>A formal balance check: AIPW on baseline data should — and does — find nothing</h2>
<p><span class="math display">\[\hat\tau_{\text{baseline}} = -0.024 \quad (p = 0.196)\]</span></p>
<p>Run the doubly-robust estimator on <strong>baseline only</strong>, before the program exists. A null “effect” is exactly what a clean randomization predicts.</p>
<p><span class="takeaway fragment">Overidentification test: <span class="math inline">\(\chi^2(5) = 3.22\)</span>, <span class="math inline">\(p = 0.667\)</span> — no residual imbalance after weighting.</span></p>
<aside class="notes">
<p>This is a clever pre-flight: if randomization is real, a treatment effect estimated before treatment must be zero. AIPW returns -0.024, n.s., and the overid test fails to reject balance. It doubles as a soft introduction to doubly-robust estimation before we lean on it for real.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="after-weighting-the-two-groups-consumption-distributions-become-indistinguishable" class="slide level2 center">
<h2>After weighting, the two groups’ consumption distributions become indistinguishable</h2>

<img data-src="../stata_rct_density_y.png" class="r-stretch quarto-figure-center"><p class="caption">Log-consumption densities for treatment vs.&nbsp;control, before and after AIPW weighting. The weighted curves overlap almost perfectly.</p><aside class="notes">
<p>Visual companion to the balance test. Any small pre-existing gap in the outcome distribution is erased by the weighting scheme — the weighted treatment and control densities lie on top of each other.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="propensities-cluster-near-0.5-exactly-the-comfortable-regime-for-weighting" class="slide level2 center">
<h2>Propensities cluster near 0.5 — exactly the comfortable regime for weighting</h2>

<img data-src="../stata_rct_overlap_baseline.png" class="r-stretch quarto-figure-center"><p class="caption">Estimated propensity-score densities for both groups span roughly 0.43–0.55 with heavy overlap and no mass near 0 or 1.</p><aside class="notes">
<p>Common support is satisfied: no extreme propensities means no exploding inverse weights. This is the well-behaved world a designed RCT gives you — propensity ≈ 0.50 for everyone — which is <em>why</em> RA, IPW, and DR are about to agree.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-are-we-even-estimating-ate-and-att-are-different-questions" class="slide level2 center">
<h2>What are we even estimating? ATE and ATT are different questions</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="ate">ATE</h3>
<p><span class="math display">\[E[Y(1) - Y(0)]\]</span></p>
<ul>
<li>The <em>policymaker’s</em> question</li>
<li>“What if we scale to everyone?”</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="att">ATT</h3>
<p><span class="math display">\[E[Y(1) - Y(0) \mid T = 1]\]</span></p>
<ul>
<li>The <em>evaluator’s</em> question</li>
<li>“Did it help the participants?”</li>
</ul>
</div></div>
<p><span class="takeaway fragment">Under randomization with homogeneous effects, ATE <span class="math inline">\(=\)</span> ATT. DiD will only ever give us the ATT.</span></p>
<aside class="notes">
<p>Name the estimand for every method — this is the discipline the post insists on. Cross-sectional teffects can target either ATE or ATT. DiD is structurally ATT-only because its counterfactual is built for the treated group. Foreshadow that distinction now.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="in-an-rct-controls-dont-remove-bias-they-buy-precision" class="slide level2 center">
<h2>In an RCT, controls don’t remove bias — they buy precision</h2>
<p><span class="takeaway fragment">Randomized treatment is independent of potential outcomes, so the raw difference in means is <em>already</em> unbiased.</span></p>
<div class="fragment">
<p>No confounding here, so covariates don’t fix bias — they soak up residual variation and tighten the estimate.</p>
<aside class="notes">
<p>In observational studies the same controls would be doing the heavy lifting of identification. This is the single most important conceptual point for an RCT audience, and the most commonly muddled. Distinguish the randomized framing (adjustment = precision) from the observational framing (adjustment = bias removal). The estimators are identical; their <em>job</em> is not.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="three-strategies-three-things-to-model-outcome-treatment-or-both" class="slide level2 center">
<h2>Three strategies, three things to model: outcome, treatment, or both</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="ra-model-the-outcome">RA — model the outcome</h3>
<ul>
<li>Fits <span class="math inline">\(\hat\mu_1(X)\)</span>, <span class="math inline">\(\hat\mu_0(X)\)</span></li>
<li>ATE <span class="math inline">\(= \frac1N\sum[\hat\mu_1 - \hat\mu_0]\)</span></li>
<li>Fails if outcome model wrong</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="ipw-model-the-treatment">IPW — model the treatment</h3>
<ul>
<li>Fits propensity <span class="math inline">\(\hat p(X)\)</span></li>
<li>Reweights by <span class="math inline">\(1/\hat p\)</span>, <span class="math inline">\(1/(1-\hat p)\)</span></li>
<li>Fails on extreme weights</li>
</ul>
</div></div>
<p><span class="takeaway fragment">Doubly robust (AIPW / IPWRA) fits <strong>both</strong> — and is consistent if <em>either</em> one is correct.</span></p>
<aside class="notes">
<p>RA predicts the missing counterfactual from an outcome model; IPW reweights observed outcomes by inverse propensity; DR stitches them together. Each fails in a different way — outcome misspecification vs.&nbsp;extreme weights — which is exactly why combining them is insurance.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="doubly-robust-estimation-one-model-can-be-wrong-and-the-answer-still-holds" class="slide level2 center">
<h2>Doubly robust estimation: one model can be wrong and the answer still holds</h2>
<p><span class="math display">\[\hat\tau_{DR}^{ATE} = \frac1N \sum_{i=1}^{N}\Big[\hat\mu_1(X_i) - \hat\mu_0(X_i) + \frac{T_i\,(Y_i - \hat\mu_1)}{\hat p(X_i)} - \frac{(1-T_i)(Y_i - \hat\mu_0)}{1 - \hat p(X_i)}\Big]\]</span></p>
<p>First two terms: the RA prediction. Last two: IPW residuals that cancel RA’s bias.</p>
<p><span class="takeaway fragment">Belt and suspenders: if the belt fails, the suspenders hold. Only <em>both</em> wrong is fatal.</span></p>
<aside class="notes">
<p>Walk the two pieces. If the outcome model is right, residuals average to zero and DR collapses to RA. If the propensity model is right, the weighted residuals fix the RA bias. Getting at least one model approximately right is far easier than getting both perfect — that is the whole appeal.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-cross-sectional-toolkit-is-six-lines-of-teffects" class="slide level2 center">
<h2>The cross-sectional toolkit is six lines of teffects</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-code-line-numbers="1|3|5|7"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb1-1"><a href=""></a><span class="kw">keep</span> <span class="kw">if</span> <span class="kw">post</span>==1</span>
<span id="cb1-2"><a href=""></a>* RA — models the outcome only</span>
<span id="cb1-3"><a href=""></a>teffects ra    (<span class="fu">y</span> c.age c.edu i.female i.poverty) (treat), ate</span>
<span id="cb1-4"><a href=""></a>* IPW — models the treatment only</span>
<span id="cb1-5"><a href=""></a>teffects ipw   (<span class="fu">y</span>) (treat c.age c.edu i.female i.poverty), ate</span>
<span id="cb1-6"><a href=""></a>* Doubly <span class="kw">robust</span> — models both</span>
<span id="cb1-7"><a href=""></a>teffects ipwra (<span class="fu">y</span> c.age c.edu i.female i.poverty) (treat c.age c.edu i.female i.poverty), <span class="kw">vce</span>(<span class="kw">robust</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>The grammar is the lesson: where the covariates sit tells you what’s being modeled. RA puts them in the outcome parenthesis; IPW in the treatment parenthesis; IPWRA in both. AIPW is the alternative DR form and gives the same answer. Full do-file ships with the post.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-headline-cross-sectional-result-every-method-converges-on-0.113" class="slide level2 center" data-background-color="#141413">
<h2>The headline cross-sectional result: every method converges on 0.113</h2>
<p><span class="bignum">0.113</span></p>
<p><span class="bignum-label">ATE of the offer · RA, IPW, and doubly-robust IPWRA agree to three decimals (SE 0.019)</span></p>
<aside class="notes">
<p>This is the Act-II payoff. The simple diff-in-means is 0.116; covariate-adjusted RA/IPW/DR all land at 0.113. They converge because randomization makes both the outcome model and the propensity model approximately correct — so there is nothing for them to disagree about. ATE and ATT are also nearly identical (0.113 each), confirming homogeneous effects.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ra-ipw-and-dr-agree-because-randomization-made-every-model-approximately-right" class="slide level2 center">
<h2>RA, IPW, and DR agree because randomization made every model approximately right</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Method</th>
<th>Models</th>
<th style="text-align: center;">Estimand</th>
<th style="text-align: center;">Estimate</th>
<th style="text-align: center;">95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Simple diff-in-means</td>
<td>none</td>
<td style="text-align: center;">ATE</td>
<td style="text-align: center;">0.116</td>
<td style="text-align: center;">[0.078, 0.154]</td>
</tr>
<tr class="even">
<td>Regression adjustment</td>
<td>outcome</td>
<td style="text-align: center;">ATE</td>
<td style="text-align: center;">0.113</td>
<td style="text-align: center;">[0.075, 0.150]</td>
</tr>
<tr class="odd">
<td>Inverse prob. weighting</td>
<td>treatment</td>
<td style="text-align: center;">ATE</td>
<td style="text-align: center;">0.113</td>
<td style="text-align: center;">[0.075, 0.150]</td>
</tr>
<tr class="even">
<td>IPWRA (doubly robust)</td>
<td>both</td>
<td style="text-align: center;">ATE</td>
<td style="text-align: center;"><span class="key">0.113</span></td>
<td style="text-align: center;">[0.075, 0.150]</td>
</tr>
<tr class="odd">
<td><strong>True effect</strong></td>
<td>—</td>
<td style="text-align: center;">—</td>
<td style="text-align: center;"><strong>0.12</strong></td>
<td style="text-align: center;">—</td>
</tr>
</tbody>
</table>
<p><span class="takeaway fragment">Adjusted estimates (<span class="math inline">\(0.113\)</span>) sit just below the raw <span class="math inline">\(0.116\)</span> — that gap <em>is</em> the precision gain from controlling for the gender imbalance.</span></p>
<aside class="notes">
<p>The convergence is the reassuring signal: when methods that model different things agree, you trust the design. The 0.003 drop from 0.116 to 0.113 is the covariate adjustment doing its precision job. In a messier observational dataset these rows would scatter, and DR would be the one to trust.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="panel-data-lets-each-household-be-its-own-control-differencing-out-the-invisible" class="slide level2 center">
<h2>Panel data lets each household be its own control — differencing out the invisible</h2>
<p><span class="objection">Cross-sectional adjustment can only control for what you <em>observe</em>.</span></p>
<div class="fragment">
<p><span class="rebuttal">Difference-in-differences compares each household to <em>itself</em> over time, cancelling every time-invariant unobservable — motivation, geography, family culture.</span></p>
<aside class="notes">
<p>The motivation for going panel. Observable covariates leave unobservable confounders untouched. By comparing within-household change baseline→endline, DiD differences out anything fixed about the household. In this RCT randomization already handled confounding, so the gain is conceptual robustness, not a new number.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="did-is-a-difference-of-differences-the-control-trend-is-the-counterfactual" class="slide level2 center">
<h2>DiD is a difference of differences — the control trend is the counterfactual</h2>
<p><span class="math display">\[\hat\tau_{DiD} = \underbrace{(\bar Y_{T,post} - \bar Y_{T,pre})}_{\text{effect}\,+\,\text{trend}} - \underbrace{(\bar Y_{C,post} - \bar Y_{C,pre})}_{\text{trend only}}\]</span></p>
<p>Treated change = effect + trend. Control change = trend alone. Subtract — the trend cancels.</p>
<p><span class="takeaway fragment">Identification rides on <strong>parallel trends</strong> — plausible here because randomization equalized the groups at baseline.</span></p>
<aside class="notes">
<p>The control group’s drift (e.g.&nbsp;nationwide income growth) is what the treated group would have experienced anyway. Subtracting it isolates the program. The identifying assumption is parallel trends, not equal levels — groups can start anywhere as long as they would have moved together absent treatment. Randomization makes that very credible.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="panel-did-recovers-0.135-and-it-is-structurally-an-att-not-an-ate" class="slide level2 center">
<h2>Panel DiD recovers 0.135 — and it is structurally an ATT, not an ATE</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2" data-code-line-numbers="1|3"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb2-1"><a href=""></a><span class="kw">gen</span> treat_post = treat * <span class="kw">post</span></span>
<span id="cb2-2"><a href=""></a>xtdidregress (<span class="fu">y</span>) (treat_post), <span class="fu">group</span>(id) time(<span class="fu">year</span>) <span class="kw">vce</span>(<span class="kw">cluster</span> id)</span>
<span id="cb2-3"><a href=""></a>*  ATET = 0.135  (<span class="kw">SE</span> 0.027)  95% CI [0.081, 0.188]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><span class="key">0.135</span> sits just above the cross-sectional <span class="math inline">\(0.113\)</span> — the wider SE (<span class="math inline">\(0.027\)</span> vs <span class="math inline">\(0.019\)</span>) is the price of differencing.</p>
<aside class="notes">
<p>DiD estimates the ATT because its counterfactual — control trend applied to the treated baseline — is constructed only for the treated group. The wider SE is not a defect: it reflects honest within-household differencing. The headline value still covers 0.12. Standard errors clustered at the household level.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="doubly-robust-did-santannazhao-bring-the-either-model-guarantee-to-panels" class="slide level2 center">
<h2>Doubly robust DiD: Sant’Anna–Zhao bring the “either model” guarantee to panels</h2>
<p><span class="math display">\[\hat\tau_{DR}^{DiD} = \frac{1}{N_1}\sum_{i=1}^{N}\big[w_1(D_i) - w_0(D_i, X_i)\big]\big[\Delta Y_i - \hat\mu_{0,\Delta}(X_i)\big]\]</span></p>
<p>Subtract the control-group’s <em>predicted change</em> from each household’s actual change <span class="math inline">\(\Delta Y_i\)</span>, then IPW-reweight so controls resemble the treated. Consistent if <strong>either</strong> model is right.</p>
<p><span class="takeaway fragment">Needs only <strong>conditional</strong> parallel trends — covariate-specific time trends are allowed.</span></p>
<aside class="notes">
<p>This is the panel analogue of cross-sectional AIPW, applied to changes rather than levels. It relaxes parallel trends to a conditional version: trends can differ across covariate groups (poor vs non-poor) and the ATT is still identified. When both models are right it hits the semiparametric efficiency bound. It also dodges the heterogeneity traps of naive two-way fixed effects.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="the-resolution" class="title-slide slide level1 divider center" data-background-color="#00d4c8">
<h1>The Resolution</h1>
<p><span class="act">Act III</span></p>
</section>
<section id="two-independent-dr-did-implementations-agree-exactly-on-0.137" class="slide level2 center" data-background-color="#141413">
<h2>Two independent DR-DiD implementations agree exactly on 0.137</h2>
<p><span class="bignum">0.137</span></p>
<p><span class="bignum-label">ATT of the offer · <code>drdid</code> and <code>xthdidregress aipw</code> match to four decimals (SE 0.027)</span></p>
<aside class="notes">
<p>The community drdid package and Stata 17’s built-in xthdidregress aipw return identical 0.137 — a clean cross-implementation check. xthdidregress labels it “cohort 2024” because it is built for staggered adoption; our two-period design has a single cohort. The DR-DiD is the most robust panel estimator in the toolkit.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="cross-section-vs.-panel-different-estimands-different-data-same-truth-inside-the-bars" class="slide level2 center">
<h2>Cross-section vs.&nbsp;panel: different estimands, different data, same truth inside the bars</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Method</th>
<th style="text-align: center;">Estimand</th>
<th style="text-align: center;">Data</th>
<th style="text-align: center;">Estimate</th>
<th style="text-align: center;">95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>RA / IPW / DR</td>
<td style="text-align: center;">ATE</td>
<td style="text-align: center;">endline</td>
<td style="text-align: center;">0.113</td>
<td style="text-align: center;">[0.075, 0.150]</td>
</tr>
<tr class="even">
<td>Basic DiD</td>
<td style="text-align: center;">ATT</td>
<td style="text-align: center;">both waves</td>
<td style="text-align: center;">0.135</td>
<td style="text-align: center;">[0.081, 0.188]</td>
</tr>
<tr class="odd">
<td>DR-DiD (<code>drdid</code>)</td>
<td style="text-align: center;">ATT</td>
<td style="text-align: center;">both waves</td>
<td style="text-align: center;"><span class="key">0.137</span></td>
<td style="text-align: center;">[0.084, 0.191]</td>
</tr>
<tr class="even">
<td>DR-DiD (<code>xthdidregress</code>)</td>
<td style="text-align: center;">ATT</td>
<td style="text-align: center;">both waves</td>
<td style="text-align: center;">0.137</td>
<td style="text-align: center;">[0.084, 0.191]</td>
</tr>
<tr class="odd">
<td><strong>True effect</strong></td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">—</td>
<td style="text-align: center;"><strong>0.12</strong></td>
<td style="text-align: center;">—</td>
</tr>
</tbody>
</table>
<p><span class="takeaway fragment">DiD’s value is <strong>not</strong> a tighter SE — it is robustness to time-invariant unobservables.</span></p>
<aside class="notes">
<p>The DiD estimates (0.135–0.137) sit slightly above the cross-sectional 0.113, but every interval brackets 0.12. The reason to reach for DiD is not precision — its SEs are wider — but insurance against fixed confounders that randomization would not be providing in an observational world.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="offer-vs.-receipt-only-85-complied-so-the-per-recipient-effect-is-larger" class="slide level2 center">
<h2>Offer vs.&nbsp;receipt: only 85% complied, so the per-recipient effect is larger</h2>
<p>Most of the deck estimated the <em>offer</em> (<code>treat</code>, intent-to-treat). The effect of <em>receipt</em> (<code>D</code>) needs the random offer as an <strong>instrument</strong>, because take-up is a choice.</p>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Specification</th>
<th style="text-align: center;">Estimand</th>
<th style="text-align: center;">Estimate</th>
<th style="text-align: center;">95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>etregress</code> (IV)</td>
<td style="text-align: center;">ATE (receipt)</td>
<td style="text-align: center;">0.147</td>
<td style="text-align: center;">[0.099, 0.195]</td>
</tr>
<tr class="even">
<td><code>teffects ipwra</code> + <span class="math inline">\(y_0\)</span></td>
<td style="text-align: center;">ATE (receipt)</td>
<td style="text-align: center;"><span class="key">0.117</span></td>
<td style="text-align: center;">[0.054, 0.180]</td>
</tr>
</tbody>
</table>
<p><span class="takeaway fragment">The doubly-robust receipt estimate (<span class="math inline">\(0.117\)</span>) lands closest to the truth; both cover <span class="math inline">\(0.12\)</span>.</span></p>
<aside class="notes">
<p>treat is the valid instrument for D: randomized, strongly predictive of receipt, affecting consumption only through the transfer. etregress gives 0.147 — larger than the offer effect because non-compliers dilute the ITT. The DR receipt estimate, controlling for baseline y0, is 0.117, nearest to 0.12. The Wald test rho=0 (p=0.901) finds no endogeneity, as expected in a clean RCT.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="receipt-model-overlap-holds-too-the-iv-story-rests-on-solid-balance" class="slide level2 center">
<h2>Receipt-model overlap holds too — the IV story rests on solid balance</h2>

<img data-src="../stata_rct_overlap_receipt.png" class="r-stretch quarto-figure-center"><p class="caption">Propensity-score densities for receivers vs.&nbsp;non-receivers of the transfer show ample common support after IPWRA weighting.</p><aside class="notes">
<p>A robustness companion to the receipt estimate. After IPWRA weighting the effective samples rebalance to roughly 999 vs 1,001, weighted covariate means align (age 35.0 vs 35.2, poverty 31.1% vs 31.4%), and propensity overlap is sufficient. The receipt analysis is not resting on a fragile extrapolation.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="does-any-of-this-make-the-result-causal-no-design-does-methods-only-discipline" class="slide level2 center">
<h2>Does any of this <em>make</em> the result causal? No — design does, methods only discipline</h2>
<p><span class="objection">Objection.</span> Twelve estimators all near 0.12 — surely that proves the cash transfer caused the gain?</p>
<div class="fragment">
<p><span class="rebuttal">Response.</span> The <em>randomization</em> identifies the effect; the estimators merely recover it efficiently and robustly. On real observational data the same methods rest on conditional independence and parallel trends — assumptions a clean RCT hands you for free but the world rarely does.</p>
<aside class="notes">
<p>Steelman then answer. The convergence is reassuring because the design is sound, not because averaging methods manufactures identification. The pedagogical point of the simulation is to show <em>what good methods do when the design is good</em> — so you recognize the difference when the design is not.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section></section>
<section id="when-the-design-is-clean-every-honest-estimator-finds-the-same-truth-and-that-agreement-is-the-point." class="title-slide slide level1 divider center" data-background-color="#141413">
<h1>When the design is clean, every honest estimator finds the same truth — and that agreement is the point.</h1>
<aside class="notes">
<p>The single takeaway resolving the Act-I hook. We planted 0.12 and recovered 0.11–0.14 across twelve specifications, every CI covering the truth. In an RCT, convergence across RA, IPW, DR, DiD, and DR-DiD is a feature — and doubly-robust panel methods are the insurance you carry into the messier, non-randomized settings where that convergence is no longer free.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="slides_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="slides_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="slides_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="slides_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="slides_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="slides_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="slides_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>