* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- convergence_data_prepared.dta ----
use "convergence_data_prepared.dta", clear
label data "Analysis panel: GDP per capita + population, 84 countries"
note _dta: Balanced panel of 84 countries, 1960-2019 (5,040 rows). Built from pwt100.dta in Section 3: keep country/ccode/year/pop/rgdpe, compute gdppc=rgdpe/pop, drop oil producers and countries under 1 million, restrict to countries with data since 1960.
note ccode: 3-letter ISO country code (PWT countrycode, renamed).. Construction: rename countrycode ccode in Section 3.. Units: ISO-3 code. Source: Penn World Table 10.0
note country: Country name.. Construction: Carried verbatim from PWT 10.0.. Units: string. Source: Penn World Table 10.0
note year: Annual time index.. Construction: Restricted to 1960 onwards for the balanced panel.. Units: year. Source: Penn World Table 10.0
note gdppc: Expenditure-side real GDP at chained PPPs per person - the headline income measure.. Construction: gen gdppc = rgdpe / pop (rgdpe is in millions; pop in millions).. Units: 2017 US$ (PPP). Source: Computed from PWT 10.0
note pop: Total population.. Construction: PWT pop; the under-1-million filter drops small countries before the panel is fixed.. Units: millions of persons. Source: Penn World Table 10.0
save "convergence_data_prepared.dta", replace

* ---- pwt100.dta ----
use "pwt100.dta", clear
label data "Penn World Table 10.0 source (52 macro series, 183 economies)"
note _dta: Penn World Table 10.0 (Feenstra, Inklaar & Timmer 2015). Annual macro panel; the post uses countrycode, country, year, pop, and rgdpe (to form gdppc=rgdpe/pop). The remaining columns carry the official PWT variable labels.
note countrycode: 3-letter ISO country code.. Construction: Source PWT identifier; renamed to ccode in the prepared file.. Units: ISO-3 code. Source: Penn World Table 10.0
note country: Country name.. Construction: Carried verbatim from PWT 10.0.. Units: string. Source: Penn World Table 10.0
note currency_unit: Name of the national currency.. Units: string. Source: Penn World Table 10.0
note year: Annual time index.. Construction: Restricted to 1960 onwards for the balanced panel.. Units: year. Source: Penn World Table 10.0
note rgdpe: Expenditure-side real GDP at chained PPPs - used to form gdppc=rgdpe/pop.. Construction: PWT series; the post's per-capita income numerator.. Units: millions of 2017 US$ (PPP). Source: Penn World Table 10.0
note rgdpo: Source: Penn World Table 10.0
note pop: Total population.. Construction: PWT pop; the under-1-million filter drops small countries before the panel is fixed.. Units: millions of persons. Source: Penn World Table 10.0
note emp: Source: Penn World Table 10.0
note avh: Source: Penn World Table 10.0
note hc: Human capital index based on years of schooling and returns to education (see PWT note hc).. Units: index. Source: Penn World Table 10.0
note ccon: Source: Penn World Table 10.0
note cda: Source: Penn World Table 10.0
note cgdpe: Source: Penn World Table 10.0
note cgdpo: Source: Penn World Table 10.0
note cn: Source: Penn World Table 10.0
note ck: Source: Penn World Table 10.0
note ctfp: Source: Penn World Table 10.0
note cwtfp: Source: Penn World Table 10.0
note rgdpna: Source: Penn World Table 10.0
note rconna: Source: Penn World Table 10.0
note rdana: Source: Penn World Table 10.0
note rnna: Source: Penn World Table 10.0
note rkna: Source: Penn World Table 10.0
note rtfpna: Source: Penn World Table 10.0
note rwtfpna: Source: Penn World Table 10.0
note labsh: Source: Penn World Table 10.0
note irr: Source: Penn World Table 10.0
note delta: Source: Penn World Table 10.0
note xr: Source: Penn World Table 10.0
note pl_con: Source: Penn World Table 10.0
note pl_da: Source: Penn World Table 10.0
note pl_gdpo: Source: Penn World Table 10.0
note i_cig: Source: Penn World Table 10.0
note i_xm: Source: Penn World Table 10.0
note i_xr: Source: Penn World Table 10.0
note i_outlier: Source: Penn World Table 10.0
note i_irr: Source: Penn World Table 10.0
note cor_exp: Source: Penn World Table 10.0
note statcap: Source: Penn World Table 10.0
note csh_c: Source: Penn World Table 10.0
note csh_i: Source: Penn World Table 10.0
note csh_g: Source: Penn World Table 10.0
note csh_x: Source: Penn World Table 10.0
note csh_m: Source: Penn World Table 10.0
note csh_r: Source: Penn World Table 10.0
note pl_c: Source: Penn World Table 10.0
note pl_i: Source: Penn World Table 10.0
note pl_g: Source: Penn World Table 10.0
note pl_x: Source: Penn World Table 10.0
note pl_m: Source: Penn World Table 10.0
note pl_n: Source: Penn World Table 10.0
note pl_k: Source: Penn World Table 10.0
save "pwt100.dta", replace
