* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- kansas.dta ----
use "kansas.dta", clear
label data "Balanced state-quarter panel: log GSP per capita + covariates"
note _dta: The augsynth package's bundled kansas object, copied to CSV. Kansas (FIPS 20) is the single treated unit from 2012 Q2; 49 donor states. 5,250 rows = 50 states x 105 quarters. Revenue series are annual (NA in 3 of 4 quarters).
note fips: Federal Information Processing Standard numeric state identifier (Kansas = 20).. Construction: From the augsynth kansas object; the panel unit id.. Units: code. Source: augsynth kansas
note year: Year of the observation (1990-2016).. Construction: From the kansas object.. Units: year. Source: augsynth kansas
note qtr: Quarter of the year (1 = Q1 ... 4 = Q4).. Construction: From the kansas object.. Units: 1-4. Source: augsynth kansas
note state: Full U.S. state name.. Construction: From the kansas object.. Units: string. Source: augsynth kansas
note gdp: Quarterly gross state product (gross domestic product by state).. Construction: From the kansas object (BEA GSP).. Units: US$ (millions). Source: BEA (via augsynth)
note revenuepop: Total state revenue per resident; observed annually only.. Construction: From the kansas object; NA in non-reporting quarters.. Units: US$ per capita. Source: augsynth kansas
note rev_state_total: Total state-government revenue for the state-year; observed annually only.. Construction: From the kansas object; NA in non-reporting quarters.. Units: US$. Source: augsynth kansas
note rev_local_total: Total local-government revenue for the state-year; observed annually only.. Construction: From the kansas object; NA in non-reporting quarters.. Units: US$. Source: augsynth kansas
note popestimate: Estimated state resident population for the quarter.. Construction: From the kansas object; used as the per-capita denominator.. Units: persons. Source: augsynth kansas
note qtrly_estabs_count: Number of business establishments in the state-quarter (QCEW).. Construction: From the kansas object.. Units: establishments. Source: BLS QCEW (via augsynth)
note month1_emplvl: Employment count in the first month of the quarter (QCEW).. Construction: From the kansas object.. Units: persons. Source: BLS QCEW (via augsynth)
note month2_emplvl: Employment count in the second month of the quarter (QCEW).. Construction: From the kansas object.. Units: persons. Source: BLS QCEW (via augsynth)
note month3_emplvl: Employment count in the third month of the quarter (QCEW).. Construction: From the kansas object.. Units: persons. Source: BLS QCEW (via augsynth)
note total_qtrly_wages: Total wages paid in the state-quarter (QCEW).. Construction: From the kansas object.. Units: US$. Source: BLS QCEW (via augsynth)
note taxable_qtrly_wages: Portion of quarterly wages subject to unemployment-insurance tax (QCEW).. Construction: From the kansas object.. Units: US$. Source: BLS QCEW (via augsynth)
note avg_wkly_wage: Average weekly wage in the state-quarter (QCEW).. Construction: From the kansas object.. Units: US$ per week. Source: BLS QCEW (via augsynth)
note year_qtr: Time index as year plus quarter fraction (e.g. 2012.25 = 2012 Q2).. Construction: year + (qtr-1)/4; the panel's time variable in augsynth().. Units: decimal year. Source: Derived
note treated: 1 for Kansas (FIPS 20) from 2012 Q2 onward, 0 for all other state-quarters.. Construction: Indicator switched on at year_qtr >= 2012.25 for Kansas only.. Units: 0/1. Source: augsynth kansas
note gdpcapita: Gross state product per resident.. Construction: gdp / popestimate (scaled).. Units: US$ per capita. Source: Derived
note lngdp: Natural log of quarterly gross state product.. Construction: log(gdp).. Units: log US$. Source: Derived
note lngdpcapita: Natural log of gross state product per capita - the study outcome.. Construction: log(gdpcapita).. Units: log US$ per capita. Source: Derived
note revstatecapita: Total state revenue per resident; annual covariate (log-transformed in the model).. Construction: rev_state_total / popestimate; NA in non-reporting quarters.. Units: US$ per capita. Source: Derived
note revlocalcapita: Total local revenue per resident; annual covariate (log-transformed in the model).. Construction: rev_local_total / popestimate; NA in non-reporting quarters.. Units: US$ per capita. Source: Derived
note emplvl1capita: First-month employment level as a share of population.. Construction: month1_emplvl / popestimate.. Units: ratio. Source: Derived
note emplvl2capita: Second-month employment level as a share of population.. Construction: month2_emplvl / popestimate.. Units: ratio. Source: Derived
note emplvl3capita: Third-month employment level as a share of population.. Construction: month3_emplvl / popestimate.. Units: ratio. Source: Derived
note emplvlcapita: Quarterly employment level as a share of population; an ASCM covariate.. Construction: Quarterly employment / popestimate.. Units: ratio. Source: Derived
note totalwagescapita: Total quarterly wages per resident.. Construction: total_qtrly_wages / popestimate.. Units: US$ per capita. Source: Derived
note taxwagescapita: Taxable quarterly wages per resident.. Construction: taxable_qtrly_wages / popestimate.. Units: US$ per capita. Source: Derived
note avgwklywagecapita: Average weekly wage used as an ASCM covariate (log-transformed in the model).. Construction: From avg_wkly_wage; an auxiliary covariate.. Units: US$ per week. Source: Derived
note estabscapita: Business establishments as a share of population; an ASCM covariate.. Construction: qtrly_estabs_count / popestimate.. Units: ratio. Source: Derived
note abb: Two-letter U.S. state postal abbreviation (e.g. KS for Kansas).. Construction: From the kansas object.. Units: string. Source: augsynth kansas
save "kansas.dta", replace
