* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- aceh_tsunami_district_panel.dta ----
use "aceh_tsunami_district_panel.dta", clear
label data "Annual district panel: GDP growth + covariates + treatment"
note _dta: Annual district panel; 125 synthetic Sumatran districts, 1999-2012 (1,750 rows). District GDP growth, covariates, treatment indicators, and centroids for Conley spatial standard errors. Growth is missing in 1999 and for Subulussalam 2003-2006.
note district_id: Unique identifier for the district (Kabupaten/Kota); the panel key.. Construction: Assigned as <PROVINCE-ABBREV>_D<nn>; Aceh districts carry real names in district_name.. Units: string. Source: Assigned (this study)
note district_name: Name of the district. Real names for Aceh's 23 districts; systematic placeholders elsewhere.. Construction: Real Aceh district names hand-coded from the paper's maps; other provinces use 'Province District k'.. Units: string. Source: Assigned (this study)
note province: Indonesian province the unit belongs to (district panel: 10 Sumatra provinces; sub-district panel: always Aceh).. Construction: Hand-coded; 10 Sumatra provinces in the district panel, constant 'Aceh' in the sub-district panel.. Units: string. Source: Assigned (this study)
note region_group: Coarse grouping used to build estimation samples.. Construction: Derived from province: Aceh, North Sumatra, or Rest of Sumatra.. Units: {Aceh, North Sumatra, Rest of Sumatra}. Source: Derived
note district_type: Kota (urban city district) vs Kabupaten (rural regency).. Construction: Hand-coded to reproduce the paper's city/rural sample sizes (Aceh: 5 Kota, 18 Kabupaten).. Units: {Kota, Kabupaten}. Source: Assigned (this study)
note coastal: 1 if the district lies on the coast, 0 if inland.. Construction: Hand-coded; all 10 treated districts are coastal. Used to drop inland controls.. Units: 0/1. Source: Assigned (this study)
note flooded: Treatment indicator: 1 if the unit was flooded by the 2004 tsunami (the DiD 'D' variable).. Construction: Hand-coded from the inundation maps; district panel: 10 Aceh + 2 North Sumatra island districts; sub-district panel: 68 of 276 kecamatans.. Units: 0/1. Source: Assigned (this study)
note neighbour_of_flooded: 1 if a non-flooded district borders a flooded one (placebo-treated in the robustness test).. Construction: Hand-coded adjacency for the placebo test; flooded districts are dropped in that test.. Units: 0/1. Source: Assigned (this study)
note flood_treatment_group: Readable label combining treatment status and region (convenience for selecting control pools).. Construction: Derived from flooded + region_group.. Units: category. Source: Derived
note latitude: Unit-centroid latitude; time-invariant. Enables Conley spatial standard errors.. Construction: Real approximate centroids for Aceh's 23 districts; synthetic non-Aceh districts drawn within the province bounding box. Sub-districts: parent centroid + ~20 km jitter.. Units: degrees. Source: Assigned (this study)
note longitude: Unit-centroid longitude; time-invariant. Used with latitude for haversine distances.. Construction: See latitude. Used for the Conley spatial kernel (<=100 km).. Units: degrees. Source: Assigned (this study)
note year: Calendar year of the observation. Panel spans 1999-2012 (levels); growth rates defined 2000-2012.. Construction: Annual index.. Units: year. Source: Simulation
note post: 1 for years 2005 and later (simple pre/post split).. Construction: 1 if year >= 2005.. Units: 0/1. Source: Derived
note period: Event-time period for the staggered DiD dummies; baseline 2000-02 is the omitted reference.. Construction: Mapped from year: '(base year)' 1999, baseline 2000-02, pre 2003-04, tsunami 2005, recovery 2006-08, postrec 2009-12.. Units: category. Source: Derived
note gdp_const_usd_m: District real GDP excluding oil & gas, constant 2004 USD, millions.. Construction: Cumulated from the 1999 base level using the simulated gdp_growth series.. Units: million constant 2004 USD. Source: Simulation
note gdp_growth: Annual growth rate of real district GDP (main dependent variable).. Construction: district FE + year FE + treated increment (city/rural) + Aceh-control spillover + spatial & serial shocks + N(0,0.04) noise.. Units: proportion/yr. Source: Simulation
note population: District population; drives the per-capita denominator.. Construction: Cumulated from the 1999 base using pop_growth (flooded districts lose ~9.6% in 2005).. Units: persons. Source: Simulation
note pop_growth: Annual population growth rate (carries the 2005 death/displacement shock).. Construction: district FE + year FE + flooded x population increment (death shock 2005) + noise.. Units: proportion/yr. Source: Simulation
note gdp_pc_usd: Real GDP per capita.. Construction: gdp_const_usd_m * 1e6 / population.. Units: constant 2004 USD. Source: Derived
note gdp_pc_growth: Annual growth rate of real GDP per capita; no significant 2005 loss, significant 2006-08 gain.. Construction: gdp_growth - pop_growth (reproduces the paper's per-capita table by construction).. Units: proportion/yr. Source: Derived
note va_agri_share: Agriculture value added as % of GDP; Aceh falls 44->32% after 2004.. Construction: Province trajectory + district/type offset.. Units: % of GDP. Source: Simulation
note va_manu_share: Manufacturing value added as % of GDP; Aceh falls ~6->3.5% after 2004.. Construction: Province trajectory + noise.. Units: % of GDP. Source: Simulation
note va_serv_share: Services / tertiary value added as % of GDP; Aceh rises ~40->55% after 2004.. Construction: Province trajectory + offset.. Units: % of GDP. Source: Simulation
note capital_formation_pc_usd: Gross capital formation per capita; reproduces the post-tsunami investment bonanza.. Construction: Smooth path + reconstruction spike (peak 2006) for Aceh; smooth for donors.. Units: current USD per capita. Source: Simulation
note poverty_rate: Share of population below the poverty line; Aceh improves after 2005 (synthetic-control predictor).. Construction: District base + downward trend.. Units: %. Source: Simulation
note doctors_per_1000: Physicians per 1,000 people; Aceh rises faster after 2005 (synthetic-control predictor).. Construction: District base + upward trend.. Units: per 1,000. Source: Simulation
note water_access_pct: % of households with clean-water access; Aceh boosted after 2005 (synthetic-control predictor).. Construction: District base + upward trend.. Units: %. Source: Simulation
note sanitation_access_pct: % of households with sanitation access; Aceh boosted after 2005 (synthetic-control predictor).. Construction: District base + upward trend.. Units: %. Source: Simulation
note electricity_access_pct: % of households with electricity; Aceh 84% (2004) -> 97% (2012).. Construction: Aceh boosted path; others smooth upward trend.. Units: %. Source: Simulation
note hdi: Human Development Index; Aceh ~69 -> ~73 over the period.. Construction: Aceh boosted path; others smooth upward trend.. Units: index 0-100. Source: Simulation
save "aceh_tsunami_district_panel.dta", replace

* ---- aceh_tsunami_subdistrict_panel.dta ----
use "aceh_tsunami_subdistrict_panel.dta", clear
label data "Annual Aceh sub-district panel: night-lights + flood dose"
note _dta: Annual sub-district (kecamatan) panel; 276 Aceh kecamatans, 1999-2012 (3,864 rows). Satellite night-lights (DMSP-OLS proxy) and continuous/quintile flood intensity. Night-lights growth is missing in 1999.
note kecamatan_id: Unique identifier for the sub-district; the sub-district panel key.. Construction: Assigned KEC_001 .. KEC_276.. Units: string. Source: Assigned (this study)
note kecamatan_name: Readable name linking the kecamatan to its parent district.. Construction: Built as <ParentDistrict>_Kec_<nn>.. Units: string. Source: Assigned (this study)
note district_name: Name of the district. Real names for Aceh's 23 districts; systematic placeholders elsewhere.. Construction: Real Aceh district names hand-coded from the paper's maps; other provinces use 'Province District k'.. Units: string. Source: Assigned (this study)
note province: Indonesian province the unit belongs to (district panel: 10 Sumatra provinces; sub-district panel: always Aceh).. Construction: Hand-coded; 10 Sumatra provinces in the district panel, constant 'Aceh' in the sub-district panel.. Units: string. Source: Assigned (this study)
note flooded: Treatment indicator: 1 if the unit was flooded by the 2004 tsunami (the DiD 'D' variable).. Construction: Hand-coded from the inundation maps; district panel: 10 Aceh + 2 North Sumatra island districts; sub-district panel: 68 of 276 kecamatans.. Units: 0/1. Source: Assigned (this study)
note share_pop_flooded: Share of the kecamatan's population in flooded area - the headline continuous dose.. Construction: latent dose * 0.62 + noise (flooded only); GRUMP-population analogue.. Units: 0-1. Source: Simulation
note share_area_flooded: Share of the kecamatan's physical area flooded; tiny mean (~1.2%) gives a large coefficient.. Construction: latent dose * 0.00566 + noise (flooded only).. Units: 0-1. Source: Simulation
note flood_intensity_quintile: Quintile of the flooding-intensity distribution among flooded units; only the top quintile shows a significant effect.. Construction: qcut of the latent dose into 5 groups among flooded kecamatans; 0 for non-flooded.. Units: 0-5. Source: Derived
note area_km2: Approximate land area of the kecamatan; sets the number of night-light pixels.. Construction: Drawn lognormal (30-1500 km^2).. Units: km^2. Source: Simulation
note n_pixels: Number of ~0.86 km^2 night-light grid cells in the kecamatan.. Construction: round(area_km2 / 0.86); 30x30 arc-second pixels ~0.86 km^2 at the equator.. Units: count. Source: Derived
note latitude: Unit-centroid latitude; time-invariant. Enables Conley spatial standard errors.. Construction: Real approximate centroids for Aceh's 23 districts; synthetic non-Aceh districts drawn within the province bounding box. Sub-districts: parent centroid + ~20 km jitter.. Units: degrees. Source: Assigned (this study)
note longitude: Unit-centroid longitude; time-invariant. Used with latitude for haversine distances.. Construction: See latitude. Used for the Conley spatial kernel (<=100 km).. Units: degrees. Source: Assigned (this study)
note year: Calendar year of the observation. Panel spans 1999-2012 (levels); growth rates defined 2000-2012.. Construction: Annual index.. Units: year. Source: Simulation
note post: 1 for years 2005 and later (simple pre/post split).. Construction: 1 if year >= 2005.. Units: 0/1. Source: Derived
note period: Event-time period for the staggered DiD dummies; baseline 2000-02 is the omitted reference.. Construction: Mapped from year: '(base year)' 1999, baseline 2000-02, pre 2003-04, tsunami 2005, recovery 2006-08, postrec 2009-12.. Units: category. Source: Derived
note avg_luminosity: Mean Digital Number (brightness) across the kecamatan's pixels; flooded 2004 mean ~5.79, non-flooded ~2.36.. Construction: nl_sum / n_pixels, top-coded at 63 (DMSP saturation).. Units: DN (0-63). Source: Simulation
note nl_sum: Sum of Digital Numbers over all pixels in the kecamatan (the unit-level activity measure).. Construction: exp(nl_log) - 0.001.. Units: DN-sum. Source: Derived
note nl_log: log( sum of (DN + 0.001) ) - the transformed regression variable matching the paper's log night-lights.. Construction: Cumulated from the 2004 anchor using the nl_growth series.. Units: log DN-sum. Source: Simulation
note nl_growth: Annual growth rate of log night-lights (main sub-district dependent variable).. Construction: kecamatan FE + year FE + theta(period)*dose^2 (flooded) + N(0,0.005) noise.. Units: proportion/yr. Source: Simulation
save "aceh_tsunami_subdistrict_panel.dta", replace
