* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- saving.dta ----
use "saving.dta", clear
label data "Savings panel: 56 countries x 15 periods (standardized)"
note _dta: Strongly balanced panel from Su, Shi & Phillips (2016). All five economic variables are standardized to mean 0, SD 1; year is coded 1-15 (= 1995-2010). C-LASSO selects K=2 groups with opposite-signed CPI and interest-rate effects.
note code: Numeric country identifier in the savings panel (1-56).. Construction: Anonymized integer code; no country-name mapping is provided in the file.. Units: integer code. Source: Su, Shi & Phillips (2016)
note year: Time index of the panel. In the savings panel coded 1-15 (= 1995-2010); in the democracy panel the calendar year.. Construction: Sequential period index (savings) / calendar year (democracy).. Units: period / year. Source: Source panels
note savings: Standardized savings-to-GDP ratio - the outcome of the savings application.. Construction: Savings/GDP standardized to mean 0, SD 1 across the panel.. Units: SD units. Source: Su, Shi & Phillips (2016)
note lagsavings: One-period lag of the standardized savings ratio; the dynamic-model persistence term.. Construction: L.savings within country; standardized to mean 0, SD 1.. Units: SD units. Source: Su, Shi & Phillips (2016)
note cpi: Standardized consumer-price-index inflation - the regressor whose sign reverses across groups.. Construction: CPI inflation standardized to mean 0, SD 1.. Units: SD units. Source: Su, Shi & Phillips (2016)
note interest: Standardized real interest rate; also exhibits a group sign reversal.. Construction: Real interest rate standardized to mean 0, SD 1.. Units: SD units. Source: Su, Shi & Phillips (2016)
note gdp: Standardized GDP growth rate; positive in both savings groups.. Construction: GDP growth standardized to mean 0, SD 1.. Units: SD units. Source: Su, Shi & Phillips (2016)
save "saving.dta", replace

* ---- democracy.dta ----
use "democracy.dta", clear
label data "Democracy & growth panel: 98 countries, 1970-2010 (ANRR 2019)"
note _dta: Acemoglu, Naidu, Restrepo & Robinson (2019) panel. lnPGDP and GDP lags are log per-capita GDP x100; lnTrade and lnMort are likewise x100. The post uses lnPGDP, Democracy, and ly1 (lags ly2-ly4 support the empirical.do extensions).
note name: Country name string for the democracy panel.. Construction: Country identifier carried alongside the numeric code.. Units: string. Source: Acemoglu et al. (2019)
note country: Generated numeric country code; the panel id for the democracy application.. Construction: Generated integer code (embedded label: 'Generated numeric country code').. Units: integer code. Source: Acemoglu et al. (2019)
note year: Time index of the panel. In the savings panel coded 1-15 (= 1995-2010); in the democracy panel the calendar year.. Construction: Sequential period index (savings) / calendar year (democracy).. Units: period / year. Source: Source panels
note lnPGDP: Log of GDP per capita in 2000 constant dollars, multiplied by 100 - the growth outcome.. Construction: 100 x log(real GDP per capita, 2000 constant USD).. Units: log USD x100. Source: Acemoglu et al. (2019)
note Democracy: Binary democracy measure of Acemoglu, Naidu, Restrepo & Robinson: 1 if democratic country-year, else 0.. Construction: ANRR dichotomous democracy classification.. Units: 0/1. Source: Acemoglu et al. (2019)
note ly1: First lag of lnPGDP - the dynamic-model persistence term.. Construction: L1.lnPGDP within country.. Units: log USD x100. Source: Acemoglu et al. (2019)
note ly2: Second lag of lnPGDP (used in the empirical.do lag-structure extensions).. Construction: L2.lnPGDP within country.. Units: log USD x100. Source: Acemoglu et al. (2019)
note ly3: Third lag of lnPGDP (used in the lag-structure extensions).. Construction: L3.lnPGDP within country.. Units: log USD x100. Source: Acemoglu et al. (2019)
note ly4: Fourth lag of lnPGDP (used in the lag-structure extensions).. Construction: L4.lnPGDP within country.. Units: log USD x100. Source: Acemoglu et al. (2019)
note lnpop: Log of population.. Construction: log(population).. Units: log persons. Source: Acemoglu et al. (2019)
note lnpop95: Log of population in 1995 (time-invariant per country).. Construction: log(population in 1995).. Units: log persons. Source: Acemoglu et al. (2019)
note lnTrade: Log of trade (exports + imports as % of GDP), multiplied by 100.. Construction: 100 x log(trade share of GDP).. Units: log x100. Source: Acemoglu et al. (2019)
note lnMort: Log of the child mortality rate, multiplied by 100.. Construction: 100 x log(child mortality rate).. Units: log x100. Source: Acemoglu et al. (2019)
note transition: 1 if the country-year is a democratic-transition year, else 0.. Construction: ANRR transition-year flag.. Units: 0/1. Source: Acemoglu et al. (2019)
note transid: 1 if the country ever experiences a transition, else 0 (time-invariant per country).. Construction: ANRR transition-country flag.. Units: 0/1. Source: Acemoglu et al. (2019)
save "democracy.dta", replace
