* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- industrial_park_district_panel.dta ----
use "industrial_park_district_panel.dta", clear
label data "Satellite district-year panel: activity outcomes + treatment + covariates"
note _dta: Balanced annual satellite panel, 139 synthetic woredas, 2005-2020. Carries the staggered open_year, the activity outcomes (IHS light, raw light, impervious ratio), geography, road density, and 2007 baseline characteristics used for the unit-specific trend interactions.
note district_id: Synthetic woreda identifier; the panel's unit of analysis and DiD fixed-effect / cluster key.. Construction: Sequential synthetic codes ET_D001 .. ET_D139.. Units: string. Source: Synthetic (this study)
note district_name: Human-readable name for the woreda (real Ethiopian district names used as labels).. Construction: Assigned from a name scaffold; calibrated to the paper's park geography.. Units: string. Source: Synthetic (this study)
note region: Ethiopian regional state the woreda belongs to.. Construction: Assigned per woreda (e.g. Oromia, Addis Ababa, Amhara, Tigray, Sidama).. Units: string. Source: Synthetic (this study)
note region_id: Integer code for the regional state; used in region x year and region x round fixed effects.. Construction: 1..12, one per region.. Units: code. Source: Synthetic (this study)
note treated: 1 if the woreda ever receives an industrial park (group indicator), else 0 (never-treated control).. Construction: 1 for the 17 park-hosting woredas, 0 for the 122 matched controls.. Units: 0/1. Source: Synthetic (this study)
note open_year: Calendar year the woreda's park opened; missing for never-treated controls.. Construction: Staggered rollout: 2008 anchor, then 2014-2020 build-out (2-3 woredas/year).. Units: year. Source: Synthetic (this study)
note treatment: Time-varying DiD indicator: 1 for a treated woreda in years at/after its open_year, else 0.. Construction: 1[treated == 1 and year >= open_year].. Units: 0/1. Source: Synthetic (this study)
note nearby: 1 for a control woreda within 10 km of an operational park (spillover/SUTVA test), else 0.. Construction: 1 if a never-treated woreda lies within 10 km of any open park in that year.. Units: 0/1. Source: Synthetic (this study)
note event_time: Year minus the woreda's open_year (event time k); the event-study time axis.. Construction: year - open_year for treated woredas.. Units: years (k). Source: Synthetic (this study)
note year: Annual time index of the satellite panel.. Construction: 2005-2020, balanced for all 139 woredas.. Units: year. Source: Synthetic (this study)
note post: 1 for years at/after the median opening year (2017), used to collapse the design into the naive 2x2.. Construction: 1[year >= 2017].. Units: 0/1. Source: Synthetic (this study)
note light_intensity: Untransformed mean nighttime luminosity of the woreda (VIIRS-like, calibrated).. Construction: Simulated; treated park-cities carry an intrinsically bright base (the bright-base device).. Units: DN (light units). Source: Synthetic (this study)
note ihs_light: Inverse hyperbolic sine of nighttime luminosity; a log-like transform that handles zeros.. Construction: asinh(light_intensity); coefficients read approximately as proportional changes.. Units: asinh(DN). Source: Synthetic (this study)
note light_positive: 1 if the woreda has positive nighttime luminosity, else 0.. Construction: 1[light_intensity > 0].. Units: 0/1. Source: Synthetic (this study)
note impervious_ratio: Share of the woreda's land that is built-up/impervious surface; observed only every five years.. Construction: Simulated impervious-surface ratio calibrated to the GISD30-style product.. Units: 0-1 (share). Source: Synthetic (this study)
note longitude: Woreda centroid longitude (decimal degrees).. Construction: Assigned per woreda, calibrated to the paper's park geography.. Units: degrees. Source: Synthetic (this study)
note latitude: Woreda centroid latitude (decimal degrees).. Construction: Assigned per woreda, calibrated to the paper's park geography.. Units: degrees. Source: Synthetic (this study)
note elevation: Woreda mean elevation above sea level.. Construction: Assigned per woreda (time-invariant).. Units: metres. Source: Synthetic (this study)
note slope: Woreda mean terrain slope.. Construction: Assigned per woreda (time-invariant).. Units: degrees. Source: Synthetic (this study)
note dist_addis_km: Road/great-circle distance from the woreda to the capital, Addis Ababa.. Construction: Computed from woreda coordinates; a heterogeneity moderator.. Units: km. Source: Synthetic (this study)
note dist_state_capital_km: Distance from the woreda to its regional-state capital.. Construction: Computed from woreda coordinates; a heterogeneity moderator.. Units: km. Source: Synthetic (this study)
note dist_nearest_city_km: Distance from the woreda to the nearest city; the steepest effect moderator.. Construction: Computed from woreda coordinates; a heterogeneity moderator.. Units: km. Source: Synthetic (this study)
note urbanization_rate_2007: Share of the woreda's population in urban areas at the 2007 baseline.. Construction: 2007 baseline value; interacted with centred time for the unit-specific trends.. Units: 0-1 (share). Source: Synthetic (this study)
note employment_rate_2007: Share of the woreda's working-age population employed at the 2007 baseline.. Construction: 2007 baseline value; interacted with centred time for the unit-specific trends.. Units: 0-1 (share). Source: Synthetic (this study)
note log_pop_density_2007: Natural log of population per km^2 at the 2007 baseline.. Construction: log of 2007 population density; interacted with centred time for the trends.. Units: log persons/km^2. Source: Synthetic (this study)
note population_2007: Woreda population at the 2007 baseline.. Construction: 2007 baseline population count.. Units: persons. Source: Synthetic (this study)
note primary_road_density: Density of primary roads in the woreda; a road-access moderator.. Construction: Assigned per woreda; positive interaction with treatment (amplifies the effect).. Units: km/km^2 (density). Source: Synthetic (this study)
note paved_road_density: Density of paved roads in the woreda; the significant road moderator.. Construction: Assigned per woreda; positive interaction with treatment (amplifies the effect).. Units: km/km^2 (density). Source: Synthetic (this study)
note share_christian_2007: Share of the woreda population that is Christian at the 2007 baseline.. Construction: 2007 baseline value; interacted with centred time for the unit-specific trends.. Units: 0-1 (share). Source: Synthetic (this study)
note share_amharic_2007: Share of the woreda population speaking Amharic at the 2007 baseline.. Construction: 2007 baseline value; interacted with centred time for the unit-specific trends.. Units: 0-1 (share). Source: Synthetic (this study)
note labor_intensive_park: 1 if the woreda's park is labor-intensive (textiles/garments), else 0 (park-type context).. Construction: Assigned per treated woreda; 0 for controls.. Units: 0/1. Source: Synthetic (this study)
note public_park: 1 if the park is publicly (government) developed, else 0 (park-type context).. Construction: Assigned per treated woreda; 0 for controls.. Units: 0/1. Source: Synthetic (this study)
note china_aid: 1 if the park involves Chinese financing/aid, else 0 (context indicator).. Construction: Assigned per treated woreda; 0 for controls.. Units: 0/1. Source: Synthetic (this study)
note transport_project: 1 if the woreda has an associated transport project, else 0 (context indicator).. Construction: Assigned per woreda.. Units: 0/1. Source: Synthetic (this study)
save "industrial_park_district_panel.dta", replace

* ---- industrial_park_household_rcs.dta ----
use "industrial_park_household_rcs.dta", clear
label data "DHS household repeated cross-section: living-standards outcomes"
note _dta: DHS-style repeated cross-section: each round samples DIFFERENT households, so there is no within-household panel key. Effects are identified off district x region-round group means with DHS survey weights; only coarse event phases are available.
note hh_id: Synthetic per-round household identifier; NOT a panel key (each round samples different households).. Construction: Sequential codes HH_000000 .. across all rounds.. Units: string. Source: Synthetic (this study)
note survey_round: Calendar year of the DHS round the respondent belongs to.. Construction: One of five rounds: 2000, 2005, 2011, 2016, 2019.. Units: year. Source: Synthetic (this study)
note district_id: Synthetic woreda identifier; the panel's unit of analysis and DiD fixed-effect / cluster key.. Construction: Sequential synthetic codes ET_D001 .. ET_D139.. Units: string. Source: Synthetic (this study)
note region_id: Integer code for the regional state; used in region x year and region x round fixed effects.. Construction: 1..12, one per region.. Units: code. Source: Synthetic (this study)
note treated: 1 if the woreda ever receives an industrial park (group indicator), else 0 (never-treated control).. Construction: 1 for the 17 park-hosting woredas, 0 for the 122 matched controls.. Units: 0/1. Source: Synthetic (this study)
note treatment: Time-varying DiD indicator: 1 for a treated woreda in years at/after its open_year, else 0.. Construction: 1[treated == 1 and year >= open_year].. Units: 0/1. Source: Synthetic (this study)
note event_phase: Round position relative to the district's park opening; the RCS event-study axis (k = -1 reference).. Construction: Survey round position minus the opening round, for treated districts.. Units: phase (k). Source: Synthetic (this study)
note durable_goods_pc: Standardized count of household durable goods per capita; a living-standards outcome.. Construction: Standardized score (mean ~0); ATT reads against a near-zero mean.. Units: standardized. Source: Synthetic (this study)
note housing_quality: 1 if the household has electricity, piped water, a toilet, and a finished floor, else 0.. Construction: Composite 0/1 indicator over the four housing amenities.. Units: 0/1. Source: Synthetic (this study)
note wealth_index: Composite standardized household wealth index; effects read in standard deviations.. Construction: Standardized composite (mean ~0, SD ~1).. Units: SD (z-score). Source: Synthetic (this study)
note hh_size: Number of members in the household; a demographic control.. Construction: Integer count, 1-12.. Units: persons. Source: Synthetic (this study)
note age_head: Age of the household head (years); a demographic control.. Construction: Integer years, 18-90.. Units: years. Source: Synthetic (this study)
note survey_weight: Respondent sampling weight for the complex DHS design; used to weight all RCS regressions.. Construction: Calibrated to a DHS-style design (mean ~1).. Units: weight. Source: Synthetic (this study)
save "industrial_park_household_rcs.dta", replace

* ---- industrial_park_individual_rcs.dta ----
use "industrial_park_individual_rcs.dta", clear
label data "DHS individual repeated cross-section: employment + women's empowerment"
note _dta: DHS-style repeated cross-section of individuals; the analytical climax splits by sex. The five dv_* sub-items are the wife-beating-acceptance scenarios that compose dv_accept.
note ind_id: Synthetic per-round individual identifier; NOT a panel key (each round samples different individuals).. Construction: Sequential codes IND_000000 .. across all rounds.. Units: string. Source: Synthetic (this study)
note survey_round: Calendar year of the DHS round the respondent belongs to.. Construction: One of five rounds: 2000, 2005, 2011, 2016, 2019.. Units: year. Source: Synthetic (this study)
note district_id: Synthetic woreda identifier; the panel's unit of analysis and DiD fixed-effect / cluster key.. Construction: Sequential synthetic codes ET_D001 .. ET_D139.. Units: string. Source: Synthetic (this study)
note region_id: Integer code for the regional state; used in region x year and region x round fixed effects.. Construction: 1..12, one per region.. Units: code. Source: Synthetic (this study)
note treated: 1 if the woreda ever receives an industrial park (group indicator), else 0 (never-treated control).. Construction: 1 for the 17 park-hosting woredas, 0 for the 122 matched controls.. Units: 0/1. Source: Synthetic (this study)
note treatment: Time-varying DiD indicator: 1 for a treated woreda in years at/after its open_year, else 0.. Construction: 1[treated == 1 and year >= open_year].. Units: 0/1. Source: Synthetic (this study)
note event_phase: Round position relative to the district's park opening; the RCS event-study axis (k = -1 reference).. Construction: Survey round position minus the opening round, for treated districts.. Units: phase (k). Source: Synthetic (this study)
note sex: Respondent sex; the heterogeneity split for the employment/empowerment climax (1 = women).. Construction: 1 for women, 0 for men.. Units: 0/1. Source: Synthetic (this study)
note age: Age of the individual respondent (years); a demographic control.. Construction: Integer years, 15-62.. Units: years. Source: Synthetic (this study)
note age_sq: Square of respondent age; a demographic control for nonlinear age effects.. Construction: age^2.. Units: years^2. Source: Synthetic (this study)
note nonag_employment: 1 if the individual works in a non-agricultural job, else 0; the headline employment outcome.. Construction: 0/1 indicator; the average effect is null while the female effect is significant.. Units: 0/1. Source: Synthetic (this study)
note decision_power: 1 if the woman participates in household decision-making, else 0 (empowerment outcome, women).. Construction: 0/1 indicator.. Units: 0/1. Source: Synthetic (this study)
note savings_account: 1 if the woman owns a savings/bank account, else 0 (financial-inclusion outcome, women).. Construction: 0/1 indicator.. Units: 0/1. Source: Synthetic (this study)
note dv_accept: 1 if the respondent justifies wife-beating in any of the five DHS scenarios, else 0 (gender-norms outcome).. Construction: Composite over the five dv_* sub-items; treatment lowers it.. Units: 0/1. Source: Synthetic (this study)
note dv_goingout: DHS sub-item - 1 if wife-beating is justified for going out without telling the husband, else 0.. Construction: 0/1 DHS attitude sub-item composing dv_accept.. Units: 0/1. Source: Synthetic (this study)
note dv_kids: DHS sub-item - 1 if wife-beating is justified for neglecting the children, else 0.. Construction: 0/1 DHS attitude sub-item composing dv_accept.. Units: 0/1. Source: Synthetic (this study)
note dv_arguing: DHS sub-item - 1 if wife-beating is justified for arguing with the husband, else 0.. Construction: 0/1 DHS attitude sub-item composing dv_accept.. Units: 0/1. Source: Synthetic (this study)
note dv_sex: DHS sub-item - 1 if wife-beating is justified for refusing to have sex, else 0.. Construction: 0/1 DHS attitude sub-item composing dv_accept.. Units: 0/1. Source: Synthetic (this study)
note dv_food: DHS sub-item - 1 if wife-beating is justified for burning the food, else 0.. Construction: 0/1 DHS attitude sub-item composing dv_accept.. Units: 0/1. Source: Synthetic (this study)
note hh_size: Number of members in the household; a demographic control.. Construction: Integer count, 1-12.. Units: persons. Source: Synthetic (this study)
note age_head: Age of the household head (years); a demographic control.. Construction: Integer years, 18-90.. Units: years. Source: Synthetic (this study)
note survey_weight: Respondent sampling weight for the complex DHS design; used to weight all RCS regressions.. Construction: Calibrated to a DHS-style design (mean ~1).. Units: weight. Source: Synthetic (this study)
save "industrial_park_individual_rcs.dta", replace
