* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- lalonde_dowhy.dta ----
use "lalonde_dowhy.dta", clear
label data "NSW job-training evaluation: treatment, outcome, 8 covariates"
note _dta: Lalonde NSW Demonstration experimental sample, exported verbatim from DoWhy's lalonde_dataset(). One row per participant; treat is the randomized assignment, re78 the outcome, the other eight columns are pre-treatment covariates.
note treat: Randomized treatment indicator: 1 if assigned to NSW job training, 0 if control.. Construction: From NSW random assignment; cast from boolean to integer in the post.. Units: 0/1. Source: NSW Demonstration (LaLonde 1986)
note re78: Post-program real annual earnings in 1978 - the outcome variable.. Construction: Observed earnings; real (inflation-adjusted) US dollars.. Units: US$ (1978). Source: NSW Demonstration follow-up
note age: Participant age at baseline, in years.. Construction: Observed at enrollment.. Units: years. Source: NSW Demonstration baseline
note educ: Completed years of schooling at baseline.. Construction: Observed at enrollment.. Units: years. Source: NSW Demonstration baseline
note black: Race indicator: 1 if the participant is Black, else 0.. Construction: Observed demographic at baseline.. Units: 0/1. Source: NSW Demonstration baseline
note hisp: Ethnicity indicator: 1 if the participant is Hispanic, else 0.. Construction: Observed demographic at baseline.. Units: 0/1. Source: NSW Demonstration baseline
note married: Marital-status indicator: 1 if married at baseline, else 0.. Construction: Observed demographic at baseline.. Units: 0/1. Source: NSW Demonstration baseline
note nodegr: 1 if the participant lacks a high-school diploma, else 0.. Construction: Observed at baseline (no high-school degree).. Units: 0/1. Source: NSW Demonstration baseline
note re74: Pre-program real annual earnings in 1974 (prior earnings, a key confounder).. Construction: Observed earnings; real US dollars.. Units: US$ (1974). Source: NSW Demonstration baseline
note re75: Pre-program real annual earnings in 1975 (prior earnings, a key confounder).. Construction: Observed earnings; real US dollars.. Units: US$ (1975). Source: NSW Demonstration baseline
save "lalonde_dowhy.dta", replace
