* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- v113i06.dta ----
use "v113i06.dta", clear
label data "Bank-quarter panel: NPL + 7 financial ratios + instrument"
note _dta: Strongly balanced quarterly panel of 350 US commercial banks, 2006:Q1-2014:Q4 (TIME 1-36). Replication data from Kripfganz & Sarafidis (2025), JSS 113(6). NPL is the dependent variable; INEFF is endogenous and instrumented by INTEREST; the 350x350 spatial weight matrix is the separate file W.csv.
note ID: Anonymized US commercial-bank identifier (1-350); the panel cross-section unit.. Construction: Integer bank code from the replication package; declared with xtset ID TIME.. Units: 1-350. Source: Kripfganz & Sarafidis (2025)
note TIME: Quarter counter 1-36, mapping 2006:Q1 (=1) to 2014:Q4 (=36).. Construction: Sequential quarter index from the replication package; the panel time variable.. Units: 1-36 (quarters). Source: Kripfganz & Sarafidis (2025)
note NPL: Non-performing loans as a share of total loans, in percentage points; the dependent variable (credit risk).. Construction: Bank-quarter NPL/total-loans from the replication package; modelled with spatial and temporal lags.. Units: % (percentage points). Source: Kripfganz & Sarafidis (2025)
note INEFF: Bank operational inefficiency; treated as the endogenous regressor in the NPL equation.. Construction: Bank-quarter inefficiency measure; instrumented by INTEREST and lagged exogenous regressors.. Units: ratio. Source: Kripfganz & Sarafidis (2025)
note CAR: Regulatory capital adequacy ratio of the bank.. Construction: Bank-quarter CAR from the replication package; an exogenous covariate.. Units: %. Source: Kripfganz & Sarafidis (2025)
note SIZE: Natural log of total assets; a proxy for bank scale and systemic exposure.. Construction: log of bank total assets, bank-quarter; an exogenous covariate.. Units: log (ln assets). Source: Kripfganz & Sarafidis (2025)
note BUFFER: Capital buffer above the regulatory minimum (leverage ratio minus the 8% threshold).. Construction: Leverage ratio minus 8, bank-quarter; an exogenous covariate (protective: enters NPL negatively).. Units: percentage points. Source: Kripfganz & Sarafidis (2025)
note PROFIT: Bank profitability, annualized return on equity.. Construction: Bank-quarter ROE from the replication package; an exogenous covariate.. Units: % (annualized ROE). Source: Kripfganz & Sarafidis (2025)
note QUALITY: Loan loss provisions as a share of assets; a flow indicator of asset quality.. Construction: Bank-quarter provisions/assets from the replication package; an exogenous covariate.. Units: %. Source: Kripfganz & Sarafidis (2025)
note LIQUIDITY: Loans relative to deposits; the covariate with the largest effect on NPL in the full model.. Construction: Bank-quarter loan-to-deposit ratio from the replication package; an exogenous covariate.. Units: ratio. Source: Kripfganz & Sarafidis (2025)
note INTEREST: Interest expenses relative to deposits; the excluded instrument for the endogenous INEFF.. Construction: Bank-quarter interest-expense/deposits from the replication package; enters only the iv() instrument set.. Units: ratio. Source: Kripfganz & Sarafidis (2025)
save "v113i06.dta", replace
