* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- store_data.dta ----
use "store_data.dta", clear
label data "Simulated retail cross-section (sales, coupons, income, day)"
note _dta: Simulated with set.seed(42); income confounds coupons and sales. coupons = 60 - 0.5-income + N(0,5); sales = 10 + 0.2-coupons + 0.3-income + 0.5-dayofweek + N(0,3).
note sales: Simulated sales for the store (the outcome variable).. Construction: sales = 10 + 0.2-coupons + 0.3-income + 0.5-dayofweek + N(0,3); rounded to 2 decimals.. Units: index units. Source: Simulation (this study)
note coupons: Number/intensity of coupons distributed (the regressor of interest).. Construction: coupons = 60 - 0.5-income + N(0,5); rounded to 2 decimals. Negatively driven by income (the confounder).. Units: count/index. Source: Simulation (this study)
note income: Neighborhood income level - the confounder that drives both coupons and sales.. Construction: income ~ N(50, 10); rounded to 2 decimals.. Units: index units. Source: Simulation (this study)
note dayofweek: Day-of-week indicator used as an additional control in ?5.4.. Construction: Uniform draw sample(1:7); 1=first day ... 7=last day.. Units: 1-7. Source: Simulation (this study)
save "store_data.dta", replace

* ---- flights_sample.dta ----
use "flights_sample.dta", clear
label data "Cleaned 2013 NYC flights sample (delays, air time, route)"
note _dta: Sampled with set.seed(123) from flights kept with non-missing dep_delay/air_time/origin/dest, dep_delay in (-30,120), and non-singleton origin-dest routes. From the nycflights13 package (US BTS).
note dep_delay: Departure delay in minutes (the outcome in the flights regressions).. Construction: From nycflights13; cleaned sample keeps dep_delay in (-30, 120).. Units: minutes. Source: nycflights13 (US BTS)
note arr_delay: Arrival delay in minutes.. Construction: From nycflights13 (carried in the saved sample; not used in the post's regressions).. Units: minutes. Source: nycflights13 (US BTS)
note air_time: Time in the air, in minutes (the regressor of interest in the flights example).. Construction: From nycflights13; cleaned to non-missing values.. Units: minutes. Source: nycflights13 (US BTS)
note origin: Origin airport code - one of New York's three airports; used as a fixed effect.. Construction: From nycflights13: EWR, JFK, or LGA.. Units: code. Source: nycflights13 (US BTS)
note dest: Destination airport code; used as a fixed effect alongside origin.. Construction: From nycflights13 (IATA destination code).. Units: code. Source: nycflights13 (US BTS)
note carrier: Two-letter airline carrier code.. Construction: From nycflights13 (carried in the sample; not used in the post's regressions).. Units: code. Source: nycflights13 (US BTS)
note month: Calendar month of the scheduled departure.. Construction: From nycflights13.. Units: 1-12. Source: nycflights13 (US BTS)
note day: Calendar day of month of the scheduled departure.. Construction: From nycflights13.. Units: 1-31. Source: nycflights13 (US BTS)
note hour: Scheduled departure hour (local).. Construction: From nycflights13.. Units: 0-23. Source: nycflights13 (US BTS)
save "flights_sample.dta", replace

* ---- wagepan.dta ----
use "wagepan.dta", clear
label data "Wooldridge wage panel: 545 men, 1980-1987 (balanced)"
note _dta: Standard Wooldridge wagepan dataset (originally Vella & Verbeek 1998). Balanced panel of young working men; many regressors are 0/1 industry, occupation, region, and year-dummy indicators.
note nr: Unique individual identifier (the panel unit; used as the individual fixed effect).. Construction: From the Wooldridge wagepan dataset.. Units: id. Source: Wooldridge wagepan
note year: Year of the observation.. Construction: From wagepan; used as the year fixed effect in two-way FE models.. Units: year. Source: Wooldridge wagepan
note agric: 1 if employed in agriculture, else 0.. Construction: From wagepan industry indicators.. Units: 0/1. Source: Wooldridge wagepan
note black: 1 if the individual is Black, else 0 (time-invariant).. Construction: From wagepan.. Units: 0/1. Source: Wooldridge wagepan
note bus: 1 if employed in business and repair services, else 0.. Construction: From wagepan industry indicators.. Units: 0/1. Source: Wooldridge wagepan
note construc: 1 if employed in construction, else 0.. Construction: From wagepan industry indicators.. Units: 0/1. Source: Wooldridge wagepan
note ent: 1 if employed in entertainment, else 0.. Construction: From wagepan industry indicators.. Units: 0/1. Source: Wooldridge wagepan
note exper: Years of (potential) labor-market experience - the regressor of interest in ?7.. Construction: From wagepan; increments by one year per individual per year.. Units: years. Source: Wooldridge wagepan
note fin: 1 if employed in finance, insurance, or real estate, else 0.. Construction: From wagepan industry indicators.. Units: 0/1. Source: Wooldridge wagepan
note hisp: 1 if the individual is Hispanic, else 0 (time-invariant).. Construction: From wagepan.. Units: 0/1. Source: Wooldridge wagepan
note poorhlth: 1 if the individual reports being in poor health, else 0.. Construction: From wagepan.. Units: 0/1. Source: Wooldridge wagepan
note hours: Annual hours worked.. Construction: From wagepan.. Units: hours/year. Source: Wooldridge wagepan
note manuf: 1 if employed in manufacturing, else 0.. Construction: From wagepan industry indicators.. Units: 0/1. Source: Wooldridge wagepan
note married: 1 if married, else 0.. Construction: From wagepan.. Units: 0/1. Source: Wooldridge wagepan
note min: 1 if employed in mining, else 0.. Construction: From wagepan industry indicators.. Units: 0/1. Source: Wooldridge wagepan
note nrthcen: 1 if resident of the North Central census region, else 0.. Construction: From wagepan region indicators.. Units: 0/1. Source: Wooldridge wagepan
note nrtheast: 1 if resident of the Northeast census region, else 0.. Construction: From wagepan region indicators.. Units: 0/1. Source: Wooldridge wagepan
note occ1: 1 if in occupation group 1, else 0 (occupational dummies occ1-occ9).. Construction: From wagepan occupation indicators.. Units: 0/1. Source: Wooldridge wagepan
note occ2: 1 if in occupation group 2, else 0.. Construction: From wagepan occupation indicators.. Units: 0/1. Source: Wooldridge wagepan
note occ3: 1 if in occupation group 3, else 0.. Construction: From wagepan occupation indicators.. Units: 0/1. Source: Wooldridge wagepan
note occ4: 1 if in occupation group 4, else 0.. Construction: From wagepan occupation indicators.. Units: 0/1. Source: Wooldridge wagepan
note occ5: 1 if in occupation group 5, else 0.. Construction: From wagepan occupation indicators.. Units: 0/1. Source: Wooldridge wagepan
note occ6: 1 if in occupation group 6, else 0.. Construction: From wagepan occupation indicators.. Units: 0/1. Source: Wooldridge wagepan
note occ7: 1 if in occupation group 7, else 0.. Construction: From wagepan occupation indicators.. Units: 0/1. Source: Wooldridge wagepan
note occ8: 1 if in occupation group 8, else 0.. Construction: From wagepan occupation indicators.. Units: 0/1. Source: Wooldridge wagepan
note occ9: 1 if in occupation group 9, else 0.. Construction: From wagepan occupation indicators.. Units: 0/1. Source: Wooldridge wagepan
note per: 1 if employed in personal services, else 0.. Construction: From wagepan industry indicators.. Units: 0/1. Source: Wooldridge wagepan
note pro: 1 if employed in professional and related services, else 0.. Construction: From wagepan industry indicators.. Units: 0/1. Source: Wooldridge wagepan
note pub: 1 if employed in public administration, else 0.. Construction: From wagepan industry indicators.. Units: 0/1. Source: Wooldridge wagepan
note rur: 1 if resident in a rural area, else 0.. Construction: From wagepan.. Units: 0/1. Source: Wooldridge wagepan
note south: 1 if resident of the South census region, else 0.. Construction: From wagepan region indicators.. Units: 0/1. Source: Wooldridge wagepan
note educ: Years of schooling (time-invariant; drops out under individual FE).. Construction: From wagepan.. Units: years. Source: Wooldridge wagepan
note tra: 1 if employed in transportation, communications, or utilities, else 0.. Construction: From wagepan industry indicators.. Units: 0/1. Source: Wooldridge wagepan
note trad: 1 if employed in wholesale or retail trade, else 0.. Construction: From wagepan industry indicators.. Units: 0/1. Source: Wooldridge wagepan
note union: 1 if wage is set by a collective-bargaining agreement, else 0.. Construction: From wagepan.. Units: 0/1. Source: Wooldridge wagepan
note lwage: Natural log of the hourly wage (the outcome in the wage regressions).. Construction: From wagepan (log of hourly wage).. Units: log US$. Source: Wooldridge wagepan
note d81: 1 if the observation year is 1981, else 0.. Construction: From wagepan year dummies d81-d87.. Units: 0/1. Source: Wooldridge wagepan
note d82: 1 if the observation year is 1982, else 0.. Construction: From wagepan year dummies d81-d87.. Units: 0/1. Source: Wooldridge wagepan
note d83: 1 if the observation year is 1983, else 0.. Construction: From wagepan year dummies d81-d87.. Units: 0/1. Source: Wooldridge wagepan
note d84: 1 if the observation year is 1984, else 0.. Construction: From wagepan year dummies d81-d87.. Units: 0/1. Source: Wooldridge wagepan
note d85: 1 if the observation year is 1985, else 0.. Construction: From wagepan year dummies d81-d87.. Units: 0/1. Source: Wooldridge wagepan
note d86: 1 if the observation year is 1986, else 0.. Construction: From wagepan year dummies d81-d87.. Units: 0/1. Source: Wooldridge wagepan
note d87: 1 if the observation year is 1987, else 0.. Construction: From wagepan year dummies d81-d87.. Units: 0/1. Source: Wooldridge wagepan
note expersq: Square of labor-market experience (captures the concave wage-experience profile).. Construction: exper^2.. Units: years^2. Source: Wooldridge wagepan (derived)
save "wagepan.dta", replace
