<!DOCTYPE html>
<html lang="en"><head>
<script src="slides_files/libs/clipboard/clipboard.min.js"></script>
<script src="slides_files/libs/quarto-html/tabby.min.js"></script>
<script src="slides_files/libs/quarto-html/popper.min.js"></script>
<script src="slides_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="slides_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="slides_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="slides_files/libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="dcterms.date" content="2026-06-11">
  <title>Synthetic Difference-in-Differences in Stata</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/theme/quarto-530021870a52ee60b3f5e86ec9e6fece.css">
  <link href="slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Synthetic Difference-in-Differences in Stata</h1>
  <p class="subtitle">Re-evaluating California’s Proposition 99 with the sdid command</p>
  <div class="title-result-strip">
    <div class="kr"><span class="kr-num">−15.60</span><span class="kr-cap">SDID · ATT packs per capita</span></div>
    <div class="kr"><span class="kr-num">−19.48</span><span class="kr-cap">synthetic control</span></div>
    <div class="kr"><span class="kr-num">−27.35</span><span class="kr-cap">naive 2×2 DiD</span></div>
  </div>
  <p class="author"><a href="https://carlos-mendez.org">Carlos Mendez</a></p>
  <p class="institute">Nagoya University (GSID)</p>
  <p class="date">June 11, 2026</p>
</section>
<section>
<section id="the-tension" class="title-slide slide level1 divider center" data-background-color="#d97757">
<h1>The Tension</h1>
<p><span class="act">Act I</span></p>
</section>
<section id="did-proposition-99-cut-smoking-we-can-never-observe-the-california-that-voted-no" class="slide level2 center">
<h2>Did Proposition 99 cut smoking? We can never observe the California that voted <em>no</em></h2>
<p>In November 1988, California raised its cigarette tax by 25 cents a pack and funded an anti-smoking campaign.</p>
<div class="fragment">
<p>To measure the effect we need California’s smoking <em>without</em> the law — a counterfactual we never get to see. <em>Every method here is a different way to imagine it.</em></p>
<aside class="notes">
<p>This is the textbook comparative case study: one large unit adopts a policy and we want the causal effect, even though the untreated California is forever unobserved. Set the stakes here — the whole talk is about how to build that dashed counterfactual line credibly.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="three-estimators-one-dataset-three-different-answers-from-27-to-16" class="slide level2 center">
<h2>Three estimators, one dataset, three different answers — from −27 to −16</h2>

<img data-src="../stata_sdid_compare_paths.png" class="r-stretch quarto-figure-center"><p class="caption">ATT in packs per capita. The naive 2×2 DiD counterfactual sits highest (−27), synthetic control next (−19.5), and SDID closest to California (−15.6). All four lines track California before 1989, then separate.</p><aside class="notes">
<p>The spoiler figure. Don’t explain each line yet — just plant that the answer to “how big was the effect?” depends entirely on how you build the counterfactual, and the three credible methods bracket a range. We earn each line in Act II and return to this picture in Act III.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="where-were-going" class="slide level2 center">
<h2>Where we’re going</h2>
<ul>
<li class="fragment">The case: Proposition 99 and a 39-state, 31-year panel</li>
<li class="fragment">Three estimators written as <strong>one</strong> weighted regression</li>
<li class="fragment">SDID’s signature: unit weights <em>and</em> time weights</li>
<li class="fragment">Inference with a single treated unit — placebo, not bootstrap</li>
</ul>
<aside class="notes">
<p>Built from the post’s learning objectives. Teaching deck, so we give the audience a map. Each bullet is roughly one act-segment.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="the-investigation" class="title-slide slide level1 divider center" data-background-color="#6a9bcc">
<h1>The Investigation</h1>
<p><span class="act">Act II</span></p>
</section>
<section id="the-lab-39-states-19702000-one-outcome-one-treated-unit" class="slide level2 center">
<h2>The lab: 39 states, 1970–2000, one outcome, one treated unit</h2>
<ul>
<li class="fragment"><strong>Outcome</strong> <span class="math inline">\(Y_{it}\)</span> — annual cigarette sales, packs per capita</li>
<li class="fragment"><strong>Treated</strong> <span class="math inline">\(W_{it}\)</span> — California from 1989 only (<span class="math inline">\(N_{tr}=1\)</span>)</li>
<li class="fragment"><strong>Donor pool</strong> — 38 control states, no comparable tobacco program</li>
<li class="fragment"><strong>No covariates</strong> — SC and SDID see <em>exactly</em> the same information</li>
</ul>
<p><span class="comment">1,209 observations, of which only <strong>12</strong> are treated. That extreme imbalance is the defining feature of a comparative case study — and it dictates how we do inference.</span></p>
<aside class="notes">
<p>The panel is strongly balanced (no gaps), which every method requires. The “outcome only, no covariates” design is deliberate: it means any difference between SC and SDID comes from the estimator, not from a different set of predictors. California is id 3 after an alphabetical encode.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-naive-picture-already-warns-us-california-was-on-a-different-level-and-trend" class="slide level2 center">
<h2>The naive picture already warns us: California was on a different level <em>and</em> trend</h2>

<img data-src="../stata_sdid_raw_trends.png" class="r-stretch quarto-figure-center"><p class="caption">California (orange) already smoked less than the 38-state average and was declining through the 1980s; after 1989 the gap widens — but the two series differed in level and slope before the policy, so a raw comparison is not enough.</p><aside class="notes">
<p>California sits at a different level than the average donor and was already on a steeper downward trend before 1989. A credible estimate must deal with both problems. This figure is the motivation for everything that follows — it is why DiD against the simple average is shaky.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-estimand-is-the-att-the-effect-of-the-policy-on-california" class="slide level2 center">
<h2>The estimand is the ATT — the effect of the policy <em>on California</em></h2>
<p><span class="math display">\[\tau = \frac{1}{N_{tr}\, T_{post}} \sum_{i:\, W_i = 1}\ \sum_{t &gt; T_{pre}} \left[\, Y_{it}(1) - Y_{it}(0) \,\right]\]</span></p>
<p><span class="comment">Average, over treated units and post-1988 years, of the outcome <em>with</em> the policy minus the outcome that <em>would</em> have occurred without it. With <span class="math inline">\(N_{tr}=1\)</span>, every method is just a different way to impute the missing <span class="math inline">\(Y_{it}(0)\)</span>.</span></p>
<aside class="notes">
<p>Name the estimand explicitly: this is the average treatment effect on the treated, not a population ATE. Because California was not randomly assigned to treatment, this is an observational design — identification rests on a stable comparison group and no California-specific shock, not on randomization.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="sdid-is-one-weighted-two-way-fixed-effects-regression" class="slide level2 center">
<h2>SDID is one weighted two-way fixed-effects regression</h2>
<p><span class="math display">\[\left(\hat{\tau}^{sdid}, \hat{\mu}, \hat{\alpha}, \hat{\beta}\right) = \underset{\tau,\mu,\alpha,\beta}{\arg\min} \sum_{i=1}^{N} \sum_{t=1}^{T} \left(Y_{it} - \mu - \alpha_i - \beta_t - W_{it}\,\tau\right)^{2}\, \hat{\omega}_i^{sdid}\, \hat{\lambda}_t^{sdid}\]</span></p>
<p><span class="comment"><span class="math inline">\(\alpha_i\)</span> is a state fixed effect, <span class="math inline">\(\beta_t\)</span> a year fixed effect, <span class="math inline">\(\tau\)</span> the ATT. The two extra terms — <span class="math inline">\(\hat{\omega}_i\)</span> (unit weight) and <span class="math inline">\(\hat{\lambda}_t\)</span> (time weight) — are everything that separates SDID from ordinary regression.</span></p>
<aside class="notes">
<p>This is the unifying view of Arkhangelsky et al.&nbsp;(2021). Read the symbols against the Stata variables: Y is packspercapita, W is treated. Set the two weights to special values and you recover the older estimators — that is the next two slides.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="set-both-weights-uniform-and-you-get-plain-did-drop-the-time-weights-and-unit-fe-and-you-get-sc" class="slide level2 center">
<h2>Set both weights uniform and you get plain DiD; drop the time weights and unit FE and you get SC</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="did-special-case">DiD — special case</h3>
<ul>
<li><span class="math inline">\(\hat{\omega}_i,\ \hat{\lambda}_t\)</span> both <strong>uniform</strong></li>
<li>unit FE <span class="math inline">\(\alpha_i\)</span> <strong>kept</strong></li>
<li>credibility rests on parallel trends vs.&nbsp;<em>all</em> controls</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="sc-special-case">SC — special case</h3>
<ul>
<li><span class="math inline">\(\hat{\omega}_i\)</span> <strong>optimized</strong>, no <span class="math inline">\(\hat{\lambda}_t\)</span></li>
<li>unit FE <span class="math inline">\(\alpha_i\)</span> <strong>dropped</strong></li>
<li>must match California’s <em>level</em> <strong>and</strong> trend</li>
</ul>
</div></div>
<p><span class="comment">SDID keeps the best of both: optimized <span class="math inline">\(\hat{\omega}_i\)</span> <em>and</em> <span class="math inline">\(\hat{\lambda}_t\)</span>, with the unit FE retained — match the trend, allow a level gap.</span></p>
<aside class="notes">
<p>DiD is just two-way fixed effects — uniform everything. SC keeps unit weights but, by dropping the unit fixed effect, must reproduce California’s level outright, a demanding requirement and the reason SC sometimes cannot find a good fit. The contrast is genuinely inseparable, which is why it earns a two-column slide.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="unit-weights-make-the-synthetic-track-californias-pre-period-path" class="slide level2 center">
<h2>Unit weights make the synthetic track California’s pre-period path</h2>
<p><span class="math display">\[\hat{\omega}^{sdid} = \underset{\omega \in \Omega}{\arg\min} \sum_{t=1}^{T_{pre}} \left(\omega_0 + \sum_{i=1}^{N_{co}} \omega_i\, Y_{it} - \frac{1}{N_{tr}} \sum_{i=N_{co}+1}^{N} Y_{it}\right)^{2} + \zeta^{2}\, T_{pre}\, \lVert \omega \rVert_2^{2}\]</span></p>
<p><span class="comment">The intercept <span class="math inline">\(\omega_0\)</span> lets SDID match California’s <em>trend</em> without matching its <em>level</em>. The ridge penalty <span class="math inline">\(\zeta^{2} T_{pre} \lVert \omega \rVert_2^{2}\)</span> spreads weight across donors instead of betting on one or two.</span></p>
<aside class="notes">
<p>Choose nonnegative weights summing to one (the set Ω) so the weighted control outcome, plus an intercept, comes as close as possible to California in every pre-treatment year. The penalty is what makes SDID’s weights diffuse compared to classic SC — a deliberate trade of a little pre-period fit for a more stable comparison group.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="time-weights-are-sdids-signature-which-pre-years-predict-the-post-period" class="slide level2 center">
<h2>Time weights are SDID’s signature: which pre-years predict the post-period?</h2>
<p><span class="math display">\[\hat{\lambda}^{sdid} = \underset{\lambda \in \Lambda}{\arg\min} \sum_{i=1}^{N_{co}} \left(\lambda_0 + \sum_{t=1}^{T_{pre}} \lambda_t\, Y_{it} - \frac{1}{T_{post}} \sum_{t=T_{pre}+1}^{T} Y_{it}\right)^{2} + \zeta_{\lambda}^{2}\, N_{co}\, \lVert \lambda \rVert^{2}\]</span></p>
<p><span class="comment">Find pre-period year weights so the weighted pre-period outcome matches each control’s <em>post-period average</em>. Years that look most like the post-period get the most weight — we will see all of it land on <strong>1986–1988</strong>.</span></p>
<aside class="notes">
<p>This is the mirror image of the unit-weight problem. DiD and SC treat 1972 and 1988 as equally informative; SDID does not. The intuition: smoking behavior in 1972 tells us little about the 1995 counterfactual, while the late 1980s tell us a lot. This is the one ingredient SC lacks entirely.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="against-the-simple-38-state-average-the-22-did-says-27.35-packs" class="slide level2 center">
<h2>Against the simple 38-state average, the 2×2 DiD says −27.35 packs</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Term</th>
<th style="text-align: right;">Coefficient</th>
<th style="text-align: right;">SE</th>
<th style="text-align: center;">Sig. 5%?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>cal#post</code> (DiD)</td>
<td style="text-align: right;"><span class="key">−27.35</span></td>
<td style="text-align: right;">10.91</td>
<td style="text-align: center;">yes</td>
</tr>
<tr class="even">
<td><code>1.post</code></td>
<td style="text-align: right;">−28.51</td>
<td style="text-align: right;">1.75</td>
<td style="text-align: center;">yes</td>
</tr>
<tr class="odd">
<td><code>1.cal</code></td>
<td style="text-align: right;">−14.36</td>
<td style="text-align: right;">6.79</td>
<td style="text-align: center;">yes</td>
</tr>
</tbody>
</table>
<p><span class="comment">The 2×2 DiD: California’s before/after drop (−55.9) minus the controls’ drop (−28.5) = <strong>−27.35</strong> packs.</span></p>
<aside class="notes">
<p>This is the simplest credible estimate — a 2×2 difference-in-differences, computed by hand with reg packspercapita i.cal##i.post. But it trusts parallel trends against the simple average of 38 very different states, and the raw-trends figure already showed California drifting away from that average before 1989. If California was on a steeper path for unrelated reasons, DiD overstates the effect.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-weighted-donor-pool-fits-the-pre-period-almost-perfectly-and-shrinks-the-estimate-to-19.48" class="slide level2 center">
<h2>A weighted donor pool fits the pre-period almost perfectly — and shrinks the estimate to −19.48</h2>

<img data-src="../stata_sdid_sc_path.png" class="r-stretch quarto-figure-center"><p class="caption">Synthetic California (blue dashed) tracks real California (orange) almost perfectly before 1989, then the two separate sharply.</p><aside class="notes">
<p>Synthetic control replaces the simple average with a weighted average chosen to track California before 1989. Pre-period RMSE is 1.66 packs, R² 0.98 — synthetic California reproduces the real one almost exactly. Built from six donors dominated by Utah (0.39), Montana (0.23), Nevada (0.21). The estimate, −19.48, is smaller than the naive DiD: a better comparison group absorbs part of the apparent drop.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-gap-hugs-zero-before-1989-then-opens-to-about-27-by-2000" class="slide level2 center">
<h2>The gap hugs zero before 1989, then opens to about −27 by 2000</h2>

<img data-src="../stata_sdid_sc_gap.png" class="r-stretch quarto-figure-center"><p class="caption">The estimated gap (California minus synthetic) is flat and near zero through 1988 — the pre-period fit is good — then falls steadily to roughly −27 packs by 2000.</p><aside class="notes">
<p>The flat pre-period gap is the whole credibility argument for synthetic control: if the synthetic matches California for nineteen years and then diverges exactly when the policy starts, the divergence is plausibly the policy. Averaged over the post-period, the growing gap gives the −19.5 headline. The compounding gap is consistent with a program whose effect builds over time.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="sdid-matches-the-trend-not-the-level-and-lands-at-15.60" class="slide level2 center">
<h2>SDID matches the <em>trend</em>, not the level — and lands at −15.60</h2>

<img data-src="../stata_sdid_sdid_main.png" class="r-stretch quarto-figure-center"><p class="caption">The SDID diagnostic: California (red) versus the trend-matched synthetic (blue dashed), which sits above California by a roughly constant gap. The green ribbon shows the time weights, concentrated on 1986–1988.</p><aside class="notes">
<p>The synthetic Control line sits above California throughout — SDID does not try to close that level gap because the unit fixed effect absorbs it. What matters is that the two lines stay parallel before 1989 and diverge after. SDID is −15.60, smaller than both DiD (−27.35) and SC (−19.48), roughly a 20% reduction — and the number reported in Arkhangelsky et al.&nbsp;(2021).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="sdid-puts-all-its-pre-period-weight-on-19861988" class="slide level2 center">
<h2>SDID puts <em>all</em> its pre-period weight on 1986–1988</h2>

<img data-src="../stata_sdid_lambda.png" class="r-stretch quarto-figure-center"><p class="caption">SDID’s pre-period time weights fall almost entirely on 1986, 1987, and 1988 (0.37, 0.21, 0.43); the earlier sixteen years get zero.</p><aside class="notes">
<p>Of nineteen pre-policy years, SDID weights only the three most similar to the post-1989 period and zero on 1970–1985. DiD and SC, by contrast, treat 1972 and 1988 as equally informative. This single picture is the clearest statement of what time weights buy you. Unit weights are also diffuse — Nevada 0.12, New Hampshire 0.11, Connecticut 0.08 — spread across roughly twenty states, where synth2 leaned on six.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="one-command-three-estimators-change-only-method" class="slide level2 center">
<h2>One command, three estimators — change only <code>method()</code></h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-code-line-numbers="1|2|3"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb1-1"><a href=""></a>sdid packspercapita state <span class="fu">year</span> treated, method(did)  <span class="kw">vce</span>(noinference) <span class="kw">graph</span></span>
<span id="cb1-2"><a href=""></a>sdid packspercapita state <span class="fu">year</span> treated, method(<span class="kw">sc</span>)   <span class="kw">vce</span>(noinference) <span class="kw">graph</span></span>
<span id="cb1-3"><a href=""></a>sdid packspercapita state <span class="fu">year</span> treated, method(sdid) <span class="kw">vce</span>(noinference) <span class="kw">graph</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><span class="comment"><code>method(did)</code> returns −27.349 — identical to the hand-computed 2×2. <code>method(sc)</code> returns −19.620, essentially the standalone <code>synth2</code>’s −19.481. All three are special cases of one weighted regression.</span></p>
<aside class="notes">
<p>This is Clarke et al.’s (2024) practical payoff: you don’t switch packages or rewrite the model — one option flips the estimator, and estimation, inference (vce), and the diagnostic graph all work identically. The tiny SC gap reflects different regularization: sdid matches the full pre-period path with a ridge penalty, synth2 optimizes Abadie’s predictor-weighting V-matrix. Because the weights are computed once and reused, it is computationally cheap.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="stacked-side-by-side-the-ranking-is-transparent-did-27-sc-19.5-sdid-15.6" class="slide level2 center">
<h2>Stacked side by side, the ranking is transparent: DiD −27, SC −19.5, SDID −15.6</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Method</th>
<th>Command</th>
<th style="text-align: center;">ATT</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Raw 2×2 DiD</td>
<td><code>reg y i.cal##i.post</code></td>
<td style="text-align: center;">−27.35</td>
</tr>
<tr class="even">
<td>DiD (unified)</td>
<td><code>sdid …, method(did)</code></td>
<td style="text-align: center;">−27.35</td>
</tr>
<tr class="odd">
<td>Synthetic control</td>
<td><code>synth2 …</code></td>
<td style="text-align: center;">−19.48</td>
</tr>
<tr class="even">
<td>SC (unified)</td>
<td><code>sdid …, method(sc)</code></td>
<td style="text-align: center;">−19.62</td>
</tr>
<tr class="odd">
<td><strong>SDID</strong></td>
<td><code>sdid …, method(sdid)</code></td>
<td style="text-align: center;"><span class="key"><strong>−15.60</strong></span></td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>The story is consistent — Proposition 99 reduced smoking — but magnitude depends on how the counterfactual is built. The naive DiD is most extreme because its comparison group was already on a different trajectory. SC fixes the comparison group. SDID, by additionally allowing a level gap and weighting the informative late-1980s years, is most conservative. Reasonable methods bracket the truth; SDID’s contribution is robustness to the assumption — exact parallel trends — the others lean on hardest.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="the-resolution" class="title-slide slide level1 divider center" data-background-color="#00d4c8">
<h1>The Resolution</h1>
<p><span class="act">Act III</span></p>
</section>
<section id="sdid-is-the-preferred-single-number-15.60-packs-20-fewer-cigarettes" class="slide level2 center" data-background-color="#141413">
<h2>SDID is the preferred single number: −15.60 packs, ~20% fewer cigarettes</h2>
<p><span class="bignum">−15.60</span></p>
<p><span class="bignum-label"><span class="math inline">\(\hat{\tau}^{sdid}\)</span>, the ATT of Proposition 99 on California · matches Arkhangelsky et al.&nbsp;(2021)</span></p>
<aside class="notes">
<p>Between the no-controls baseline and the kitchen-sink comparison, SDID lands at −15.60 — the most conservative of the three because it leans least on exact parallel trends. It allows a constant level gap (unit FE) and concentrates on the informative late-1980s years. This is the number to report.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="with-one-treated-unit-placebo-is-the-only-valid-inference" class="slide level2 center">
<h2>With one treated unit, placebo is the <em>only</em> valid inference</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="undefined-or-unreliable">Undefined or unreliable</h3>
<ul>
<li><strong>Jackknife</strong> — deletes one unit at a time; deleting California leaves no treated unit</li>
<li><strong>Bootstrap</strong> — needs the number of treated units to grow</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="the-valid-choice">The valid choice</h3>
<ul>
<li><strong>Placebo</strong> — assign the treatment to a <em>control</em> state, re-estimate, repeat</li>
<li>the spread of placebo effects becomes the variance</li>
</ul>
</div></div>
<p><span class="comment">The design forces the method: <span class="math inline">\(N_{tr}=1\)</span> rules out jackknife and bootstrap, leaving the permutation procedure.</span></p>
<aside class="notes">
<p>This is not a free choice. The jackknife is literally undefined here — when it deletes California, the treated-removed estimate does not exist. The bootstrap’s asymptotics require many treated units. The placebo procedure keeps the controls, repeatedly assigns the treatment structure to a control state as a fake treatment, and uses the placebo spread as the variance. Run it with vce(placebo) seed(1213).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-placebo-se-is-9.88-honest-about-how-hard-one-case-is" class="slide level2 center" data-background-color="#141413">
<h2>The placebo SE is 9.88 — honest about how hard one case is</h2>
<p><span class="bignum">9.88</span></p>
<p><span class="bignum-label">placebo standard error · 95% CI [−35.0, 3.8] <em>includes zero</em> (<span class="math inline">\(p = 0.114\)</span> by normal approximation)</span></p>
<aside class="notes">
<p>With a single treated unit and a noisy donor pool, the SDID interval is genuinely wide — by the normal-approximation criterion we cannot reject “no effect” at 5%. This is not a flaw in SDID; it is honesty about the precision available from one case. But the normal approximation is not the sharpest way to use the placebo distribution — that’s the next slide.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-permutation-test-ranks-california-extreme-only-1-of-38-placebos-is-as-large-p-0.026" class="slide level2 center">
<h2>The permutation test ranks California extreme: only 1 of 38 placebos is as large, p = 0.026</h2>

<img data-src="../stata_sdid_placebo_hist.png" class="r-stretch quarto-figure-center"><p class="caption">California’s estimated effect (orange line, −15.6) sits in the extreme left tail of the placebo distribution; almost every control state shows an effect near zero.</p><aside class="notes">
<p>The placebo effects for control states cluster around zero — reassuring, since those states passed no comparable policy — while California’s −15.6 lands far in the left tail. Only 1 of 38 controls produced an effect as large in magnitude, a permutation p-value of 0.026. The two inferential lenses are complementary: the rank-based test says the drop is very unlikely to be noise (significant at 5%), while the conservative interval reminds us the precision of the magnitude is limited. Report both.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-strongest-objection-and-the-answer" class="slide level2 center">
<h2>The strongest objection — and the answer</h2>
<p><span class="objection">Objection.</span> SDID’s interval includes zero, so we cannot even be sure Proposition 99 did anything.</p>
<div class="fragment">
<p><span class="rebuttal">Response.</span> The <em>magnitude</em> is imprecise, but the <em>sign</em> is robust: the permutation test (<span class="math inline">\(p = 0.026\)</span>) ranks California’s drop far in the placebo tail, and all three estimators agree the effect is negative. Wide intervals are the honest price of one treated unit — not evidence of no effect.</p>
<aside class="notes">
<p>Steelman the objection, don’t strawman it. With N_tr = 1 power is inherently limited, and no method escapes that. But the two lenses tell complementary stories — the conservative normal interval is wide while the rank-based test is significant. The right summary reports both rather than cherry-picking. Identification still rests on no California-specific shock in 1989 and no cross-border spillovers; those are arguments to make substantively, not settle statistically.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="let-the-estimator-that-leans-least-on-parallel-trends-choose-your-number." class="slide level2 divider center" data-background-color="#141413">
<h2>Let the estimator that leans <em>least</em> on parallel trends choose your number.</h2>
<aside class="notes">
<p>The single takeaway. Three constructions of the counterfactual bracket “Proposition 99 cut smoking by roughly 16–20 packs per capita per year.” SDID is the preferred single number because, by allowing a constant level gap and up-weighting the informative late-1980s years, it relies least on the exact parallel-trends assumption the others lean on hardest. The natural next step is staggered adoption with many treated units, where bootstrap and jackknife become appropriate.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="slides_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="slides_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="slides_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="slides_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="slides_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="slides_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="slides_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>