* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- wfh_simulated_data.dta ----
use "wfh_simulated_data.dta", clear
label data "Simulated WFH observational cross-section (5,000 employees)"
note _dta: Fully synthetic cross-section of 5,000 employees generated by generate_wfh_data (seed 42). Binary treatment work_from_home, continuous outcome productivity, two confounders (introversion, num_children), and one instrument (subway_disruption). True ATE = 1.0 by construction; the exclusion restriction holds because subway_disruption does not enter the outcome equation.
note work_from_home: Binary treatment: 1 if the employee works from home, 0 if office-based.. Construction: Bernoulli draw with P from logit(-1.5 + 0.3*introversion + 0.2*num_children + 1.0*subway_disruption); non-random (observational) assignment.. Units: 0/1. Source: Simulation
note productivity: Continuous outcome: employee productivity, in points.. Construction: 50 + 1.0*work_from_home + 0.8*introversion - 0.5*num_children + Normal(0,2) noise; the coefficient 1.0 on work_from_home is the true ATE.. Units: points. Source: Simulation
note introversion: Personality trait; higher values = more introverted. A confounder of WFH and productivity.. Construction: Normal(mean=5, sd=1.5) draw. Raises both the probability of WFH (logit coef 0.3) and productivity (outcome coef 0.8).. Units: scale (~0-10). Source: Simulation
note num_children: Count of children in the household. A confounder of WFH and productivity.. Construction: Poisson(lambda=1.5) draw. Raises the probability of WFH (logit coef 0.2) but lowers productivity (outcome coef -0.5).. Units: count. Source: Simulation
note subway_disruption: Binary instrument: 1 if the employee lives near a disrupted subway line. Affects treatment only (exclusion restriction).. Construction: Bernoulli(0.4) draw. Enters the treatment logit (coef 1.0) but NOT the outcome equation, so the exclusion restriction holds by construction.. Units: 0/1. Source: Simulation
save "wfh_simulated_data.dta", replace
