* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- sim_resource_curse.dta ----
use "sim_resource_curse.dta", clear
label data "Simulated district-year panel: resource curse with known ground-truth effects"
note _dta: Balanced annual district panel; 300 synthetic districts across 8 countries, 2003-2012. Four-level treatment (no mining; mining at low/medium/high prices), heavily imbalanced at 85/5/5/5. Outcome is log nighttime lights. Structure mirrors Hodler, Lechner & Raschky (2023); the CIA holds by construction. True ATEs: 1-0=0.25, 2-0=0.30, 3-0=0.55, 2-1=0.05, 3-1=0.30, 3-2=0.25.
note district_id: Synthetic district ID; the panel unit observed across years.. Construction: 1..300, one per district (each district appears in all 10 years).. Units: integer ID. Source: Simulation
note country_id: Country to which the district belongs; used as a first-stage control (W).. Construction: 1..8; districts are nested within 8 countries.. Units: integer ID. Source: Simulation
note year: Annual time index; used as a first-stage control (W).. Construction: 2003-2012 (balanced; every district observed in each year).. Units: year. Source: Simulation
note treatment: Four-level discrete treatment: no mining vs mining at low/medium/high mineral prices.. Construction: 0 = no mining; 1/2/3 = mining at low/medium/high prices. Heavily imbalanced (85/5/5/5).. Units: 0-3 (category). Source: Simulation
note mining: Binary flag: whether the district-year has active mining (treatment >= 1).. Construction: 1 if treatment in {1,2,3}, else 0.. Units: 0/1. Source: Simulation
note price_index: Continuous mineral-price index that defines the mining treatment level (0 when no mining).. Construction: 0 for untreated rows; positive and increasing across low/medium/high price levels.. Units: index (>=0). Source: Simulation
note exec_constraints: Institutional-quality measure: strength of constraints on executive power; a hypothesized moderator of the mining effect.. Construction: Discrete 1-6 scale assigned per country/district (X feature).. Units: 1-6 scale. Source: Simulation
note quality_of_govt: Continuous institutional-quality index; an alternative moderator used to cross-validate the executive-constraints finding.. Construction: Country-level index in [0.22, 0.70] (X feature).. Units: 0-1. Source: Simulation
note gdp_pc: District/country GDP per capita; an X heterogeneity feature.. Construction: Country-level value in [500, 5000] (8 distinct values).. Units: US$. Source: Simulation
note elevation: District mean elevation above sea level; a geographic X feature.. Construction: Simulated per district (time-invariant).. Units: meters. Source: Simulation
note temperature: District mean temperature; a geographic X feature.. Construction: Simulated per district (time-invariant).. Units: degrees Celsius. Source: Simulation
note ruggedness: Terrain ruggedness index; a geographic X feature.. Construction: Simulated per district (time-invariant).. Units: index (>=0). Source: Simulation
note distance_capital: Distance from the district to the national capital; a geographic X feature (top heterogeneity splitter by importance).. Construction: Simulated per district (time-invariant).. Units: meters. Source: Simulation
note agri_suitability: Index of land suitability for agriculture; a geographic X feature.. Construction: Simulated per district in [0, ~1] (time-invariant).. Units: 0-1. Source: Simulation
note population: District population; a demographic X feature.. Construction: Simulated per district (time-invariant).. Units: people. Source: Simulation
note ethnic_frac: Index of ethnic/linguistic heterogeneity within the district; a demographic X feature.. Construction: Simulated per district in [~0.20, ~0.90] (time-invariant).. Units: 0-1. Source: Simulation
note ntl_log: Natural log of nighttime light intensity - the headline development outcome.. Construction: Simulated from the DGP: mining base effect + institutional moderation + price premia + mean-zero noise (SD 0.25).. Units: log NTL. Source: Simulation
note conflict: Binary indicator of armed-conflict incidence in the district-year (secondary outcome; not analysed in the post).. Construction: Simulated from a parallel process: mining base 0.70, institutional dampening -0.50, price premia 0.15/0.50, base rate 0.12.. Units: 0/1. Source: Simulation
save "sim_resource_curse.dta", replace
