* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- data.dta ----
use "data.dta", clear
label data "Wide source: SHDI + sub-indices + HDI components (2013 & 2019)"
note _dta: One row per region; each variable appears twice with a year suffix (e.g. edindex2013/edindex2019). South American subset of the Global Data Lab Subnational HDI (Smits & Permanyer 2019).
note GDLcode: Unique identifier of the sub-national region in the Global Data Lab database.. Construction: Assigned by the Global Data Lab (e.g. ARGr101 = a region of Argentina).. Units: code. Source: Global Data Lab
note region: Name of the sub-national region.. Construction: From the Global Data Lab SHDI database.. Units: string. Source: Global Data Lab
note country: Country containing the region (12 South American countries).. Construction: From the Global Data Lab SHDI database.. Units: string. Source: Global Data Lab
note SubContinent: Geographic sub-continent of the region (constant: South America).. Construction: From the Global Data Lab SHDI database; this subset is South America only.. Units: string. Source: Global Data Lab
note shdi2013: Composite Subnational HDI for 2013.. Construction: Geometric mean of the 2013 education, health, and income sub-indices.. Units: 0-1. Source: Global Data Lab
note shdi2019: Composite Subnational HDI for 2019.. Construction: Geometric mean of the 2019 education, health, and income sub-indices.. Units: 0-1. Source: Global Data Lab
note healthindex2013: SHDI health dimension index for 2013.. Construction: Derived from regional life expectancy (Global Data Lab).. Units: 0-1. Source: Global Data Lab
note healthindex2019: SHDI health dimension index for 2019.. Construction: Derived from regional life expectancy (Global Data Lab).. Units: 0-1. Source: Global Data Lab
note incindex2013: SHDI income dimension index for 2013.. Construction: Derived from log GNI per capita (Global Data Lab).. Units: 0-1. Source: Global Data Lab
note incindex2019: SHDI income dimension index for 2019.. Construction: Derived from log GNI per capita (Global Data Lab).. Units: 0-1. Source: Global Data Lab
note edindex2013: SHDI education dimension index for 2013.. Construction: Derived from expected and mean years of schooling (Global Data Lab).. Units: 0-1. Source: Global Data Lab
note edindex2019: SHDI education dimension index for 2019.. Construction: Derived from expected and mean years of schooling (Global Data Lab).. Units: 0-1. Source: Global Data Lab
note esch2013: Expected years of schooling for a school-entry-age child (2013).. Construction: Global Data Lab education component.. Units: years. Source: Global Data Lab
note esch2019: Expected years of schooling for a school-entry-age child (2019).. Construction: Global Data Lab education component.. Units: years. Source: Global Data Lab
note msch2013: Mean years of schooling of the adult population (2013).. Construction: Global Data Lab education component.. Units: years. Source: Global Data Lab
note msch2019: Mean years of schooling of the adult population (2019).. Construction: Global Data Lab education component.. Units: years. Source: Global Data Lab
note lifexp2013: Life expectancy at birth in years (2013); basis of the health sub-index.. Construction: Global Data Lab health component.. Units: years. Source: Global Data Lab
note lifexp2019: Life expectancy at birth in years (2019); basis of the health sub-index.. Construction: Global Data Lab health component.. Units: years. Source: Global Data Lab
note gnic2013: Gross National Income per capita (2013); basis of the income sub-index.. Construction: Global Data Lab income component, in 2011 PPP US$.. Units: 2011 PPP US$. Source: Global Data Lab
note gnic2019: Gross National Income per capita (2019); basis of the income sub-index.. Construction: Global Data Lab income component, in 2011 PPP US$.. Units: 2011 PPP US$. Source: Global Data Lab
note lgnic2013: Natural log of GNI per capita (2013); used to build the income sub-index.. Construction: log(gnic2013).. Units: log 2011 PPP US$. Source: Global Data Lab
note lgnic2019: Natural log of GNI per capita (2019); used to build the income sub-index.. Construction: log(gnic2019).. Units: log 2011 PPP US$. Source: Global Data Lab
note pop2013: Regional population in 2013.. Construction: Global Data Lab population estimate.. Units: thousands of persons. Source: Global Data Lab
note pop2019: Regional population in 2019.. Construction: Global Data Lab population estimate.. Units: thousands of persons. Source: Global Data Lab
save "data.dta", replace

* ---- data_long.dta ----
use "data_long.dta", clear
label data "Long panel: 3 sub-indices used by the pooled PCA (153 x 2 periods)"
note _dta: Reshaped from data.csv: each region x year is a row; sub-indices and SHDI rounded to 4 dp, pop to 1 dp; adds a region_country display label.
note GDLcode: Unique identifier of the sub-national region in the Global Data Lab database.. Construction: Assigned by the Global Data Lab (e.g. ARGr101 = a region of Argentina).. Units: code. Source: Global Data Lab
note region: Name of the sub-national region.. Construction: From the Global Data Lab SHDI database.. Units: string. Source: Global Data Lab
note country: Country containing the region (12 South American countries).. Construction: From the Global Data Lab SHDI database.. Units: string. Source: Global Data Lab
note period: Time period of the observation in the long panel (Y2013 or Y2019).. Construction: Created when reshaping wide to long; one row per region per period.. Units: Y2013 / Y2019. Source: Derived (reshape)
note education: SHDI education dimension index (higher = more education).. Construction: Global Data Lab education index from expected & mean years of schooling; long-panel copy of edindex2013/edindex2019, rounded to 4 dp.. Units: 0-1. Source: Global Data Lab
note health: SHDI health dimension index (higher = better health).. Construction: Global Data Lab health index from life expectancy; long-panel copy of healthindex2013/healthindex2019, rounded to 4 dp.. Units: 0-1. Source: Global Data Lab
note income: SHDI income dimension index (higher = higher income).. Construction: Global Data Lab income index from log GNI per capita; long-panel copy of incindex2013/incindex2019, rounded to 4 dp.. Units: 0-1. Source: Global Data Lab
note shdi_official: Global Data Lab's published composite Subnational HDI (validation benchmark).. Construction: Geometric mean of the three sub-indices: (Education x Health x Income)^(1/3); long-panel copy of shdi2013/shdi2019, rounded to 4 dp.. Units: 0-1. Source: Global Data Lab
note pop: Regional population for the period.. Construction: Global Data Lab population; long-panel copy of pop2013/pop2019, rounded to 1 dp.. Units: thousands of persons. Source: Global Data Lab
note region_country: Human-readable label combining a shortened region name with a 3-letter country code.. Construction: First 25 chars of region name + uppercase country abbreviation, e.g. 'City of Buenos Aires (ARG)'.. Units: string. Source: Derived (this study)
save "data_long.dta", replace
