// app.js — wires DOM controls in index.html to dgp/charts modules.
// Runs after window.DGP, window.CHARTS are defined.
//
// Generated by /project:write-app from app.js.tmpl for python_iv.

(function () {
  "use strict";

  // ------------------------------------------------------------------
  // Tab switching.
  // ------------------------------------------------------------------
  function activateTab(paneId) {
    document.querySelectorAll(".tab-strip button").forEach(btn => {
      const isActive = btn.dataset.pane === paneId;
      btn.classList.toggle("active", isActive);
      btn.setAttribute("aria-selected", isActive ? "true" : "false");
    });
    document.querySelectorAll(".tab-pane").forEach(pane => {
      pane.classList.toggle("active", pane.id === paneId);
    });
    window.scrollTo({ top: 0, behavior: "smooth" });
  }
  document.querySelectorAll(".tab-strip button").forEach(btn => {
    btn.addEventListener("click", () => activateTab(btn.dataset.pane));
  });
  document.querySelectorAll(".cta-card").forEach(card => {
    card.addEventListener("click", () => activateTab(card.dataset.goto));
  });

  function debounce(fn, ms) {
    let h = null;
    return function () { clearTimeout(h); h = setTimeout(fn, ms); };
  }

  // ------------------------------------------------------------------
  // IV DGP (inline — dgp.js's simulate_* are for LASSO).
  //   Z ~ N(0, 1)
  //   U ~ N(0, 1)                  (unobserved confounder)
  //   X = pi * Z + gamma * U + v   (endogenous regressor)
  //   Y = beta * X + gamma * U + e (outcome, U also enters Y)
  //   --> Cov(X, U) != 0 makes OLS biased; Z is exogenous of (U, e, v)
  //   so IV recovers beta.
  // ------------------------------------------------------------------
  function simulate_iv(opts) {
    const n = Math.max(20, opts.n | 0);
    const pi = +opts.pi;
    const gamma = +opts.gamma;
    const beta = +opts.beta;
    const seed = opts.seed >>> 0;
    const rng = DGP.mulberry32(seed || 1);
    const normal = DGP.makeNormal(rng);

    const Z = new Float64Array(n);
    const U = new Float64Array(n);
    const X = new Float64Array(n);
    const Y = new Float64Array(n);
    for (let i = 0; i < n; i++) {
      Z[i] = normal();
      U[i] = normal();
      const v = normal();
      const e = normal();
      X[i] = pi * Z[i] + gamma * U[i] + v;
      Y[i] = beta * X[i] + gamma * U[i] + e;
    }
    return { Z, U, X, Y, n, beta_true: beta };
  }

  // OLS slope and intercept of Y on X.
  function ols_xy(X, Y, n) {
    let mx = 0, my = 0;
    for (let i = 0; i < n; i++) { mx += X[i]; my += Y[i]; }
    mx /= n; my /= n;
    let sxy = 0, sxx = 0;
    for (let i = 0; i < n; i++) {
      const dx = X[i] - mx;
      sxy += dx * (Y[i] - my);
      sxx += dx * dx;
    }
    if (sxx < 1e-12) return { slope: NaN, intercept: NaN, se: NaN };
    const slope = sxy / sxx;
    const intercept = my - slope * mx;
    // residual variance
    let rss = 0;
    for (let i = 0; i < n; i++) {
      const r = Y[i] - intercept - slope * X[i];
      rss += r * r;
    }
    const sigma2 = rss / Math.max(1, n - 2);
    const se = Math.sqrt(sigma2 / sxx);
    return { slope, intercept, se };
  }

  // IV (2SLS) slope and intercept: regress X on Z (first stage), then Y on Xhat.
  // For single instrument, beta_IV = cov(Y, Z) / cov(X, Z).
  function iv_yxz(Y, X, Z, n) {
    let my = 0, mx = 0, mz = 0;
    for (let i = 0; i < n; i++) { my += Y[i]; mx += X[i]; mz += Z[i]; }
    my /= n; mx /= n; mz /= n;
    let szy = 0, szx = 0, szz = 0;
    for (let i = 0; i < n; i++) {
      const dz = Z[i] - mz;
      szy += dz * (Y[i] - my);
      szx += dz * (X[i] - mx);
      szz += dz * dz;
    }
    if (Math.abs(szx) < 1e-12 || szz < 1e-12) {
      return { slope: NaN, intercept: NaN, se: NaN, fs_slope: NaN, F: NaN };
    }
    const fs_slope = szx / szz;          // first-stage slope of X on Z
    const slope = szy / szx;              // IV slope
    const intercept = my - slope * mx;
    // SE via classical 2SLS: var(beta_IV) ≈ sigma^2 / (n * var(Xhat))
    // var(Xhat) = fs_slope^2 * var(Z)
    let rss = 0;
    for (let i = 0; i < n; i++) {
      const r = Y[i] - intercept - slope * X[i];
      rss += r * r;
    }
    const sigma2 = rss / Math.max(1, n - 2);
    const varXhat = (fs_slope * fs_slope) * (szz / n);
    const se = Math.sqrt(sigma2 / Math.max(1e-12, n * varXhat));
    // First-stage F: F = (n - 2) * R²_fs / (1 - R²_fs), with R² = szx²/(szz*sxx_resid_of_X_on_const)
    // Simpler: F = (fs_slope^2 * szz) / (residual var of first stage / (n-2))
    let fs_rss = 0;
    const fs_int = mx - fs_slope * mz;
    for (let i = 0; i < n; i++) {
      const r = X[i] - fs_int - fs_slope * Z[i];
      fs_rss += r * r;
    }
    const fs_sigma2 = fs_rss / Math.max(1, n - 2);
    const F = (fs_slope * fs_slope) * szz / Math.max(1e-12, fs_sigma2);
    return { slope, intercept, se, fs_slope, F };
  }

  // ------------------------------------------------------------------
  // TAB 1 — IV concept animation (DAG).
  // ------------------------------------------------------------------
  CHARTS.iv_dag_animation(document.getElementById("intro-anim"));

  // ------------------------------------------------------------------
  // TAB 2 — Instrument strength slider.
  // ------------------------------------------------------------------
  const st = {
    n: 200, pi: 0.80, gamma: 0.60, beta: 0.94, seed: 17,
    chart: CHARTS.ols_vs_iv_chart(document.getElementById("st-chart")),
  };

  function st_refit() {
    const sim = simulate_iv({ n: st.n, pi: st.pi, gamma: st.gamma,
                              beta: st.beta, seed: st.seed });
    const ols = ols_xy(sim.X, sim.Y, sim.n);
    const iv  = iv_yxz(sim.Y, sim.X, sim.Z, sim.n);
    st.sim = sim; st.ols = ols; st.iv = iv;

    // Build (X, Y) points array for the chart
    const points = [];
    for (let i = 0; i < sim.n; i++) points.push([sim.X[i], sim.Y[i]]);
    st.chart.update({
      points,
      ols_slope: ols.slope, ols_int: ols.intercept,
      iv_slope: iv.slope,   iv_int: iv.intercept,
      beta_true: st.beta,
    });

    function fmt(x, dp) {
      return (x === null || Number.isNaN(x) || !Number.isFinite(x))
        ? "—" : x.toFixed(dp);
    }
    document.getElementById("st-ols-b").textContent  = fmt(ols.slope, 3);
    document.getElementById("st-ols-se").textContent = fmt(ols.se, 4);
    document.getElementById("st-iv-b").textContent   = fmt(iv.slope, 3);
    document.getElementById("st-iv-se").textContent  = fmt(iv.se, 4);
    document.getElementById("st-f").textContent      = fmt(iv.F, 2);
    document.getElementById("st-true").textContent   = st.beta.toFixed(2);
  }

  const onStParamChange = debounce(st_refit, 60);
  function bindSlider(id, key, valFmt) {
    document.getElementById(id).addEventListener("input", e => {
      const v = +e.target.value;
      st[key] = v;
      document.getElementById(id + "-val").textContent = valFmt(v);
      onStParamChange();
    });
  }
  bindSlider("st-n",  "n",     v => v);
  bindSlider("st-pi", "pi",    v => v.toFixed(2));
  bindSlider("st-g",  "gamma", v => v.toFixed(2));
  bindSlider("st-b",  "beta",  v => v.toFixed(2));
  document.getElementById("st-reseed").addEventListener("click", () => {
    st.seed = Math.floor(Math.random() * 1e9) + 1;
    st_refit();
  });
  document.getElementById("st-reset").addEventListener("click", () => {
    st.n = 200; st.pi = 0.80; st.gamma = 0.60; st.beta = 0.94; st.seed = 17;
    document.getElementById("st-n").value  = st.n;
    document.getElementById("st-pi").value = st.pi;
    document.getElementById("st-g").value  = st.gamma;
    document.getElementById("st-b").value  = st.beta;
    document.getElementById("st-n-val").textContent  = st.n;
    document.getElementById("st-pi-val").textContent = st.pi.toFixed(2);
    document.getElementById("st-g-val").textContent  = st.gamma.toFixed(2);
    document.getElementById("st-b-val").textContent  = st.beta.toFixed(2);
    st_refit();
  });

  st_refit();

  // ------------------------------------------------------------------
  // TAB 3 — OLS vs IV Monte Carlo simulator.
  // ------------------------------------------------------------------
  const sm = {
    n: 120, pi: 0.70, gamma: 0.80, beta: 0.94, seed: 23,
    hist: CHARTS.iv_vs_ols_histograms(document.getElementById("sm-hist")),
  };

  function sm_single() {
    const sim = simulate_iv({ n: sm.n, pi: sm.pi, gamma: sm.gamma,
                              beta: sm.beta, seed: sm.seed });
    const ols = ols_xy(sim.X, sim.Y, sim.n);
    const iv  = iv_yxz(sim.Y, sim.X, sim.Z, sim.n);
    function fmt(x, dp) {
      return (x === null || Number.isNaN(x) || !Number.isFinite(x))
        ? "—" : x.toFixed(dp);
    }
    document.getElementById("sm-ols-single").textContent = fmt(ols.slope, 3);
    document.getElementById("sm-iv-single").textContent  = fmt(iv.slope, 3);
  }

  function sm_param_change() {
    sm_single();
    // Clear the histogram when params change (forces a fresh run)
    document.getElementById("sm-hist").style.display = "none";
    document.getElementById("sm-ols-mean").textContent = "—";
    document.getElementById("sm-ols-sd").textContent = "—";
    document.getElementById("sm-ols-bias").textContent = "—";
    document.getElementById("sm-iv-mean").textContent = "—";
    document.getElementById("sm-iv-sd").textContent = "—";
    document.getElementById("sm-iv-bias").textContent = "—";
    document.querySelector("#sm-progress > div").style.width = "0%";
    document.getElementById("sm-progress-label").textContent = "";
  }

  const onSmParamChange = debounce(sm_param_change, 80);
  function bindSmSlider(id, key, valFmt) {
    document.getElementById(id).addEventListener("input", e => {
      const v = +e.target.value;
      sm[key] = v;
      document.getElementById(id + "-val").textContent = valFmt(v);
      onSmParamChange();
    });
  }
  bindSmSlider("sm-n",  "n",     v => v);
  bindSmSlider("sm-pi", "pi",    v => v.toFixed(2));
  bindSmSlider("sm-g",  "gamma", v => v.toFixed(2));
  bindSmSlider("sm-b",  "beta",  v => v.toFixed(2));

  document.getElementById("sm-run").addEventListener("click", function () {
    const btn = this;
    btn.disabled = true;
    const progBar = document.querySelector("#sm-progress > div");
    const progLabel = document.getElementById("sm-progress-label");
    const histEl = document.getElementById("sm-hist");

    const N_SIMS = 100;
    const olsArr = [];
    const ivArr  = [];
    let i = 0;
    function step() {
      const batch = 2;
      const end = Math.min(N_SIMS, i + batch);
      for (; i < end; i++) {
        const sim = simulate_iv({
          n: sm.n, pi: sm.pi, gamma: sm.gamma, beta: sm.beta,
          seed: sm.seed + i + 1,
        });
        const ols = ols_xy(sim.X, sim.Y, sim.n);
        const iv  = iv_yxz(sim.Y, sim.X, sim.Z, sim.n);
        if (Number.isFinite(ols.slope)) olsArr.push(ols.slope);
        if (Number.isFinite(iv.slope))  ivArr.push(iv.slope);
      }
      const pct = (i / N_SIMS) * 100;
      progBar.style.width = pct + "%";
      progLabel.textContent = `simulation ${i} / ${N_SIMS}`;
      if (i < N_SIMS) {
        setTimeout(step, 0);
      } else {
        progLabel.textContent = `done (${N_SIMS} simulations)`;
        histEl.style.display = "block";
        sm.hist.update({ ols: olsArr, iv: ivArr, beta_true: sm.beta });

        const meanO = d3.mean(olsArr);
        const meanI = d3.mean(ivArr);
        const sdO   = d3.deviation(olsArr);
        const sdI   = d3.deviation(ivArr);
        function fmt(x, dp) {
          return (x === undefined || x === null || Number.isNaN(x))
            ? "—" : x.toFixed(dp);
        }
        document.getElementById("sm-ols-mean").textContent = fmt(meanO, 3);
        document.getElementById("sm-ols-sd").textContent   = fmt(sdO, 3);
        document.getElementById("sm-ols-bias").textContent = fmt(meanO - sm.beta, 3);
        document.getElementById("sm-iv-mean").textContent  = fmt(meanI, 3);
        document.getElementById("sm-iv-sd").textContent    = fmt(sdI, 3);
        document.getElementById("sm-iv-bias").textContent  = fmt(meanI - sm.beta, 3);
        btn.disabled = false;
      }
    }
    step();
  });

  sm_single();

  // ------------------------------------------------------------------
  // TAB 4 — Forest plot from results.json (post's 14 estimates).
  // ------------------------------------------------------------------
  const fp = {
    chart: CHARTS.forest_plot(document.getElementById("fp-chart")),
    data: null,
  };

  function fp_refresh() {
    if (!fp.data) return;
    const outcomes = Array.from(document.querySelectorAll("#fp-outcomes input:checked")).map(el => el.value);
    const methods  = Array.from(document.querySelectorAll("#fp-methods input:checked")).map(el => el.value);
    fp.chart.update(fp.data.estimates, methods, outcomes);
  }

  document.querySelectorAll("#fp-outcomes input, #fp-methods input").forEach(el => {
    el.addEventListener("change", fp_refresh);
  });

  fetch("data/results.json").then(r => r.json()).then(data => {
    fp.data = data;
    fp_refresh();
  }).catch(err => {
    document.getElementById("fp-chart").innerHTML =
      `<div style="padding:20px;color:#d97757;">Failed to load results.json: ${err}</div>`;
  });

  // ------------------------------------------------------------------
  // Global error handler.
  // ------------------------------------------------------------------
  window.addEventListener("error", function (e) {
    console.error("[write-app] uncaught error:", e.error);
  });
})();
