* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- raw_data.dta ----
use "raw_data.dta", clear
label data "Raw CDC county mortality + ACA expansion timing (uncleaned)"
note _dta: Raw merged input: one row per county-year, 2009-2019. Contains the CDC mortality counts/rates, population denominators, county socioeconomic covariates, and the state ACA-expansion adoption fields. The analysis sample data_prepared.csv is built from this by the post's R script.
note state: Full name of the U.S. state the county belongs to.. Construction: From the CDC mortality file.. Units: string. Source: CDC WONDER
note stfips: Numeric federal (FIPS) identifier for the state (1-56).. Construction: From the CDC mortality file.. Units: FIPS. Source: CDC WONDER
note county: County name followed by its two-letter state abbreviation, e.g. "Autauga County, AL".. Construction: From the CDC mortality file; the trailing two characters give state_abb in the prepared data.. Units: string. Source: CDC WONDER
note county_code: Five-digit federal (FIPS) county identifier; the unit id for the panel.. Construction: From the CDC mortality file.. Units: FIPS. Source: CDC WONDER
note year: Annual time index of the observation.. Construction: From the CDC mortality file (2009-2019).. Units: year. Source: CDC WONDER
note year_code: CDC WONDER's year code; numerically equal to the calendar year here.. Construction: From the CDC mortality file.. Units: year. Source: CDC WONDER
note deaths: Count of deaths among adults aged 20-64 in the county-year.. Construction: From the CDC mortality file (numerator of the crude rate).. Units: count. Source: CDC WONDER
note population_20_64: County adult population aged 20-64 (denominator of the crude mortality rate).. Construction: From the CDC mortality file.. Units: persons. Source: CDC WONDER
note crude_rate_20_64: Deaths per 100,000 adults aged 20-64 - the DiD outcome variable.. Construction: 100,000 x deaths / population_20_64 (as supplied by CDC WONDER).. Units: per 100,000. Source: CDC WONDER
note population_total: Total resident population of the county-year (all ages).. Construction: From the CDC mortality file.. Units: persons. Source: CDC WONDER
note population_20_64_hispanic: Adults aged 20-64 identifying as Hispanic (numerator for perc_hispanic).. Construction: From the CDC mortality file.. Units: persons. Source: CDC WONDER
note population_20_64_female: Female adults aged 20-64 (numerator for perc_female).. Construction: From the CDC mortality file.. Units: persons. Source: CDC WONDER
note population_20_64_white: White adults aged 20-64 (numerator for perc_white).. Construction: From the CDC mortality file.. Units: persons. Source: CDC WONDER
note unemployed: County count of unemployed persons in the labor force.. Construction: From the county labor-market series in the merged file.. Units: persons. Source: BLS (merged)
note labor_force: County civilian labor force count (denominator of the raw unemployment rate).. Construction: From the county labor-market series in the merged file.. Units: persons. Source: BLS (merged)
note unemp_rate: County unemployment rate (baseline covariate).. Construction: Raw fractional rate rescaled to percent (x100) in the prepared data.. Units: %. Source: Derived (BLS)
note poverty_rate: Share of the county population below the federal poverty line.. Construction: From the county socioeconomic series in the merged file (already in percent).. Units: %. Source: Census (merged)
note median_income: County median household income; in the raw file expressed in US$, rescaled to thousands of US$ in the prepared data.. Construction: From the county socioeconomic series; the prepared data divides by 1,000.. Units: US$ (raw) / US$ 000s (prepared). Source: Census (merged)
note expansion_status: Whether the state had adopted and implemented Medicaid expansion.. Construction: From the state ACA-expansion timing source.. Units: category. Source: KFF / ACA timing
note Description: Free-text note on the state's expansion implementation (date, retroactivity, etc.).. Construction: From the state ACA-expansion timing source.. Units: string. Source: KFF / ACA timing
note yaca: Calendar year the state implemented Medicaid expansion; missing (NA) for never-expanders.. Construction: Parsed from the state ACA-expansion timing source; arrives as a string with "NA" sentinels and is coerced to numeric.. Units: year. Source: KFF / ACA timing
note maca: Calendar month (1-12) in which the state implemented expansion; missing for never-expanders.. Construction: Parsed from the state ACA-expansion timing source.. Units: month (1-12). Source: KFF / ACA timing
save "raw_data.dta", replace

* ---- data_prepared.dta ----
use "data_prepared.dta", clear
label data "Balanced county-year analysis panel for the DiD pipeline"
note _dta: Analysis sample: drop the five pre-2014 expanders (DC, DE, MA, NY, VT); keep counties with full mortality coverage 2009-2019 and full covariate coverage in 2013 and 2014. set_wt is the fixed 2013 adult population; treat_year/Treat_2014/Post are the treatment-timing indicators. Cohorts: 1,222 never-expand, 978 in 2014, 171 in 2015, 93 in 2016, 140 in 2019.
note state_abb: Two-letter U.S. state postal abbreviation.. Construction: Last two characters of the county string (str_sub).. Units: code. Source: Derived
note county: County name followed by its two-letter state abbreviation, e.g. "Autauga County, AL".. Construction: From the CDC mortality file; the trailing two characters give state_abb in the prepared data.. Units: string. Source: CDC WONDER
note county_code: Five-digit federal (FIPS) county identifier; the unit id for the panel.. Construction: From the CDC mortality file.. Units: FIPS. Source: CDC WONDER
note year: Annual time index of the observation.. Construction: From the CDC mortality file (2009-2019).. Units: year. Source: CDC WONDER
note population_20_64: County adult population aged 20-64 (denominator of the crude mortality rate).. Construction: From the CDC mortality file.. Units: persons. Source: CDC WONDER
note yaca: Calendar year the state implemented Medicaid expansion; missing (NA) for never-expanders.. Construction: Parsed from the state ACA-expansion timing source; arrives as a string with "NA" sentinels and is coerced to numeric.. Units: year. Source: KFF / ACA timing
note crude_rate_20_64: Deaths per 100,000 adults aged 20-64 - the DiD outcome variable.. Construction: 100,000 x deaths / population_20_64 (as supplied by CDC WONDER).. Units: per 100,000. Source: CDC WONDER
note perc_female: Percent of the county's 20-64 population that is female (baseline covariate).. Construction: 100 x population_20_64_female / population_20_64.. Units: %. Source: Derived (CDC)
note perc_white: Percent of the county's 20-64 population that is white (baseline covariate).. Construction: 100 x population_20_64_white / population_20_64.. Units: %. Source: Derived (CDC)
note perc_hispanic: Percent of the county's 20-64 population that is Hispanic (baseline covariate).. Construction: 100 x population_20_64_hispanic / population_20_64.. Units: %. Source: Derived (CDC)
note unemp_rate: County unemployment rate (baseline covariate).. Construction: Raw fractional rate rescaled to percent (x100) in the prepared data.. Units: %. Source: Derived (BLS)
note poverty_rate: Share of the county population below the federal poverty line.. Construction: From the county socioeconomic series in the merged file (already in percent).. Units: %. Source: Census (merged)
note median_income: County median household income; in the raw file expressed in US$, rescaled to thousands of US$ in the prepared data.. Construction: From the county socioeconomic series; the prepared data divides by 1,000.. Units: US$ (raw) / US$ 000s (prepared). Source: Census (merged)
note set_wt: Each county's 2013 population aged 20-64, held constant across all 11 years (the population weight).. Construction: population_20_64 in 2013, broadcast to every year of the county so weighting does not conflate population growth with mortality change.. Units: persons. Source: Derived (CDC)
note treat_year: Year the county's state expanded Medicaid (2014/2015/2016/2019), or 0 for never-treated counties.. Construction: yaca if 2014 <= yaca <= 2019, else 0 - the did package's never-treated coding.. Units: year / 0. Source: Derived
note Treat_2014: 1 if the county's state expanded Medicaid in 2014, else 0.. Construction: 1 if yaca == 2014, else 0.. Units: 0/1. Source: Derived
note Post: 1 for years 2014 and later, else 0 (the post period in the 2x2 design).. Construction: 1 if year >= 2014, else 0.. Units: 0/1. Source: Derived
save "data_prepared.dta", replace
