<!DOCTYPE html>
<html lang="en"><head>
<script src="slides_files/libs/clipboard/clipboard.min.js"></script>
<script src="slides_files/libs/quarto-html/tabby.min.js"></script>
<script src="slides_files/libs/quarto-html/popper.min.js"></script>
<script src="slides_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="slides_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="slides_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="slides_files/libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="dcterms.date" content="2026-06-11">
  <title>Carbon Taxes and CO2 Emissions</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/theme/quarto-530021870a52ee60b3f5e86ec9e6fece.css">
  <link href="slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Carbon Taxes and CO2 Emissions</h1>
  <p class="subtitle">A synthetic-control analysis of Sweden’s 1991 reform, in Python</p>
  <div class="title-result-strip">
    <div class="kr"><span class="kr-num">−11.3%</span><span class="kr-cap">synthetic Sweden, CO2 per yr</span></div>
    <div class="kr"><span class="kr-num">3×</span><span class="kr-cap">tax vs price response</span></div>
    <div class="kr"><span class="kr-num">6</span><span class="kr-cap">donor countries</span></div>
  </div>
  <p class="author"><a href="https://carlos-mendez.org">Carlos Mendez</a></p>
  <p class="institute">Nagoya University (GSID)</p>
  <p class="date">June 11, 2026</p>
</section>
<section>
<section id="the-tension" class="title-slide slide level1 divider center" data-background-color="#d97757">
<h1>The Tension</h1>
<p><span class="act">Act I</span></p>
</section>
<section id="swedens-emissions-rose-0.55-tcapita-after-the-carbon-tax-or-did-they" class="slide level2 center">
<h2>Sweden’s emissions <em>rose</em> 0.55 t/capita after the carbon tax — or did they?</h2>
<p>In 1991 Sweden put one of the world’s first prices on carbon. A naive before/after says emissions went <strong>up</strong> 0.55 t per capita.</p>
<div class="fragment">
<p>The economy also grew, the fleet changed, oil prices swung. <em>Compared to what would have happened anyway?</em></p>
<aside class="notes">
<p>The central problem of causal inference in one slide. Sweden’s raw post-1990 mean is higher than its pre-1990 mean only because the post window runs to 2005 and the whole economy grew. The naive number is an arithmetic fact and a useless causal answer. We need a counterfactual Sweden — one that never got the tax. That is the entire job of the rest of the deck.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="the-spoiler-sweden-flattens-after-1990-while-its-synthetic-twin-keeps-climbing" class="slide level2 center">
<h2>The spoiler: Sweden flattens after 1990 while its synthetic twin keeps climbing</h2>

<img data-src="../python_sc_co2tax_synth_sweden_fit.png" class="r-stretch quarto-figure-center"><p class="caption">Sweden (actual) vs Synthetic Sweden, a weighted blend of donor countries. Lines overlap before 1990; they split after.</p><aside class="notes">
<p>Don’t explain the construction yet — just plant the picture. Before 1990 the two lines are on top of each other; that is the fit we earn. After 1990 the gap is the effect we will defend with three placebo tests. We come back to this image as the payoff in Act III.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="where-were-going" class="slide level2 center">
<h2>Where we’re going</h2>
<ul>
<li class="fragment">Three estimators, escalating discipline: naive → DiD → synthetic control</li>
<li class="fragment">Building Synthetic Sweden from a donor pool, then reading the gap</li>
<li class="fragment">Three placebo tests: in-time, in-space, leave-one-out</li>
<li class="fragment">Was it just a recession? A second synthetic control on GDP</li>
<li class="fragment">Why consumers responded: tax vs price elasticities (OLS / IV)</li>
</ul>
</section></section>
<section>
<section id="the-investigation" class="title-slide slide level1 divider center" data-background-color="#6a9bcc">
<h1>The Investigation</h1>
<p><span class="act">Act II</span></p>
</section>
<section id="the-lab-15-oecd-economies-46-years-30-of-them-before-the-reform" class="slide level2 center">
<h2>The lab: 15 OECD economies, 46 years, 30 of them before the reform</h2>
<ul>
<li class="fragment"><strong>Outcome</strong> — per-capita transport CO2 in metric tons, 1960–2005</li>
<li class="fragment"><strong>Treated unit</strong> — Sweden; the carbon tax switches on in 1991</li>
<li class="fragment"><strong>Donor pool</strong> — 14 other advanced economies, untreated</li>
<li class="fragment"><strong>Window</strong> — 30 pre-treatment years to fit, 16 post-treatment to measure</li>
</ul>
<p><span class="comment">A long pre-period is a structural advantage: it lets us check the counterfactual <em>before</em> the policy, where we know the gap should be zero.</span></p>
</section>
<section id="the-estimand-is-the-att-how-much-lower-were-swedish-emissions-than-a-no-reform-sweden" class="slide level2 center">
<h2>The estimand is the ATT: how much lower were Swedish emissions than a no-reform Sweden?</h2>
<p><span class="math display">\[\tau_t = Y^{\text{obs}}_{\text{Sweden},t} - \hat Y^{N}_{\text{Sweden},t}, \qquad \hat Y^{N}_{\text{Sweden},t}=\sum_{j=2}^{J+1} w_j\, Y_{jt}\]</span></p>
<p>We never observe <span class="math inline">\(\hat Y^{N}\)</span> — Sweden <em>without</em> the tax. Synthetic control estimates it as a weighted blend of donors.</p>
<p><span class="comment"><span class="math inline">\(Y^{\text{obs}}\)</span> is what happened; <span class="math inline">\(\hat Y^{N}\)</span> is the counterfactual; the gap <span class="math inline">\(\tau_t\)</span> is the treatment effect on the treated.</span></p>
<aside class="notes">
<p>ATT, not ATE: we estimate the effect for the one treated unit, Sweden, not an average over a population. The donor weights w_j are non-negative and sum to one, so the synthetic is a genuine convex combination — an interpolation among real countries, never an extrapolation. That convexity is what makes the method credible.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="did-against-denmark-flips-the-naive-sign-but-parallel-trends-fail-in-the-pre-period" class="slide level2 center">
<h2>DiD against Denmark flips the naive sign — but parallel trends fail in the pre-period</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Comparison</th>
<th style="text-align: right;"><span class="math inline">\(\hat\tau\)</span> (ATT)</th>
<th style="text-align: right;">SE</th>
<th style="text-align: center;"><span class="math inline">\(p\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Naive Sweden pre/post</td>
<td style="text-align: right;">+0.55</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="even">
<td>DiD vs Denmark</td>
<td style="text-align: right;"><span class="key">−0.140</span></td>
<td style="text-align: right;">0.116</td>
<td style="text-align: center;">0.23</td>
</tr>
<tr class="odd">
<td>DiD vs OECD pool (cluster SE)</td>
<td style="text-align: right;">−0.214</td>
<td style="text-align: right;">0.083</td>
<td style="text-align: center;">0.02</td>
</tr>
</tbody>
</table>
<p><span class="comment">Differencing against a control flips +0.55 to negative — but one control is underpowered, and the pre-trends don’t line up.</span></p>
<aside class="notes">
<p>Denmark alone reproduces Andersson’s −0.140 exactly, but p = 0.23: one control is a noisy counterfactual. The full 14-country pool with cluster-robust SEs tightens to −0.214, p = 0.02. The catch: the pre-1990 CO2 plots show Sweden and the OECD mean were not on parallel trends. DiD’s key assumption is visibly violated — which is exactly why we move to synthetic control, which does not need parallel trends, only a good pre-period fit.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="synthetic-control-chooses-the-donor-weights-by-data-under-two-hard-constraints" class="slide level2 center">
<h2>Synthetic control chooses the donor weights by data, under two hard constraints</h2>
<p><span class="math display">\[w^* = \arg\min_{w}\ (X_1 - X_0 w)^\top V (X_1 - X_0 w) \quad \text{s.t.} \quad w_j \geq 0,\ \sum_j w_j = 1\]</span></p>
<p><span class="math inline">\(X_1\)</span> are Sweden’s pre-treatment predictors; <span class="math inline">\(X_0\)</span> the donors’. The optimiser also picks <span class="math inline">\(V\)</span> to minimise pre-period CO2 prediction error.</p>
<p><span class="comment">Non-negative weights that sum to one <span class="math inline">\(\Rightarrow\)</span> the synthetic is a convex blend — no extrapolation, no parallel-trends assumption.</span></p>
<aside class="notes">
<p>Two nested optimisations: pick the donor weights w given the predictor-importance matrix V, then pick V so the resulting synthetic best tracks Sweden’s actual CO2 in the pre-period. The constraints are the whole point — they force the counterfactual to live inside the convex hull of real countries.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="pysyncon-picks-the-same-six-donors-as-anderssons-r-code" class="slide level2 center">
<h2>pysyncon picks the same six donors as Andersson’s R code</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-code-line-numbers="1-3|4-8|9-11|12"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href=""></a>controls <span class="op">=</span> [c <span class="cf">for</span> c <span class="kw">in</span> countries <span class="cf">if</span> c <span class="op">!=</span> <span class="st">"Sweden"</span>]</span>
<span id="cb1-2"><a href=""></a>dataprep <span class="op">=</span> Dataprep(</span>
<span id="cb1-3"><a href=""></a>    foo<span class="op">=</span>panel, dependent<span class="op">=</span><span class="st">"CO2_transport_capita"</span>,</span>
<span id="cb1-4"><a href=""></a>    predictors<span class="op">=</span>[<span class="st">"GDP_per_capita"</span>, <span class="st">"vehicles_capita"</span>,</span>
<span id="cb1-5"><a href=""></a>                <span class="st">"gas_cons_capita"</span>, <span class="st">"urban_pop"</span>],</span>
<span id="cb1-6"><a href=""></a>    treatment_identifier<span class="op">=</span><span class="st">"Sweden"</span>, controls_identifier<span class="op">=</span>controls,</span>
<span id="cb1-7"><a href=""></a>    time_optimize_ssr<span class="op">=</span><span class="bu">range</span>(<span class="dv">1960</span>, <span class="dv">1990</span>),</span>
<span id="cb1-8"><a href=""></a>)</span>
<span id="cb1-9"><a href=""></a>synth <span class="op">=</span> Synth()</span>
<span id="cb1-10"><a href=""></a>synth.fit(dataprep<span class="op">=</span>dataprep, optim_method<span class="op">=</span><span class="st">"Nelder-Mead"</span>)</span>
<span id="cb1-11"><a href=""></a><span class="bu">print</span>(synth.weights().sort_values(ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">6</span>))</span>
<span id="cb1-12"><a href=""></a><span class="co"># Denmark .29 · Belgium .27 · New Zealand .15 · Greece .11 · US .10 · Switzerland .08</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Two objects do all the work: Dataprep packs the panel into the matrices the optimiser needs; Synth.fit runs the nested optimisation. The donor set is identical to Andersson’s R run; the percentage shares differ a little because scipy’s Nelder-Mead and R’s kernlab interior-point solver are different optimisers reaching the same family of solutions.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="six-donors-carry-100-of-the-weight-denmark-and-belgium-dominate" class="slide level2 center">
<h2>Six donors carry 100% of the weight — Denmark and Belgium dominate</h2>

<img data-src="../python_sc_co2tax_synth_weights.png" class="r-stretch quarto-figure-center"><p class="caption">Donor weights for Synthetic Sweden. Six countries share all the weight; the other nine get essentially zero.</p><aside class="notes">
<p>Denmark 29% and Belgium 27% together are over half — small, advanced European economies with Sweden-like income, urbanisation, and energy mix. New Zealand brings the urbanisation match; Greece, the US, and Switzerland fill in. Concentrated weights like these signal a tight fit. Weights spread thinly across many donors would be a red flag that no good counterfactual exists in the pool.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="pre-1990-the-gap-is-near-zero-post-1990-it-widens-monotonically-to-0.36-t" class="slide level2 center">
<h2>Pre-1990 the gap is near zero; post-1990 it widens monotonically to −0.36 t</h2>

<img data-src="../python_sc_co2tax_synth_gap.png" class="r-stretch quarto-figure-center"><p class="caption">Year-by-year gap, Sweden minus Synthetic Sweden. Flat before the reform; a widening wedge after.</p><aside class="notes">
<p>The pre-period gap hugging zero is the validation: the synthetic mimics both the level and the trend of real Swedish emissions before any policy. After 1990 the gap opens steadily — 2005 gap −0.36 t/capita (−15% vs the synthetic level), averaging −0.27 t/capita or −11.3% per year across the post window. About one ton of avoided per-capita CO2 every 3.7 years.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-headline-11.3-per-year-for-16-years" class="slide level2 center" data-background-color="#141413">
<h2>The headline: −11.3% per year for 16 years</h2>
<p><span class="bignum">−11.3%</span></p>
<p><span class="bignum-label">average annual gap, Synthetic Sweden, 1990–2005 (2005 gap −0.36 t/capita, −15%)</span></p>
<aside class="notes">
<p>This is the central estimate. It sits between the no-controls baseline and the noisy DiD numbers, and it matches Andersson’s reported range and the R tutor’s −10.9% within rounding. But the SCM optimiser is designed to make the treated unit look unique post-period — so a number alone is not enough. Placebo tests are the price of admission.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="falsification-1-backdate-the-reform-to-1980-and-no-fake-gap-appears" class="slide level2 center">
<h2>Falsification 1 — backdate the reform to 1980 and no fake gap appears</h2>

<img data-src="../python_sc_co2tax_placebo_in_time.png" class="r-stretch quarto-figure-center"><p class="caption">In-time placebo: fit as if the tax arrived in 1980. Sweden and its synthetic stay locked together.</p><aside class="notes">
<p>We re-fit using only pre-1980 data and pretend the reform happened in 1980. If the SCM manufactured gaps from noise, one would show up here. It doesn’t — Sweden tracks its synthetic through 1990 with no divergence at the placebo date. The method does not invent gaps where no policy exists.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="falsification-2-swedens-gap-beats-14-of-15-placebo-countries-p-0.067" class="slide level2 center">
<h2>Falsification 2 — Sweden’s gap beats 14 of 15 placebo countries, p = 0.067</h2>

<img data-src="../python_sc_co2tax_placebo_in_space.png" class="r-stretch quarto-figure-center"><p class="caption">In-space placebos: re-run the SCM pretending each donor was treated. Sweden (bold) sits outside the grey bundle.</p><aside class="notes">
<p>We re-run the whole SCM fifteen times, treating each country as if it were Sweden, and rank by the post-/pre-treatment MSPE ratio — dividing by pre-period fit so badly-fit units don’t get spurious credit. Sweden has the highest ratio of any unit. The permutation p-value is 0.067: only one in fifteen random reassignments is as extreme. With 15 donors, 1/15 ≈ 0.067 is the smallest p the design can deliver — and we hit it.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="falsification-3-drop-any-single-donor-and-the-effect-stays-in-8.813" class="slide level2 center">
<h2>Falsification 3 — drop any single donor and the effect stays in 8.8%–13%</h2>

<img data-src="../python_sc_co2tax_placebo_leave_one_out.png" class="r-stretch quarto-figure-center"><p class="caption">Leave-one-out: Synthetic Sweden recomputed dropping each high-weight donor in turn. All firmly negative.</p><aside class="notes">
<p>Maybe one quirky donor — Denmark — drives everything? We re-fit six times, each excluding one high-weight donor. The reduction ranges from 8.8% (drop Switzerland) to 13% (drop Denmark); all six bracket the headline 11% and stay negative. Even the most conservative exclusion beats the unweighted DiD. The result is not a single-donor artefact. All three falsification tests pass.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="was-it-just-a-recession-synthetic-gdp-overlaps-actual-gdp-within-233-by-2005" class="slide level2 center">
<h2>Was it just a recession? Synthetic GDP overlaps actual GDP within $233 by 2005</h2>

<img data-src="../python_sc_co2tax_gdp_synth.png" class="r-stretch quarto-figure-center"><p class="caption">Sweden’s actual GDP vs a separately-built Synthetic Sweden (GDP). The paths overlap throughout the post-period.</p><aside class="notes">
<p>The standard objection: emissions fell because the early-1990s recession depressed driving, not because of the tax. Two answers. First, the CO2 gap never rebounds when GDP recovers after 1993 — a recession story predicts a rebound. Second, a separate synthetic control with GDP as the outcome (Denmark 61%, Norway 20%, Finland 10%, US 9%) tracks Sweden’s actual GDP to within $233 per capita by 2005, under 1% of the level. No measurable growth penalty. The policy worked and the economy was fine.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="pass-through-is-complete-consumers-paid-1.15-of-every-tax-krona-at-the-pump" class="slide level2 center">
<h2>Pass-through is complete: consumers paid 1.15 of every tax krona at the pump</h2>
<p><span class="math display">\[\Delta p^*_t = \beta_0 + \beta_1\, \Delta \Theta_t + \beta_2\, \Delta T_t + \varepsilon_t, \qquad \hat\beta_2 = 1.15\ (\text{SE } 0.15)\]</span></p>
<p>The 95% CI is roughly <span class="math inline">\([0.85, 1.45]\)</span> — it contains 1. We cannot reject full pass-through.</p>
<p><span class="comment">If oil firms had absorbed the tax, the price signal never reaches drivers. They didn’t — so the behavioural channel is real.</span></p>
<aside class="notes">
<p>Regressing the year-on-year change in the retail price on changes in the oil price and the energy-plus-carbon tax. β₂ = 1.15, statistically indistinguishable from one. Working in first differences strips out time-invariant levels and isolates the response to new tax movements. This matters: the demand elasticities below are responses to a real pump-price change, not to a hidden refiner absorption.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="consumers-respond-3-more-strongly-to-a-tax-krona-than-to-a-price-krona" class="slide level2 center">
<h2>Consumers respond ~3× more strongly to a tax krona than to a price krona</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="price-semi-elasticity">Price semi-elasticity</h3>
<ul>
<li><span class="math inline">\(\hat\beta_{\text{price}} = -0.060\)</span></li>
<li>+1 SEK/litre real price <span class="math inline">\(\Rightarrow\)</span> −6% gasoline use</li>
<li>stable across OLS1–OLS4</li>
<li>IV (oil price): −0.064</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="tax-semi-elasticity">Tax semi-elasticity</h3>
<ul>
<li><span class="math inline">\(\hat\beta_{\text{tax}} = -0.186\)</span></li>
<li>+1 SEK/litre real tax <span class="math inline">\(\Rightarrow\)</span> −18.6% gasoline use</li>
<li>stable across OLS1–OLS4</li>
<li>IV: pinned at −0.186</li>
</ul>
</div></div>
<p><span class="comment">Salience + permanence: a tax is announced, debated, and persistent; a price drift is just a number on a billboard.</span></p>
<aside class="notes">
<p>Log-level model, so coefficients are semi-elasticities. The 3-to-1 ratio is the section’s headline behavioural finding, and it barely moves across four nested OLS specs or three IV variants. Newey-West HAC(16) SEs — matching Andersson’s Stata — are actually tighter than HC1 here. Both elasticities stay highly significant.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="iv-barely-moves-ols-and-that-itself-is-informative" class="slide level2 center">
<h2>IV barely moves OLS — and that itself is informative</h2>

<img data-src="../python_sc_co2tax_iv_vs_ols_coefs.png" class="r-stretch quarto-figure-center"><p class="caption">Price and tax semi-elasticities under OLS4 and three IV specifications. The tax coefficient is locked at −0.186.</p><aside class="notes">
<p>We instrument the carbon-tax-exclusive price with the real oil price (Sweden is too small to move world oil) and the real energy tax (set on long policy lead times). The tax elasticity is −0.186 to four decimals across every spec; the price elasticity nudges from −0.060 to −0.064. Had OLS been badly endogenous, IV would have moved it. Andersson’s Wu-Hausman test cannot reject price exogeneity — so we read OLS4 as causal.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-carbon-tax-alone-explains-75-of-the-2005-reform-wedge" class="slide level2 center">
<h2>The carbon tax alone explains ~75% of the 2005 reform wedge</h2>

<img data-src="../python_sc_co2tax_disentangling.png" class="r-stretch quarto-figure-center"><p class="caption">Three counterfactual CO2 paths. The orange-to-blue gap is the carbon-tax-only contribution; orange-to-teal adds the VAT.</p><aside class="notes">
<p>The 1990/91 reform bundled a carbon tax, a new VAT on fuel, and a small energy-tax cut. Using Andersson’s pre-computed counterfactual paths, the carbon-tax-only wedge — between the actual line and the with-VAT-but-no-carbon-tax line — reaches −0.57 t/capita in 2005, about 75% of the total reform gap that year, and averages 9.5% of the no-carbon-tax-with-VAT baseline. The carbon tax does most of the work after 2000, when the rate is ratcheted sharply upward.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="the-resolution" class="title-slide slide level1 divider center" data-background-color="#00d4c8">
<h1>The Resolution</h1>
<p><span class="act">Act III</span></p>
</section>
<section id="one-sentence-the-tax-cut-co2-11-a-year-at-no-measurable-cost-to-growth" class="slide level2 center">
<h2>One sentence: the tax cut CO2 ~11% a year, at no measurable cost to growth</h2>
<table class="caption-top">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Quantity</th>
<th style="text-align: right;">Value</th>
<th>Reading</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Synthetic gap, avg</td>
<td style="text-align: right;"><span class="key">−11.3%</span></td>
<td>CO2 cut ~a tenth, every year, 16 years</td>
</tr>
<tr class="even">
<td>Permutation <span class="math inline">\(p\)</span></td>
<td style="text-align: right;">0.067</td>
<td>1 of 15 placebos is this extreme</td>
</tr>
<tr class="odd">
<td>Leave-one-out</td>
<td style="text-align: right;">8.8%–13%</td>
<td>survives dropping any single donor</td>
</tr>
<tr class="even">
<td>Tax vs price</td>
<td style="text-align: right;">3×</td>
<td>tax bites 3× harder per SEK</td>
</tr>
<tr class="odd">
<td>Synthetic GDP gap</td>
<td style="text-align: right;">&lt; $233/cap</td>
<td>no detectable growth penalty</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Five numbers, five independent pieces of evidence. The effect is large, robust to three falsification tests, not driven by any one donor, mechanistically explained by complete pass-through and a salient-tax response, and free of a growth penalty. This is what a credible synthetic-control case study looks like.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-strongest-objection-and-the-answer" class="slide level2 center">
<h2>The strongest objection — and the answer</h2>
<p><span class="objection">Objection.</span> Sweden is one country, one observation. With 15 donors the smallest possible <span class="math inline">\(p\)</span> is <span class="math inline">\(1/15 \approx 0.067\)</span> — you hit the floor, not a clean rejection. And the analysis stops in 2005.</p>
<div class="fragment">
<p><span class="rebuttal">Response.</span> All true, and stated plainly. But three independent falsifications point the same way, the GDP placebo rules out the recession story, and the demand-side mechanism is identified separately. The design under-claims by construction; the convergence of evidence is the argument, not any single <span class="math inline">\(p\)</span>.</p>
<aside class="notes">
<p>Steelman, don’t strawman. Single-country external validity is genuinely limited; the donor pool caps the p-value; there’s no post-2005 EV-era data. None of this is hidden. The defence is that the SCM gap, three placebos, the GDP counterfactual, and the elasticity mechanism are independent and all agree — and the headline number is robust to every leave-one-out exclusion.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section></section>
<section id="a-salient-persistent-fully-passed-through-carbon-tax-cut-emissions-without-cutting-growth." class="title-slide slide level1 divider center" data-background-color="#141413">
<h1>A salient, persistent, fully passed-through carbon tax cut emissions — without cutting growth.</h1>
<aside class="notes">
<p>The single takeaway, the resolution of the Act-I hook. The naive +0.55 was an illusion of confounding; the disciplined counterfactual reveals a −11.3% reduction that survives every falsification — and the economy was fine. Revenue-neutral tax swaps can deliver real emission cuts even when the average tax burden is unchanged, because the composition of taxes carries more behavioural weight than the level.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="slides_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="slides_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="slides_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="slides_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="slides_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="slides_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="slides_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>