// app.js — wires the DOM controls in index.html to dgp/lasso/charts.
// Generated by /project:write-app for content/post/python_EconML/.
// Runs after window.DGP, window.LASSO, window.CHARTS are defined.

(function () {
  "use strict";

  // ------------------------------------------------------------------
  // Helpers.
  // ------------------------------------------------------------------
  function debounce(fn, ms) {
    let h = null;
    return function () { clearTimeout(h); h = setTimeout(fn, ms); };
  }
  function fmt(x) { return (x === null || x === undefined || Number.isNaN(x)) ? "—" : x.toFixed(3); }
  function fmt4(x) { return (x === null || x === undefined || Number.isNaN(x)) ? "—" : x.toFixed(4); }
  function setText(id, text) {
    const el = document.getElementById(id);
    if (el) el.textContent = text;
  }

  // ------------------------------------------------------------------
  // Tab switching.
  // ------------------------------------------------------------------
  function activateTab(paneId) {
    document.querySelectorAll(".tab-strip button").forEach(btn => {
      const isActive = btn.dataset.pane === paneId;
      btn.classList.toggle("active", isActive);
      btn.setAttribute("aria-selected", isActive ? "true" : "false");
    });
    document.querySelectorAll(".tab-pane").forEach(pane => {
      pane.classList.toggle("active", pane.id === paneId);
    });
    window.scrollTo({ top: 0, behavior: "smooth" });
  }
  document.querySelectorAll(".tab-strip button").forEach(btn => {
    btn.addEventListener("click", () => activateTab(btn.dataset.pane));
  });
  document.querySelectorAll(".cta-card[data-goto]").forEach(card => {
    card.addEventListener("click", () => activateTab(card.dataset.goto));
  });

  // ------------------------------------------------------------------
  // TAB 1 — L1/L2 animation.
  // ------------------------------------------------------------------
  if (document.getElementById("intro-anim")) {
    CHARTS.l1_vs_l2_animation(document.getElementById("intro-anim"));
  }

  // ------------------------------------------------------------------
  // TAB 2 — Shrinkage Lab (penalty slider).
  // ------------------------------------------------------------------
  const lab = {
    n: 200, p: 40, signal: 0.6, lambdaIdx: 40, seed: 1,
    path: null,
    chart: CHARTS.coefficient_path(document.getElementById("lab-path")),
  };

  function lab_refit() {
    const sim = DGP.simulate_lasso({ n: lab.n, p: lab.p, signal: lab.signal, seed: lab.seed });
    lab.sim = sim;
    lab.path = LASSO.lasso_path(sim.X, sim.y, sim.n, sim.p, { nLam: 80, maxIter: 60, tol: 1e-5 });
    lab_render();
  }

  function lab_render() {
    if (!lab.path) return;
    const K = lab.path.lambdas.length;
    const k = Math.max(0, Math.min(K - 1, lab.lambdaIdx));
    const lambda = lab.path.lambdas[k];
    const beta = lab.path.betas[k];
    lab.chart.update(lab.path, lambda);

    setText("lab-l-val", lambda.toExponential(2));
    let nz = 0;
    for (let j = 0; j < beta.length; j++) if (Math.abs(beta[j]) > 1e-9) nz++;
    setText("lab-stat-nz", nz);
    setText("lab-stat-alpha-l", beta[0].toFixed(3));

    // Post-OLS on selected support (treatment column 0 forced in).
    const support = [];
    for (let j = 0; j < beta.length; j++) if (Math.abs(beta[j]) > 1e-9) support.push(j);
    if (!support.includes(0)) support.unshift(0);
    const n = lab.sim.n, p = lab.sim.p;
    const d = new Float64Array(n);
    for (let i = 0; i < n; i++) d[i] = lab.sim.X[i * p + 0];
    const rest = support.filter(j => j !== 0);
    const Xs = LASSO.subset_columns(lab.sim.X, n, p, rest);
    const ols = LASSO.ols_with_treatment(d, Xs, lab.sim.y, n, rest.length);
    setText("lab-stat-alpha-o", ols ? ols.alpha_hat.toFixed(3) : "—");
  }

  const onLabParamChange = debounce(lab_refit, 80);
  document.getElementById("lab-n").addEventListener("input", e => {
    lab.n = +e.target.value;
    setText("lab-n-val", lab.n);
    onLabParamChange();
  });
  document.getElementById("lab-p").addEventListener("input", e => {
    lab.p = +e.target.value;
    setText("lab-p-val", lab.p);
    onLabParamChange();
  });
  document.getElementById("lab-s").addEventListener("input", e => {
    lab.signal = +e.target.value;
    setText("lab-s-val", lab.signal.toFixed(2));
    onLabParamChange();
  });
  document.getElementById("lab-l").addEventListener("input", e => {
    lab.lambdaIdx = +e.target.value;
    lab_render(); // λ change is cheap, no debounce
  });

  // Initial fit.
  lab_refit();

  // ------------------------------------------------------------------
  // TAB 3 — Bias Contest (residualized DML vs Naive on simulated DGP).
  // ------------------------------------------------------------------
  const sh = {
    n: 200, p: 40, signal: 0.5, asymmetry: 0.80, seed: 7,
    cmp: CHARTS.alpha_compare(document.getElementById("sh-compare")),
    hist: CHARTS.alpha_histograms(document.getElementById("sh-hist")),
  };

  function sh_refit() {
    const sim = DGP.simulate_dl({
      n: sh.n, p: sh.p, signal: sh.signal,
      asymmetry: sh.asymmetry, seed: sh.seed,
    });
    sh.sim = sim;
    const rig = LASSO.double_lasso(sim.X, sim.d, sim.y, sim.n, sim.p, "rigorous");
    const cvr = LASSO.double_lasso(sim.X, sim.d, sim.y, sim.n, sim.p, "cv",
                                   { nLam: 50, seed: sh.seed });
    sh.rig = rig;
    sh.cv = cvr;
    sh_render();
  }

  function sh_render() {
    const r = sh.rig, c = sh.cv;
    setText("sh-rig-alpha", fmt(r.alpha_hat));
    setText("sh-rig-se",    fmt4(r.se_alpha));
    setText("sh-rig-iy",    r.n_Iy);
    setText("sh-rig-id",    r.n_Id);
    setText("sh-rig-un",    r.n_union);

    setText("sh-cv-alpha", fmt(c.alpha_hat));
    setText("sh-cv-se",    fmt4(c.se_alpha));
    setText("sh-cv-iy",    c.n_Iy);
    setText("sh-cv-id",    c.n_Id);
    setText("sh-cv-un",    c.n_union);

    sh.cmp.update({
      rigorous: r.alpha_hat,
      cv: c.alpha_hat,
      alpha_true: sh.sim.alpha_true,
    });
  }

  const onShParamChange = debounce(sh_refit, 120);
  document.getElementById("sh-n").addEventListener("input", e => {
    sh.n = +e.target.value;
    setText("sh-n-val", sh.n);
    onShParamChange();
  });
  document.getElementById("sh-p").addEventListener("input", e => {
    sh.p = +e.target.value;
    setText("sh-p-val", sh.p);
    onShParamChange();
  });
  document.getElementById("sh-s").addEventListener("input", e => {
    sh.signal = +e.target.value;
    setText("sh-s-val", sh.signal.toFixed(2));
    onShParamChange();
  });
  document.getElementById("sh-a").addEventListener("input", e => {
    sh.asymmetry = +e.target.value;
    setText("sh-a-val", sh.asymmetry.toFixed(2));
    onShParamChange();
  });

  document.getElementById("sh-run").addEventListener("click", function () {
    const btn = this;
    btn.disabled = true;
    const progBar = document.querySelector("#sh-progress > div");
    const progLabel = document.getElementById("sh-progress-label");
    const histEl = document.getElementById("sh-hist");

    const N_SIMS = 100;
    const alphas_rig = [];
    const alphas_cv = [];

    let i = 0;
    function step() {
      const batch = 2;
      const end = Math.min(N_SIMS, i + batch);
      for (; i < end; i++) {
        const sim = DGP.simulate_dl({
          n: sh.n, p: sh.p, signal: sh.signal,
          asymmetry: sh.asymmetry, seed: sh.seed + i + 1,
        });
        const r = LASSO.double_lasso(sim.X, sim.d, sim.y, sim.n, sim.p, "rigorous");
        const c = LASSO.double_lasso(sim.X, sim.d, sim.y, sim.n, sim.p, "cv",
                                     { nLam: 40, seed: sh.seed + i + 1 });
        if (Number.isFinite(r.alpha_hat)) alphas_rig.push(r.alpha_hat);
        if (Number.isFinite(c.alpha_hat)) alphas_cv.push(c.alpha_hat);
      }
      const pct = (i / N_SIMS) * 100;
      if (progBar) progBar.style.width = pct + "%";
      if (progLabel) progLabel.textContent = `simulation ${i} / ${N_SIMS}`;
      if (i < N_SIMS) {
        setTimeout(step, 0);
      } else {
        if (progLabel) progLabel.textContent = `done (${N_SIMS} simulations)`;
        histEl.style.display = "block";
        sh.hist.update({
          alphas_rig, alphas_cv,
          alpha_true: sh.sim.alpha_true,
        });
        btn.disabled = false;
      }
    }
    step();
  });

  // Initial fit.
  sh_refit();

  // ------------------------------------------------------------------
  // TAB 4 — Forest plot + GATE chart from real EconML output.
  // ------------------------------------------------------------------
  const fp = {
    chart: CHARTS.forest_plot(document.getElementById("fp-chart")),
    gate: CHARTS.gate_lines(document.getElementById("fp-gate")),
    data: null,
  };

  function fp_refresh() {
    if (!fp.data) return;
    const outcomes = Array.from(document.querySelectorAll("#fp-outcomes input:checked")).map(el => el.value);
    const methods  = Array.from(document.querySelectorAll("#fp-methods input:checked")).map(el => el.value);
    fp.chart.update(fp.data.estimates, methods, outcomes);
  }

  document.querySelectorAll("#fp-outcomes input, #fp-methods input").forEach(el => {
    el.addEventListener("change", fp_refresh);
  });

  fetch("data/results.json").then(r => r.json()).then(data => {
    fp.data = data;
    fp_refresh();
    if (data.gate_by_exec) {
      fp.gate.update(data.gate_by_exec);
    }
  }).catch(err => {
    document.getElementById("fp-chart").innerHTML =
      `<div style="padding:20px;color:#d97757;">Failed to load results.json: ${err}</div>`;
  });

  // ------------------------------------------------------------------
  // Global error handler.
  // ------------------------------------------------------------------
  window.addEventListener("error", function (e) {
    console.error("[write-app:python_EconML] uncaught error:", e.error);
  });
})();
