<!DOCTYPE html>
<html lang="en"><head>
<script src="slides_files/libs/clipboard/clipboard.min.js"></script>
<script src="slides_files/libs/quarto-html/tabby.min.js"></script>
<script src="slides_files/libs/quarto-html/popper.min.js"></script>
<script src="slides_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="slides_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="slides_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="slides_files/libs/quarto-html/quarto-syntax-highlighting-dark-f1aadacce99040138bbb613f9330654f.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="dcterms.date" content="2026-10-03">
  <title>Introduction to Difference-in-Differences in Python</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #e1e4e8; background-color: #24292e; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #e1e4e8; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #f97583; } /* Attribute */
    code span.bn { color: #79b8ff; } /* BaseN */
    code span.bu { color: #f97583; } /* BuiltIn */
    code span.cf { color: #f97583; } /* ControlFlow */
    code span.ch { color: #9ecbff; } /* Char */
    code span.cn { color: #79b8ff; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #f97583; } /* DataType */
    code span.dv { color: #79b8ff; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #f97583; font-weight: bold; } /* Extension */
    code span.fl { color: #79b8ff; } /* Float */
    code span.fu { color: #b392f0; } /* Function */
    code span.im { color: #9ecbff; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #f97583; } /* Keyword */
    code span.op { color: #e1e4e8; } /* Operator */
    code span.ot { color: #b392f0; } /* Other */
    code span.pp { color: #f97583; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #79b8ff; } /* SpecialChar */
    code span.ss { color: #9ecbff; } /* SpecialString */
    code span.st { color: #9ecbff; } /* String */
    code span.va { color: #ffab70; } /* Variable */
    code span.vs { color: #9ecbff; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/theme/quarto-db6389aca580c90ada52aff7de3e23ec.css">
  <link href="slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script>
    // MathJax 2 (the reveal math plugin): use the TeX web fonts, never locally installed
    // STIX fonts, whose accent metrics misplace hats and tildes (macOS ships STIX).
    window.MathJax = { "HTML-CSS": { availableFonts: [], preferredFont: null, webFont: "TeX" } };
  </script>
</head>
<body class="quarto-dark">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Introduction to Difference-in-Differences in Python</h1>
  <p class="subtitle">Does after-school tutoring raise GPA? Separating the program from the trend</p>
  <div class="title-result-strip">
    <div class="kr"><span class="kr-num">25.32</span><span class="kr-cap">ATT · GPA points (DiD)</span></div>
    <div class="kr"><span class="kr-num">+43%</span><span class="kr-cap">naive overstates the DiD effect</span></div>
    <div class="kr"><span class="kr-num">0</span><span class="kr-cap">significant pre-trends</span></div>
  </div>
  <p class="author"><a href="https://carlos-mendez.org">Carlos Mendez</a></p>
  <p class="institute">Nagoya University (GSID)</p>
  <p class="date">October 3, 2026</p>
</section>
<section>
<section id="the-tension" class="title-slide slide level1 divider center" data-background-color="#d97757">
<h1>The Tension</h1>
<p><span class="act">Act I</span></p>
</section>
<section id="tutored-schools-gpa-jumped-36-points-case-closed" class="slide level2 center">
<h2>Tutored schools’ GPA jumped 36 points — case closed?</h2>
<p>A district launched after-school tutoring in <strong>10 of its 35 high schools</strong>. One year later, average GPA in those schools rose from <strong>60.17</strong> to <strong>96.37</strong>.</p>
<div class="fragment">
<p>A <strong>36.20-point</strong> leap. <em>But the 25 untreated schools also improved — from 71.22 to 82.10.</em> How much of the jump is really the program?</p>
<aside class="notes">
<p>This is the central hook. The naive before-after story looks like a triumph, but part of the gain is a district-wide trend that would have happened anyway. The whole tutorial exists to separate the program from the trend.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="the-naive-before-after-credits-the-entire-36-point-rise-to-the-program" class="slide level2 center">
<h2>The naive before-after credits the entire 36-point rise to the program</h2>

<img data-src="../did101_its.png" class="r-stretch quarto-figure-center"><p class="caption">Treated-group GPA rising from 60.17 to 96.37: the naive estimator credits the full 36.20-point increase to tutoring, ignoring everything else that changed.</p><aside class="notes">
<p>Plant the suspicion without resolving it. Curriculum reforms, new textbooks, students maturing: any of these could lift GPA in all schools, not just the treated ones. The naive approach conflates the treatment effect with the secular trend.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-plan-from-a-naive-before-after-to-an-8-period-event-study" class="slide level2 center">
<h2>The plan: from a naive before-after to an 8-period event study</h2>
<ul>
<li class="fragment">The lab: 35 schools in 2 periods, a clean 2×2 design</li>
<li class="fragment">Why the naive estimate overstates, and how a comparison group fixes it</li>
<li class="fragment">Manual double-differencing, then OLS and two-way fixed effects in PyFixest</li>
<li class="fragment">Four standard errors: does inference change the verdict?</li>
<li class="fragment">An 8-period event study, then five tempting misreadings</li>
</ul>
<aside class="notes">
<p>Teaching deck, so we signpost. Five “Before you look” slides along the way ask the room to predict before each reveal; on AhaSlides each one is followed by a live quiz.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="the-investigation" class="title-slide slide level1 divider center" data-background-color="#6a9bcc">
<h1>The Investigation</h1>
<p><span class="act">Act II</span></p>
</section>
<section id="a-clean-22-lab-35-schools-2-periods-simultaneous-adoption" class="slide level2 center">
<h2>A clean 2×2 lab: 35 schools, 2 periods, simultaneous adoption</h2>

<img data-src="../did101_panelview.png" class="r-stretch quarto-figure-center"><p class="caption">Panel structure: 10 treated schools (orange) switch on after the intervention; 25 comparison schools (steel blue) never do. Timing is simultaneous and treatment, once on, stays on.</p><aside class="notes">
<p>The simulated case study from Corral and Yang (2024): 70 observations (35 schools × 2 periods); the outcome is the average GPA of low-income students. A textbook 2×2: all 10 treated schools (ids 26–35) adopt at the same moment, no school drops out of treatment, perfectly balanced. The cleanliness is deliberate: it isolates the DiD logic.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="before-you-look-what-happened-in-the-schools-without-tutoring" class="slide level2 center" data-background-color="#1a3a8a">
<h2>Before you look: what happened in the schools <em>without</em> tutoring?</h2>
<p>Tutored schools rose 36.20 points. What did the 25 comparison schools do, and where does that leave DiD?</p>
<p><strong>A.</strong>&nbsp; They stayed flat, so DiD is about 36</p>
<p><strong>B.</strong>&nbsp; They rose by about 11 points, so DiD is about 25</p>
<p><strong>C.</strong>&nbsp; They fell, so DiD is larger than 36</p>
<aside class="notes">
<p>Ask the room to commit before the means table. Give 20 seconds, then take the vote. Answer on the next slide: B. Comparison schools rose by 10.88 points (71.22 to 82.10) with no program at all; that region-wide drift is part of the treated schools’ 36.20 too, so the DiD effect is 36.20 − 10.88 = 25.32. (AhaSlides interactive I1 follows.)</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-comparison-group-reveals-an-11-point-trend-the-program-never-caused" class="slide level2 center">
<h2>The comparison group reveals an 11-point trend the program never caused</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Group</th>
<th style="text-align: right;">Pre</th>
<th style="text-align: right;">Post</th>
<th style="text-align: right;">Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Comparison (25)</td>
<td style="text-align: right;">71.22</td>
<td style="text-align: right;">82.10</td>
<td style="text-align: right;"><span class="key">+10.88</span></td>
</tr>
<tr class="even">
<td>Treated (10)</td>
<td style="text-align: right;">60.17</td>
<td style="text-align: right;">96.37</td>
<td style="text-align: right;">+36.20</td>
</tr>
</tbody>
</table>
<p><span class="takeaway fragment">The comparison group’s +10.88 is the secular trend: the rise that would have happened anyway.</span></p>
<aside class="notes">
<p>The answer to the vote: B. The comparison schools never got tutoring, yet their GPA still rose 10.88 points. Under parallel trends we assume the treated schools would have drifted by the same amount without the program. That single number is what the naive estimator wrongly handed to the program.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="did-is-a-double-difference-36.20-minus-10.88-equals-25.32" class="slide level2 center">
<h2>DiD is a double difference: 36.20 minus 10.88 equals 25.32</h2>
<p><span class="math display">\[DiD = \Big(\bar{Y}^{post}_{treat} - \bar{Y}^{pre}_{treat}\Big) - \Big(\bar{Y}^{post}_{ctrl} - \bar{Y}^{pre}_{ctrl}\Big)\]</span></p>
<p><span class="math display">\[DiD = (96.37 - 60.17) - (82.10 - 71.22) = 36.20 - 10.88 = 25.32\]</span></p>
<p><span class="takeaway fragment">Subtract the trend the comparison group reveals; what is left is the program’s effect.</span></p>
<aside class="notes">
<p>The treated runner sped up by 36.20 units; the comparison runner by 10.88. The coaching effect is the extra 25.32 units only the coached runner gained. Rounding note: 25.32 is the arithmetic on means rounded to two decimals; with unrounded means the DiD is 25.315 (trend 10.886), exactly the regression coefficient on the coming slides. The naive 36.20 overstates 25.32 by 43%.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-counterfactual-where-treated-schools-would-have-landed-without-tutoring" class="slide level2 center">
<h2>The counterfactual: where treated schools would have landed without tutoring</h2>

<img data-src="../did101_counterfactual.png" class="r-stretch quarto-figure-center"><p class="caption">Three lines: comparison (steel, 71.22→82.10), treated (orange, 60.17→96.37) and the counterfactual (teal dashed, 60.17→71.05). The 25.32 gap between the actual and counterfactual treated outcome is the ATT.</p><aside class="notes">
<p>The counterfactual is the treated pre-period level (60.17) plus the comparison group’s change (10.88) = 71.05: where treated schools would be if they had only drifted with the trend. The actual post mean is 96.37; the gap of 25.32 is the program’s effect. Parallel trends does not require equal levels (treated schools start lower), only equal trends.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="did-identifies-the-att-not-the-ate-under-parallel-trends" class="slide level2 center">
<h2>DiD identifies the ATT, not the ATE, under parallel trends</h2>
<p><span class="math display">\[E[Y_{i,1}(0) - Y_{i,0}(0) \mid D=1] = E[Y_{i,1}(0) - Y_{i,0}(0) \mid D=0]\]</span></p>
<p>Without the program, both groups would have <em>changed</em> by the same amount.</p>
<p><span class="takeaway fragment">The estimand is the ATT: the average effect for the schools that actually got the program.</span></p>
<aside class="notes">
<p>State the estimand explicitly. DiD recovers the ATT, the effect on the treated, not the ATE. The two diverge when treatment effects vary with selection into treatment. Parallel trends is the identifying assumption, and it concerns an unobserved counterfactual, so no test can prove it. SUTVA (no spillovers between schools) is the other load-bearing assumption.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-treatedpost-interaction-recovers-the-same-25.32-and-every-coefficient-is-a-group-mean" class="slide level2 center">
<h2>A treated×post interaction recovers the same 25.32, and every coefficient is a group mean</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-code-line-numbers="1|2"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href=""></a>fit_ols <span class="op">=</span> pf.feols(<span class="st">"gpa ~ treated + post + txp"</span>, data<span class="op">=</span>df, vcov<span class="op">=</span><span class="st">"HC1"</span>)</span>
<span id="cb1-2"><a href=""></a><span class="bu">print</span>(fit_ols.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<table class="caption-top">
<thead>
<tr class="header">
<th>Coefficient</th>
<th style="text-align: right;">Estimate</th>
<th>Maps to</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td style="text-align: right;">71.215</td>
<td>comparison pre-mean</td>
</tr>
<tr class="even">
<td>treated</td>
<td style="text-align: right;">−11.049</td>
<td>baseline level gap</td>
</tr>
<tr class="odd">
<td>post</td>
<td style="text-align: right;">+10.886</td>
<td>common time trend</td>
</tr>
<tr class="even">
<td>txp</td>
<td style="text-align: right;"><span class="key">25.315</span></td>
<td>the DiD estimate</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>The manual double difference is exactly an OLS regression with a treated dummy, a post dummy and their interaction. Every coefficient is a group mean or a difference of group means; txp = 25.315 is the ATT. HC1 is heteroskedasticity-robust but treats each school’s two observations as independent; the next model clusters by school.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="before-you-look-replace-treated-and-post-with-fixed-effects" class="slide level2 center" data-background-color="#1a3a8a">
<h2>Before you look: replace <code>treated</code> and <code>post</code> with fixed effects</h2>
<p>Swap them for school and period fixed effects, and cluster by school. What changes?</p>
<p><strong>A.</strong>&nbsp; The coefficient stays at 25.315; only the standard error changes</p>
<p><strong>B.</strong>&nbsp; Both the coefficient and the standard error change</p>
<p><strong>C.</strong>&nbsp; Nothing changes: same coefficient, same standard error</p>
<aside class="notes">
<p>Ask: does absorbing the groups and periods with fixed effects move the DiD coefficient? Answer on the next slide: A. In a balanced 2×2 panel the school effects absorb <code>treated</code> and the period effects absorb <code>post</code> without touching the interaction, so the coefficient stays 25.315. The standard error moves from 0.615 (HC1) to 0.585 (clustered by school). (AhaSlides interactive I2 follows.)</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="two-way-fixed-effects-the-same-25.315-now-with-school-clustered-errors" class="slide level2 center">
<h2>Two-way fixed effects: the same 25.315, now with school-clustered errors</h2>
<p><span class="math display">\[Y_{it} = \beta\,(\text{Treat}_i \times \text{Post}_t) + \gamma_i + \vartheta_t + \varepsilon_{it}\]</span></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2" data-code-line-numbers="1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href=""></a>fit_twfe <span class="op">=</span> pf.feols(<span class="st">"gpa ~ txp | id + time"</span>, data<span class="op">=</span>df, vcov<span class="op">=</span>{<span class="st">"CRV1"</span>: <span class="st">"id"</span>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><span class="takeaway fragment">Coefficient unchanged at 25.315; the SE moves from 0.615 (HC1) to 0.585 (clustered by school).</span></p>
<aside class="notes">
<p>The answer to the vote: A. Because treated is collinear with the school fixed effects and post with the period fixed effects, only txp survives, and it is still 25.315. Everything left of the pipe is estimated; everything right of it is absorbed. Clustering by school allows each school’s two observations to be correlated.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="before-you-look-does-female_share-move-the-estimate" class="slide level2 center" data-background-color="#1a3a8a">
<h2>Before you look: does <code>female_share</code> move the estimate?</h2>
<p>The share of female students varies a little within schools. Add it to the model: what happens to 25.315?</p>
<p><strong>A.</strong>&nbsp; It falls by more than one GPA point</p>
<p><strong>B.</strong>&nbsp; It rises by more than one GPA point</p>
<p><strong>C.</strong>&nbsp; It barely moves: less than 0.1 points</p>
<aside class="notes">
<p>Ask the room to commit before the coefficient plot. Answer on the next slide: C. The estimate moves from 25.315 to 25.328, a shift of 0.013, and female_share itself is insignificant (p = 0.714). (AhaSlides interactive I3 follows.)</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="three-specifications-one-answer-25.315-to-25.328" class="slide level2 center">
<h2>Three specifications, one answer: 25.315 to 25.328</h2>

<img data-src="../did101_coefplot.png" class="r-stretch quarto-figure-center"><p class="caption">The txp estimate across OLS/HC1, TWFE/CRV1 and TWFE + covariate/CRV1: all clustered tightly around 25.32, with narrow intervals far from zero.</p><p><span class="takeaway fragment">Stability is the reassuring part; an insignificant covariate does not prove the fixed effects capture everything.</span></p>
<aside class="notes">
<p>The answer to the vote: C. Adding female_share moves the estimate by 0.013 (25.315 to 25.328), and the covariate is insignificant (p = 0.714). The design, not the controls, does the heavy lifting. One caution: a covariate the program itself could change (for example, if tutoring attracted more female students) is a bad control and should be measured before treatment or left out.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="before-you-look-which-standard-error-is-largest" class="slide level2 center" data-background-color="#1a3a8a">
<h2>Before you look: which standard error is largest?</h2>
<p>Same model, same coefficient (25.315), four variance estimators: iid, HC1, CRV1 (clustered by school) and CRV3 (a leave-one-school-out jackknife). Which reports the largest standard error?</p>
<p><strong>A.</strong>&nbsp; iid</p>
<p><strong>B.</strong>&nbsp; HC1</p>
<p><strong>C.</strong>&nbsp; CRV3</p>
<aside class="notes">
<p>Ask: which estimator is the most conservative here? Answer on the next slide: C. CRV3 gives 0.637, then iid 0.607; HC1 and CRV1 are nearly identical at 0.585. None comes close to changing the conclusion: the smallest t-statistic is 39.72. (AhaSlides interactive I4 follows.)</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="inference-choices-barely-move-the-needle-when-the-signal-is-this-strong" class="slide level2 center">
<h2>Inference choices barely move the needle when the signal is this strong</h2>

<img data-src="../did101_se_comparison.png" class="r-stretch quarto-figure-center"><p class="caption">Standard errors across iid, HC1, CRV1 and CRV3. CRV3 is largest (0.637); HC1 and CRV1 are nearly identical (0.585). All four give overwhelmingly significant results.</p><p><span class="takeaway fragment">Here the design, not the variance estimator, decides the verdict: every t-statistic is above 39.</span></p>
<aside class="notes">
<p>The answer to the vote: C. CRV3 re-estimates the model leaving out one school at a time; it corrects CRV1’s tendency to understate uncertainty when clusters are few or influential. What matters is the 10 treated schools, not the 35 clusters: with few treated clusters, prefer CRV3 or the wild cluster bootstrap. With an effect of 25 points, an estimate would need to fall to about 1.2 to 1.3 points before the choice mattered (Exercise 4 in the post).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="the-resolution" class="title-slide slide level1 divider center" data-background-color="#00d4c8">
<h1>The Resolution</h1>
<p><span class="act">Act III</span></p>
</section>
<section id="the-program-raises-gpa-by-25.32-points-not-36.20" class="slide level2 center" data-background-color="#141413">
<h2>The program raises GPA by 25.32 points, not 36.20</h2>
<p><span class="bignum">25.32</span></p>
<p><span class="bignum-label">ATT, stable across specifications (25.315–25.328) · the naive 36.20 overstated it by 43%</span></p>
<aside class="notes">
<p>The Act III payoff. The naive before-after said 36.20; DiD says 25.32. The 10.88-point gap is the secular trend the naive estimator wrongly credited to the program: a 43% overstatement. R² is near 0.995 in the two-way fixed-effects models, unrealistically high because the data are simulated.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-event-study-panel-treatment-switches-on-in-period-5" class="slide level2 center">
<h2>The event-study panel: treatment switches on in period 5</h2>

<img data-src="../did101_panelview_event.png" class="r-stretch quarto-figure-center"><p class="caption">Panel structure for the event study: 35 schools across 8 periods. Treatment begins in period 5; the 10 treated schools switch from light to dark orange, and the 25 comparison schools stay steel blue.</p><aside class="notes">
<p>Four pre-treatment and four post-treatment periods; each of the 10 treated schools contributes one observation per event time. Simultaneous adoption, with no staggering, is what lets this simple event study separate leads from lags cleanly. Comparison schools have no event time; the code gives them a placeholder so they stay in the sample.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="before-you-look-what-should-the-event-study-show" class="slide level2 center" data-background-color="#1a3a8a">
<h2>Before you look: what should the event study show?</h2>
<p>Eight periods, one coefficient per period, each relative to t = −1. If parallel trends holds, what do we see?</p>
<p><strong>A.</strong>&nbsp; Leads near zero; lags jump to about 25 and stay roughly flat</p>
<p><strong>B.</strong>&nbsp; Leads near zero; lags climb steadily from about 10 to about 40</p>
<p><strong>C.</strong>&nbsp; Leads already around 25</p>
<aside class="notes">
<p>Ask: what is the signature of a credible design with this program? Answer on the next slide: A. The leads are 0.34, −0.32 and 0.59 (all p &gt; 0.17); the lags are 25.03, 24.71, 24.77 and 25.70, roughly flat. (AhaSlides interactive I5 follows.)</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="leads-near-zero-and-an-effect-from-the-first-treated-period-a-textbook-event-study" class="slide level2 center">
<h2>Leads near zero and an effect from the first treated period: a textbook event study</h2>

<img data-src="../did101_event_study.png" class="r-stretch quarto-figure-center"><p class="caption">Event-study coefficients by period relative to treatment. Leads (t = −4 to −2) sit near zero with intervals covering zero; lags (t = 0 to 3) jump to about 25 and stay flat.</p><aside class="notes">
<p>The answer to the vote: A. The 8-period extension (280 observations) replaces the single interaction with one coefficient per event time, omitting t = −1 as the reference. The leads are consistent with parallel trends, though no pre-test can prove it. The effect appears at t = 0 relative to t = −1 and holds across all four lags: no build-up, no fade-out.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-numbers-behind-the-picture-quiet-leads-loud-lags" class="slide level2 center">
<h2>The numbers behind the picture: quiet leads, loud lags</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Period</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: center;">95% CI</th>
<th style="text-align: center;">Significant?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>t = −4</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: center;">[−0.47, 1.16]</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="even">
<td>t = −3</td>
<td style="text-align: right;">−0.32</td>
<td style="text-align: center;">[−1.22, 0.57]</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="odd">
<td>t = −2</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: center;">[−0.27, 1.45]</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="even">
<td>t = 0</td>
<td style="text-align: right;"><span class="key">25.03</span></td>
<td style="text-align: center;">[24.12, 25.93]</td>
<td style="text-align: center;">yes</td>
</tr>
<tr class="odd">
<td>t = 3</td>
<td style="text-align: right;">25.70</td>
<td style="text-align: center;">[24.08, 27.32]</td>
<td style="text-align: center;">yes</td>
</tr>
</tbody>
</table>
<p><span class="takeaway fragment">Three near-zero leads are consistent with parallel trends; four large lags trace a stable effect.</span></p>
<aside class="notes">
<p>t = −1 is the omitted reference (normalized to zero). The three leads are small and insignificant, which supports (but cannot prove) the design. The four lags (25.03, 24.71, 24.77, 25.70) are all significant at p &lt; 0.001 and roughly flat: the effect appears in the first treated period and shows no decay over four periods.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="five-tempting-misreadings" class="title-slide slide level1 divider center" data-background-color="#1a3a8a">
<h1>Five tempting misreadings</h1>
<p><span class="act">Common misconceptions</span></p>
<aside class="notes">
<p>DiD looks simple, and that simplicity invites a few recurring misreadings. Each of the next five slides states a tempting claim and answers it with this tutorial’s own numbers.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="insignificant-leads-prove-parallel-trends-they-are-evidence-not-proof" class="slide level2 center">
<h2>“Insignificant leads prove parallel trends”: they are evidence, not proof</h2>
<p><span class="objection">Myth.</span> The leads (0.34, −0.32, 0.59; all p &gt; 0.17) are insignificant, so parallel trends holds.</p>
<div class="fragment">
<p><span class="rebuttal">Truth.</span> Parallel trends concerns an unobserved counterfactual, which no data can show. And pre-tests have little power: a one-point gap would still fit inside the t = −2 interval, [−0.27, 1.45].</p>
<aside class="notes">
<p>Roth (2022), “Pretest with caution”. In the post’s interactive lab, a pre-trend of 0.2 GPA points per period leaves every lead insignificant, yet biases the pooled DiD estimate by +0.70.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="the-groups-must-start-at-the-same-gpa-only-the-trends-must-match" class="slide level2 center">
<h2>“The groups must start at the same GPA”: only the trends must match</h2>
<p><span class="objection">Myth.</span> DiD needs the treated and comparison schools to start from the same level.</p>
<div class="fragment">
<p><span class="rebuttal">Truth.</span> Treated schools start <strong>11.05 points below</strong> comparison schools (60.17 versus 71.22), and DiD is still valid. Differencing removes any gap in levels; only the <em>trends</em> must be parallel.</p>
<aside class="notes">
<p>The <code>treated</code> coefficient in the OLS interaction model is exactly this baseline gap, −11.049. The school fixed effects absorb it in the two-way model.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="is-the-programs-effect-for-every-school-it-is-the-att" class="slide level2 center">
<h2>“25.32 is the program’s effect for every school”: it is the ATT</h2>
<p><span class="objection">Myth.</span> The estimate tells us what tutoring would do in any school.</p>
<div class="fragment">
<p><span class="rebuttal">Truth.</span> DiD identifies the <strong>average effect on the 10 treated schools</strong>. It says nothing about how the 25 comparison schools would have responded, which could differ if schools chose the program because they expected to benefit.</p>
<aside class="notes">
<p>ATT and ATE diverge when the treatment effect varies in ways related to selection into treatment. Report the estimand explicitly.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="adding-controls-always-makes-did-more-credible-design-does-controls-may-not" class="slide level2 center">
<h2>“Adding controls always makes DiD more credible”: design does, controls may not</h2>
<p><span class="objection">Myth.</span> The more covariates, the more believable the estimate.</p>
<div class="fragment">
<p><span class="rebuttal">Truth.</span> Adding <code>female_share</code> moved the estimate by <strong>0.013</strong> (25.315 to 25.328): the credibility comes from the design. A covariate the program itself can change is a <strong>bad control</strong> and can bias the estimate.</p>
<aside class="notes">
<p>Measure time-varying covariates before treatment, or leave them out, whenever the program could plausibly affect them.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="the-se-choice-never-matters-it-can-decide-the-result-for-smaller-effects" class="slide level2 center">
<h2>“The SE choice never matters”: it can decide the result for smaller effects</h2>
<p><span class="objection">Myth.</span> All four standard errors agreed here, so the choice of estimator is irrelevant.</p>
<div class="fragment">
<p><span class="rebuttal">Truth.</span> They agree because the effect is about <strong>40 standard errors</strong> from zero. An estimate of <strong>1.19</strong> points would pass with CRV1 but fail with CRV3 (threshold <strong>1.30</strong>): with small effects, the choice decides the verdict.</p>
<aside class="notes">
<p>Exercise 4 in the post computes these thresholds: 2.03 standard errors with 34 degrees of freedom (35 schools minus one).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="does-precision-make-this-causal-no-the-assumptions-still-carry-it" class="slide level2 center">
<h2>Does precision make this causal? No — the assumptions still carry it</h2>
<p><span class="objection">Objection.</span> The estimate is precise and the pre-trends are flat, so DiD has proven that tutoring caused the gain.</p>
<div class="fragment">
<p><span class="rebuttal">Response.</span> Precision is not identification. The 25.32 ATT rests on <strong>parallel trends</strong> and <strong>SUTVA</strong>; flat pre-trends support them but cannot prove them. The data are <em>simulated</em>: in the field, expect imperfect pre-trends, smaller effects and R² well below 0.99.</p>
<aside class="notes">
<p>Steelman, do not strawman. The event study probes but cannot confirm parallel trends; it only checks the pre-period. SUTVA (no spillovers) is assumed, not tested. With staggered real-world timing and effects that vary across adoption cohorts, the standard TWFE estimator can be badly biased (Goodman-Bacon; Callaway–Sant’Anna; Gardner). This deck evaluates a method on clean data, not a substantive claim about tutoring.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section></section>
<section id="a-credible-comparison-group-not-the-variance-estimator-is-what-makes-the-effect-causal." class="title-slide slide level1 divider center" data-background-color="#141413">
<h1>A credible comparison group, not the variance estimator, is what makes the effect causal.</h1>
<aside class="notes">
<p>The single takeaway. DiD strips the 10.88-point common trend that the naive estimator wrongly credited to the program, leaving a stable 25.32-point ATT. The design (a comparison group, fixed effects, quiet pre-trends) does the work; the choice of standard error is a footnote here, and only here.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="slides_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="slides_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="slides_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="slides_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="slides_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="slides_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="slides_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>