* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- synthetic_panel_2country_intuition.dta ----
use "synthetic_panel_2country_intuition.dta", clear
label data "Two-country intuition panel: treated vs matched control"
note _dta: Two-unit annual panel for the section-3 intuition example. Borealis (control) is the counterfactual by construction; Atlantia (treated) equals it plus an injected effect that turns on in 2012 and grows 1.5 units/year, so the post-2012 gap equals the effect.
note country: Synthetic unit name (panel id).. Construction: Two-country file: 'Atlantia (treated)' / 'Borealis (control)'. Multi-country file: C01-C25 (C01-C05 treated, C06-C25 donors).. Units: string. Source: Simulation
note year: Annual time index.. Construction: Two-country file 2000-2023; multi-country file 1985-2023.. Units: year. Source: Simulation
note outcome: The single observed outcome path for each unit in the intuition example.. Construction: Common trend 40 + 1.2*t + 3*sin(2*pi*t/9) + N(0,0.6); treated also adds the injected post-2012 effect.. Units: index. Source: Simulation
note treat: 1 from the intervention year onward for the treated unit, else 0.. Construction: as.integer(year >= 2012) for Atlantia; 0 for Borealis.. Units: 0/1. Source: Simulation
note role: Whether the unit is the treated unit or the control/counterfactual.. Construction: 'treated' for Atlantia, 'control' for Borealis.. Units: category. Source: Simulation
save "synthetic_panel_2country_intuition.dta", replace

* ---- synthetic_panel_multicountry.dta ----
use "synthetic_panel_multicountry.dta", clear
label data "Reusable 25-country factor-model panel (known effect)"
note _dta: Balanced annual panel of 25 synthetic countries x 39 years = 975 rows. Five treated units (C01-C05) with staggered adoption (2010/2013/2016) and twenty never-treated donors (C06-C25). Built from a three-factor model; ships the true counterfactual and true injected-effect columns for grading.
note country: Synthetic unit name (panel id).. Construction: Two-country file: 'Atlantia (treated)' / 'Borealis (control)'. Multi-country file: C01-C25 (C01-C05 treated, C06-C25 donors).. Units: string. Source: Simulation
note year: Annual time index.. Construction: Two-country file 2000-2023; multi-country file 1985-2023.. Units: year. Source: Simulation
note treated_unit: 1 if the country is ever treated (C01-C05), 0 for a never-treated donor.. Construction: 1 for the five treated units, 0 for the twenty donors.. Units: 0/1. Source: Simulation
note adopt_year: The year treatment switches on for a treated unit; missing for donors.. Construction: C01/C02 2010, C03 2013, C04/C05 2016; NA for donors.. Units: year. Source: Simulation
note treat_ms: 1 from a treated unit's adoption year onward, else 0 (the multisynth treatment column).. Construction: as.integer(year >= adopt_year) for treated units; 0 for donors.. Units: 0/1. Source: Simulation
note gdp_index: The primary observed outcome; for treated units it includes the injected effect.. Construction: Y(0) from a three-factor model (mu + L1*f1 + L2*f2 + L3*f3 + noise) plus the injected effect for treated units.. Units: index. Source: Simulation
note trade_index: A second correlated observed outcome used by augsynth_multiout.. Construction: 0.6*gdp_index_cf + nu + k*f1 + noise, plus 0.6x the gdp injected effect for treated units.. Units: index. Source: Simulation
note gdp_index_cf: The untreated potential outcome for gdp_index - the true counterfactual revealed for grading.. Construction: Y(0) from the factor model, before adding any injected effect (equals gdp_index for donors).. Units: index. Source: Simulation (ground truth)
note trade_index_cf: The untreated potential outcome for trade_index - the true counterfactual revealed for grading.. Construction: Second-outcome Y(0) before adding any injected effect (equals trade_index for donors).. Units: index. Source: Simulation (ground truth)
note true_effect_gdp: The known treatment effect on gdp_index (gdp_index minus gdp_index_cf); 0 before adoption and for donors.. Construction: post*jump + slope*(year - adopt): a jump at adoption plus a yearly ramp.. Units: index units. Source: Simulation (ground truth)
note true_effect_trade: The known treatment effect on trade_index; 0 before adoption and for donors.. Construction: 0.6 * true_effect_gdp.. Units: index units. Source: Simulation (ground truth)
save "synthetic_panel_multicountry.dta", replace
