<!DOCTYPE html>
<html lang="en"><head>
<script src="slides_files/libs/clipboard/clipboard.min.js"></script>
<script src="slides_files/libs/quarto-html/tabby.min.js"></script>
<script src="slides_files/libs/quarto-html/popper.min.js"></script>
<script src="slides_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="slides_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="slides_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="slides_files/libs/quarto-html/quarto-syntax-highlighting-dark-f1aadacce99040138bbb613f9330654f.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="dcterms.date" content="2026-09-28">
  <title>The FWL Theorem: Making Multivariate Regressions Intuitive</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #e1e4e8; background-color: #24292e; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #e1e4e8; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #f97583; } /* Attribute */
    code span.bn { color: #79b8ff; } /* BaseN */
    code span.bu { color: #f97583; } /* BuiltIn */
    code span.cf { color: #f97583; } /* ControlFlow */
    code span.ch { color: #9ecbff; } /* Char */
    code span.cn { color: #79b8ff; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #f97583; } /* DataType */
    code span.dv { color: #79b8ff; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #f97583; font-weight: bold; } /* Extension */
    code span.fl { color: #79b8ff; } /* Float */
    code span.fu { color: #b392f0; } /* Function */
    code span.im { color: #9ecbff; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #f97583; } /* Keyword */
    code span.op { color: #e1e4e8; } /* Operator */
    code span.ot { color: #b392f0; } /* Other */
    code span.pp { color: #f97583; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #79b8ff; } /* SpecialChar */
    code span.ss { color: #9ecbff; } /* SpecialString */
    code span.st { color: #9ecbff; } /* String */
    code span.va { color: #ffab70; } /* Variable */
    code span.vs { color: #9ecbff; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/theme/quarto-9b58ec14c6e77dd4bed0a59f9cec700e.css">
  <link href="slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script>
    // MathJax 2 (the reveal math plugin): use the TeX web fonts, never locally installed
    // STIX fonts, whose accent metrics misplace hats and tildes (macOS ships STIX).
    window.MathJax = { "HTML-CSS": { availableFonts: [], preferredFont: null, webFont: "TeX" } };
  </script>
</head>
<body class="quarto-dark">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">The FWL Theorem: Making Multivariate Regressions Intuitive</h1>
  <p class="subtitle">Partialling-out a confounder to estimate a known +0.2 causal effect</p>
  <div class="title-result-strip">
    <div class="kr"><span class="kr-num">+0.200</span><span class="kr-cap">true coupon effect (ATE)</span></div>
    <div class="kr"><span class="kr-num">+0.267</span><span class="kr-cap">FWL = full OLS, income held fixed</span></div>
    <div class="kr"><span class="kr-num">50</span><span class="kr-cap">simulated stores</span></div>
  </div>
  <p class="author"><a href="https://carlos-mendez.org">Carlos Mendez</a></p>
  <p class="institute">Nagoya University (GSID)</p>
  <p class="date">September 28, 2026</p>
</section>
<section>
<section id="the-tension" class="title-slide slide level1 divider center" data-background-color="#d97757">
<h1>The Tension</h1>
<p><span class="act">Act I</span></p>
</section>
<section id="we-planted-a-0.2-coupon-effect-in-50-stores-will-a-regression-find-it" class="slide level2 center">
<h2>We planted a +0.2 coupon effect in 50 stores — will a regression find it?</h2>
<p>A retail chain hands out discount coupons in 50 stores. <em>Do the coupons increase sales?</em></p>
<div class="fragment">
<p>We simulated the stores, so we know the truth: <strong>+0.2</strong>. <em>Will the simplest regression find it?</em></p>
<aside class="notes">
<p>The hook: one dataset, one question, and — unusually — a known answer. Because we built the data, we can grade every estimator against the truth. Do not reveal the naive result yet; the next slide asks the room to predict it.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="before-you-look-what-sign-will-the-naive-slope-take" class="slide level2 center" data-background-color="#1a3a8a">
<h2>Before you look: what sign will the naive slope take?</h2>
<p>Regress sales on coupons alone, with no controls. The true effect is +0.2.</p>
<p><strong>A.</strong>&nbsp; Positive, close to the true +0.2</p>
<p><strong>B.</strong>&nbsp; Roughly zero</p>
<p><strong>C.</strong>&nbsp; Negative</p>
<aside class="notes">
<p>Ask the room: regress sales on coupons with no controls — what sign does the slope take? Give 20 seconds, then take the vote. Follow-up for the discussion: if it is not +0.2, which variable is to blame? Answer on the next slide: C, negative (−0.1059), because income confounds the comparison. (AhaSlides interactive I1 follows.)</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="naive-regression-coupons-look-like-they-reduce-sales" class="slide level2 center">
<h2>Naive regression: coupons look like they <em>reduce</em> sales</h2>

<img data-src="../fwl_naive_regression.png" class="r-stretch quarto-figure-center"><p class="caption">Daily sales vs.&nbsp;coupon usage across 50 stores. The orange fit slopes down — coupons appear to hurt sales.</p><aside class="notes">
<p>The answer to the vote: negative. The slope is −0.1059 even though we planted +0.2. Don’t explain the mechanism yet — just plant that the raw picture is negative and misleading. Income is the culprit; we earn the reversal in Act II and return to this picture in the side-by-side at the end.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="where-were-going" class="slide level2 center">
<h2>Where we’re going</h2>
<ul>
<li>The setup: a known +0.2 effect, confounded by income</li>
<li>Measure the bias exactly with the OVB identity</li>
<li>The FWL recipe: residualize, residualize, regress</li>
<li>Which shortcuts are safe, and which ones mislead</li>
<li>See the conditional relationship — and the bridge to DML</li>
</ul>
<aside class="notes">
<p>Built from the post’s learning objectives. Teaching deck, so we signpost. Keep it to one breath per line. Six “Before you look” slides along the way ask the room to predict before each reveal.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="the-investigation" class="title-slide slide level1 divider center" data-background-color="#6a9bcc">
<h1>The Investigation</h1>
<p><span class="act">Act II</span></p>
</section>
<section id="income-is-a-confounder-that-opens-a-backdoor-from-coupons-to-sales" class="slide level2 center">
<h2>Income is a confounder that opens a backdoor from coupons to sales</h2>
<div class="columns">
<div class="column" style="width:55%;">
<ul>
<li class="fragment"><strong>Income</strong> → fewer coupons (wealthier stores use fewer)</li>
<li class="fragment"><strong>Income</strong> → more sales (wealthier stores spend more)</li>
<li class="fragment"><strong>Coupons</strong> → sales: true effect <strong>+0.2</strong></li>
</ul>
</div><div class="column" style="width:45%;">
<p><span class="takeaway fragment">The path <code>coupons ← income → sales</code> is non-causal. Leave it open and the negative income→coupon link leaks into the coupon slope.</span></p>
</div></div>
<aside class="notes">
<p>This is the DAG from the post in words. Income drives both the treatment and the outcome — the textbook confounder. Blocking the backdoor means conditioning on income. FWL is the elegant way to do exactly that and to picture it.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-simulated-lab-with-a-known-answer-the-true-effect-is-exactly-0.2" class="slide level2 center">
<h2>A simulated lab with a known answer: the true effect is exactly +0.2</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-code-line-numbers="3-4|5|6-7"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href=""></a><span class="kw">def</span> simulate_store_data(n<span class="op">=</span><span class="dv">50</span>, seed<span class="op">=</span><span class="dv">42</span>):</span>
<span id="cb1-2"><a href=""></a>    rng <span class="op">=</span> np.random.default_rng(seed)</span>
<span id="cb1-3"><a href=""></a>    income    <span class="op">=</span> rng.normal(<span class="dv">50</span>, <span class="dv">10</span>, n)                    <span class="co"># the confounder</span></span>
<span id="cb1-4"><a href=""></a>    dayofweek <span class="op">=</span> rng.integers(<span class="dv">1</span>, <span class="dv">8</span>, n)                    <span class="co"># day of week, 1 to 7</span></span>
<span id="cb1-5"><a href=""></a>    coupons   <span class="op">=</span> <span class="dv">60</span> <span class="op">-</span> <span class="fl">0.5</span> <span class="op">*</span> income <span class="op">+</span> rng.normal(<span class="dv">0</span>, <span class="dv">5</span>, n)  <span class="co"># income → fewer coupons</span></span>
<span id="cb1-6"><a href=""></a>    sales     <span class="op">=</span> (<span class="dv">10</span> <span class="op">+</span> <span class="fl">0.2</span> <span class="op">*</span> coupons <span class="op">+</span> <span class="fl">0.3</span> <span class="op">*</span> income       <span class="co"># true effect = +0.2</span></span>
<span id="cb1-7"><a href=""></a>                 <span class="op">+</span> <span class="fl">0.5</span> <span class="op">*</span> dayofweek <span class="op">+</span> rng.normal(<span class="dv">0</span>, <span class="dv">3</span>, n))</span>
<span id="cb1-8"><a href=""></a>    <span class="cf">return</span> pd.DataFrame(...)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><span class="takeaway fragment">We <em>plant</em> the answer (+0.2) in the data, then check whether each estimator finds it.</span></p>
<aside class="notes">
<p>Why simulate? Because the true causal effect is known by construction — exactly +0.2 — so we can grade every method against ground truth. 50 stores, income centered at $50K. Day of week is drawn uniformly from 1 to 7, independently of income and coupons. Coupons fall with income; sales rise with coupons, income, and day of week. The draw order (income, day of week, coupons, sales) matters for reproducing the seed-42 sample. The full function rounds each column to two decimals before returning the DataFrame.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-naive-slope-is-0.106-and-points-the-wrong-way-p-0.365" class="slide level2 center">
<h2>The naive slope is −0.106 — and points the wrong way (p = 0.365)</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">Coupons coef.</th>
<th style="text-align: right;">SE</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Naive OLS (no controls)</td>
<td style="text-align: right;"><span class="key">−0.1059</span></td>
<td style="text-align: right;">0.1158</td>
<td style="text-align: center;">0.365</td>
</tr>
</tbody>
</table>
<p><span class="takeaway fragment">Not just imprecise — the sign is <em>backwards</em> from the true +0.2. The confounder is pulling it down.</span></p>
<aside class="notes">
<p>Each extra percentage point of coupons is “associated with” $106 less in daily sales — but it is not significant and it contradicts the planted +0.2. Wealthy neighborhoods use fewer coupons yet spend more, so the raw slope inherits income’s negative coupon link. This is the result the controls will fix.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="add-income-as-a-control-and-the-slope-flips-to-0.267-p-0.031" class="slide level2 center">
<h2>Add income as a control and the slope flips to +0.267 (p = 0.031)</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">Coupons coef.</th>
<th style="text-align: right;">Income coef.</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Naive OLS</td>
<td style="text-align: right;">−0.1059</td>
<td style="text-align: right;">—</td>
<td style="text-align: center;">0.365</td>
</tr>
<tr class="even">
<td>Full OLS (+ income)</td>
<td style="text-align: right;"><span class="key">+0.2673</span></td>
<td style="text-align: right;">+0.3836</td>
<td style="text-align: center;">0.031</td>
</tr>
</tbody>
</table>
<p><span class="takeaway fragment">Conditioning on income blocks the backdoor: the estimate jumps to +0.267, close to the true +0.2.</span></p>
<aside class="notes">
<p>One control reverses the conclusion. The CI [0.025, 0.509] now excludes zero. Income itself is strongly positive (+0.3836, p &lt; 0.001), confirming richer stores spend more — call it γ̂; we need it on the next slides. But how big is the bias, exactly, and what is the regression <em>doing</em> when it “controls for” income?</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="before-you-look-which-regression-gives-δ" class="slide level2 center" data-background-color="#1a3a8a">
<h2>Before you look: which regression gives δ̂?</h2>
<p>Gap: <span class="math inline">\(-0.1059 - 0.2673 = -0.3732 = \hat\gamma \times \hat\delta\)</span><br>
Income’s coefficient in the full model: <span class="math inline">\(\hat\gamma = 0.3836\)</span></p>
<p><strong>A.</strong>&nbsp; income on coupons</p>
<p><strong>B.</strong>&nbsp; coupons on income</p>
<p><strong>C.</strong>&nbsp; sales on income</p>
<aside class="notes">
<p>Ask the room: the gap between the naive and the full slope is −0.3732, and it equals γ̂ × δ̂ with γ̂ = 0.3836. Which auxiliary regression supplies δ̂: income on coupons, or coupons on income? Answer on the next slide: A — regress the omitted variable (income) on the treatment (coupons). Its slope, −0.9730, gives 0.3836 × (−0.9730) = −0.3732, the whole gap. The reverse regression (slope −0.3935) gives −0.151 and reconciles nothing. C is the partialling-out regression for sales, a different auxiliary regression altogether. If anyone assumes the two directions are interchangeable, point out that both slopes share the same covariance but divide it by different variances (coupons’ versus income’s), so they differ. (AhaSlides interactive I2 follows.)</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-ovb-identity-accounts-for-the-whole-gap-to-the-last-digit" class="slide level2 center">
<h2>The OVB identity accounts for the whole gap, to the last digit</h2>
<p><span class="math display">\[\underbrace{0.2673}_{\hat\beta_1\ \text{full}} + \underbrace{0.3836}_{\hat\gamma} \times \underbrace{(-0.9730)}_{\hat\delta} = \underbrace{-0.1059}_{\hat\beta_1^{\,\text{naive}}}\]</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Regression</th>
<th style="text-align: right;">Slope</th>
<th style="text-align: right;"><span class="math inline">\(\hat\gamma \times\)</span> slope</th>
<th style="text-align: right;">Implied naive</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>income ~ coupons ✓</td>
<td style="text-align: right;">−0.9730</td>
<td style="text-align: right;">−0.3732</td>
<td style="text-align: right;"><span class="key">−0.1059</span></td>
</tr>
<tr class="even">
<td>coupons ~ income ✗</td>
<td style="text-align: right;">−0.3935</td>
<td style="text-align: right;">−0.151</td>
<td style="text-align: right;">+0.116</td>
</tr>
</tbody>
</table>
<p><span class="takeaway fragment">Omitted variable on the left, treatment on the right — then the bias is measurable, not mysterious.</span></p>
<aside class="notes">
<p>Read the identity aloud: naive slope = full-regression slope + (income’s effect on sales) × (how income moves with coupons). γ̂ &gt; 0 and δ̂ &lt; 0, so the bias is negative — and large enough to flip the sign. The identity is exact in the sample and links the naive slope to the full-regression estimate 0.2673, not to the true 0.2. Direction matters: δ̂ comes from regressing income ON coupons. Flip it (coupons on income, slope −0.3935) and the bias term is −0.151, which would imply a naive slope of +0.116 — not the −0.106 we observe, so it reconciles nothing. Population version: δ = −1.0, so the naive slope converges to 0.2 + 0.3 × (−1.0) = −0.10. More data will not rescue it.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fwl-any-multivariate-coefficient-is-a-univariate-slope-on-residuals" class="slide level2 center">
<h2>FWL: any multivariate coefficient is a univariate slope on residuals</h2>
<p><span class="math display">\[\hat\beta_1^{\mathrm{FWL}}=\frac{\mathrm{Cov}(\tilde y,\ \tilde x_1)}{\mathrm{Var}(\tilde x_1)}\]</span></p>
<p><span class="math inline">\(\tilde x_1\)</span>: coupons with income regressed out. <span class="math inline">\(\tilde y\)</span>: sales with income regressed out.</p>
<p><span class="takeaway fragment">Remove income from coupons, remove income from sales, then regress the leftovers. Same <span class="math inline">\(\hat\beta_1\)</span>.</span></p>
<aside class="notes">
<p>Frisch &amp; Waugh (1933), Lovell (1963); Lovell (2008) gives a short teaching proof. This is an algebraic identity, not an approximation. The tilde is partialling-out: keep only the variation orthogonal to income — uncorrelated with income in the sample, not necessarily independent of it. The intercept counts as one more control. Full OLS and residualize-both return the same coefficient on coupons; we test the residualize-X-only shortcut in a moment.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fwl-by-hand-one-covariance-over-one-variance-returns-0.2673" class="slide level2 center">
<h2>FWL by hand: one covariance over one variance returns 0.2673</h2>
<p><span class="math display">\[\hat\beta_1=\frac{\widehat{\mathrm{Cov}}(\tilde y,\tilde x_1)}{\widehat{\mathrm{Var}}(\tilde x_1)}=\frac{3.9380}{14.7320}=0.2673\]</span></p>
<p><span class="math display">\[M_2 = I_n - X_2(X_2^\top X_2)^{-1}X_2^\top \qquad \hat\beta_1=\frac{x_1^\top M_2\, y}{x_1^\top M_2\, x_1}=0.2673\]</span></p>
<p><span class="comment"><span class="math inline">\(M_2\)</span> is the residual maker: <span class="math inline">\(M_2 X_2 = 0\)</span>, symmetric, idempotent. <span class="math inline">\(X_2\)</span> holds a column of ones and income.</span></p>
<p><span class="takeaway fragment">No regression library needed: plain NumPy returns the same 0.2673.</span></p>
<aside class="notes">
<p>Two residual vectors, one covariance, one variance. Trap: np.cov divides by n − 1 by default, np.var by n unless ddof=1 — mix them and the slope inflates by 50/49 to 0.2728. The matrix form multiplies the raw x1 and y by M2; the matrix does the residualizing inside the product. That is Line 4 of the proof in the post, and it returns 0.2673 once more.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="three-lines-of-statsmodels-reproduce-the-multivariate-coefficient" class="slide level2 center">
<h2>Three lines of statsmodels reproduce the multivariate coefficient</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2" data-code-line-numbers="2|3|5-6"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href=""></a><span class="co"># residualize each variable with respect to income</span></span>
<span id="cb2-2"><a href=""></a>df[<span class="st">"coupons_tilde"</span>] <span class="op">=</span> smf.ols(<span class="st">"coupons ~ income"</span>, df).fit().resid</span>
<span id="cb2-3"><a href=""></a>df[<span class="st">"sales_tilde"</span>]   <span class="op">=</span> smf.ols(<span class="st">"sales ~ income"</span>,   df).fit().resid</span>
<span id="cb2-4"><a href=""></a><span class="co"># regress residual sales on residual coupons (no intercept)</span></span>
<span id="cb2-5"><a href=""></a>fwl <span class="op">=</span> smf.ols(<span class="st">"sales_tilde ~ coupons_tilde - 1"</span>, df).fit()</span>
<span id="cb2-6"><a href=""></a>fwl.params[<span class="st">"coupons_tilde"</span>]   <span class="co"># 0.2673, same as full OLS</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><span class="takeaway fragment">Residuals are mean-zero, so we drop the intercept. The coefficient on <code>coupons_tilde</code> <em>is</em> the controlled effect.</span></p>
<aside class="notes">
<p>The full script is in the post; these are the load-bearing lines. Residualize coupons on income, residualize sales on income, then regress residual on residual without an intercept — both residual series have mean zero. Next, a tempting shortcut: what if we skip residualizing sales and keep the raw outcome?</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="before-you-look-does-the-step-1-shortcut-keep-both-numbers" class="slide level2 center" data-background-color="#1a3a8a">
<h2>Before you look: does the Step 1 shortcut keep both numbers?</h2>
<p>Step 1 regresses <em>raw</em> sales on residualized coupons, with <em>no intercept</em>.</p>
<p><strong>A.</strong>&nbsp; Same coefficient (0.2673) and the same SE, about 0.12</p>
<p><strong>B.</strong>&nbsp; Same coefficient, but a much larger SE</p>
<p><strong>C.</strong>&nbsp; A different coefficient</p>
<aside class="notes">
<p>Ask the room: this regression uses residualized coupons but raw sales, with no intercept. (a) Will the coefficient still be 0.2673? (b) Will the standard error still be about 0.12? Answer on the next slide: B — the coefficient is exactly 0.2673, but the SE jumps to 1.2715. (AhaSlides interactive I3 follows.)</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="step-1-keeps-the-coefficient-but-its-se-balloons-to-1.2715" class="slide level2 center">
<h2>Step 1 keeps the coefficient, but its SE balloons to 1.2715</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Regression</th>
<th style="text-align: right;">Coupons coef.</th>
<th style="text-align: right;">SE</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Full OLS (+ income)</td>
<td style="text-align: right;">+0.2673</td>
<td style="text-align: right;">0.1203</td>
<td style="text-align: center;">0.031</td>
</tr>
<tr class="even">
<td>Step 1 (no intercept)</td>
<td style="text-align: right;">+0.2673</td>
<td style="text-align: right;"><span class="key">1.2715</span></td>
<td style="text-align: center;">0.834</td>
</tr>
</tbody>
</table>
<p><span class="takeaway fragment">Right coefficient, wrong SE: stop here and you would conclude coupons do nothing.</span></p>
<aside class="notes">
<p>The coefficient survives: coupons_tilde is orthogonal to both the constant and income, so x̃₁ᵀy = x̃₁ᵀỹ (corollary (a) of the proof). So all three estimators — full OLS, residualize-X-only, residualize-both — return the same coefficient on coupons. The SE does not: it is more than ten times larger, and p = 0.834. Raw sales is not mean-zero (its mean is 33.61), so dropping the intercept matters a great deal. The next slide takes the jump apart.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="step-1s-se-explodes-because-the-intercept-is-missing" class="slide level2 center">
<h2>Step 1’s SE explodes because the intercept is missing</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Regression (coef. 0.2673 in every row)</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">SSR</th>
<th style="text-align: right;">df</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Step 1, no intercept</td>
<td style="text-align: right;"><span class="key">1.2715</span></td>
<td style="text-align: right;">57,181</td>
<td style="text-align: right;">49</td>
</tr>
<tr class="even">
<td>Step 1 + intercept</td>
<td style="text-align: right;">0.1437</td>
<td style="text-align: right;">715</td>
<td style="text-align: right;">48</td>
</tr>
<tr class="odd">
<td>Step 1, demeaned sales</td>
<td style="text-align: right;">0.1422</td>
<td style="text-align: right;">715</td>
<td style="text-align: right;">49</td>
</tr>
<tr class="even">
<td>Full regression</td>
<td style="text-align: right;">0.1203</td>
<td style="text-align: right;">491</td>
<td style="text-align: right;">47</td>
</tr>
</tbody>
</table>
<p><span class="takeaway fragment">The intercept alone closes 98% of the SE gap; the rest is income still left in sales.</span></p>
<aside class="notes">
<p>Forced through the origin, the Step 1 line must also explain the level of sales, and it cannot: the sales mean of 33.6 stays in the residuals. The SSR is 57,181 without an intercept and 715 with one; the difference equals n × mean(sales)² exactly. In SE levels, (1.2715 − 0.1437) / (1.2715 − 0.1203) = 0.98. Demeaning sales instead of adding an intercept gives 0.1422: the same SSR of 715, divided by 49 instead of 48 (factor √(48/49) = 0.9897). The last step, 0.1437 → 0.1203, is income’s variation still in sales: residualizing sales on income cuts the SSR from 715 to 491.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="before-you-look-will-step-2s-se-equal-the-full-models-0.1203" class="slide level2 center" data-background-color="#1a3a8a">
<h2>Before you look: will Step 2’s SE equal the full model’s 0.1203?</h2>
<p>Step 2 residualizes sales too, then regresses residual on residual, with no intercept.</p>
<p><strong>A.</strong>&nbsp; Yes, exactly 0.1203</p>
<p><strong>B.</strong>&nbsp; Close, but slightly smaller</p>
<p><strong>C.</strong>&nbsp; Close, but slightly larger</p>
<aside class="notes">
<p>Ask the room: Step 2 regresses residualized sales on residualized coupons. Will its standard error equal the full model’s 0.1203? Answer on the next slide: B — 0.1178. Same residuals, but the software divides by 49 degrees of freedom instead of 47. (AhaSlides interactive I4 follows.)</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="step-2-leaves-the-same-residuals-only-the-degrees-of-freedom-differ" class="slide level2 center">
<h2>Step 2 leaves the same residuals — only the degrees of freedom differ</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Regression</th>
<th style="text-align: right;">Coupons coef.</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">Residual df</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Step 2: <span class="math inline">\(\tilde y\)</span> on <span class="math inline">\(\tilde x_1\)</span></td>
<td style="text-align: right;">+0.2673</td>
<td style="text-align: right;">0.1178</td>
<td style="text-align: right;">49</td>
</tr>
<tr class="even">
<td>Full OLS (+ income)</td>
<td style="text-align: right;">+0.2673</td>
<td style="text-align: right;"><span class="key">0.1203</span></td>
<td style="text-align: right;">47</td>
</tr>
</tbody>
</table>
<p><span class="comment">SE ratio <span class="math inline">\(= \sqrt{47/49} = 0.9794\)</span>: the full model spends two df on the intercept and income.</span></p>
<p><span class="takeaway fragment">Same residuals, same coefficient: report the full-model SE, 0.1203.</span></p>
<aside class="notes">
<p>Line 2 of the proof says ỹ = x̃₁β̂₁ + e: the residual-on-residual regression leaves exactly the full model’s residuals, so the SSR is identical (the code check prints “Same residuals: True”). The variance factor is shared too; only the divisor changes, 49 instead of 47. Step 2’s software SE of 0.1178 slightly overstates precision, because the software does not know that two parameters were already estimated in the partialling-out step. Report 0.1203. Either way, the coupon effect is significant.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="partialling-out-drawn-residuals-are-what-a-straight-line-in-income-leaves-over" class="slide level2 center">
<h2>Partialling-out, drawn: residuals are what a straight line in income leaves over</h2>

<img data-src="../fwl_residuals_income.png" class="r-stretch quarto-figure-center"><p class="caption">Coupon usage vs.&nbsp;income; the orange line is the income→coupons fit, dashed lines are the residuals each store keeps.</p><aside class="notes">
<p>Look at the dashed segments first. The downward fit confirms richer stores use fewer coupons. Each dashed line is a residual — how unusual a store’s coupon use is <em>given</em> its income. Partialling-out throws away the line and keeps only those segments: “among similar-income stores, who couponed more or less than expected?” By construction the residuals are uncorrelated with income — not independent of it. A curved dependence on income could still hide in them.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-hidden-positive-relationship-the-table-couldnt-show-you" class="slide level2 center">
<h2>The hidden positive relationship the table couldn’t show you</h2>

<img data-src="../fwl_partialled_out.png" class="r-stretch quarto-figure-center"><p class="caption">Residualized sales vs.&nbsp;residualized coupons. With income removed from both, the slope is the +0.267 conditional effect.</p><aside class="notes">
<p>This is the payoff plot — the conditional relationship a multivariate regression captures but cannot draw. Stores that couponed more than expected also sold more than expected. The slope of this single line is exactly 0.2673, the full-regression coefficient, now visible to a non-technical audience.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="before-you-look-does-adding-the-means-back-change-the-slope" class="slide level2 center" data-background-color="#1a3a8a">
<h2>Before you look: does adding the means back change the slope?</h2>
<p>Shift each residual by its variable’s sample mean. Every point moves up and to the right.</p>
<p><strong>A.</strong>&nbsp; No, the slope is unchanged</p>
<p><strong>B.</strong>&nbsp; Yes, the slope gets steeper</p>
<p><strong>C.</strong>&nbsp; Yes, the slope gets flatter</p>
<aside class="notes">
<p>Ask the room: adding the sample means back shifts every point up and to the right. Will it change the slope? Answer on the next slide: A — the slope is 0.2673 again. Adding a constant to either axis moves the cloud, not its tilt; the intercept absorbs the shift. (AhaSlides interactive I5 follows.)</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="adding-the-means-back-keeps-the-slope-but-restores-readable-units" class="slide level2 center">
<h2>Adding the means back keeps the slope but restores readable units</h2>

<img data-src="../fwl_scaled_residuals.png" class="r-stretch quarto-figure-center"><p class="caption">Same residual scatter shifted by the sample means — axes now read ~34% coupons and ~$33.6K sales, slope still +0.267.</p><aside class="notes">
<p>A residual of −5 doesn’t mean −5% coupon usage; it means 5 points below what income predicts. Adding each variable’s mean back shifts the axes into interpretable units without touching the slope (still 0.2673, p = 0.029). The SE moves slightly, 0.119 against Step 2’s 0.118 — degrees of freedom again: this regression estimates an intercept, so it has 48 residual df instead of 49. This is a display device for a slide or a stakeholder report; for inference, report the full-model SE of 0.1203.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="before-you-look-does-a-second-control-move-the-coupon-coefficient" class="slide level2 center" data-background-color="#1a3a8a">
<h2>Before you look: does a second control move the coupon coefficient?</h2>
<p>Add day of week as a second control. In the DGP it is independent of both coupons and income.</p>
<p><strong>A.</strong>&nbsp; Not at all: it stays exactly 0.2673</p>
<p><strong>B.</strong>&nbsp; Slightly</p>
<p><strong>C.</strong>&nbsp; A lot: day of week is a second confounder</p>
<aside class="notes">
<p>Ask the room: the DGP makes day of week independent of coupons and of income. Will adding it as a second control change the coupon coefficient — and if so, by how much, and why? Answer on the next slide: B — from 0.2673 to 0.2706, a shift of about 0.003. (AhaSlides interactive I6 follows.)</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-second-control-barely-moves-the-coefficient-and-fwl-still-matches-it" class="slide level2 center">
<h2>A second control barely moves the coefficient — and FWL still matches it</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">Coupons coef.</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">Residual df</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Full OLS (+ income + day)</td>
<td style="text-align: right;">+0.2706</td>
<td style="text-align: right;">0.1194</td>
<td style="text-align: right;">46</td>
</tr>
<tr class="even">
<td>FWL (+ income + day)</td>
<td style="text-align: right;"><span class="key">+0.2706</span></td>
<td style="text-align: right;">0.1157</td>
<td style="text-align: right;">49</td>
</tr>
</tbody>
</table>
<p><span class="comment">0.2673 → 0.2706: day of week’s chance partial association with coupons, given income (partial corr. −0.021). Not a precision gain.</span></p>
<p><span class="takeaway fragment">FWL holds for any number of controls: partial them all out at once.</span></p>
<aside class="notes">
<p>The OVB identity describes the shift exactly: 0.2673 = 0.2706 + 0.3195 × (−0.0101), where 0.3195 is day of week’s coefficient in the three-variable model and −0.0101 is its slope on coupons after controlling for income. That is a tiny chance association in this sample — not the raw correlation of −0.076, and not a precision gain. Precision shows up in the SE, which moves separately (0.1203 → 0.1194). Because day of week is independent of coupons and income in the DGP, the shift would vanish in large samples. Day of week itself is not significant (0.3195, p = 0.198). The FWL recipe is unchanged — residualize on the full control set, then regress. This is exactly why fixed-effects packages (reghdfe, fixest, pyfixest) partial out hundreds of dummies first.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="the-resolution" class="title-slide slide level1 divider center" data-background-color="#00d4c8">
<h1>The Resolution</h1>
<p><span class="act">Act III</span></p>
</section>
<section id="after-partialling-out-income-the-estimated-effect-is-0.267" class="slide level2 center" data-background-color="#141413">
<h2>After partialling out income, the estimated effect is +0.267</h2>
<p><span class="bignum">+0.267</span></p>
<p><span class="bignum-label"><span class="math inline">\(\hat\beta_1\)</span> on coupons, full OLS = FWL · SE 0.1203 · 95% CI [0.025, 0.509] contains the true +0.200</span></p>
<aside class="notes">
<p>Between the misleading naive −0.106 and the planted truth +0.200, the conditioned estimate lands at +0.267 — close, with the gap due to just 50 observations. Closing the backdoor removes the bias, not the sampling noise. The point: the same data, honestly conditioned, recovers the right sign and roughly the right magnitude. The SE to report is the full-model 0.1203.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="simpsons-paradox-resolved-the-slope-flips-from-0.106-to-0.267" class="slide level2 center">
<h2>Simpson’s paradox, resolved: the slope flips from −0.106 to +0.267</h2>

<img data-src="../fwl_comparison.png" class="r-stretch quarto-figure-center"><p class="caption">Left: naive negative slope. Right: positive slope after partialling out income. Same 50 stores.</p><aside class="notes">
<p>The single most persuasive slide. Left panel is the confounded raw slope (−0.106), right panel is the conditional relationship (slope +0.267, an estimate of the true +0.2), and only the conditioning changed. A trend in the aggregate reverses once you condition on the relevant variable — the textbook definition of Simpson’s paradox. This is what FWL lets you <em>draw</em>.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="every-fwl-variant-matches-its-full-regression-only-the-se-moves" class="slide level2 center">
<h2>Every FWL variant matches its full regression — only the SE moves</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Method</th>
<th style="text-align: right;">Coupons coef.</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">df</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Naive OLS (no controls)</td>
<td style="text-align: right;">−0.1059</td>
<td style="text-align: right;">0.1158</td>
<td style="text-align: right;">48</td>
</tr>
<tr class="even">
<td>Full OLS (+ income)</td>
<td style="text-align: right;"><span class="key">+0.2673</span></td>
<td style="text-align: right;"><span class="key">0.1203</span></td>
<td style="text-align: right;">47</td>
</tr>
<tr class="odd">
<td>FWL Step 1 (no intercept)</td>
<td style="text-align: right;">+0.2673</td>
<td style="text-align: right;">1.2715</td>
<td style="text-align: right;">49</td>
</tr>
<tr class="even">
<td>FWL Step 1 + intercept</td>
<td style="text-align: right;">+0.2673</td>
<td style="text-align: right;">0.1437</td>
<td style="text-align: right;">48</td>
</tr>
<tr class="odd">
<td>FWL Step 2 (residualize both)</td>
<td style="text-align: right;">+0.2673</td>
<td style="text-align: right;">0.1178</td>
<td style="text-align: right;">49</td>
</tr>
<tr class="even">
<td>Full OLS (+ income + day)</td>
<td style="text-align: right;">+0.2706</td>
<td style="text-align: right;">0.1194</td>
<td style="text-align: right;">46</td>
</tr>
<tr class="odd">
<td>FWL (+ income + day)</td>
<td style="text-align: right;">+0.2706</td>
<td style="text-align: right;">0.1157</td>
<td style="text-align: right;">49</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Every FWL variant matches its full-regression twin to four decimals, and plain NumPy returns 0.2673 too. The only thing that moves the coefficient is which controls you partial out, not how you do the algebra. Within each family (one control, two controls), the SEs differ for two reasons only: how much variation is left in the residuals (Step 1 leaves the sales mean and income’s share of sales in them) and the residual degrees of freedom. Across families, and for the naive row, the variation left in coupons after the controls also changes. +0.267 sits beside the true +0.200 — the difference is sampling noise in 50 stores.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="does-fwl-make-this-causal-no-it-visualizes-it-does-not-identify" class="slide level2 center">
<h2>Does FWL make this causal? No — it visualizes, it does not identify</h2>
<p><span class="objection">Objection.</span> Residualizing on income looks like a trick that manufactures a causal effect.</p>
<div class="fragment">
<p><span class="rebuttal">Response.</span> FWL is pure algebra — it only reproduces what OLS already computes. The causal reading needs one assumption: income is the only confounder. FWL pictures that adjustment; it cannot certify it.</p>
<aside class="notes">
<p>Steelman, don’t strawman. The estimate is causal here only because the simulation guarantees no unmeasured confounding; in real data that must be argued, not assumed. Linearity is the second caveat, and it is subtler than “nonlinear confounding breaks FWL”. Linear partialling-out removes only the linear part of income. That is harmless when only the treatment (coupon) equation curves in income: the outcome equation is still correctly specified, and the coefficient stays unbiased (Exercise 7: 0.200). It fails when the outcome (sales) equation has a nonlinear income term that the linear control misses and that moves with coupons beyond linear income (0.127). Adding income² restores 0.200; flexible learners — DML — do this automatically. And if a second confounder is omitted, no amount of residualizing on income saves you.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="fwl-is-double-machine-learning-with-a-linear-mop" class="slide level2 center">
<h2>FWL is Double Machine Learning with a linear mop</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="fwl-here">FWL (here)</h3>
<ul>
<li>residualize <span class="math inline">\(y\)</span>, <span class="math inline">\(d\)</span> with <strong>OLS</strong></li>
<li>regress residual <span class="math inline">\(y\)</span> on residual <span class="math inline">\(d\)</span></li>
<li>misses outcome curves that move with <span class="math inline">\(d\)</span></li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="double-ml">Double ML</h3>
<ul>
<li>residualize <span class="math inline">\(y\)</span>, <span class="math inline">\(d\)</span> with <strong>cross-fitted ML</strong> (forest, lasso)</li>
<li>regress residual <span class="math inline">\(y\)</span> on residual <span class="math inline">\(d\)</span></li>
<li>learns nonlinear, high-dim controls</li>
</ul>
</div></div>
<p><span class="takeaway fragment">Same residualize-then-regress logic; swap OLS for cross-fitted flexible learners and you get a debiased estimate — causal only if no confounder is unmeasured.</span></p>
<aside class="notes">
<p>Chernozhukov et al.&nbsp;(2018). The whole DML estimator is FWL with the OLS partial-out replaced by cross-fitted machine learning: each store’s residuals come from models fit on the other folds, then the same residual-on-residual regression runs. It still needs no unmeasured confounding and learners that are good enough. It matters when the outcome depends on the controls in ways a linear control misses and those terms move with the treatment; a curve in the treatment equation alone is harmless for linear FWL. Master FWL and DML stops being mysterious — it is this same plot, learned with a smarter mop. The companion post python_doubleml runs it on a real experiment.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section id="dont-read-the-coefficient-read-the-partialled-out-scatter." class="title-slide slide level1 divider center" data-background-color="#141413">
<h1>Don’t read the coefficient — read the partialled-out scatter.</h1>
<aside class="notes">
<p>The one sentence to remember. A multivariate coefficient is a univariate slope on residuals; FWL lets you see it, and seeing it is what turns a confounded −0.106 into an honest +0.267.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="slides_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="slides_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="slides_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="slides_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="slides_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="slides_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="slides_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>