* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- synthetic-co2-cross-section.dta ----
use "synthetic-co2-cross-section.dta", clear
label data "Synthetic CO2 cross-section: outcome + 12 candidate regressors"
note _dta: Fully synthetic cross-section of 120 fictional countries, generated with set.seed(2017). One row per country; log_co2 is the outcome and the remaining 12 numeric columns are candidate regressors. 7 regressors have true nonzero effects on log_co2; 5 are pure noise correlated with GDP. Loaded in the post via read.csv from the raw GitHub URL.
note country: Synthetic country label (Country_001 ? Country_120); the cross-section key.. Construction: Sequential identifier assigned to each of the 120 simulated observations.. Units: string. Source: Synthetic (this study)
note log_co2: Natural-log CO2 emissions; the outcome all three methods explain.. Construction: log_co2 = 2.0 + 1.200-log_gdp + 0.008-industry + 0.012-fossil_fuel + 0.010-urban_pop + 0.004-democracy + 0.500-trade_network + 0.005-agriculture + N(0, 0.3^2). Noise variables enter with coefficient 0.. Units: log units. Source: Synthetic (this study)
note log_gdp: Natural-log GDP per capita; the dominant true predictor (true ? = 1.200, an elasticity).. Construction: log_gdp ~ N(8.5, 1.5^2); drives all other regressors.. Units: log units. Source: Synthetic (this study)
note industry: Industrial output share; true predictor (true ? = 0.008, composition effect).. Construction: industry = 15 + 1.5-log_gdp + N(0, 6^2).. Units: % / index. Source: Synthetic (this study)
note fossil_fuel: Fossil-fuel share of energy; true predictor (true ? = 0.012, semi-elasticity).. Construction: fossil_fuel = 30 + 3-log_gdp + N(0, 10^2).. Units: % of energy. Source: Synthetic (this study)
note urban_pop: Urbanization rate; true predictor with a moderate effect (true ? = 0.010; borderline for BMA).. Construction: urban_pop = 20 + 5-log_gdp + N(0, 12^2).. Units: % of population. Source: Synthetic (this study)
note democracy: Democratic-governance score; true predictor with a small effect (true ? = 0.004; borderline for BMA).. Construction: democracy = 5 + 2-log_gdp + N(0, 8^2).. Units: index. Source: Synthetic (this study)
note trade_network: Trade-centrality measure; true predictor with a moderate effect (true ? = 0.500).. Construction: trade_network = 0.2 + 0.05-log_gdp + N(0, 0.15^2).. Units: index (0-1 scale). Source: Synthetic (this study)
note agriculture: Agricultural share; true predictor with the weakest effect (true ? = 0.005; missed by all three methods).. Construction: agriculture = 40 - 3-log_gdp + N(0, 8^2) (negatively correlated with GDP).. Units: % / index. Source: Synthetic (this study)
note log_trade: Noise regressor - correlated with GDP but with zero true effect on log_co2.. Construction: log_trade = 3.5 + 0.1-log_gdp + N(0, 0.5^2). True ? = 0.. Units: log units. Source: Synthetic (this study)
note fdi: Noise regressor - zero true effect on log_co2 (the one noise variable not built from GDP).. Construction: fdi = 2 + N(0, 4^2). True ? = 0.. Units: % / index. Source: Synthetic (this study)
note corruption: Noise regressor - weakly (negatively) correlated with GDP but with zero true effect.. Construction: corruption = 0.8 - 0.05-log_gdp + N(0, 0.15^2). True ? = 0.. Units: index. Source: Synthetic (this study)
note log_tourism: Noise regressor - correlated with GDP (~0.3) but with zero true effect on log_co2.. Construction: log_tourism = 12 + 0.3-log_gdp + N(0, 1.2^2). True ? = 0.. Units: log units. Source: Synthetic (this study)
note log_credit: Noise regressor - correlated with GDP but with zero true effect on log_co2.. Construction: log_credit = 2.5 + 0.15-log_gdp + N(0, 0.6^2). True ? = 0.. Units: log units. Source: Synthetic (this study)
save "synthetic-co2-cross-section.dta", replace
