* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- r_sc_bayes_spatial_source_data.dta ----
use "r_sc_bayes_spatial_source_data.dta", clear
label data "State-year tobacco panel: cigarette sales + retail price"
note _dta: Balanced annual panel from the scspill replication package (Abadie et al. 2010 California tobacco data). 39 states x 31 years = 1,209 rows. California (state_id 3) is the treated unit; the other 38 states are donors. treatment = 1 for California in 1988-2000.
note state: US state identifier (the treated unit is California; the other 38 are donors).. Construction: From the scspill replication package panel (Abadie et al. 2010).. Units: string. Source: scspill package (Abadie et al. 2010)
note state_id: Integer index for the state (1-39); California is 3.. Construction: Sequential package index aligned to the alphabetical state list.. Units: integer (1-39). Source: scspill package
note year: Annual time index of the panel.. Construction: Observed year, 1970-2000 (balanced; 31 years per state).. Units: year. Source: scspill package (Abadie et al. 2010)
note cigsale: Annual per-capita cigarette pack sales - the synthetic-control outcome.. Construction: Observed tax-paid cigarette sales per capita, from the Abadie et al. (2010) tobacco data.. Units: packs per capita per year. Source: scspill package (Abadie et al. 2010)
note retprice: Average real retail price of a cigarette pack - the lone SAR covariate X.. Construction: Observed retail price per pack from the Abadie et al. (2010) tobacco data.. Units: cents per pack (real). Source: scspill package (Abadie et al. 2010)
note treatment: 1 for California in the post-treatment period, else 0 - flags the treated unit-years.. Construction: 1 if state == 'California' & year >= 1988, else 0 (package Prop 99 convention).. Units: 0/1. Source: Constructed in analysis.R
save "r_sc_bayes_spatial_source_data.dta", replace
