* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- EL_regional_conflict_replication.dta ----
use "EL_regional_conflict_replication.dta", clear
label data "Region-year panel: conflict, nighttime lights, weather instruments (+ detrended)"
note _dta: Annual region panel replicating Hodler & Raschky (2014). 96,591 region-year observations across 5,689 subnational regions, 1994-2010. Conflict outcomes from UCDP, nighttime lights from DMSP, instruments from lagged rainfall and the Palmer Drought Severity Index. Each estimation variable ships raw and detrended (_dt = residual from a region-specific linear time trend); regressions use the _dt series.
note objectid: Unique identifier for each subnational administrative region (the panel unit).. Construction: Region code from the original replication; panel set via tsset objectid year.. Units: integer ID. Source: Hodler & Raschky (2014)
note year: Annual time index (the panel time variable).. Construction: Observation year, 1994-2010.. Units: year. Source: Hodler & Raschky (2014)
note countrycode: Three-letter ISO country code of the region's country.. Construction: From the original panel (variable label 'ISO').. Units: ISO 3166-1 alpha-3. Source: Hodler & Raschky (2014)
note countryname: Name of the country containing the region.. Construction: From the original panel (variable label 'NAME_0').. Units: string. Source: Hodler & Raschky (2014)
note ucdp_death_dummy: 1 if the region-year had at least one conflict-related death, else 0 (outcome 1).. Construction: From UCDP geocoded battle deaths aggregated to the region-year.. Units: 0/1. Source: UCDP GED
note ucdp_25death_dummy: 1 if the region-year had 25 or more conflict-related deaths, else 0 (outcome 2).. Construction: From UCDP geocoded battle deaths aggregated to the region-year.. Units: 0/1. Source: UCDP GED
note llnlight01: Log nighttime light intensity lagged one year - proxy for local economic activity (endogenous regressor).. Construction: Natural log of DMSP-OLS nighttime light intensity, lagged one year.. Units: log intensity. Source: DMSP-OLS nighttime lights
note l2lnrain01: Log rainfall lagged two years - instrument 1 for economic activity.. Construction: Natural log of annual rainfall (GPCC), lagged two years.. Units: log mm. Source: Rainfall (GPCC)
note l2meanpdsi: Lagged Palmer Drought Severity Index - instrument 2 (higher = less drought).. Construction: Mean PDSI for the region, lagged two years; the label reads '(Non) Drought'.. Units: PDSI (index). Source: PDSI
note ucdp_death_dummy_dt: Detrended conflict (1+ deaths): residual from a region-specific linear time trend.. Construction: Residual of ucdp_death_dummy on year, fitted within each region (objectid).. Units: deviation. Source: Derived (this study)
note ucdp_25death_dummy_dt: Detrended conflict (25+ deaths): residual from a region-specific linear time trend.. Construction: Residual of ucdp_25death_dummy on year, fitted within each region (objectid).. Units: deviation. Source: Derived (this study)
note llnlight01_dt: Detrended log nighttime lights - the endogenous regressor used in all regressions.. Construction: Residual of llnlight01 on year, fitted within each region (objectid).. Units: deviation (log). Source: Derived (this study)
note l2lnrain01_dt: Detrended log rainfall - instrument 1 as used in the regressions.. Construction: Residual of l2lnrain01 on year, fitted within each region (objectid).. Units: deviation (log). Source: Derived (this study)
note l2meanpdsi_dt: Detrended PDSI - instrument 2 as used in the regressions.. Construction: Residual of l2meanpdsi on year, fitted within each region (objectid).. Units: deviation. Source: Derived (this study)
save "EL_regional_conflict_replication.dta", replace
