* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- main_data.dta ----
use "main_data.dta", clear
label data "Country-year panel: GDP, 10-yr growth + 90 correlates"
note _dta: The Kremer, Willis & You (2021) replication panel: Penn World Table 10.0 GDP plus 50+ institutional, policy, geographic and cultural growth correlates. Pre-cleaned to exclude very small countries (<200,000 pop) and resource-dependent economies (>75% resource rents). loggdp_growth_10 is forward-looking, so the last usable year is 2007/2008.
note code: Three-letter ISO country code; the panel identifier and the merge key to WDICountry.. Units: ISO3 string. Source: Replication panel / WDI
note legor_uk: 1 if the country's legal system is of British (common-law) origin.. Units: 0/1. Source: La Porta et al. (legal origin)
note legor_fr: 1 if the country's legal system is of French civil-law origin.. Units: 0/1. Source: La Porta et al. (legal origin)
note legor_ge: 1 if the country's legal system is of German civil-law origin.. Units: 0/1. Source: La Porta et al. (legal origin)
note legor_sc: 1 if the country's legal system is of Scandinavian origin.. Units: 0/1. Source: La Porta et al. (legal origin)
note legor_so: 1 if the country's legal system is of socialist origin.. Units: 0/1. Source: La Porta et al. (legal origin)
note euro1900: Share of European settlers around 1900.. Units: 0-1 share. Source: Historical sources
note logem4: Log of early-settler mortality (Acemoglu-Johnson-Robinson institutions instrument).. Units: log deaths per 1,000. Source: Acemoglu, Johnson & Robinson (2001)
note meantemp: Country mean temperature (long-run geographic correlate).. Units: degrees Celsius. Source: Geographic data
note lt100km: Share of population living within 100km of the coast.. Units: 0-1 share. Source: Geographic data
note avelf: Index of ethno-linguistic fractionalization (probability two random people differ).. Units: 0-1 index. Source: Fractionalization data
note temp1: First of five temperature-zone indicators (geographic control).. Units: 0-1 share. Source: Geographic data
note temp2: Second of five temperature-zone indicators.. Units: 0-1 share. Source: Geographic data
note temp3: Third of five temperature-zone indicators.. Units: 0-1 share. Source: Geographic data
note temp4: Fourth of five temperature-zone indicators.. Units: 0-1 share. Source: Geographic data
note temp5: Fifth of five temperature-zone indicators.. Units: 0-1 share. Source: Geographic data
note edes1975: Percent of population of European descent in 1975.. Units: %. Source: Historical sources
note landlock: 1 if the country is landlocked, else 0.. Units: 0/1. Source: Geographic data
note goldm: Indicator for significant gold endowment.. Units: 0/1. Source: Geological resource data
note iron: Indicator for significant iron endowment.. Units: 0/1. Source: Geological resource data
note silv: Indicator for significant silver endowment.. Units: 0/1. Source: Geological resource data
note zinc: Indicator for significant zinc endowment.. Units: 0/1. Source: Geological resource data
note oilres: Oil-reserves endowment measure.. Units: reserves measure. Source: Geological resource data
note lat_abst: Absolute latitude of the country, scaled 0-1 (distance from the equator).. Units: 0-1 (|lat|/90). Source: Geographic data
note avexpr: Average index of protection against expropriation risk (institutional quality).. Units: 0-10 index. Source: Acemoglu, Johnson & Robinson (2001)
note tropics: Share of land area in tropical climate zones.. Units: 0-1 share. Source: Geographic data
note g7089n: Average growth of neighboring countries, 1970-1989 (spatial spillover control).. Units: % per year. Source: Replication panel (derived)
note VSM_power_dist: Hofstede culture dimension: acceptance of unequal power distribution.. Units: 0-100 index. Source: Hofstede VSM
note VSM_individualism: Hofstede culture dimension: individualism vs. collectivism.. Units: 0-100 index. Source: Hofstede VSM
note VSM_masculinity: Hofstede culture dimension: masculinity vs. femininity.. Units: 0-100 index. Source: Hofstede VSM
note VSM_uncertain_avoid: Hofstede culture dimension: tolerance for uncertainty/ambiguity.. Units: 0-100 index. Source: Hofstede VSM
note VSM_indulgence: Hofstede culture dimension. NOTE: the embedded .dta labels for VSM_indulgence and VSM_longterm are swapped at source; this column is the long-term-orientation dimension.. Units: 0-100 index. Source: Hofstede VSM
note VSM_longterm: Hofstede culture dimension. NOTE: the embedded .dta labels for VSM_longterm and VSM_indulgence are swapped at source; this column is the indulgence/restraint dimension.. Units: 0-100 index. Source: Hofstede VSM
note population_1900: Mid-year population around 1900 (historical control).. Units: thousands. Source: Historical demographic sources
note year: Annual time index, 1960-2017.. Units: year. Source: Replication panel
note country: Country name corresponding to the ISO3 code.. Units: string. Source: Replication panel
note inc_tax: Share of government revenue from taxes on income, profits and capital gains.. Units: % of revenue. Source: World Bank WDI
note sev_tax: Share of government revenue from taxes on goods and services.. Units: % of revenue. Source: World Bank WDI
note credit: Domestic credit provided by the financial sector, share of GDP; financial-development correlate.. Units: % of GDP. Source: World Bank WDI
note WDI_credit: Alternative WDI credit series used in the multivariate convergence set. (Embedded .dta label is a copy artifact.). Units: % of GDP. Source: World Bank WDI
note WDI_GDP_pc: GDP per capita level from World Bank WDI.. Units: US$. Source: World Bank WDI
note miliexp: Military spending as a share of GDP.. Units: % of GDP. Source: World Bank WDI
note gov_spending: General government final consumption expenditure as a share of GDP.. Units: % of GDP. Source: World Bank WDI
note WDI_secondary: Gross secondary-school enrollment ratio.. Units: % gross. Source: World Bank WDI
note WDI_primary: Gross primary-school enrollment ratio.. Units: % gross. Source: World Bank WDI
note WDI_tertiary: Gross tertiary-school enrollment ratio.. Units: % gross. Source: World Bank WDI
note laborparti: Total labor-force participation rate, population 15+ (modeled ILO estimate).. Units: % of 15+ population. Source: World Bank WDI / ILO
note tariff_all_ew: Applied tariff rate, simple (equal-weighted) mean across all products.. Units: %. Source: World Bank WDI
note inflation: Annual inflation rate; a short-run macro-policy correlate. (Embedded .dta label is a copy artifact; the variable is inflation.). Units: % per year. Source: World Bank WDI
note tariff_all_vw: Applied tariff rate, trade-weighted mean across all products.. Units: %. Source: World Bank WDI
note investment: Investment share of GDP; a Solow fundamental (steady-state determinant).. Units: % of GDP. Source: World Bank WDI
note working_population_prop: Population aged 15-64 as a share of total.. Units: % of total. Source: World Bank WDI
note population_growth: Annual rate of total-population growth; a Solow fundamental.. Units: % per year. Source: World Bank WDI
note population: Total population.. Units: persons. Source: World Bank WDI
note resource_rents: Sum of natural-resource rents as a share of GDP (cleaning threshold variable).. Units: % of GDP. Source: World Bank WDI
note fuel_exports: Fuel exports as a share of merchandise exports.. Units: % of exports. Source: World Bank WDI
note mineral_exports: Ores and metals exports as a share of merchandise exports.. Units: % of exports. Source: World Bank WDI
note fuel_mineral_exports: Combined fuel and ores/metals exports as a share of merchandise exports.. Units: % of exports. Source: World Bank WDI
note lvaw_garriga: Central-bank-independence index, Garriga (2016), weighted version.. Units: 0-1 index. Source: Garriga (2016)
note barrolee2060: Mean years of schooling, population aged 20-60; the human-capital Solow fundamental.. Construction: (sum) w_yr_sch from the Barro-Lee dataset.. Units: years. Source: Barro-Lee
note edugap: Gap in schooling between men and women (used in the multivariate convergence set).. Units: years. Source: Barro-Lee (derived)
note overallscore: Heritage Foundation overall economic-freedom score.. Units: 0-100. Source: Heritage Foundation
note propertyrights: Heritage Foundation property-rights component.. Units: 0-100. Source: Heritage Foundation
note governmentintegrity: Heritage Foundation government-integrity component.. Units: 0-100. Source: Heritage Foundation
note taxburden: Heritage Foundation tax-burden component.. Units: 0-100. Source: Heritage Foundation
note businessfreedom: Heritage Foundation business-freedom component.. Units: 0-100. Source: Heritage Foundation
note investmentfreedom: Heritage Foundation investment-freedom component.. Units: 0-100. Source: Heritage Foundation
note financialfreedom: Heritage Foundation financial-freedom component.. Units: 0-100. Source: Heritage Foundation
note WGI_gov_effectiveness: Worldwide Governance Indicators: government-effectiveness estimate.. Units: z-score (~ -2.5 to 2.5). Source: World Bank WGI
note WGI_regulatory_quality: Worldwide Governance Indicators: regulatory-quality estimate.. Units: z-score (~ -2.5 to 2.5). Source: World Bank WGI
note WGI_rule_law: Worldwide Governance Indicators: rule-of-law estimate.. Units: z-score (~ -2.5 to 2.5). Source: World Bank WGI
note WGI_control_corruption: Worldwide Governance Indicators: control-of-corruption estimate.. Units: z-score (~ -2.5 to 2.5). Source: World Bank WGI
note WGI_pol_stability: Worldwide Governance Indicators: political-stability / absence-of-violence estimate.. Units: z-score (~ -2.5 to 2.5). Source: World Bank WGI
note igov_rpppPercentofGDP: General-government investment as a share of GDP (IMF igov_rppp).. Units: % of GDP. Source: IMF Investment & Capital Stock dataset
note ipriv_rpppPercentofGDP: Private investment as a share of GDP (IMF ipriv_rppp).. Units: % of GDP. Source: IMF Investment & Capital Stock dataset
note pri_inv: Private investment share of GDP (one of the 10 correlates in the fixed multivariate sample).. Units: % of GDP. Source: IMF Investment & Capital Stock dataset
note democ: Polity democracy sub-index. Special codes -66 (interruption), -77 (interregnum), -88 (transition) denote non-scores, not values.. Units: 0-10 (+ Polity special codes). Source: Polity IV
note autoc: Polity autocracy sub-index. Special codes -66/-77/-88 denote non-scores, not values.. Units: 0-10 (+ Polity special codes). Source: Polity IV
note polity2: Combined Polity score; the headline democracy correlate in the OVB worked example. Interpolated/analysis-ready (no special missing codes).. Units: -10 (autocracy) to +10 (democracy). Source: Polity IV
note FH_political_rights: Freedom House political-rights rating (1 = most free, 7 = least free); a short-run institutional correlate.. Units: 1-7 rating. Source: Freedom House
note FH_civil_liberties: Freedom House civil-liberties rating (1 = most free, 7 = least free).. Units: 1-7 rating. Source: Freedom House
note totalscore: Composite total score used as an auxiliary institutional measure.. Units: score. Source: Replication panel
note logrgdpna: Log real GDP per capita, PWT national-accounts growth series (rgdpna); base for the 10-year growth rate.. Units: log US$. Source: Penn World Table 10.0
note logcgdpo: Log real GDP per capita, PWT output-side series at current PPPs (cgdpo).. Units: log US$. Source: Penn World Table 10.0
note logrgdpo: Log real GDP per capita, PWT output-side series (rgdpo).. Units: log US$. Source: Penn World Table 10.0
note logrgdpe: Log real GDP per capita, PWT expenditure-side series (rgdpe).. Units: log US$. Source: Penn World Table 10.0
note logrgdpo_91: Log real GDP per capita, PWT output-side series anchored to a 1991 base.. Units: log US$. Source: Penn World Table 10.0
note country_id: Numeric panel id (Stata egen group(code)); used as the panel/cluster unit.. Construction: group(code). Units: integer id. Source: Derived (this study)
note loggdp_WDI: Natural log of GDP per capita from World Bank WDI (alternative income series).. Units: log US$. Source: World Bank WDI
note loggdp: Natural log of real GDP per capita from Penn World Table 10.0; the initial-income regressor in convergence regressions.. Construction: log(GDPpc), PWT real GDP per capita (national-accounts series, logrgdpna).. Units: log US$ (PPP). Source: Penn World Table 10.0
note loggdp_pw: Alternative log GDP-per-capita measure used in robustness checks.. Units: log US$. Source: Penn World Table 10.0
note loggdp_growth_10: Forward-looking 10-year annualized growth rate of GDP per capita; the main outcome variable.. Construction: 100 x (F10.logrgdpna - logrgdpna)/10 over a 10-year horizon (forward-looking; last usable year ~2007).. Units: % per year. Source: Penn World Table 10.0 (derived)
save "main_data.dta", replace

* ---- WDICountry.dta ----
use "WDICountry.dta", clear
label data "World Bank country metadata lookup (code, region, income group)"
note _dta: World Development Indicators country-metadata file. Only the code and region columns are used by the analysis (to build the four-way region_group); the remaining columns are the WDI country attributes (currency, income group, accounting standards, latest-survey dates). Aggregate rows (e.g. 'Arab World', 'World') have blank region and are not matched. Column names were normalized to valid Stata identifiers; values are unchanged.
note country_code: Three-letter ISO country code; the lookup key (matches main_data code).. Units: ISO3 string. Source: World Bank WDI
note short_name: Short display name of the economy.. Units: string. Source: World Bank WDI
note table_name: Name as used in WDI tables (drop-if-empty filter in the merge).. Units: string. Source: World Bank WDI
note long_name: Full official name of the economy.. Units: string. Source: World Bank WDI
note iso2_code: Two-letter ISO country code.. Units: ISO2 string. Source: World Bank WDI
note currency_unit: Name of the national currency.. Units: string. Source: World Bank WDI
note special_notes: Free-text WDI notes about the economy.. Units: string. Source: World Bank WDI
note region: WDI geographic region; the merged key used to build the four-way region_group (Section 6.2). Blank for aggregate rows.. Units: region name. Source: World Bank WDI
note income_group: WDI income classification (Low / Lower-middle / Upper-middle / High income).. Units: category. Source: World Bank WDI
note wb_2_code: World Bank internal two-letter economy code.. Units: string. Source: World Bank WDI
note national_accounts_base_year: Base year of the national-accounts series.. Units: year (string). Source: World Bank WDI
note national_accounts_reference_year: Reference year for the national-accounts series.. Units: year. Source: World Bank WDI
note sna_price_valuation: System-of-National-Accounts price-valuation basis.. Units: category. Source: World Bank WDI
note lending_category: IDA/IBRD/Blend lending category.. Units: category. Source: World Bank WDI
note other_groups: Other World Bank groupings the economy belongs to (e.g. HIPC, EMU).. Units: category. Source: World Bank WDI
note system_of_national_accounts: SNA standard followed (e.g. 1993 SNA, 2008 SNA).. Units: category. Source: World Bank WDI
note alternative_conversion_factor: Periods using an alternative currency-conversion factor.. Units: string. Source: World Bank WDI
note ppp_survey_year: Year of the latest ICP purchasing-power-parity survey.. Units: year. Source: World Bank WDI
note balance_of_payments_manual_in_us: IMF BPM edition used for balance-of-payments data.. Units: category. Source: World Bank WDI
note external_debt_reporting_status: Status of the economy's external-debt reporting.. Units: category. Source: World Bank WDI
note system_of_trade: General vs. special trade-recording system.. Units: category. Source: World Bank WDI
note government_accounting_concept: Budgetary vs. consolidated central-government accounting concept.. Units: category. Source: World Bank WDI
note imf_data_dissemination_standard: IMF data-dissemination subscription (SDDS/GDDS/e-GDDS).. Units: category. Source: World Bank WDI
note latest_population_census: Year of the latest population census.. Units: year (string). Source: World Bank WDI
note latest_household_survey: Latest household survey (type and year).. Units: string. Source: World Bank WDI
note source_of_most_recent_income_and: Survey source of the most recent income and expenditure data.. Units: string. Source: World Bank WDI
note vital_registration_complete: Whether vital (births/deaths) registration is complete.. Units: Yes/blank. Source: World Bank WDI
note latest_agricultural_census: Year(s) of the latest agricultural census.. Units: year (string). Source: World Bank WDI
note latest_industrial_data: Year of the latest industrial data.. Units: year. Source: World Bank WDI
note latest_trade_data: Year of the latest trade data.. Units: year. Source: World Bank WDI
save "WDICountry.dta", replace
