<!DOCTYPE html>
<html lang="en"><head>
<script src="slides_files/libs/clipboard/clipboard.min.js"></script>
<script src="slides_files/libs/quarto-html/tabby.min.js"></script>
<script src="slides_files/libs/quarto-html/popper.min.js"></script>
<script src="slides_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="slides_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="slides_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="slides_files/libs/quarto-html/quarto-syntax-highlighting-dark-f1aadacce99040138bbb613f9330654f.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="dcterms.date" content="2026-10-05">
  <title>The Synthetic Control Method in Stata</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #e1e4e8; background-color: #24292e; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #e1e4e8; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #f97583; } /* Attribute */
    code span.bn { color: #79b8ff; } /* BaseN */
    code span.bu { color: #f97583; } /* BuiltIn */
    code span.cf { color: #f97583; } /* ControlFlow */
    code span.ch { color: #9ecbff; } /* Char */
    code span.cn { color: #79b8ff; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #f97583; } /* DataType */
    code span.dv { color: #79b8ff; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #f97583; font-weight: bold; } /* Extension */
    code span.fl { color: #79b8ff; } /* Float */
    code span.fu { color: #b392f0; } /* Function */
    code span.im { color: #9ecbff; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #f97583; } /* Keyword */
    code span.op { color: #e1e4e8; } /* Operator */
    code span.ot { color: #b392f0; } /* Other */
    code span.pp { color: #f97583; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #79b8ff; } /* SpecialChar */
    code span.ss { color: #9ecbff; } /* SpecialString */
    code span.st { color: #9ecbff; } /* String */
    code span.va { color: #ffab70; } /* Variable */
    code span.vs { color: #9ecbff; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="slides_files/libs/revealjs/dist/theme/quarto-9b58ec14c6e77dd4bed0a59f9cec700e.css">
  <link href="slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="slides_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-dark">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">The Synthetic Control Method in Stata</h1>
  <p class="subtitle">Did Proposition 99 cut smoking in California?</p>
  <div class="title-result-strip">
    <div class="kr"><span class="kr-num">−19.00</span><span class="kr-cap">ATT · packs per capita / yr</span></div>
    <div class="kr"><span class="kr-num">0.974</span><span class="kr-cap">pre-treatment R² (synth2)</span></div>
    <div class="kr"><span class="kr-num">0.026</span><span class="kr-cap">in-space placebo p-value</span></div>
  </div>
  <p class="author"><a href="https://carlos-mendez.org">Carlos Mendez</a></p>
  <p class="institute">Nagoya University (GSID)</p>
  <p class="date">October 5, 2026</p>
</section>
<section>
<section id="the-tension" class="title-slide slide level1 divider center" data-background-color="#d97757">
<h1>The Tension</h1>
<p><span class="act">Act I</span></p>
</section>
<section id="smoking-was-falling-everywhere-so-did-the-tax-change-anything" class="slide level2 center">
<h2>Smoking was falling everywhere, so did the tax change anything?</h2>
<p>In 1988, California voters passed <strong>Proposition 99</strong>, effective January 1989. It raised the cigarette tax by 25 cents per pack. It also funded anti-smoking education.</p>
<div class="fragment">
<p>Yet cigarette sales were already falling nationwide. In California, the decline began in the late 1970s. <em>What would California have done without the law?</em></p>
<aside class="notes">
<p>A simple before-and-after comparison confounds the policy with a trend that pushed sales down everywhere. This is the central problem of policy evaluation with a single treated unit. We cannot simply compare California before and after 1989. Secular trends, such as rising health awareness and federal regulation, were already lowering sales across the country. We therefore need a credible counterfactual: a California that never passed Proposition 99.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="a-raw-comparison-hints-at-an-effect-but-the-comparator-is-crude" class="slide level2 center">
<h2>A raw comparison hints at an effect, but the comparator is crude</h2>

<img data-src="../stata_sc_raw_trends.png" class="r-stretch quarto-figure-center"><p class="caption">Cigarette sales per capita, 1970–2000: California (solid blue) versus the unweighted average of 38 control states (dashed gray). The orange line marks Proposition 99 (1989).</p><aside class="notes">
<p>California starts close to the donor average in 1970. The gap then widens through the 1970s and stays near 20 packs for most of the 1980s. By 1988, California sold 90.1 packs per capita against a donor average of 113.8, already 23.72 packs below it before the law. The unweighted average also gives equal weight to New Hampshire and Utah, which average 213 and 64 packs per capita over 1970–2000. Their smoking levels are very different from those of California. We need an <em>optimal</em> weighted comparator, and that comparator is the synthetic control.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="where-we-are-going" class="slide level2 center">
<h2>Where we are going</h2>
<ul>
<li class="fragment">The lab: a 39-state, 31-year panel and the ATT estimand</li>
<li class="fragment">Build “synthetic California” with <code>synth2</code>, a weighted blend of donor states</li>
<li class="fragment">Three inference tools: in-space placebo, in-time placebo, and leave-one-out</li>
<li class="fragment">The lesson: prefer a transparent counterfactual to an untestable parallel-trends assumption</li>
</ul>
</section></section>
<section>
<section id="the-investigation" class="title-slide slide level1 divider center" data-background-color="#6a9bcc">
<h1>The Investigation</h1>
<p><span class="act">Act II</span></p>
</section>
<section id="the-lab-39-states-31-years-one-treated-unit-the-att" class="slide level2 center">
<h2>The lab: 39 states × 31 years, one treated unit, the ATT</h2>
<ul>
<li class="fragment"><strong>Outcome</strong>: <code>cigsale</code>, cigarette sales per capita (packs)</li>
<li class="fragment"><strong>Treatment</strong>: Proposition 99, California only, from 1989</li>
<li class="fragment"><strong>Predictors</strong>: log GDP per capita, share aged 15–24, retail price, beer, and <code>cigsale</code> in 1975, 1980, and 1988</li>
</ul>
<p><span class="takeaway fragment">Strongly balanced panel: 1,209 observations, 19 pre-treatment years, and 12 post-treatment years. The estimand is the <strong>ATT</strong> for California, the one treated unit, <em>not</em> the ATE.</span></p>
<aside class="notes">
<p>With a single treated unit and aggregate data, the parallel-trends assumption of difference-in-differences is hard to test. SCM instead builds an explicit counterfactual, so we can <em>see</em> the quality of the match in the pre-treatment period. California is state == 3 in the data.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="scm-builds-a-counterfactual-by-matching-pre-treatment-predictors" class="slide level2 center">
<h2>SCM builds a counterfactual by matching pre-treatment predictors</h2>
<p><span class="math display">\[\min_{W} \sum_{m=1}^{M} v_m \left( X_{1m} - \sum_{j=2}^{J+1} w_j X_{jm} \right)^2\]</span></p>
<p>We pick donor weights <span class="math inline">\(w_j \ge 0\)</span> that sum to one and match the predictors <span class="math inline">\(X_{1m}\)</span> of California. The weights <span class="math inline">\(v_m\)</span> set how much each predictor matters. The solution is the closest feasible blend of donors.</p>
<p><span class="takeaway fragment">The synthetic control is a <strong>convex combination</strong> of real states, so it never extrapolates beyond the donor pool.</span></p>
<aside class="notes">
<p>This is a nested optimization. The outer problem picks the V-weights to minimize the pre-1989 prediction error of the outcome. These weights set how much each predictor counts in the matching distance. The inner problem picks the W-weights, the donor shares, that minimize the weighted predictor distance. The nonnegativity and sum-to-one constraints keep the synthetic control interpretable and limit overfitting.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-treatment-effect-is-the-gap-between-actual-and-synthetic-california" class="slide level2 center">
<h2>The treatment effect is the gap between actual and synthetic California</h2>
<p><span class="math display">\[\hat{\tau}_t = Y_{1t} - \sum_{j=2}^{J+1} w_j^* Y_{jt}\]</span></p>
<p>The effect in year <span class="math inline">\(t\)</span> is actual minus synthetic sales. A negative <span class="math inline">\(\hat{\tau}_t\)</span> means that the law <em>lowered</em> sales. Each year from 1989 to 2000 yields one such gap.</p>
<p><span class="takeaway fragment">Identification rests on <strong>good pre-treatment fit</strong>, <strong>no interference</strong>, <strong>no anticipation</strong>, and <strong>no donor contamination</strong>; only the fit is directly visible in the data.</span></p>
<aside class="notes">
<p>The ATT is the mean of these yearly gaps over 1989–2000. Unlike difference-in-differences, the method does not ask us to accept parallel trends on faith. If the synthetic control tracks California closely before 1989, the later divergence is a credible estimate of the effect. No interference means that Proposition 99 did not change sales in other states. No anticipation means that sales in California did not respond before 1989. No donor contamination means that the donor states adopted no similar programs during the sample period. Good fit means that the synthetic control reproduces the pre-1989 path.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="one-synth2-call-fits-the-baseline-synthetic-control" class="slide level2 center">
<h2>One <code>synth2</code> call fits the baseline synthetic control</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-code-line-numbers="1|2|3"><pre class="sourceCode numberSource stata number-lines code-with-copy"><code class="sourceCode stata"><span id="cb1-1"><a href=""></a>synth2 cigsale lnincome age15to24 retprice beer <span class="co">///</span></span>
<span id="cb1-2"><a href=""></a>    cigsale(1988) cigsale(1980) cigsale(1975), <span class="co">///</span></span>
<span id="cb1-3"><a href=""></a>    trunit(3) trperiod(1989) xperiod(1980(1)1988) nested allopt</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><span class="takeaway fragment"><code>trunit(3)</code> = California · <code>trperiod(1989)</code> = treatment year · <code>nested</code> = outer V / inner W · <code>allopt</code> = multiple starts to avoid local optima.</span></p>
<aside class="notes">
<p>The specification uses seven predictors. Four economic and demographic variables are averaged over 1980–1988, and cigarette sales enter at three anchor years before treatment (1975, 1980, and 1988). The <code>nested allopt</code> combination is slower, but it lowers the risk of a spurious local optimum in the search over the V-weights. It is a careful choice, not a gold standard.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="synthetic-california-tracks-the-pre-1989-path-closely-but-not-exactly" class="slide level2 center">
<h2>Synthetic California tracks the pre-1989 path closely, but not exactly</h2>

<img data-src="../stata_sc_pred.png" class="r-stretch quarto-figure-center"><p class="caption">Actual versus synthetic California, 1970–2000: close before 1989 apart from 1970, then a widening gap.</p><aside class="notes">
<p>The synth2 command reports an R² of 0.974 and an RMSE of 1.756 packs over the 19 pre-treatment years. Its R² divides by the variation of the synthetic series; the conventional R² with the same weights is 0.976. The fit is close but not exact: the largest pre-period gap is 5.88 packs, in 1970, and the later gaps are much smaller. This close match makes it unlikely that the post-1989 divergence merely continues a pre-existing difference.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="age-1524-and-1975-sales-dominate-the-v-weights-but-v-is-fragile" class="slide level2 center">
<h2>Age 15–24 and 1975 sales dominate the V-weights, but V is fragile</h2>

<img data-src="../stata_sc_weight_vars.png" class="r-stretch quarto-figure-center"><p class="caption">Predictor (V-matrix) weights: how much each predictor counts in the matching distance.</p><aside class="notes">
<p>The dominant V-weights are age 15–24 (0.546) and cigsale(1975) (0.422), while log GDP per capita gets essentially zero weight. These weights are fragile, because V is poorly identified. The placebo refit of the same model gives age 15–24 only 0.002 and cigsale(1975) 0.768, while the donor weights barely change. We should therefore read V as one of many near-equivalent solutions, not as a ranking of what matters. In the baseline fit, six of the seven predictors are closely matched, and five biases are below 0.3%. Log GDP per capita is the exception: its −2.16% bias compares logarithms, so synthetic California falls short by 0.22 log points, a GDP per capita about 20% lower. The simple average of the controls misses 1988 sales by 26.3%, against 1.74% for the synthetic control.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="synthetic-california-is-a-blend-of-five-states-led-by-utah-at-one-third" class="slide level2 center">
<h2>Synthetic California is a blend of five states, led by Utah at one-third</h2>

<img data-src="../stata_sc_weight_unit.png" class="r-stretch quarto-figure-center"><p class="caption">Donor weights: the five states that compose synthetic California (33 others get a reported weight of zero).</p><aside class="notes">
<p>The weights are Utah 33.4%, Nevada 23.5%, Montana 20.2%, Colorado 16.1%, and Connecticut 6.8%. SCM solutions are typically sparse. The method selects the blend whose weighted predictors, including past sales, match California, not individually similar or nearby states. Low-sales Utah and high-sales Nevada, for example, bracket California. Because Utah carries a third of the weight, we later drop each donor in turn in a leave-one-out check.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="by-2000-real-california-sold-38-fewer-packs-than-its-synthetic-twin" class="slide level2 center" data-background-color="#141413">
<h2>By 2000, real California sold 38% fewer packs than its synthetic twin</h2>
<p><span class="bignum">−19.00</span></p>
<p><span class="bignum-label">average ATT, packs per capita / yr (1989–2000); −7.59 in 1989 deepening to −26.37 by 1999</span></p>
<aside class="notes">
<p>The effect grows over time. By 2000, actual sales in California (41.6 packs) sit 25.76 packs below the synthetic control (67.4), a reduction of 38%. With about 34 million residents, that gap implies roughly 900 million fewer packs in 2000 alone. The growing gap is consistent with cumulative behavioral change and shifting social norms. Part of the gap in 1999–2000 may also reflect Proposition 10, which raised the tax by a further 50 cents per pack in January 1999.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-gap-widens-through-the-1990s-though-not-in-every-year" class="slide level2 center">
<h2>The gap widens through the 1990s, though not in every year</h2>

<img data-src="../stata_sc_eff.png" class="r-stretch quarto-figure-center"><p class="caption">Treatment effect (actual minus synthetic California) over time; the negative gap widens after 1989.</p><aside class="notes">
<p>The effect starts at −7.59 packs in 1989, reaches −26.37 by 1999, and stands at −25.76 in 2000. The path is not monotonic; for instance, the gap narrows briefly in 1998. Is the gap real, or could a state that was never treated show a gap this large by chance? Act III tests the result in three ways.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="the-resolution" class="title-slide slide level1 divider center" data-background-color="#00d4c8">
<h1>The Resolution</h1>
<p><span class="act">Act III</span></p>
</section>
<section id="california-has-the-most-extreme-signal-to-noise-ratio-of-all-39-states" class="slide level2 center">
<h2>California has the most extreme signal-to-noise ratio of all 39 states</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>State</th>
<th style="text-align: right;">Pre MSPE</th>
<th style="text-align: right;">Post/Pre MSPE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>California</td>
<td style="text-align: right;">3.17</td>
<td style="text-align: right;"><span class="key">123.5</span></td>
</tr>
<tr class="even">
<td>Georgia</td>
<td style="text-align: right;">1.46</td>
<td style="text-align: right;">80.0</td>
</tr>
<tr class="odd">
<td>Virginia</td>
<td style="text-align: right;">2.78</td>
<td style="text-align: right;">79.0</td>
</tr>
<tr class="even">
<td>Missouri</td>
<td style="text-align: right;">1.20</td>
<td style="text-align: right;">70.9</td>
</tr>
</tbody>
</table>
<p><span class="takeaway fragment">The post/pre MSPE ratio asks how much worse the fit becomes <em>after</em> 1989 than before. California has the highest ratio, well above the runner-up.</span></p>
<aside class="notes">
<p>A genuine effect should inflate the post-treatment prediction error relative to a small pre-treatment error. California has a ratio of 123.5, well above Georgia (80.0) and Virginia (79.0). The table comes from the placebo run, which refits California with <code>sigf(6)</code> and without <code>allopt</code>. That refit has an RMSE of 1.780 (pre-MSPE 3.17), slightly worse than the baseline RMSE of 1.756. The ratio is the preferred statistic because it rewards both a large gap and a tight pre-treatment fit.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="run-the-placebo-on-every-state-california-is-the-clear-outlier" class="slide level2 center">
<h2>Run the placebo on every state: California is the clear outlier</h2>

<img data-src="../stata_sc_eff_pboUnit.png" class="r-stretch quarto-figure-center"><p class="caption">Gaps for California (purple) and the 19 placebo states retained by cut(2): the lines overlap near zero before 1989, and California falls below almost every placebo afterward.</p><aside class="notes">
<p>The in-space placebo applies the same SCM to each control state, as if each had been treated in 1989. This is a permutation test: if treatment were assigned to one state at random, how often would we see a gap as large as the one for California? Rarely: by the post/pre MSPE ratio, California ranks first among all 39 units. The figure shows its path as a clear outlier among the 19 retained placebos.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="across-all-39-states-a-ratio-this-large-occurs-2.6-of-the-time" class="slide level2 center" data-background-color="#141413">
<h2>Across all 39 states, a ratio this large occurs 2.6% of the time</h2>
<p><span class="bignum">0.026</span></p>
<p><span class="bignum-label">in-space placebo p-value, all controls (1/39); p = 0.050 after the cut(2) fit filter (1/20)</span></p>
<aside class="notes">
<p>Using all states, p = 1/39 = 0.026. The cut(2) filter removes the 19 states whose pre-treatment MSPE exceeds twice that of California, which leaves 20 states, California included, and p = 1/20 = 0.050. That value sits right at the conventional threshold, a mechanical consequence of having few comparison units. We report both: the unfiltered p is the less conservative of the two, while the filtered p compares California only with placebos that fit well.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="significance-holds-in-most-post-treatment-years" class="slide level2 center">
<h2>Significance holds in most post-treatment years</h2>

<img data-src="../stata_sc_pvalLeft_pboUnit.png" class="r-stretch quarto-figure-center"><p class="caption">Left-sided permutation p-values over time (left-sided, because the effect is negative): p = 0.050 in most years.</p><aside class="notes">
<p>Left-sided p-values are the right choice for a negative effect. They are computed on the 20 units retained by cut(2), and they equal 0.050 in 8 of 12 post-treatment years. In 1990–1992 and 1998, one or two retained placebos show a gap at least as negative as that of California, so p rises to 0.100–0.150. Effect size alone does not explain this, because the smallest gap, in 1989, still reaches p = 0.050. From 1993 onward, California is the most extreme state in every year except 1998.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-fake-1985-treatment-produces-much-smaller-gaps" class="slide level2 center">
<h2>A fake 1985 treatment produces much smaller gaps</h2>

<img data-src="../stata_sc_pred_pboTime1985.png" class="r-stretch quarto-figure-center"><p class="caption">In-time placebo: actual versus synthetic California with a fake treatment in 1985. A modest gap opens during 1985–1988, and the lines split much further after the real 1989 policy.</p><aside class="notes">
<p>If the design were spurious, a fake earlier date would produce an effect of similar size. Instead, the fake-period gaps (1985–1988) range from −3.33 to −8.65 packs, while the gaps from 1989 onward range from −13.97 to −25.59 packs. The fake model uses a reduced specification: covariates are averaged over 1980–1984, the 1988 lag is dropped, and the fit period is 1970–1984. The synth2 command does not print the fit of this fake-1985 model. The R² of 0.953 in the log belongs to the same reduced specification estimated with the real date 1989. The fake-period gaps are much smaller than the real ones, but they are not zero.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-gap-stays-modest-at-the-fake-date-and-grows-after-the-real-one" class="slide level2 center">
<h2>The gap stays modest at the fake date and grows after the real one</h2>

<img data-src="../stata_sc_eff_pboTime1985.png" class="r-stretch quarto-figure-center"><p class="caption">In-time placebo effect: smaller gaps during the fake 1985–1988 window, larger gaps after the real 1989 treatment.</p><aside class="notes">
<p>Fake-period gaps average −5.99 packs. At the real date, the gap steps down by 5.74 packs, from −8.39 in 1988 to −14.12 in 1989, and it widens further in later years. The model thus finds much smaller effects at the fake date than after the real one. This pattern supports the design only in part, because the gap already steps down by a similar amount in 1987. The fake-period gaps are also not zero.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="no-single-donor-drives-the-sign-of-the-effect-leave-one-out-gaps-stay-negative" class="slide level2 center">
<h2>No single donor drives the sign of the effect: leave-one-out gaps stay negative</h2>

<img data-src="../stata_sc_loo_combined.png" class="r-stretch quarto-figure-center"><p class="caption">Leave-one-out output in seven panels. In the last two, each gray line drops one weighted donor, and the paths stay close to the full-pool fit.</p><aside class="notes">
<p>We drop each of the five weighted donors in turn and refit the model. For 2000, the leave-one-out gaps range from −28.35 to −23.49 around −25.61, the value from the refit inside the same command. The spread of 4.87 packs is about 19% of the estimate. Every leave-one-out gap stays negative in every post-treatment year, even when Utah, with a third of the weight, is removed. The note printed under the figure is inaccurate: each gray line, not each panel, drops one donor. The deployed figure comes from the original run and still carries this note; the corrected do-file now writes an accurate one.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="does-choosing-controls-by-fit-make-this-causal-not-by-itself" class="slide level2 center">
<h2>Does choosing controls by fit make this causal? Not by itself</h2>
<p><span class="objection">Objection.</span> A data-driven counterfactual is still a model. It cannot manufacture identification. Pre-1989 fit does not guarantee post-1989 validity.</p>
<div class="fragment">
<p><span class="rebuttal">Response.</span> Correct. The ATT is credible only under <strong>no interference</strong>, <strong>no anticipation</strong>, <strong>no donor contamination</strong>, and <strong>good pre-treatment fit</strong>. SCM makes the last condition <em>visible</em> and disciplines the comparator. It cannot rule out cross-border shopping or an idiosyncratic donor such as Utah. It also gives no standard errors, so inference rests on the placebos.</p>
<aside class="notes">
<p>We should take the critique seriously. The value of SCM lies in transparency; it does not deliver identification for free. The five-state synthetic control is sensitive to the predictor set: the ATT moves from −19.00 to −17.71 in the reduced specification of the in-time placebo, estimated with the real date. Utah, with its distinct smoking norms, shows how one idiosyncratic donor could matter. By design, the donor pool also excludes states with large tobacco control programs or large tax increases. Recent conformal-inference methods offer more formal confidence intervals.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section></section>
<section id="let-the-pre-treatment-fit-not-a-parallel-trends-assumption-earn-the-counterfactual." class="title-slide slide level1 divider center" data-background-color="#141413">
<h1>Let the pre-treatment fit, not a parallel-trends assumption, earn the counterfactual.</h1>
<aside class="notes">
<p>This is the single takeaway of the talk. With one treated unit, a transparent weighted counterfactual that we can validate before treatment is more honest than an untestable parallel-trends story. For California, three checks support a negative effect: the placebo in space, the placebo in time, and leave-one-out. The in-time placebo, however, supports its timing only in part. Our estimate is that Proposition 99 cut sales by about 19 packs per capita per year over 1989–2000.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="slides_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="slides_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="slides_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="slides_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="slides_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="slides_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="slides_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="slides_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>