* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- prop99_example.dta ----
use "prop99_example.dta", clear
label data "State-year panel: cigarette sales + Prop 99 treatment"
note _dta: Strongly balanced state-year panel, 39 US states, 1970-2000 (1,209 obs). Outcome = cigarette packs per capita; treated = 1 for California in 1989-2000. The canonical Proposition 99 panel (Abadie et al. 2010) distributed with the sdid package; outcome-only (no covariates).
note state: US state name - the panel unit. 39 states: California (treated) plus 38 control states forming the donor pool.. Construction: From the distributed dataset; encoded to a numeric id in the post (encode state, gen(id)) for xtset/synth2.. Units: string. Source: Abadie et al. (2010) / sdid package
note year: Calendar year - the panel time index (19 pre-treatment years 1970-1988, 12 post-treatment years 1989-2000).. Construction: Annual observations; strongly balanced (every state observed every year, no gaps).. Units: year. Source: Abadie et al. (2010) / sdid package
note packspercapita: Annual per-capita cigarette pack sales - the sole outcome Y_it. Mean about 119 packs; range roughly 41-296.. Construction: Distributed outcome series; the only outcome in the panel (no income, price, or demographic covariates).. Units: packs per capita per year. Source: Abadie et al. (2010) / sdid package
note treated: Treatment status W_it: 1 for California in 1989-2000 (the 12 post-Proposition-99 years), 0 otherwise. Only 12 of 1,209 observations are treated.. Construction: 1 where state == California and year >= 1989; the single-treated-unit block design.. Units: 0/1. Source: Abadie et al. (2010) / sdid package
save "prop99_example.dta", replace
