* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- carbontax_data.dta ----
use "carbontax_data.dta", clear
label data "OECD country panel: transport CO2 + synthetic-control predictors"
note _dta: Balanced annual panel of 15 advanced economies, 1960-2005 (690 rows). Sweden is the treated unit (1991 carbon-tax reform; treatment dated 1990). Donor pool = the other 14 countries; the synthetic control selects six (Denmark, Belgium, New Zealand, Greece, US, Switzerland). GDP_per_capita has 10 missing values.
note Countryno: Integer identifier for each of the 15 OECD countries in the panel.. Construction: Sequential code 1..15 assigned in alphabetical country order (1=Australia ... 15=United States).. Units: integer code. Source: Andersson (2019) replication file
note country: Name of the OECD country.. Construction: One of the 15 advanced economies: Australia, Belgium, Canada, Denmark, France, Greece, Iceland, Japan, New Zealand, Poland, Portugal, Spain, Sweden, Switzerland, United States.. Units: string. Source: Andersson (2019) replication file
note year: Annual time index (the panel time variable).. Construction: 1960-2005, balanced for every country.. Units: year. Source: Andersson (2019) replication file
note CO2_transport_capita: Per-capita carbon-dioxide emissions from the transport sector - the outcome variable.. Construction: Total transport-sector CO2 emissions divided by population, per country-year.. Units: metric tons / capita. Source: OECD/IEA via Andersson (2019)
note GDP_per_capita: Real gross domestic product per capita - a synthetic-control predictor.. Construction: Real GDP per capita (PPP-adjusted in Andersson's source); averaged over 1980-1989 as an SCM predictor.. Units: US$ per capita (real). Source: PWT / World Bank via Andersson (2019)
note gas_cons_capita: Per-capita road-transport gasoline consumption - a synthetic-control predictor.. Construction: Gasoline consumption divided by population, per country-year; averaged 1980-1989 as an SCM predictor.. Units: kg oil-equivalent / capita (approx.). Source: IEA via Andersson (2019)
note vehicles_capita: Per-capita stock of motor vehicles - a synthetic-control predictor.. Construction: Number of registered vehicles divided by population (often expressed per 1,000 people), per country-year; averaged 1980-1989 as an SCM predictor.. Units: vehicles per capita. Source: Andersson (2019) replication file
note urban_pop: Share of the national population living in urban areas - a synthetic-control predictor.. Construction: Urban population as a percentage of total population, per country-year; averaged 1980-1989 as an SCM predictor.. Units: % (0-100). Source: World Bank via Andersson (2019)
note pop_density: People per unit of land area (auxiliary covariate; not in the headline predictor set).. Construction: Total population divided by land area, per country-year.. Units: persons / km^2 (approx.). Source: World Bank via Andersson (2019)
save "carbontax_data.dta", replace

* ---- disentangling_data.dta ----
use "disentangling_data.dta", clear
label data "Sweden counterfactual CO2 paths - carbon tax vs VAT decomposition"
note _dta: Sweden-only annual series, 1960-2005 (46 rows). The three scenario columns (CarbonTaxandVAT, NoCarbonTaxWithVAT, NoCarbonTaxNoVAT) are simulated and present only from 1970 onward (36 non-missing). Used in Exercise 4.3; the gap between scenarios attributes the reduction to each tax component.
note year: Annual time index (the panel time variable).. Construction: 1960-2005, balanced for every country.. Units: year. Source: Andersson (2019) replication file
note CO2_reductions_simulation: Simulated per-capita CO2 reduction attributable to the reform (model-based).. Construction: Difference between simulated actual and counterfactual emission paths for Sweden, per year.. Units: metric tons / capita. Source: Simulated (Andersson 2019)
note CO2_reductions_synth: Per-capita CO2 reduction implied by the Synthetic-Sweden gap (Sweden minus synthetic).. Construction: Sweden actual transport CO2 minus Synthetic-Sweden transport CO2, per year.. Units: metric tons / capita. Source: Computed via synthetic control (Andersson 2019)
note CarbonTaxandVAT: Simulated transport CO2 with all three components active (carbon tax, VAT, energy tax) - the factual path.. Construction: Demand model simulated at the actual price/tax bundle, per year.. Units: metric tons / capita. Source: Simulated (Andersson 2019)
note NoCarbonTaxWithVAT: Simulated transport CO2 if the carbon tax were removed but the VAT retained.. Construction: Demand model simulated with the carbon tax switched off and VAT on, per year.. Units: metric tons / capita. Source: Simulated (Andersson 2019)
note NoCarbonTaxNoVAT: Simulated transport CO2 if both the carbon tax and the VAT were removed (energy tax only).. Construction: Demand model simulated with carbon tax and VAT both switched off, per year.. Units: metric tons / capita. Source: Simulated (Andersson 2019)
save "disentangling_data.dta", replace
