* stata_codebook.do - attach long-form notes to the .dta files (run once in Stata).
* Generated by build_data_dictionary.py - do not edit by hand.

* ---- assets3_raw.dta ----
use "assets3_raw.dta", clear
label data "401(k) eligibility and household net assets (assets3 excerpt)"
note _dta: Cross-section of 9,913 households exported from Stata 19's built-in assets3 sample (Chernozhukov & Hansen 2004). Outcome = assets; treatment = e401k; the rest are heterogeneity/nuisance covariates. Binary covariates are stored as value-label text, not 0/1 codes.
note assets: Household net total financial assets - the outcome variable.. Construction: From the assets3 sample; net of liabilities, so values can be negative.. Units: US$. Source: Chernozhukov & Hansen (2004) / Stata assets3
note e401k: Whether the household head's employer offers a 401(k) plan (eligibility, not participation) - the treatment.. Construction: Value-label text from the assets3 sample (Eligible / Not eligible).. Units: category. Source: Stata assets3
note age: Age of the household head in years.. Construction: From the assets3 sample.. Units: years. Source: Stata assets3
note educ: Years of completed education of the household head.. Construction: From the assets3 sample.. Units: years. Source: Stata assets3
note income: Annual household income.. Construction: From the assets3 sample.. Units: US$. Source: Stata assets3
note incomecat: Coarse household-income category used for the prespecified GATE groups.. Construction: Discrete income bin from the assets3 sample (0 = lowest ? 4 = highest).. Units: 0-4. Source: Stata assets3
note pension: Whether the household receives defined-benefit pension benefits.. Construction: Value-label text from the assets3 sample (Receives pension / No pension).. Units: category. Source: Stata assets3
note married: Marital status of the household head.. Construction: Value-label text from the assets3 sample (Married / Not married).. Units: category. Source: Stata assets3
note twoearn: Whether the household has two earners.. Construction: Value-label text from the assets3 sample (Yes / No).. Units: category. Source: Stata assets3
note ira: Whether the household holds an Individual Retirement Account (IRA).. Construction: Value-label text from the assets3 sample (Yes / No).. Units: category. Source: Stata assets3
note ownhome: Whether the household owns its home.. Construction: Value-label text from the assets3 sample (Yes / No).. Units: category. Source: Stata assets3
save "assets3_raw.dta", replace
